### ISSUE TITLE
Xcode7 + Calabash + Code Coverage

### ISSUE THREAD

**Issue by nishabe** [calabash/calabash-ios#1032]
Hello Team,
Is it possible to set up Xcode7 and Calabash to see code coverage while Calabash based UI test suit is triggered?

**Comment by TeresaP** [comment]
It sure is. I'm going to write a blog post on it.

**Comment by nishabe** [comment]
Thanks, could you please provide the gist of those steps or any links so that I can proceed with my experiment?

**Comment by TeresaP** [comment]
http://teresap.github.io/2016/03/17/code-coverage-with-calabash

**Comment by nishabe** [comment]
@TeresaP , I see that you are using - (NSString*)flushGCov:(NSString*)ignored to flush. Where and how you call this method during test?

**Comment by nishabe** [comment]
Thanks, @TeresaP .
I am trying to use the same ruby files that you have shared in my project. 
The command I used in the terminal is:
cucumber CODE_COVERAGE_BUILD_PARENT_PATH=/Users/me/Desktop/myApp/
But I see the error as: 
uninitialized constant CodeCoverage::CODE_COVERAGE_INTERMEDIATES_DIR (NameError)
Any thoughts?

**Comment by TeresaP** [comment]
@nishabe did you see the gist with the Ruby code? I think it had everything you need

**Comment by jmoody** [comment]
Add a link to Teresa's blog post to the Wiki Sidebar under Guides.

**Comment by TeresaP** [comment]
@nishabe I went back to take a look this morning and saw what you meant. I updated env.rb with the lines that you need. Thanks for trying it out!

**Comment by nishabe** [comment]
Hi Teresa,
I am just wondering if you got a chance to see my last comments on the gist
page.
Your help much appreciated.
Thanks,
Aneesh

**Comment by nishabe** [comment]
@TeresaP , I have added some  more comments in your original gist page. Could you pls have a look?
