### ISSUE TITLE
Predefined calabash steps are defined using `Then`

### ISSUE THREAD

**Issue by cohitre** [calabash/calabash-ios#1053]
The Gherkin syntax gives meaning to the `Given`, `When` and `Then` keywords.  

Except for the `Given my app is running` step all of the steps are defined using `Then`. Is there a specific reason for this? Most of the predefined steps are action steps and thus should be used through the `When` keyword

From https://cucumber.io/docs/reference#steps

> Given
> 
> Given steps are used to describe the initial context of the system—the scene of the scenario. It is typically something that happened in the past.
> 
> When
> 
> When steps are used to describe an event, or an action. This can be a person interacting with the system, or it can be an event triggered by another system.
> 
> Then
> 
> Then steps are used to describe an expected outcome, or result.

**Comment by jmoody** [comment]
Ah, the predefined steps.  I never think about these at all.

There is no reason at all.

Even if the Step uses `Then` you can use use `When` in your features - they will be matched correctly.

**Comment by jmoody** [comment]
@cohitre If you want to change the keywords, please make a pull request.

Thanks!

**Comment by cohitre** [comment]
I was getting the step undefined message when writing my tests using the `When` keyword. Might be related to my cucumber version (2.3.2):

```
You can implement step definitions for undefined steps with these snippets:

When(/^I fill "([^"]*)" with "([^"]*)"$/) do |arg1, arg2|
  pending # Write code here that turns the phrase above into concrete actions
end
```

In any case, seems like updating the keywords is more trouble than it's worth since I should be writing my own steps definitions anyway. :+1:
