### ISSUE TITLE
"wait_for_elements_do_not_exist" queries elements by "all *"

### ISSUE THREAD

**Issue by rKrums** [calabash/calabash-ios#1059]
I'm using `calabash-cucumber (0.18.1)` 

I noticed that `wait_for_elements_do_not_exist` looks for elements with argument `all`

For me, this looks like a wrong behaviour, because the element could be pushed off screen or hidden, but the query will still detect it, and raise the error.

**Comment by jmoody** [comment]
Can you show me in code where you are seeing this?  Maybe I don't understand the point you are making.

**Comment by rKrums** [comment]
For example:

`query(ElementToBeDeleted)` - returns the element
`delete_element(ElementToBeDeleted)` - deletes the cell

now
 
`query(ElementToBeDeleted)` - returns empty array

`query(all ElementToBeDeleted)` - returns the element

and
`wait_for_elements_exist(ElementToBeDeleted)` - raises wait error

**Comment by jmoody** [comment]
I don't see that `wait_for_elements_exist` uses the `all` in the query.

Looking at the code in wait_helpers.rb, do you see that this is happening?

**Comment by jmoody** [comment]
@rKrums Can you demonstrate this in one of the sample projects?

* https://github.com/calabash/calabash-ios-server/tree/develop/cucumber
* https://github.com/calabash/ios-smoke-test-app

or provide a link to your project?

I am also willing to do a remote debugging session with you.  Find me on [Gitter](https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by rKrums** [comment]
Thanks for interest in my problem, but I'm on a tight schedule, and currently can not do anything about this. I found a workaround for this. 

May be the element was not removed properly by the app, when it's deleted, I'm not sure, but `wait_for_elements_do_not_exist(* id:'the_element')` saw the element all the time, but `query("* id:'the_element'')` was empty at the same time

**Comment by jmoody** [comment]
Adding to the current pipeline for investigation.

**Comment by jmoody** [comment]
Pushing this to Backlog.  Without an example, I cannot debug.

**Comment by rKrums** [comment]
Just for info. Haven't encountered this anymore, and can not be reproduced on sample projects. Might be something on my app side.
