### ISSUE TITLE
Adding Calabash automatically to XCode Project

### ISSUE THREAD

**Issue by sueess** [calabash/calabash-ios#1076]
Is there a good way to add automatically the Calabash-Scheme etc. to the XCode Project and run the cucumber tests?

`calabash-ios setup` seams to be out-of-date (https://github.com/calabash/calabash-ios/wiki/calabash-ios-setup). I still tried it. I was successful, as long I opened the project after running `calabash-ios setup` and build & run it. Afterwards I could run the test from console using `cucumber`.

On my build server I obviously do not have the chance to do that using xcode. I tried to build the project from the console, but I went in multiple other problems.

Thankful for every advice!

**Comment by jmoody** [comment]
> Is there a good way to add automatically the Calabash-Scheme etc. to the XCode Project and run the cucumber tests?

The short answer is no.

> calabash-ios setup

The wiki page describes the problems with this tool. 

This page describes alternative methods:

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode

You can probably write a build script that sets the "OTHER_LDFLAGS".

> as long open the project

This is probably unnecessary; you should be able to run `xcodebuild` from the command line if the tool succeeds.

For example scripts, see any of the sample projects.  The Permissions scripts are the easiest to understand.

1. [Permissions](https://github.com/calabash/Permissions)
2. [CalWebView](https://github.com/calabash/ios-webview-test-app/)
3. [CalSmokeApp](https://github.com/calabash/ios-smoke-test-app)

**Comment by sueess** [comment]
Thanks for your fast reply. In this case calabash-ios setup does not seam to be the problem. 

> This is probably unnecessary; you should be able to run xcodebuild from the command line if the tool succeeds.
When I build the project using `xcodebuild` a "Expected 'x86_64' but found ["armv7", "arm64"]"-exception appears when I try to run cucumber.

When I use `Cordova Compile` (Im using Ionic) and run the cucumber tests while pointing on the .app-directory, the test stucks and does nothing after starting the app.

Doing it manually using XCode is the only way it works.

Thanks for any input!

**Comment by jmoody** [comment]
> When I build the project using xcodebuild a "Expected 'x86_64' but found ["armv7", "arm64"]"-exception appears when I try to run cucumber.

This means that you are trying to run a .app (arm*) built for a physical device on a iOS Simulator which requires i386 or x86_64 arches.

> point to the app directory

How are doing that?  Can you try without setting the APP or APP_BUNDLE_PATH?  Calabash now does a better job detecting the correct app for the simulator.  If you get an error, read the error message carefully - it will explain what to do.
