### ISSUE TITLE
0.19.0: undefined method `embed` in Calabash::Cucumber.map

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#1083]
```
{"status"=>"success", "value"=>true, "index"=>3}
    When I have taken a photo I like         # features/step_definitions/camera_steps.rb:73
 undefined method `embed' for #<Calabash::Cucumber::Map:0x007fe57f541c78> (NoMethodError)
 ./features/step_definitions/camera_steps.rb:86:in `/^I have taken a photo I like$/'
 features/camera.feature:23:in `When I have taken a photo I like'
```

**Comment by filipjakubowski** [comment]
Guys - I have used recent develop build
`Using calabash-cucumber 0.19.0 from https://github.com/calabash/calabash-ios.git (at develop@b643900)`
But I got en error 
`Then I press the "SignUpButton" button                # calabash-cucumber-0.19.0/features/step_definitions/calabash_steps.rb:30
      undefined method `embed' for #<Calabash::Cucumber::Map:0x00000102217cf0> (NoMethodError)`

**Comment by jmoody** [comment]
@filipjakubowski Can you show me how you reproduced?  Maybe with a sample project?  If you are up for it we can set up a tmate session.  Private message me @ [Gitter](https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by filipjakubowski** [comment]
Hello JMoody, 

this is on our iOS App - it fails on press button scenario

`Feature: Password validation
Scenario: Invalid Password Sign Up
  Given the app is running
  Then I scroll right
  Then I scroll right
  Then I scroll right
  Then I scroll right
  Then I touch button number 2
  Then I enter "filip@loot.io" into text field number 1
  Then I enter "Password" into text field number 2
  Then I enter "Password" into text field number 3
  Then I press the "SignUpButton" button`

**Comment by jmoody** [comment]
This is not enough information.  I need to see the ruby source code of an actual project.

Are you running cucumber with `bundle exec`?  If you are not, you might not be using `develop@b643900`.

**Comment by filipjakubowski** [comment]
@jmoody you may be right - I have not used **bundle exec**. ( I am too junior to Ruby maybe ;-)  - will read more about bundler ) 

I got now different more descriptive error - so I guess this helped!

`   Then I press the "SignUpButton" button                # calabash-ios-b643900ed52a/calabash-cucumber/features/step_definitions/calabash_steps.rb:30
      touch could not find view: 'button marked: 'SignUpButton'', args: {:query=>"button marked: 'SignUpButton'"} (RuntimeError)
      features/password_validation.feature:16:in `Then I press the "SignUpButton" button'`

**Comment by filipjakubowski** [comment]
I am ok with closing this one. Sorry and thx for help!

**Comment by jmoody** [comment]
> bundle exec + github gems

Your Gemfile should have the following entry:

```
gem "calabash-cucumber", :github => "calabash/calabash-ios", :branch => develop"
```

You should run `bundle update` when you want to fetch the latest sources.

You should run all ruby commands (cucumber, calabash-ios console, etc) with `bundle exec` to _use_ the gems in your Gemfile (as determined by the Gemfile.lock).

> touch could not find view: 'button marked: 'SignUpButton'',

The button could not be found, which is a problem with the test. :)  I think you know this already.
