### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_SSLClose", referenced from:... ERROR

### ISSUE THREAD

**Issue by noved210** [calabash/calabash-ios#1091]
Hi, this is my first issues post to the calabash issues. So if I should add more detail just let me know.

Okay firstly I am working on getting Calabash working to test apps developed using Cordova/Ionic. I'm pretty sure it's possible because I did get a project working with it yesterday. But I didn't write down my steps and when I tried it again this morning I got this error:

![screen shot 2016-04-29 at 1 08 30 pm](https://cloud.githubusercontent.com/assets/9397919/14922000/86f9fc40-0e0b-11e6-9215-02de3c1c4a05.png)

Here's a more details look:

![screen shot 2016-04-29 at 1 09 29 pm](https://cloud.githubusercontent.com/assets/9397919/14922030/ab6f9a62-0e0b-11e6-9c0c-60f4df586f08.png)

I've also tried following the steps in the tutorial on the wiki (https://github.com/calabash/calabash-ios/wiki/Tutorial%3A--Creating-a-cal-Target). This didn't work and I also tried to to go through the regular steps. This is the terminal input/output:

**TBDs-MacBook-Pro:~ tbd$ ionic start demoApp tabs**
Creating Ionic app in folder /Users/tbd/demoApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ✗ Unable to save ionic data: /Users/tbd/.ionic/ionic.config Error: EACCES: permission denied, open '/Users/tbd/.ionic/ionic.config'
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
Added ios platform

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd demoApp

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs

 ✗ Unable to save ionic data: /Users/tbd/.ionic/ionic.config Error: EACCES: permission denied, open '/Users/tbd/.ionic/ionic.config'

Create an ionic.io account to send Push Notifications and use the Ionic View app?
(Y/n): n
 ✗ Unable to save ionic data: /Users/tbd/.ionic/ionic.config Error: EACCES: permission denied, open '/Users/tbd/.ionic/ionic.config'
+---------------------------------------------------------+
+ New Ionic Updates for April 2016
+
+ The View App just landed. Preview your apps on any device
+ http://view.ionic.io
+
+ Invite anyone to preview and test your app
+ ionic share EMAIL
+
+ Generate splash screens and icons with ionic resource
+ http://ionicframework.com/blog/automating-icons-and-splash-screens/
+
+---------------------------------------------------------+
TBDs-MacBook-Pro:~ tbd$ ls
1myApp			Library			demoApp
AndroidStudioProjects	Movies			myApp
Applications		Music			temp
Desktop			Pictures		testApp
Documents		Public			testApp_2
Downloads		calabash-sandbox
TBDs-MacBook-Pro:~ tbd$ cd demoApp/

**TBDs-MacBook-Pro:demoApp tbd$ ionic platform add ios**

Updated the hooks directory to have execute permissions
Downloading Default Ionic Resources
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
 ✗ Unable to save ionic data: /Users/tbd/.ionic/ionic.config Error: EACCES: permission denied, open '/Users/tbd/.ionic/ionic.config'
[=============================]  100%  0.0s
Done adding default Ionic resources
Adding icons for platform: ios
Error: Platform ios already added.

**TBDs-MacBook-Pro:demoApp tbd$ ionic build ios**

.
.
Cordova build output
.
.

**TBDs-MacBook-Pro:ios tbd$ open HelloCordova.xcodeproj/
TBDs-MacBook-Pro:ios tbd$ ../../../calabash-sandbox **

This terminal is now ready to use with Calabash.
To exit, type 'exit'.

**[tbd@calabash-sandbox]$ calabash-ios setup**

Checking if Xcode is running...
Detected running Xcode. You may need to restart Xcode after setup.
Found Project: HelloCordova

----------Info----------
caution: excluded filename not matched:  __MACOSX/*
caution: excluded filename not matched:  calabash.framework/.DS_Store
---------------------------

----------Info----------
Setting up project file for calabash-ios.
---------------------------

----------Info----------
Making backup of project file: /Users/tbd/demoApp/platforms/ios/HelloCordova.xcodeproj/project.pbxproj
Saved as /Users/tbd/demoApp/platforms/ios/HelloCordova.xcodeproj/project.pbxproj.bak
---------------------------
Duplicating target: HelloCordova to new target: HelloCordova-cal
Adding CFNetwork.framework to target HelloCordova-cal
Adding calabash.framework to target HelloCordova-cal
Adding Other Linker options to target HelloCordova-cal

----------Setup done----------
Please validate by running the -cal target
from Xcode.
When starting the iOS Simulator using the
new -cal target, you should see:

  "Started LPHTTP server on port 37265"

in the application log in Xcode.

After validating, you can generate a features folder:
Go to your project (the dir containing the .xcodeproj file).
Then run calabash-ios gen
(if you don't already have a features folder).
---------------------------

**[tbd@calabash-sandbox]$ calabash-ios gen**

----------Question----------
I'm about to create a features directory here:

/Users/tbd/demoApp/platforms/ios/features

This directory will contain all of your calabash tests.
Shall I proceed? (Y/n)
---------------------------
y

Created: /Users/tbd/demoApp/platforms/ios/features

----------Question----------
I want to create a Gemfile for you.
Shall I proceed? (Y/n)
y

Created: /Users/tbd/demoApp/platforms/ios/Gemfile

---------------------------
My work is done here.
[tbd@calabash-sandbox]$ 

When I look at the project I'm still seeing the same errors as I get from the linked method at the top of the post. Maybe I'm going about it wrong or am wrong about Calabash being able to work with an Ionic application. Any help would be greatly appreciated and if I need to I could also post the setting for the working project v/s any of the many that don't work.

Thanks in advance - noved210

PS: as requested by the guidelines: 

TBDs-MacBook-Pro:~ tbd$ xcodebuild -version
Xcode 7.3
Build version 7D175
TBDs-MacBook-Pro:~ tbd$ calabash-ios version
0.19.0
TBDs-MacBook-Pro:~ tbd$ curl http://localhost:37265/version
curl: (7) Failed to connect to localhost port 37265: Connection refused

I currently don't have github set up on my machine. But if the problem requires that someone looks at the projects getting creating a repo setup is something I would gladly do if requested.

**Comment by jmoody** [comment]
You have two options:

1. Increase your deployment target to iOS 7.0
2. Include the Security.framework

**Comment by noved210** [comment]
Thanks sooooooo much! I changed the deployment target and that didn't work but adding the security framework did help. My app is now compiling and the tests seem to be running!!
