### ISSUE TITLE
Calabash 0.19 - new Map class is missing "embed" method

### ISSUE THREAD

**Issue by nfrydenholm** [calabash/calabash-ios#1092]
I'm in the progress of updating a couple of apps to Calabash 0.19 (and latest runloop + Cucumber 2.3.3 (we have been using 1.3.2 so far), and almost everything is working.

But if I perform e.g. a touch on a query that does not match anything, I end up with a "noMethodError" when the _map.rb_ tries to do the _screenshot_and_raise in the assert_map_results method_.
It makes it impossible to see what the real error in the test is.

**The error**
The error looks like this
`NoMethodError: undefined method `embed' for #<Calabash::Cucumber::Map:0x007fa26409ab88>`
and happens when trying to fail with the message from this method in the Map class

```
   def self.assert_map_results(map_results, msg)
        compact = map_results.compact
        if compact.empty? or compact.member? '<VOID>' or compact.member? '*****'
          Map.new.screenshot_and_raise msg
        end
      end

```
I believe the issue is related to this old workaround https://groups.google.com/forum/#!searchin/calabash-ios/embed/calabash-ios/RI_JfFsrwtY/ASuv1MWWj38J - but now that the Map is a class, our old workaround with just defining a dummy "embed" method is not enough.

**How to reproduce**
Perform e.g. a touch with a query that is not matched, and you should see the problem when the Map class tries to do the prober errorhandling with screenshot_and_raise

**Attempted workaround**
I have tried to extend the Map class with and embed method, but clearly I'm not doing it correct, since it's not working :)

```
module DBA module Calabash module Cucumber

  class ::Map
    def embed(arg1, arg2, arg3)
      puts "hello from embed in Map"
    end

  end
```

**Comment by jmoody** [comment]
I have been waiting for a report.

https://github.com/calabash/calabash-ios/issues/1083

Fixed in develop.  Will be available in 0.19.1.

I might try to push a pre-release over the weekend.

Apologies.

**Comment by nfrydenholm** [comment]
sorry I didn't see the #1083 issue - I actually did search for issues with embed, before I submitted this one :)

**Comment by jmoody** [comment]
@nfrydenholm Missed you at Evolve this year. 

No worries about opening an issue.

Cheers!

**Comment by nfrydenholm** [comment]
Yeah, I wish I could have gone to Evolve again this year, but sadly my manager got to attend the "Leader summit" at Evolve, while I had to stay home and work 😮
