### ISSUE TITLE
Podspec typo?

### ISSUE THREAD

**Issue by tachtevrenidis** [calabash/calabash-ios#1097]
I don't know if this is happening to me only but this line is the podspec causes build failure:

`"OTHER_LDFLAGS" => "-ObjC -force_load \"$(PODS_ROOT)/calabash/calabash.framework/calabash\"" }`

because the path the is created in my filesystem is cased differently:

`/Users/user/Development/project/Pods/Calabash/calabash.framework`

so I always have to go and manually edit the generated .xcconfig to upper case 'Calabash' and then it works.

**Comment by jmoody** [comment]
@tachtevrenidis Can you reproduce with a sample project?

It might be something unique to your setup for this particular project.

**Comment by jmoody** [comment]
Upon reflection, I do _not_ want an end-to-end Cocoapods test in this repo.

1. This project should not have an dependencies on CocoaPods; users should be able to run the tests without installing CocoaPods.
2. The podspec should not be in this repository, it should be in the calabash-ios-server repository.  At the moment the spec relies on the fact that framework is shipped with the gem.  That will not always be the case.

Merging as is.
