### ISSUE TITLE
Touch event not working when I run cucumber but will work on the test server

### ISSUE THREAD

**Issue by noved210** [calabash/calabash-ios#1099]
Hi, 

I'm having issues with running a test on the iPhone simulator though cucumber. When I run the test 

...stuff above...

```
wait_for do
    !(query("UIWebView css:'input'")).empty?
end

touch(query("UIWebView css:'input'")[0])

wait_for_keyboard

keyboard_enter_text("blahblah@gmail.com")
```

I get an error saying that it's timed out waiting for the keyboard to show up (the touch is returning true but nothing happens):

```
[tbd@calabash-sandbox]$ cucumber 
Feature: Sample Feature

WARN: deprecated '2.1.0' - No replacement
/Users/tbd/.calabash/sandbox/Gems/gems/run_loop-2.1.0/lib/run_loop/xcode.rb:183:in `version_gte_51?'
/Users/tbd/.calabash/sandbox/Gems/gems/calabash-cucumber-0.18.2/lib/calabash-cucumber/launcher.rb:399:in `default_launch_method'
/Users/tbd/.calabash/sandbox/Gems/gems/calabash-cucumber-0.18.2/lib/calabash-cucumber/launcher.rb:330:in `default_launch_args'
/Users/tbd/.calabash/sandbox/Gems/gems/calabash-cucumber-0.18.2/lib/calabash-cucumber/launcher.rb:434:in `relaunch'
/Users/tbd/Desktop/master/platforms/ios/features/support/01_launch.rb:27:in `block in <top (required)>'
INFO: Detected app at path:
INFO: /Users/tbd/Library/Developer/Xcode/DerivedData/Swept-ddpotuuxfdgxihftrhpjxixtmqsj/Build/Products/Debug-iphonesimulator/Swept.app
INFO: Modification time of app: Fri 06 May 2016 11:45:12 ADT
INFO: If this is incorrect, set the APP variable and/or rebuild your app
INFO: It is your responsibility to ensure you are testing the right app.
  Scenario: Sample Scenario    # features/sample.feature:3
    Given the app has launched # features/steps/sample_steps.rb:1
      keyboard did not appear (Calabash::Cucumber::WaitHelpers::WaitError)
      ./features/steps/sample_steps.rb:14:in `/^the app has launched$/'
      features/sample.feature:4:in `Given the app has launched'

Failing Scenarios:
cucumber features/sample.feature:3 # Scenario: Sample Scenario

1 scenario (1 failed)
1 step (1 failed)
1m39.043s
```

When I run all the code in the calabash-ios console (after starting the test server) it works fine. The input is touched and the keyboard pops up.

What's especially weird about this is that when I run cucumber and I actually click on the input that I'm trying to automate the keyboard comes up and the rest of the test continues as I would expect it (other inputs are clicked without me needing to intervene). It seems to me that the very first touch just isn't working and the other ones do.

**Comment by jmoody** [comment]
It is a timing issue.  The web page might not be fully loaded.

Try:

```
wait_for do
  results = query("UIWebView", :isLoading)
  if results.empty?
     false
  elsif results[0] == 1
     false
   else
     true
   end
end
```

You can add a category method on WKWebView to accomplish the same thing.

If you can't add a category method because you do not control the source code, open an issue and we can discuss if we should add something to the public API.

**Comment by noved210** [comment]
You exact solution didn't work for me but you pointed me in the right direction, thank you for that!
I made a timer at the very start of the test:

```
t1 = Time.now

wait_for do
    t2 = Time.now

    if (t2 - t1) < 3
       false
     else
       true
     end
  end
```

This worked perfectly for me.
