### ISSUE TITLE
Trigger "Back to App" button

### ISSUE THREAD

**Issue by iammac360** [calabash/calabash-ios#1106]
Is it possible to trigger the "Back to" button on calabash? Our app has an onboarding process that includes an installation of a custom keyboard which must be enabled on the Settings -> General -> Keyboard.

![Image of Yaktocat](https://www.evernote.com/l/AMSY_D3AbcBD9bbaXRfUTKod1Tx7RI01JPQB/image.png)

**Comment by JoeSSS** [comment]
You can try uia_quiery :element

If the app is opened in background you can some chances

**Comment by jmoody** [comment]
My best guess is that you will not be able to touch this button.

**Comment by ark-konopacki** [comment]
@iammac360 If you still have your 'main' app launched and from this app you open that view you still can send commands via `uia`. You can get coordinates for that button and try `uia_handle_command(:tapOffset, {:x => x, :y => y})`. You cannot identify/click that button with calabash.

**Comment by jmoody** [comment]
With DeviceAgent (available with Xcode 8) try: 

```
device_agent.touch({id: "Back to < app name > "})
```

**Comment by jmoody** [comment]
@iammac360 I am closing.  Please try the DeviceAgent call and uia_query call that @JoeSSS suggested.  If the problem continues, we will address in another issue.
