### ISSUE TITLE
dismiss software update popup appearing on iOS device in middle of execution of scripts

### ISSUE THREAD

**Issue by swati017** [calabash/calabash-ios#1107]
@jmoody  Hi,

I am facing an issue with the software update notification appearing in middle of testing my app on iOS device. I want to click the button (remind me later) to dismiss the popup so that my script doesn't fail. I am using calabash, ruby and cucumber for writing the scripts to test the app on phone.

Can anyone help me in this issue through the code to dismiss the popup. Is there any calabash method which can capture iOS generated alerts like this.  I tried using calabash UIA methods but once the app is at background , calabash framework won't be in picture. Or is there any script which I can use with my ruby scripts to dismiss the iOS generated popup like this.

we are testing this app on different WiFis hence we can not block those WiFis from router end so thinking to handle it from code level.

**Comment by jmoody** [comment]
Follow the advice in this thread: https://groups.google.com/forum/#!topic/calabash-ios/iIE5sIABTME

This is beyond the scope of what Calabash can offer.  All solutions must be done at the network or physical device level.
