### ISSUE TITLE
(Calabash + Jenkins) Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.

### ISSUE THREAD

**Issue by VPovianet** [calabash/calabash-ios#1120]
Hi,

I have a problem for integrate Calabash at Jenkins.

My version is : 
run-loop version : 2.1.3
calabash-ios version : 0.19.2
XCode : 7.3.1

My error is :

```
2016-07-28 15:03:13 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-28 15:03:13 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
  Scenario: Sample Scenario          # features/sample.feature:3
  Calabash::Cucumber::LaunchError: 
  
  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
  
  Logfile: /Users/Shared/Jenkins/.run-loop/results/2016-07-28_15-02-43/run_loop.out
  
          2016-07-28 15:02:44.828 instruments[16525:172847] WebKit Threading Violation - initial use of WebKit from a secondary thread.

```

I launch my job Jenkins retrieve my code and launch this script :

```
DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer" 
export DEVELOPER_DIR

xcodebuild -project calabash.xcodeproj -sdk iphoneos9.3 -configuration Debug -arch armv7 VALID_ARCHS="i386 armv7 armv7s arm64 x86_64 " OBJROOT="${WORKSPACE}" SYMROOT="${WORKSPACE}" clean build

DEBUG=1 APP=$WORKSPACE/Debug-iphoneos/calabash.app DEVICE_TARGET="*************" DEVICE_ENDPOINT=http://192.168.0.45:37265 SCREENSHOT_PATH=../../screenshot cucumber
```

My log of my iPhone is :

```
Jul 28 15:09:37 iPhone-de-Ariya notification_proxy[333] <Error>: 0x40081000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Jul 28 15:09:40 iPhone-de-Ariya notification_proxy[333] <Error>: 0x40197000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Jul 28 15:09:42 iPhone-de-Ariya kernel[0] <Notice>: 071379.282936 wlan0.A[7369] updateLinkQualityMetrics@1991:Report LQM to User Land 100, fAverageRSSI -70
Jul 28 15:09:44 iPhone-de-Ariya gputoolsd[919] <Notice>: schedule invalidation <DYTransport 0x1657d040, error: lost transport connection (31)>
Jul 28 15:09:44 iPhone-de-Ariya DTServiceHub[347] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
Jul 28 15:09:44 iPhone-de-Ariya gputoolsd[919] <Notice>: terminating daemon 0x1657cdf0
Jul 28 15:09:44 iPhone-de-Ariya notification_proxy[333] <Error>: 0x40081000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Jul 28 15:10:14 iPhone-de-Ariya gputoolsd[920] <Notice>: schedule invalidation <DYTransport 0x14650170, error: lost transport connection (31)>
Jul 28 15:10:14 iPhone-de-Ariya gputoolsd[920] <Notice>: terminating daemon 0x1464ff30
Jul 28 15:10:14 iPhone-de-Ariya DTServiceHub[347] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
Jul 28 15:10:14 iPhone-de-Ariya notification_proxy[333] <Error>: 0x40115000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Jul 28 15:10:14 iPhone-de-Ariya notification_proxy[333] <Error>: 0x40115000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

```
When i launch calabash in command line with a terminal. Calabash run and no problem (I generate calabash.app with XCode).

With command line :
 
`APP=calabash.app DEVICE_TARGET="*************" DEVICE_ENDPOINT="http://192.168.0.45:37265" cucumber  `

Sorry for my english. 

Thanks you,

VP

**Comment by TitouanVanBelle** [comment]
I am experiencing the same issue as well with 0.17.1 as explained in this SO post http://stackoverflow.com/questions/38655681/timed-out-waiting-for-uiautomation-run-loop-error-while-writing-to-fifo-using-ca

**Comment by jmoody** [comment]
```
-arch armv7 VALID_ARCHS="i386 armv7 armv7s arm64 x86_64 "
```

That is wrong.

```
    ARCHS="armv7 armv7s arm64" \
    VALID_ARCHS="armv7 armv7s arm64" \
```

> DEBUG=1

Please include the instrument invocation.  It will start with `EXEC:  xcrun instruments`

In general, we do not answer questions like "it does not work in CI".

**FIFO** errors appear because:

1. The device is not enabled for development
2. The device is not eligible for development because Xcode has not finished copying the Debugging symbols
3. The bundle identifier passed to instruments is not correct

See these wiki pages:

* https://github.com/calabash/calabash-ios/wiki/Hot-Topics#3-errnoeintr-interrupted-system-call
* https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices

**Comment by TitouanVanBelle** [comment]
I am experiencing the same issue with the following configuration. 

Gemfile.lock
- run_loop (2.1.6)
- calabash-cucumber (0.17.1)
Podfile.lock
- Calabash (0.17.1)

This is how my app is built

```
xcrun xcodebuild OTHER_CFLAGS='-fembed-bitcode' -verbose -workspace FyberSDK.xcworkspace -scheme FyberTestApp -configuration Calabash -sdk iphoneos9.3 -destination 'id=42d83b5db88b4a99b164f9278772779be230f776' -derivedDataPath builds clean build | xcpretty
```

This is the comment that I run to launch the test

```
SCREENSHOT_PATH=build_reports/calabash/screenshots/ LOG_PATH=build_reports/calabash/logs/ RESET_BETWEEN_SCENARIOS=0 WANTS_TO_QUIT=0 DEBUG=0 DEVICE='42d83b5db88b4a99b164f9278772779be230f776' DEVICE_ENDPOINT=http://10.90.7.41:37265 HOST_IP=10.90.7.17 BUNDLE_ID=com.fyber.FyberTestApp bundle exec cucumber --tags ~@android-only --tags ~@ignore --tags @actions,@appstart,@banner,@credentials,@installs,@rewarded_video,@sdk,@user_segmentation -v -r FyberSDK/FyberTestApp/features/ --format pretty --format html --out build_reports/calabash/FunctionalTests.html FyberSDK/FyberTestApp/features/scenarios/
```

Here are the logs with DEBUG=1

```
INFO: Using uia strategy: 'host'
EXEC: xcrun simctl list devices --json
EXEC: xcrun instruments -s devices
DEBUG: Searching for run-loop results with glob: /Users/qa/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.005047 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 6 instruments caches
DEBUG: Will delete 1 instruments caches
DEBUG: Deleted 1 instruments caches in 0.001805 seconds
2016-07-29 12:26:30 +0200 [RunLoop:debug]: 
{
                   :app => "com.fyber.FyberTestApp",
                  :args => [
        [ 0] "-e",
        [ 1] "AUTOMATION_ENDPOINT_IP",
        [ 2] "10.90.7.17",
        [ 3] "-e",
        [ 4] "PUBLISHER_APP_ID",
        [ 5] "33453",
        [ 6] "-e",
        [ 7] "USER_ID",
        [ 8] "jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw",
        [ 9] "-e",
        [10] "SECURITY_TOKEN",
        [11] "token",
        [12] "-e",
        [13] "AUTOMATION_SSL",
        [14] "NO"
    ],
           :base_script => "run_loop_host.js",
             :bundle_id => "com.fyber.FyberTestApp",
                :device => #<Device: automation-iphone (9.3.2) 42d83b5db88b4a99b164f9278772779be230f776>,
         :device_target => "433d1f2e4d16bfdd36222c9dd46e6ee23222a68b",
           :instruments => #<Instruments 7.3>,
         :launch_method => :instruments,
        :launch_retries => 3,
              :log_file => "/Users/qa/.run-loop/results/2016-07-29_12-26-29/run_loop.out",
             :no_launch => false,
               :no_stop => false,
    :relaunch_simulator => true,
                 :reset => false,
           :results_dir => "/Users/qa/.run-loop/results/2016-07-29_12-26-29",
     :results_dir_trace => "/Users/qa/.run-loop/results/2016-07-29_12-26-29/trace",
                :script => "/Users/qa/.run-loop/results/2016-07-29_12-26-29/_run_loop.js",
           :sdk_version => nil,
                :simctl => #<Simctl: 7.3>,
                  :udid => "42d83b5db88b4a99b164f9278772779be230f776",
          :uia_strategy => :host,
                 :xcode => "7.3",
            :xcode_path => "/Applications/Xcode7.3.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on automation-iphone App: com.fyber.FyberTestApp ###
2016-07-29 12:26:30 +0200 [RunLoop:debug]: xcrun instruments -w 42d83b5db88b4a99b164f9278772779be230f776 -D /Users/qa/.run-loop/results/2016-07-29_12-26-29/trace -t /Applications/Xcode7.3.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate com.fyber.FyberTestApp -e UIARESULTSPATH /Users/qa/.run-loop/results/2016-07-29_12-26-29 -e UIASCRIPT /Users/qa/.run-loop/results/2016-07-29_12-26-29/_run_loop.js -e AUTOMATION_ENDPOINT_IP 10.90.7.17 -e PUBLISHER_APP_ID 33453 -e USER_ID jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw -e SECURITY_TOKEN token -e AUTOMATION_SSL NO >& /Users/qa/.run-loop/results/2016-07-29_12-26-29/run_loop.out
2016-07-29 12:26:30 +0200 [RunLoop:debug]: Preparation took 0.961996 seconds
2016-07-29 12:27:00 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-29 12:27:00 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
EXEC: xcrun simctl list devices --json
DEBUG: Searching for run-loop results with glob: /Users/qa/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.001866 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 5 instruments caches
DEBUG: Will delete 0 instruments caches
DEBUG: Deleted 0 instruments caches in 0.000111 seconds
2016-07-29 12:27:01 +0200 [RunLoop:debug]: 
{
                   :app => "com.fyber.FyberTestApp",
                  :args => [
        [ 0] "-e",
        [ 1] "AUTOMATION_ENDPOINT_IP",
        [ 2] "10.90.7.17",
        [ 3] "-e",
        [ 4] "PUBLISHER_APP_ID",
        [ 5] "33453",
        [ 6] "-e",
        [ 7] "USER_ID",
        [ 8] "jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw",
        [ 9] "-e",
        [10] "SECURITY_TOKEN",
        [11] "token",
        [12] "-e",
        [13] "AUTOMATION_SSL",
        [14] "NO"
    ],
           :base_script => "run_loop_host.js",
             :bundle_id => "com.fyber.FyberTestApp",
                :device => #<Device: automation-iphone (9.3.2) 42d83b5db88b4a99b164f9278772779be230f776>,
         :device_target => "433d1f2e4d16bfdd36222c9dd46e6ee23222a68b",
           :instruments => #<Instruments 7.3>,
         :launch_method => :instruments,
        :launch_retries => 3,
              :log_file => "/Users/qa/.run-loop/results/2016-07-29_12-27-01/run_loop.out",
             :no_launch => false,
               :no_stop => false,
    :relaunch_simulator => true,
                 :reset => false,
           :results_dir => "/Users/qa/.run-loop/results/2016-07-29_12-27-01",
     :results_dir_trace => "/Users/qa/.run-loop/results/2016-07-29_12-27-01/trace",
                :script => "/Users/qa/.run-loop/results/2016-07-29_12-27-01/_run_loop.js",
           :sdk_version => nil,
                :simctl => #<Simctl: 7.3>,
                  :udid => "42d83b5db88b4a99b164f9278772779be230f776",
          :uia_strategy => :host,
                 :xcode => "7.3",
            :xcode_path => "/Applications/Xcode7.3.app/Contents/Developer"
}

### Starting on automation-iphone App: com.fyber.FyberTestApp ###
2016-07-29 12:27:01 +0200 [RunLoop:debug]: xcrun instruments -w 42d83b5db88b4a99b164f9278772779be230f776 -D /Users/qa/.run-loop/results/2016-07-29_12-27-01/trace -t /Applications/Xcode7.3.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate com.fyber.FyberTestApp -e UIARESULTSPATH /Users/qa/.run-loop/results/2016-07-29_12-27-01 -e UIASCRIPT /Users/qa/.run-loop/results/2016-07-29_12-27-01/_run_loop.js -e AUTOMATION_ENDPOINT_IP 10.90.7.17 -e PUBLISHER_APP_ID 33453 -e USER_ID jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw -e SECURITY_TOKEN token -e AUTOMATION_SSL NO >& /Users/qa/.run-loop/results/2016-07-29_12-27-01/run_loop.out
2016-07-29 12:27:01 +0200 [RunLoop:debug]: Preparation took 0.036223 seconds
2016-07-29 12:27:31 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-29 12:27:31 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
EXEC: xcrun simctl list devices --json
DEBUG: Searching for run-loop results with glob: /Users/qa/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.00498 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 5 instruments caches
DEBUG: Will delete 0 instruments caches
DEBUG: Deleted 0 instruments caches in 0.000135 seconds
2016-07-29 12:27:31 +0200 [RunLoop:debug]: 
{
                   :app => "com.fyber.FyberTestApp",
                  :args => [
        [ 0] "-e",
        [ 1] "AUTOMATION_ENDPOINT_IP",
        [ 2] "10.90.7.17",
        [ 3] "-e",
        [ 4] "PUBLISHER_APP_ID",
        [ 5] "33453",
        [ 6] "-e",
        [ 7] "USER_ID",
        [ 8] "jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw",
        [ 9] "-e",
        [10] "SECURITY_TOKEN",
        [11] "token",
        [12] "-e",
        [13] "AUTOMATION_SSL",
        [14] "NO"
    ],
           :base_script => "run_loop_host.js",
             :bundle_id => "com.fyber.FyberTestApp",
                :device => #<Device: automation-iphone (9.3.2) 42d83b5db88b4a99b164f9278772779be230f776>,
         :device_target => "433d1f2e4d16bfdd36222c9dd46e6ee23222a68b",
           :instruments => #<Instruments 7.3>,
         :launch_method => :instruments,
        :launch_retries => 3,
              :log_file => "/Users/qa/.run-loop/results/2016-07-29_12-27-31/run_loop.out",
             :no_launch => false,
               :no_stop => false,
    :relaunch_simulator => true,
                 :reset => false,
           :results_dir => "/Users/qa/.run-loop/results/2016-07-29_12-27-31",
     :results_dir_trace => "/Users/qa/.run-loop/results/2016-07-29_12-27-31/trace",
                :script => "/Users/qa/.run-loop/results/2016-07-29_12-27-31/_run_loop.js",
           :sdk_version => nil,
                :simctl => #<Simctl: 7.3>,
                  :udid => "42d83b5db88b4a99b164f9278772779be230f776",
          :uia_strategy => :host,
                 :xcode => "7.3",
            :xcode_path => "/Applications/Xcode7.3.app/Contents/Developer"
}

### Starting on automation-iphone App: com.fyber.FyberTestApp ###
2016-07-29 12:27:31 +0200 [RunLoop:debug]: xcrun instruments -w 42d83b5db88b4a99b164f9278772779be230f776 -D /Users/qa/.run-loop/results/2016-07-29_12-27-31/trace -t /Applications/Xcode7.3.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate com.fyber.FyberTestApp -e UIARESULTSPATH /Users/qa/.run-loop/results/2016-07-29_12-27-31 -e UIASCRIPT /Users/qa/.run-loop/results/2016-07-29_12-27-31/_run_loop.js -e AUTOMATION_ENDPOINT_IP 10.90.7.17 -e PUBLISHER_APP_ID 33453 -e USER_ID jwzqsbmxjrwihtxbimqkhfqmueggnszwjbhawczahzqdbyessw -e SECURITY_TOKEN token -e AUTOMATION_SSL NO >& /Users/qa/.run-loop/results/2016-07-29_12-27-31/run_loop.out
2016-07-29 12:27:31 +0200 [RunLoop:debug]: Preparation took 0.035852 seconds
2016-07-29 12:28:02 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-29 12:28:02 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  @smoke
  Scenario: As an advertiser, I want to be warned that the action id must not be empty when reporting an action # FyberSDK/FyberTestApp/features/scenarios/advertisers/actions/exceptions.feature:10
 Calabash::Cucumber::Launcher::StartError: 
 
 "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
 
 Logfile: /Users/qa/.run-loop/results/2016-07-29_12-27-31/run_loop.out
 
         2016-07-29 12:27:32.453 instruments[34198:1898649] WebKit Threading Violation - initial use of WebKit from a secondary thread.
 2016-07-29 12:27:32.775 instruments[34198:1898647] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString hasPrefix:]: nil argument'
 *** First throw call stack:
 (
 	0   CoreFoundation                      0x00007fff9a824bd2 __exceptionPreprocess + 178
 	1   libobjc.A.dylib                     0x00007fff8dc3f4fa objc_exception_throw + 48
 	2   CoreFoundation                      0x00007fff9a88b3fd +[NSException raise:format:] + 205
 	3   CoreFoundation                      0x00007fff9a772be0 -[__NSCFString hasPrefix:] + 96
 	4   InstrumentsPlugIn                   0x0000000100835800 ___bestDeviceMatch_block_invoke + 502
 	5   libdispatch.dylib                   0x00007fff98e6a453 _dispatch_client_callout + 8
 	6   libdispatch.dylib                   0x00007fff98e6ba3a _dispatch_barrier_sync_f_invoke + 74
 	7   InstrumentsPlugIn                   0x00000001008355c4 _bestDeviceMatch + 233
 	8   InstrumentsPlugIn                   0x0000000100835a16 +[XRDeviceDiscovery devicesMatching:] + 57
 	9   instruments                         0x00000001004ea735 instruments + 10037
 	10  instruments                         0x00000001004ee9ef instruments + 27119
 	11  libdyld.dylib                       0x00007fff888c65ad start + 1
 )
 libc++abi.dylib: terminating with uncaught exception of type NSException
 
 
          (Calabash::Cucumber::Launcher::StartError)
 ./FyberSDK/FyberTestApp/features/support/launch.rb:34:in `Before'
 ./FyberSDK/FyberTestApp/features/support/launch.rb:18:in `call'
 ./FyberSDK/FyberTestApp/features/support/launch.rb:18:in `block in <top (required)>'
    When I report an empty action id for a valid advertiser app id                                              # FyberSDK/FyberTestApp/features/step_definitions/product_steps/advertisers_steps.rb:24
    Then I should be warned that the action id must not be empty                                                # FyberSDK/FyberTestApp/features/step_definitions/product_steps/advertisers_steps.rb:66
Retrying.. Errno::ETIMEDOUT: (Operation timed out - connect(2) for "10.90.7.41" port 37265 (10.90.7.41:37265))
      Host is down - connect(2) for "10.90.7.41" port 37265 (10.90.7.41:37265) (Errno::EHOSTDOWN)
      ./FyberSDK/FyberTestApp/features/support/launch.rb:43:in `After'
      ./FyberSDK/FyberTestApp/features/support/launch.rb:18:in `call'
      ./FyberSDK/FyberTestApp/features/support/launch.rb:18:in `block in <top (required)>
```

I'll just add that I am getting this error in a random manner. Out of 52 scenarios running, only one or two are failing but they're never the same.

**Comment by VPovianet** [comment]
Hi, 

Thanks for your help

@TitouanVanBelle 
Do you use Jenkins too? 

My problem isn't really just Calabash but Jenkins + Calabash. 
Do you managed to launch Calabash on your command line devices?  

I think my problem is with user rights (user jenkins) because when i run calabash in command line on my device physical, It works. 

But when i run Calabash from Jenkins that doesn't work with error :
`Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.`


@jmoody 

> In general, we do not answer questions like "it does not work in CI".

Sorry, where i can ask my question ?

> The device is not enabled for development
Yes, i enabled the button "Enable UI Automation". When i run calabash in command line on my physical device and simulator, It works.

> The device is not eligible for development because Xcode has not finished copying the Debugging symbols
I haven't test to wait after the build succeed but i tried run just Calabash with old file .app create. 

> The bundle identifier passed to instruments is not correct
Why ? I don't understand sorry.



If you want more details my logs :
`** BUILD SUCCEEDED **

+ DEBUG=1
+ APP=/Users/Shared/Jenkins/Home/jobs/calabash_ios/workspace/Debug-iphoneos/calabash.app
+ DEVICE_TARGET=******************
+ DEVICE_ENDPOINT=http://192.168.0.45:37265
+ SCREENSHOT_PATH=../../screenshot
+ cucumber
Feature: Sample Feature

[35mDEBUG: Searching for run-loop results with glob: /Users/Shared/Jenkins/.run-loop/results/*[0m
[35mDEBUG: Found 6 previous run-loop results[0m
[35mDEBUG: Will delete 1 previous run-loop results[0m
[35mDEBUG: Deleted 1 previous results in 0.006889 seconds[0m
[35mDEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*[0m
[35mDEBUG: Found 6 instruments caches[0m
[35mDEBUG: Will delete 1 instruments caches[0m
[35mDEBUG: Deleted 1 instruments caches in 0.002843 seconds[0m
[36mEXEC: xcrun simctl list devices --json[0m
[36mEXEC: xcrun instruments -s devices[0m
[35mDEBUG: CFBundleVersionString is not defined in Info.plist[0m
2016-07-29 12:45:00 +0200 [RunLoop:debug]: 
{
                  :app => #<APP com.ovianet.calabash 1.0 /Users/Shared/Jenkins/Home/jobs/calabash_ios/workspace/Debug-iphoneos/calabash.app>,
                 :args => [],
          :base_script => "run_loop_host.js",
            :bundle_id => "com.ovianet.calabash",
               :device => #<Device: iPhone de Ariya (9.3.2) ******************>,
         :inject_dylib => nil,
          :instruments => #<Instruments 7.3>,
             :log_file => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/run_loop.out",
          :results_dir => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00",
    :results_dir_trace => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/trace",
               :script => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/_run_loop.js",
               :simctl => #<Simctl: 7.3.1>,
                 :udid => "******************",
         :uia_strategy => :host,
                :xcode => "7.3.1",
           :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
[36mEXEC: xcrun instruments -s templates[0m

[35m### Starting on iPhone de Ariya App: com.ovianet.calabash ###[0m
2016-07-29 12:45:01 +0200 [RunLoop:debug]: xcrun instruments -w ****************** -D /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/trace -t Automation com.ovianet.calabash -e UIARESULTSPATH /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00 -e UIASCRIPT /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/_run_loop.js >& /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-00/run_loop.out
2016-07-29 12:45:01 +0200 [RunLoop:debug]: Preparation took 3.325887 seconds
2016-07-29 12:45:32 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-29 12:45:32 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
[35mDEBUG: Searching for run-loop results with glob: /Users/Shared/Jenkins/.run-loop/results/*[0m
[35mDEBUG: Found 6 previous run-loop results[0m
[35mDEBUG: Will delete 1 previous run-loop results[0m
[35mDEBUG: Deleted 1 previous results in 0.014105 seconds[0m
[35mDEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*[0m
[35mDEBUG: Found 6 instruments caches[0m
[35mDEBUG: Will delete 1 instruments caches[0m
[35mDEBUG: Deleted 1 instruments caches in 0.001429 seconds[0m
[35mDEBUG: CFBundleVersionString is not defined in Info.plist[0m
2016-07-29 12:45:32 +0200 [RunLoop:debug]: 
{
                  :app => #<APP com.ovianet.calabash 1.0 /Users/Shared/Jenkins/Home/jobs/calabash_ios/workspace/Debug-iphoneos/calabash.app>,
                 :args => [],
          :base_script => "run_loop_host.js",
            :bundle_id => "com.ovianet.calabash",
               :device => #<Device: iPhone de Ariya (9.3.2) ******************>,
         :inject_dylib => nil,
          :instruments => #<Instruments 7.3>,
             :log_file => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/run_loop.out",
          :results_dir => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32",
    :results_dir_trace => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/trace",
               :script => "/Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/_run_loop.js",
               :simctl => #<Simctl: 7.3.1>,
                 :udid => "******************",
         :uia_strategy => :host,
                :xcode => "7.3.1",
           :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}

[35m### Starting on iPhone de Ariya App: com.ovianet.calabash ###[0m
2016-07-29 12:45:32 +0200 [RunLoop:debug]: xcrun instruments -w ****************** -D /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/trace -t Automation com.ovianet.calabash -e UIARESULTSPATH /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32 -e UIASCRIPT /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/_run_loop.js >& /Users/Shared/Jenkins/.run-loop/results/2016-07-29_12-45-32/run_loop.out
2016-07-29 12:45:32 +0200 [RunLoop:debug]: Preparation took 0.142476 seconds
2016-07-29 12:46:02 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-07-29 12:46:02 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError`


Thanks for your help, I'm stuck for 3 days.

VP

**Comment by VPovianet** [comment]
Hi @jmoody ,

I'm stuck again.

I changed my code 

now :

`xcodebuild -project calabash.xcodeproj -target calabash -sdk iphoneos9.3 -configuration Debug ARCHS="armv7 armv7s arm64" VALID_ARCHS="armv7 armv7s arm64" ONLY_ACTIVE_ARCH=NO OBJROOT="${WORKSPACE}" SYMROOT="${WORKSPACE}" clean build
sleep 3s
DEVICE=*************************
ideviceinstaller -i Debug-iphoneos/calabash.app -u $DEVICE
DEBUG=1 APP=Debug-iphoneos/calabash.app BUNDLE_ID=com.********.calabash DEVICE_TARGET="*************************" DEVICE_ENDPOINT=http://192.168.0.16:37265 SCREENSHOT_PATH=../screenshot/$DEVICE_screenshot cucumber --format json --out ../cucumber/cucumber_$DEVICE.json
`

But i have problem again

There is problems with the permissions or user right or bad installation with Calabash? 

Thanks you for your help

VP

**Comment by VPovianet** [comment]
I resolve my problem !!

It's an error with Jenkins not calabash. 

To solve the problem :

Jenkins was running with launchctl load automatically on LaunchDaemons or LaunchAgents. What made Calabash plant that is not installed on the user account Jenkins .

Jenkins must run with the command line in the / Application / Jenkins:

java -jar jenkins.war

Allows you to install Jenkins on your current user in the directory ~.jenkins

Thanks you, sorry for my english

VP
