### ISSUE TITLE
Xcrun timed out after 1.19 seconds executing

### ISSUE THREAD

**Issue by wukaiying** [calabash/calabash-ios#1127]
Feature: add documents to on device

As mobile app user, I can add documents to on device
@smoke @p8-only @debugfeatures/feature_definitions/SyncTests/P8/P8AddDocumentOnDevice.feature:6
Scenario: add documents to on device

Xcrun timed out after 1.19 seconds executing

xcrun instruments -s devices

with a timeout of 30
 (RunLoop::Xcrun::TimeoutError)

./features/ios/support/01_launch.rb:40:in `Before'

launcher.relaunch(options)
 launcher.calabash_notify(self)

**Comment by jmoody** [comment]
There is not enough information in this bug report.

https://github.com/calabash/calabash-ios/wiki#reporting-problems
