### ISSUE TITLE
Xcrun timed out 

### ISSUE THREAD

**Issue by wukaiying** [calabash/calabash-ios#1130]
**Environment**:

cucumber (2.4.0)
calabash-cucumber (0.19.2)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
run_loop (2.1.7)
Xcode 7.3.1
simulator:Iphone 6s
simulator version: 9.3
OS X EI  Capitan 10.11.5

Steps to reproduce:
1. set APP_BUNDLE_PATH 
2. Launch  console input `cucumber -p smoke` to run my smoke case
3. Then i see my log

**Log:**

Xcrun timed out after 0.98 seconds executing

xcrun instruments -s templates

with a timeout of 30
 (RunLoop::Xcrun::TimeoutError)

./features/ios/support/01_launch.rb:39:in `Before'

**Comment by jmoody** [comment]
What happens when you run:

```
$ xcrun -f xcodebuild
$ xcrun instruments -s templates
$ xcrun instruments -s devices
```

**Comment by wukaiying** [comment]
**xcrun -f xcodebuild**
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

**xcrun instruments -s templates**
2016-08-17 11:09:53.830 instruments[9497:12454455] *** Terminating app due to uncaught exception 'Fatal', reason: 'Cannot create temporary directory for Instruments Analysis Core: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “com.apple.dt.instruments” in the folder “Caches”." UserInfo={NSFilePath=/Library/Caches/com.apple.dt.instruments, NSUnderlyingError=0x7f9d3e08a920 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff922134f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff896fcf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9227a4bd +[NSException raise:format:] + 205
	3   InstrumentsAnalysisCore             0x000000010c7ff7a4 _ZL35_lockedSetTemporaryDirectoryBaseURLP5NSURLPU15__autoreleasingP7NSError + 804
	4   InstrumentsAnalysisCore             0x000000010c7fff96 __64+[XRAnalysisCorePathManager setTemporaryDirectoryBaseURL:error:]_block_invoke + 22
	5   libdispatch.dylib                   0x00007fff888d840b _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff888d99f2 _dispatch_barrier_sync_f_invoke + 74
	7   InstrumentsAnalysisCore             0x000000010c7ff077 +[XRAnalysisCorePathManager setTemporaryDirectoryBaseURL:error:] + 183
	8   instruments                         0x000000010c704176 instruments + 8566
	9   instruments                         0x000000010c7089ef instruments + 27119
	10  libdyld.dylib                       0x00007fff855995ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**xcrun instruments -s devices**
2016-08-17 11:10:28.226 instruments[9507:12456031] *** Terminating app due to uncaught exception 'Fatal', reason: 'Cannot create temporary directory for Instruments Analysis Core: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “com.apple.dt.instruments” in the folder “Caches”." UserInfo={NSFilePath=/Library/Caches/com.apple.dt.instruments, NSUnderlyingError=0x7fe24bcde7f0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff922134f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff896fcf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9227a4bd +[NSException raise:format:] + 205
	3   InstrumentsAnalysisCore             0x0000000100a1f7a4 _ZL35_lockedSetTemporaryDirectoryBaseURLP5NSURLPU15__autoreleasingP7NSError + 804
	4   InstrumentsAnalysisCore             0x0000000100a1ff96 __64+[XRAnalysisCorePathManager setTemporaryDirectoryBaseURL:error:]_block_invoke + 22
	5   libdispatch.dylib                   0x00007fff888d840b _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff888d99f2 _dispatch_barrier_sync_f_invoke + 74
	7   InstrumentsAnalysisCore             0x0000000100a1f077 +[XRAnalysisCorePathManager setTemporaryDirectoryBaseURL:error:] + 183
	8   instruments                         0x0000000100928176 instruments + 8566
	9   instruments                         0x000000010092c9ef instruments + 27119
	10  libdyld.dylib                       0x00007fff855995ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by wukaiying** [comment]
**sudo xcrun instruments -s devices**

Known Devices:
MacBook Pro [C697B6F7-CA0D-5359-81BA-9368F288321F]
Apple TV 1080p (9.2) [90B80E1C-B720-4453-A30B-F784384E6D3E] (Simulator)
iPad 2 (9.3) [0EDEC2A8-3781-405C-A91F-4A67EDCD06FF] (Simulator)
iPad Air (9.3) [73CDE25C-C473-4849-979E-24C9CD865DFC] (Simulator)
iPad Air 2 (9.3) [EADE891C-47DB-42E0-BCDE-0E27C0DDEF21] (Simulator)
iPad Pro (9.3) [C8DD6A1A-F6CD-49F9-9E87-2F120B186F40] (Simulator)
iPad Retina (9.3) [601CA182-9164-47E4-9254-5EEE2E98D509] (Simulator)
iPhone 4s (9.3) [6106886B-6F40-4402-B5C4-EFCE0C4515A4] (Simulator)
iPhone 5 (9.3) [0A3863EE-C718-4A2E-B801-F0ADC17E1839] (Simulator)
iPhone 5s (9.3) [FA23D197-616C-486C-A1A5-C94E42868FE6] (Simulator)
iPhone 6 (9.3) [ABBFD794-8206-4139-AFA1-500692A310FA] (Simulator)
iPhone 6 Plus (9.3) [2A7596E9-8AA9-46F2-A0D8-A4584EB3B893] (Simulator)
iPhone 6s (9.3) [E3638E26-6A0F-4274-9E72-89158DFDBA2F] (Simulator)
iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [34963278-60D5-4A14-B16B-91299071A326] (Simulator)
iPhone 6s Plus (9.3) [2D1FA245-4E1D-4869-8BD9-05618941A702] (Simulator)
iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BAD61506-3997-4F00-AC75-CE72D90C69CB] (Simulator)

**sudo xcrun -f xcodebuild**
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild


**xcrun instruments -s templates**
Known Templates:
"Activity Monitor"
"Allocations"
"Automation"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Log"
"File Activity"
"GPU Driver"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"

could you tell me how to fix the error?

**Xcrun timed out after 0.98 seconds executing**

**xcrun instruments -s templates**

**with a timeout of 30**

**Comment by jmoody** [comment]
You should not to use `sudo`.  If you have to use `sudo` there some problem with your configuration.

I think you need to enable development on your mac.
