### ISSUE TITLE
Undefined method strip error every time I tries to setup calabash-ios

### ISSUE THREAD

**Issue by amgonzalez** [calabash/calabash-ios#1135]
Hi, 
I'm trying to setup calabash-ios with setup command. I have three different repositories for different apps in github. 

I have downloaded the project from github, and then ran calabash-ios setup in where the xcodeproj file is under my project. 

The point is I have two environments a VM machine with El Capitan (latest) where I have successfully setup calabash for the project. 

And a Mac Book pro with same version of El Capitan, where I cannot finish the setup for same project and also when I try to run a test using cucumber I get the same exception. 

Checking if Xcode is running...

Detected running Xcode. You may need to restart Xcode after setup.

Found Project: GP-Commissioning

----------Info----------

caution: excluded filename not matched:  __MACOSX/*

caution: excluded filename not matched:  calabash.framework/.DS_Store

---------------------------

----------Info----------

Setting up project file for calabash-ios.

---------------------------

----------Info----------

Making backup of project file: /Users/bairesqa/Desktop/Repositories/georgia-pacific-commissioning/GP-Commissioning/GP-Commissioning.xcodeproj/project.pbxproj

Saved as /Users/bairesqa/Desktop/Repositories/georgia-pacific-commissioning/GP-Commissioning/GP-Commissioning.xcodeproj/project.pbxproj.bak

---------------------------

---------- Info ----------

Found several targets. Please enter name of target to duplicate.

Default target: GP-Commissioning. Just hit <Enter> to select default.

GP-Commissioning

GP-CommissioningTests

GP-CommissioningUITests

input: 

Selecting default target (GP-Commissioning)

---------- - ----------

Duplicating target: GP-Commissioning to new target: GP-Commissioning-cal

Adding CFNetwork.framework to target GP-Commissioning-cal

Adding calabash.framework to target GP-Commissioning-cal

Adding Other Linker options to target GP-Commissioning-cal

```
/Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/version.rb:60:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:195:in `new'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:195:in `block (2 levels) in version'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:293:in `block in execute_command'

from /Users/bairesqa/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/open3.rb:217:in `popen_run'

from /Users/bairesqa/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/open3.rb:99:in `popen3'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:292:in `execute_command'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:193:in `block in version'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:197:in `call'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:197:in `version'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/xcode.rb:175:in `version_gte_6?'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/sim_control.rb:36:in `xcode_version_gte_6?'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/sim_control.rb:654:in `sim_app_support_dir'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/sim_control.rb:702:in `existing_sim_sdk_or_device_data_dirs'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/run_loop-2.1.3/lib/run_loop/sim_control.rb:285:in `enable_accessibility_on_sims'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/calabash-cucumber-0.19.2/bin/calabash-ios-sim.rb:12:in `calabash_sim_accessibility'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/calabash-cucumber-0.19.2/bin/calabash-ios-setup.rb:37:in `calabash_setup'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/gems/calabash-cucumber-0.19.2/bin/calabash-ios:38:in `<top (required)>'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/bin/calabash-ios:23:in `load'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/bin/calabash-ios:23:in `<main>'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'

from /Users/bairesqa/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

I have tried setting up the APP variable and the APP_BUNDLE_PATH variable when running in order to tell calabash where is the .app to use. 

I will appreciate any help from your side.

**Comment by jmoody** [comment]
Xcode is not installed or your DEVELOPER_DIR env var is pointing to an invalid path.

Please use GitHub markdown when reporting stack traces.

Since you are working with a VM, I recommend _not_ using rvm (use rbenv instead) and updating ruby to 2.3.1.

**Comment by jmoody** [comment]
And update to run-loop 2.1.8.

**Comment by amgonzalez** [comment]
Thanks Joshua. It worked.
