### ISSUE TITLE
Calabash WKWebView not available on iphone6

### ISSUE THREAD

**Issue by dittujoju** [calabash/calabash-ios#1142]
<img width="560" alt="main_m" src="https://cloud.githubusercontent.com/assets/17347387/18301011/d070f04e-7482-11e6-95c2-2285d4b8031d.png">

Can anyone tell me how to fix this? I followed the exact same procedure in the document.

**Comment by jmoody** [comment]
This means your application is not linked with WebKit.

**Comment by jmoody** [comment]
Does your application require WebKit?  If not, this is normal output.
