### ISSUE TITLE
Xcode 8 and iOS 10 support

### ISSUE THREAD

**Issue by Mikadoh** [calabash/calabash-ios#1143]
Any news about Xcode 8 / iOS support ? : https://groups.google.com/forum/#!topic/calabash-ios/g34znf0LnE4
Would be great to have an idea about the progress so far.

Thanks.

**Comment by jmoody** [comment]
Apologies.  We have been super busy sorting out details.

Right now you can pull the latest run_loop/develop and calabash-ios/develop branches and run tests with Xcode 8 / iOS 9 and 10.

Closing this issue.

**Comment by jmoody** [comment]
I am trying to keep people updated on [Gitter](https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
