### ISSUE TITLE
Calabash is closing the simulator after occurrence of exception -- iOS

### ISSUE THREAD

**Issue by chanuuuu** [calabash/calabash-ios#1152]
Hi,
     I have a case where clicking on a button raises a custom exception which is handled by the application. But when I run the app using Calabash for performing above case, it is closing simulator soon after occurrence of the exception. Is there a work around solution for this?

Regards,
Chanikya

**Comment by jmoody** [comment]
More details please.

https://github.com/calabash/calabash-ios/wiki#reporting-problems

1. Start your app manually on the simulator
2. `bundle exec run-loop simctl tail`
3. Touch your button
4. Paste the relevant information to this issue.

Possibly related to: 

* Exceptions in backdoors are caught by calabash server, preventing crash reports [#330](https://github.com/calabash/calabash-ios-server/issues/330)

**Comment by jmoody** [comment]
Sleep after the touch.

Closing.  If you have more information, I will reopen.
