### ISSUE TITLE
Problem run Spec with Xcode 8

### ISSUE THREAD

**Issue by mendesbarreto** [calabash/calabash-ios#1164]
Hello Everybody!

I am having a big problem trying to run the specs of my project on the new Xcode 8.0. When I try to run iOS 10 simulator 

```
Could not find the pid of Simulator with:
  xcrun ps x -o pid,command

  Command exited with status 72
  Message: 'xcrun: error: unable to find utility "xcrun", not a developer tool or in PATH'
   (RuntimeError)
  ./features/ios/support/01_launch.rb:27:in `Before'
```

First I was thinking I do no install `xcrun` on my mac but when I when `where xcrun` I got the right path `/usr/bin/xcrun`.  So next step I add a print `where xcrun` into `01_launch.rb` and I got the same path as before. So now I little bit lost... Someone can help ?

**Comment by Douvi** [comment]
Got the same issue, with Xcode 8 and calabash-cucumber v0.19... 

I updated to calabash-cucumber to v0.20 into my Gemfile and update my bundle :)...

**Comment by jmoody** [comment]
The `xcrun ps` problem was fixed in run-loop about a month ago.

You need to update to Calabash 0.20.0 to run with Xcode 8.0.

**Comment by jmoody** [comment]
@mendesbarreto Please make a comment if upgrading to 0.20.* does not help.

**Comment by joyitajan** [comment]
Hi , 

 I have  calabash 0.20.0 with Xcode  8.2.1 but still  getting the error message 
Message: 'xcrun: error: unable to find utility "xcrun", not a developer tool or in PATH'

./features/ios/support/01_launch.rb:27:in `Before'
