### ISSUE TITLE
DeviceAgent#query_for_coordinate fails

### ISSUE THREAD

**Issue by stopiccot** [calabash/calabash-ios#1169]
We had a custom cucumber step in our calabash setup:

```ruby
When(/^I swipe "(.*?)" to see actions()$/) do |mark, dummy|
  cell = query("view marked:'#{ mark }'")

  if cell.empty?
    screenshot_and_raise "could not find a view marked '#{mark}'"
  end

  swipe :left, query: "view marked:'#{ mark }'"
  wait_for_none_animating

  sleep(STEP_PAUSE)
end
```
After updating to calabash 0.20 and Xcode8 it stopped working, I've changed code to use `device_agent.query_for_coordinate` but it's still not working. Here is my latest debug implementation of step:

```ruby
When(/^I swipe "(.*?)" to see actions()$/) do |mark, dummy|
  p "****** CELL1 ******"
  p query("view marked:'Joined_Occurrence_Cell'")
  p "*******************"

  p "****** CELL2 ******"
  p device_agent.query({marked: "Joined_Occurrence_Cell"})
  p "*******************"

  from_point = device_agent.query_for_coordinate({marked: "Joined_Occurrence_Cell"})
  to_point = device_agent.query_for_coordinate({marked: "To"})
  pan_coordinates(from_point, to_point)
  wait_for_none_animating

  sleep(STEP_PAUSE)
end
```

Running this step outputs:

```
"****** CELL1 ******"
[{"enabled"=>true, "description"=>"<App_Platform_iOS_CustomRenderers_GestureViewRenderer: 0x804692c0; frame = (0 0; 375 70); gestureRecognizers = <NSArray: 0x801b36b0>; layer = <CALayer: 0x80470bc0>>", "visible"=>1, "id"=>"Joined_Occurrence_Cell", "rect"=>{"y"=>139, "width"=>375, "center_x"=>187.5, "x"=>0, "center_y"=>174, "height"=>70}, "label"=>nil, "value"=>nil, "alpha"=>1, "class"=>"App_Platform_iOS_CustomRenderers_GestureViewRenderer", "frame"=>{"y"=>0, "width"=>375, "x"=>0, "height"=>70}, "accessibilityElement"=>false}]
"*******************"
"****** CELL2 ******"
[]
"*******************"
    And I swipe "Joined_Occurrence_Cell" to see actions


      Waited 15 seconds for

      {:marked=>"Joined_Occurrence_Cell"}

      to match a view.

       (RuntimeError)

```

So it seems that deviceagent query for some reason fails to query existing element

**Comment by jmoody** [comment]
I am not sure I understand.

From what I see, `Core#query` is working correctly for you.  Why would you try to use `DeviceAgent#query_for_coordinate`?  Because there is no `Core#query_for_coordinate`?

In any event, try the DeviceAgent query specifier: `:all => true` which behaves somewhat like `query("all view ...")`.

**Comment by stopiccot** [comment]
I'm just following sample code from [https://github.com/calabash/calabash-ios/wiki/DeviceAgent](url):

```
    from_point = device_agent.query_for_coordinate({marked: "From"})
    to_point = device_agent.query_for_coordinate({marked: "To"})
    pan_coordinates(from_point, to_point)
```

It says to use `pan_coordinates` instead of `swipe` that it not working anymore

**Comment by jmoody** [comment]
Try to use `{marked: "To", all: true}`.

> It says to use pan_coordinates instead of swipe that it not working anymore

Were you using `uia_swipe` before?

**Comment by stopiccot** [comment]
> Were you using uia_swipe before?

I used `swipe :left, query: "view marked:'#{ mark }'"` in my custom step. Now it's not working for me. It does not fail but apps gesture recogniser does not trigger swipe event.

> Try to use {marked: "To", all: true}

Still not working for me. I get error message:

```
Waited 15 seconds for

{:marked=>"Joined Occurrence Cell", :all=>true}

to match a view.
```

**Comment by jmoody** [comment]
I wrote some documentation based on your comments.

* [When to use DeviceAgent methods](https://github.com/calabash/calabash-ios/wiki/DeviceAgent#when-should-i-use-the-new-deviceagent-methods)
* [Swipe and Flick](https://github.com/calabash/calabash-ios/wiki/DeviceAgent#swipe-and-flick)

The gist is:

1. DeviceAgent#query is not a substitute for `Core#query` or `uia_query`.  Always use Core#query unless it does not work.
2. Swipe and flick will behave differently given the same arguments - there is nothing we can do prevent this other than change the `swipe` and `flick` API itself (which we thought about doing).

**Comment by stopiccot** [comment]
Changing 
```
swipe :left, query: "view marked:'#{ mark }'"
````
 to
```
swipe(:left, {
  :query => "view marked:'#{ mark }'",
  :force => :strong,
})
```
solved the issue for me. But I don't quite get the reasoning behind that tbh.

**Comment by jmoody** [comment]
Before Xcode 8, Calabash used UIAutomation to perform gestures. 

For Xcode 8 or higher, Calabash will use DeviceAgent to perform gestures.

DeviceAgent is based on the XCUITest API.

Apple did not provide a one-to-one mapping of UIAutomation to XCUITest gestures, so we had to approximate the UIAutomation behavior with DeviceAgent.

This is why we expect that user's will need to change their `swipe` and `flick` arguments.

**Comment by stopiccot** [comment]
That's completely understandable, but I don't get what is the logic behind `:force => :strong`.  What its even doing? What is default value? Why default is not working etc..

**Comment by jmoody** [comment]
The default value is `:normal`.  TBH, I know almost nothing about the UIAutomation implementation.  In the DeviceAgent implementation, `:strong` decreases the duration of the swipe.

https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/automator/device_agent.rb#L142
