### ISSUE TITLE
Xcode 8 update, and nuke my automation

### ISSUE THREAD

**Issue by mattspeers** [calabash/calabash-ios#1171]
Hello all, 
    I just updated to Xcode 8 and now getting error message from cucumber of the following:
undefined method `[]' for #<RunLoop::DeviceAgent::Client:0x007fa5b290edb8> (NoMethodError)

My automation is using wait_tap("label marked:''yyyy")

Cucumber version 2.4.0
Ruby Version 2.3.0p0
Calabash-ios 0.19.2

**Comment by jmoody** [comment]
You must update to Calabash iOS >= 0.20.0.
