### ISSUE TITLE
Tests are taking too long to execute almost 10 * 

### ISSUE THREAD

**Issue by gkrinord** [calabash/calabash-ios#1179]
WITH CALABASH 0.20.0 Tests are taking too long to execute almost 10 * of the normal execution time for iOS 10.0.2 and iOS 9.3.5 as well.Is there any way we can reduce this time?

**Comment by jmoody** [comment]
Users are reporting a 2x _speed up_ not a slow down.

More information please.

https://github.com/calabash/calabash-ios/wiki#reporting-problems

**Comment by JoeSSS** [comment]
One user also reported that in calabash channel. After some time he said
that he probably have network problems. Fixing it he got normal speed

2016-09-30 13:29 GMT+02:00 Joshua Moody <notifications@github.com>:

**Comment by icy1007** [comment]
I am seeing a definitely speed up with 0.20.0. Mostly with text entry though.

**Comment by jmoody** [comment]
Closing because of a lack of response from reporter.
