### ISSUE TITLE
Cannot sign DeviceAgent-Runner.app - cannot find matching provisioning profile

### ISSUE THREAD

**Issue by sbalajieie** [calabash/calabash-ios#1191]
HI,
I have upgraded my calabash framework  to xcode 8 and ios10.. 
I am facing an error  "Could not find any Provisioning Profiles suitable for resigning"
 Below are my setup:

**EDITED**  What was here was impossible to read.

```
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/bsachi001c/.rvm/gems/ruby-2.3.1@tvx-mobile-automation

calabash-cucumber (0.20.0)
run_loop (2.2.1)
Mac OSX :10.11.6 
iOS version:10.0.2
Xcode version:8.0
```
### Problem

```
xcrun security find-identity -v -p code signing
4 valid identities found ( all are automation team’s account)
```

We have received a ipa file from the developers team, who has linked ipa file with calabash_framework 0.20.0

Executed the below mentioned command and console outputs:-

```
$ export APP=/Users/bsc/Documents/workspace/mobile-automation/iOS/tablets/master_Debug.ipa
$ CODE_SIGN_IDENTITY="iPhone Developer: xxx...@gmail.com (W95FEZS38E)" \ 
   DEVICE_TARGET="UDID of device" \
   DEVICE_ENDPOINT=http://x.x.71.43:37265 \
   bundle exec cucumber
```

```
Could not install /Users/bsachi001c/.rvm/gems/ruby-2.3.1@mobile-automation/gems/run_loop-2.2.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:

< snip >

  2016-10-05 10:26:43.190 iOSDeviceManager[12863:237303] EXEC: /usr/bin/xcrun codesign -d --entitlements :- /var/folders/h2/q9ywrcbs6w327h78fljhbv280_x7vl/T/4ADB341C-5CC4-43C7-BF5B-F16A1E082537-12863-000012B5333F73A5/DeviceAgent-Runner.app
  2016-10-05 10:26:43.214 iOSDeviceManager[12863:237303] ERROR: Could not find any Provisioning Profiles suitable for resigning
  2016-10-05 10:26:43.214 iOSDeviceManager[12863:237303] ERROR:       identity: #<CodesignIdentity: 2A71F370008BA750ADC8EE82F181190910C3DE0A : iPhone Developer: tvxaut...@gmail.com (W95FEZS38E)>
  2016-10-05 10:26:43.214 iOSDeviceManager[12863:237303] ERROR:    device UDID: 9ef528263f678e344c12a2eb922653c217e34177
  2016-10-05 10:26:43.214 iOSDeviceManager[12863:237303] ERROR:            app: /var/folders/h2/q9ywrcbs6w327h78fljhbv280_x7vl/T/4ADB341C-5CC4-43C7-BF5B-F16A1E082537-12863-000012B5333F73A5/DeviceAgent-Runner.app
```

**Comment by alatem1** [comment]
I have the same issue, then I had to remove XCODE 8 and reinstall 7.3.1 :(

**Comment by RuudPuts** [comment]
@sbalajieie @alatem1 check out https://github.com/calabash/ios-10-support-doc for tips on running with iOS 8.
The reason the code sign identity is necessary is to resign the DeviceAgent helper app so it can run on your device. A development signing identity is recommended. Provisioning profiles also need to be available, usually located in ~/Library/MobileDevice/Provisioning Profiles.

**Comment by jmoody** [comment]
@sbalajieie  It took me 10 minutes to reformat the information you posted into something I could get information out of.  Please take more time when creating issues.

```
# I think this is probably incorrect - this will work at some point, but I do not think it works now. 
$ export APP=/Users/bsc/Documents/workspace/mobile-automation/iOS/tablets/master_Debug.ipa

# Do this instead when targetting a physical device.
$ export APP=com.example.YourApp
```

The root of the problem is that your machine does not have provisioning profile that can be used to sign the DeviceAgent-Runner.app.

There are couple of reasons this might be happening:

1. You have no profile that includes the target device.
2. You have no profile that includes the certificate (code sign identity) you are trying to sign with.
3. There is bug in our code signing algorithm (100% possible).

As I recommended in Gitter, on the developer portal create a wildcard provisioning profile that:

1. includes your device (or devices)
2. is signed with a certificate that is installed on your machine

In the next release of run-loop (2.2.2) we have improved the code signing algorithm, but I am not sure it will fix your problem.

**Comment by redjames** [comment]
I'm getting this error when I run my scripts:
```
NoMethodError: undefined method `[]' for #<RunLoop::DeviceAgent::Client:0x007fd2fb0c5078>
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/launcher.rb:81:in `to_s'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/launcher.rb:92:in `inspect'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/run_loop-2.2.1/lib/run_loop/patches/awesome_print.rb:13:in `awesome_self'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:36:in `format'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:148:in `unnested'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:115:in `awesome'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:33:in `output_value'
       	from /Users/james/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

Versions:
```
calabash-cucumber: 0.20.3
run_loop: 2.2.2
MacOSX: 10.11.6
iOS: 10.1.1
XCode: 8.1
calabash framework on IPA: 19
calabash-ios: 0.19.2
```

Variables:
```
export DEVICE_TARGET="UDID of device"
export DEVICE_ENDPOINT=http://x.x.x.154:37265
export LC_ALL="en_US.UTF-8"
export RESET_BETWEEN_SCENARIOS=1
export CODE_SIGN_IDENTITY="iPhone Developer: XxxXxx (8W82G439V2)" \
```

Please, help :(

**Comment by TeresaP** [comment]
@redjames Couple things. One: I don't think your problem applies to the issue above, so you should open a new issue. Two: Your versions you list don't seem to match up with your log. Maybe your upgrade didn't go through.

**Comment by redjames** [comment]
Hi, @TeresaP, thank you for the answer. You're right, I didn't realize about the versions. I'll try to do again the upgrade and check it. If I get the same error again, I'll open a new issue. Regards.

**Comment by jmoody** [comment]
@TeresaP Thanks.

@redjames I am deleting your comments because I see you made a new issue.

**Comment by jmoody** [comment]
The next version of run-loop will have a possible fix.

**Comment by jmoody** [comment]
I believe this is fixed.

**Comment by alatem** [comment]
Hi,

I have this problem when try start server calabash iOS.
OSX: Sierra 10.12
Xcode 8.2
iPhone OS 10.

Note, That was running very nice but I don´t know what happens. Help me please!

calabash-ios 0.20.4> start_test_server_in_background
RuntimeError:

Could not install /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:

Could not resign app bundle at path:
    /private/var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest
with command:
    /usr/bin/xcrun codesign --verbose=4 --verify /private/var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent
=== STDERR ===
/private/var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent: CSSMERR_TP_NOT_TRUSTED
In architecture: armv7

Error creating product bundle for /var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app: Error Domain=com.facebook.XCTestBootstrap Code=0 "Failed to codesign /var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app" UserInfo={NSLocalizedDescription=Failed to codesign /var/folders/g7/_ddb2l8500l2ynjg0h6z63kw0000gn/T/6CE3B661-4AFB-4444-B465-D0F00155BA94-44988-00000124A2D41E6D/DeviceAgent-Runner.app, NSUnderlyingError=0x7fbc02dc1e80 {Error Domain=sh.calaba.iOSDeviceManger Code=5 "Code signing failed" UserInfo={NSLocalizedDescription=Code signing failed, NSLocalizedFailureReason=There was a problem code signing. Please check the logs.}}}

	install
		-d,--device-id	<device-identifier>	iOS Simulator GUIDs
		-a,--app-bundle	<path/to/app-bundle.app>	Path .app bundle (for .ipas, unzip and look inside of 'Payload')
		-c,--codesign-identity	<codesign-identity> [OPTIONAL] 	Identity used to codesign app bundle [device only]	DEFAULT=
		-u,--update-app	<true-or-false> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1


	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop/device_agent/ios_device_manager.rb:133:in `launch'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop/device_agent/client.rb:1219:in `launch_cbx_runner'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop/device_agent/client.rb:252:in `launch'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop/device_agent/client.rb:128:in `run'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/run_loop-2.2.4/lib/run_loop.rb:113:in `run'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from /Users/chris/.rvm/gems/ruby-2.3.3/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from /Users/chris/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'

**Comment by jmoody** [comment]
@alatem1 

I am very interested in your code signing problem.  However, this issue is closed.

Please open a new issue.
