### ISSUE TITLE
latest xcode, ios 10, swift 3 - cannot access queries

### ISSUE THREAD

**Issue by AndreiD** [calabash/calabash-ios#1196]
Having the latest. All works, I can run tests but I cannot access the console. Everything is from the official tutorials. gems etc. with the latest stuff.

~~~~
source "https://rubygems.org"
gem "calabash-cucumber", ">= 0.16", "< 2.0"
~~~~

~~~~
dans-iMac:TearBud dan$ DEBUG=1 bundle exec calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
NameError: undefined local variable or method `start_test_server_in_background' for main:Object
	from (irb):1
	from /Users/dan/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'
irb(main):002:0> 
~~~~

any ideas ?

**Comment by jmoody** [comment]
What version of Calabash iOS are you using?  

> .irbrc and rvm

The calabash console is an IRB that loads a special .irbrc file that is shipped in the Calabash iOS gem.

RVM, by default, uses a `~/.irbrc` which overrides the correct .irbrc file.

Try:

```
$ IRBRC="" DEBUG=1 bundle exec calabash-ios console
```

If you have the option, I recommend switching to rbenv.

**Comment by AndreiD** [comment]
thanks for responding. I tried it but same problem. How do I check the calabash ios version ?

**Comment by jmoody** [comment]
Other things to try:

```
# 1. Figure out how to configure rvm _not_ to use ~/.irbrc

# 2. Unset the IRBRC variable in the shell
$ unset IRBRC
$ bundle exec calabash-ios console

# 3. Copy the Calabash .irbrc to a local .irbrc file
$ IRBRC=.irbrc bundle exec calabash-ios console
https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/scripts/.irbrc

# 4. Switch to rbenv
```

Other than that, I am afraid I cannot help.
