### ISSUE TITLE
Xcode 8: tap_keyboard_action_key on the keyboard doesn't work in all cases e.g. Search button

### ISSUE THREAD

**Issue by kateryna-streltsova** [calabash/calabash-ios#1198]
Details: 
calabash-cucumber (0.20.0)
iOS simulator
xCode 8

Hi, I'm trying to perform a search in the app and click Search button on the appeared simulator's keyboard.
<img width="961" alt="screen shot 2016-10-10 at 17 04 44" src="https://cloud.githubusercontent.com/assets/5736987/19242660/1631dce4-8f0c-11e6-9e6a-4ff846d7c9a5.png">

I used to use calabash predefined step - step 'I touch search', but it doesn't work for instruments of Xcode 8

tap_keyboard_action_key - works on xCode 7, doesn't work on xCode 8
step 'I touch search' - works on xCode 7, doesn't work on xCode 8
keyboard_enter_char("Return") - works on both -  xCode 7 and  xCode 8

First two commands just simply don't click the button. Based on Joshua's reply last option is not recommended to use, so could you please have a look why first two don't work?

Thanks,
Kate

**Comment by jmoody** [comment]
Thanks for taking the time to make an issue.

> predefined steps

We recommend that you do use the predefined steps.  Write your own steps that are specific to your application.

> tap_keyboard_action_key does not work

I think I see the problem.  Can you paste here the output of:

```
query("* isFirstResponder:1")
```

when this view is showing with the keyboard?

**Comment by ark-konopacki** [comment]
@jmoody few fords from me
`tap_keyboard_action_key` doesn't work for me too 
it result `"status" => "success"` but button doesn't touched and keyboard still visible 
and `keyboard_enter_char("Return")` work as expected 

output `query("* isFirstResponder:1")`
```
[
    [0] {
                          "id" => "topBarSearchTextField",
                 "description" => "<HSIUITextField: 0x7fb35af6b2e0; baseClass = UITextField; frame = (55 21; 270 50); text = 'Test'; opaque = NO; tintColor = UIExtendedSRGBColorSpace 0.00392157 0.0431373 0.117647 1; gestureRecognizers = <NSArray: 0x600000a58ea0>; layer = <CALayer: 0x608000a37300>>",
                       "label" => nil,
                       "frame" => {
                 "y" => 21,
                 "x" => 55,
             "width" => 270,
            "height" => 50
        },
        "accessibilityElement" => false,
                       "value" => "Test",
                       "alpha" => 1,
                     "enabled" => true,
                     "visible" => 1,
                        "text" => "Test",
                       "class" => "HSIUITextField",
                    "selected" => false,
                        "rect" => {
                   "y" => 21,
            "center_x" => 190,
            "center_y" => 46,
                   "x" => 55,
               "width" => 270,
              "height" => 50
        }
    },
    [1] {
                          "id" => nil,
                 "description" => "<UIFieldEditor: 0x7fb35be72c00; frame = (0 0; 270 50); text = 'Test'; clipsToBounds = YES; opaque = NO; gestureRecognizers = <NSArray: 0x608001047e30>; layer = <CALayer: 0x600000837a00>; contentOffset: {0, 0}; contentSize: {270, 50}>",
                       "label" => nil,
                       "frame" => {
                 "y" => 0,
                 "x" => 0,
             "width" => 270,
            "height" => 50
        },
        "accessibilityElement" => false,
                       "value" => "Test",
                       "alpha" => 1,
                     "enabled" => true,
                     "visible" => 1,
                        "text" => "Test",
                       "class" => "UIFieldEditor",
                        "rect" => {
                   "y" => 21,
            "center_x" => 190,
            "center_y" => 46,
                   "x" => 55,
               "width" => 270,
              "height" => 50
        }
    }
]
```

**Comment by ark-konopacki** [comment]
@jmoody ok i find the issue :)
https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/automator/device_agent.rb#L277

should be 
`value = client.touch({type: "Button", marked: mark})` 
instead of 
`value = client.touch({marked: mark})` 

because in case `mark` is `Search` and we have field marked `Search` it will touch field instead of key. Can open PR if you approve this solution.

**Comment by jmoody** [comment]
@ark-konopacki Good sleuthing.

PR would be great.

I also noticed another problem whereby no search key cannot be found.  I will fix that.

**Comment by kateryna-streltsova** [comment]
Thanks, guys. Just tried to change to value = client.touch({type: "Button", marked: mark})   and tap_keyboard_action_key is working now for xCode 7 and 8

**Comment by jmoody** [comment]
@kateryna-streltsova 

> Szukaj

What is the language? Polish?

In all the localizations I test against (German, French, Danish, and English), this key has a non-localized mark of "Search" (as well as the localized text).

I think the real problem is that first responder (the text input field) is not a subclass of UITextField or UITextView.

See [device_agent:454](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/automator/device_agent.rb#L454).

With the keyboard showing, can you run:

```
> query("UITextField isFirstResponder:1")
> query("UITextView isFirstResponder:1")
```

and paste the result into this issue?

**Comment by ark-konopacki** [comment]
@jmoody it was mine keyboard with `Szukaj` and yes it is polish ;)
but with my update it work without any issues

**Comment by jmoody** [comment]
@ark-konopacki @kateryna-streltsova I believe this is fixed in the develop branch.  Ping me if not.
