### ISSUE TITLE
device_agent.query_for_coordinate fails to work on a last element of UICollectionView

### ISSUE THREAD

**Issue by xiannicolae** [calabash/calabash-ios#1203]
Hi,

I have menu layer and it looks like `device_agent.query_for_coordinate` is not working on the last element.

```
calabash-ios 0.20.0> device_agent.query_for_coordinate({marked: "NAME"})
INFO: Embed is not available in this context. Will not embed.
RuntimeError:

Waited 15 seconds for

{:marked=>"NAME"}

to match a view.


    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/failure_helpers.rb:75:in `screenshot_and_raise'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/failure_helpers.rb:88:in `fail'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/device_agent.rb:341:in `rescue in fail_with_screenshot'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/device_agent.rb:338:in `fail_with_screenshot'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/device_agent.rb:129:in `query_for_coordinate'
    from (irb):1228
    from /usr/local/var/rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

```
calabash-ios 0.20.0> element_exists("* marked: 'NAME'")
true
```

I followed the pan Gesture example from https://github.com/calabash/calabash-ios/wiki/DeviceAgent.

**Comment by jmoody** [comment]
What is the use case?  Can you explain the gesture you are trying to perform and how it fails?

If element_exists is returning true then the LPServer (Calabash iOS Server) can find the element.

You should not need to call `device_agent.query_for_coordinate`.

**Comment by xiannicolae** [comment]
Hi @jmoody ,

I have a horizontal scrolable menu layer and I need to pan right to the last element (not in view). Until this point is all good.

However, when I try to pan back to the first element, for some reasons this is not working anymore. I changed that command with `query("* marked: '#{init_point}'").first["rect"]`, but I noticed that pan gesture is slower now, plus I need to adjust the panning method and the one's using it, in order to make it work again.

**Comment by jmoody** [comment]
Have tried the `scroll_to` API:

* [scroll_to_collection_view_item](http://calabashapi.xamarin.com/ios/Calabash/Cucumber/Core.html#scroll_to_collection_view_item-instance_method)
* [scroll_to_collection_view_item_with_mark](http://calabashapi.xamarin.com/ios/Calabash/Cucumber/Core.html#scroll_to_collection_view_item-instance_method)

These were updated in 0.20.0

**Comment by jmoody** [comment]
Closing.  Only use `device_agent#` methods if absolutely necessary.  In this case, you can probably use the `Core#scroll_to*` methods.  As you mentioned, you will probably need to update your `pan` arguments when running on Xcode 8 (DeviceAgent only).
