### ISSUE TITLE
device_agent error - undefined method 'ai'

### ISSUE THREAD

**Issue by daviejaneway** [calabash/calabash-ios#1208]
Hi there,

I've recently upgraded to the latest calabash release for Xcode 8 support. I'm having some trouble with device_agent. Specifically, when I call device_agent from either the console or cucumber i get this error:

```
NoMethodError: undefined method `ai' for #<Calabash::Cucumber::DeviceAgent:0x007f9489d93558>
    from /Users//.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
    from /Users//.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:33:in `output_value'
    from /Users//.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

calabash-ios version = 0.20.3
run_loop version = 2.2.2
awesome_print version = 1.7.0

Any help would be greatly appreciated.

**Comment by jmoody** [comment]
Can you show the exact command you calling?

Is is just:

```
> device_agent
```

**Comment by jmoody** [comment]
I believe `ai` is defined in the `briar` gem.  Are you using the briar gem?  Are you using `bundle exec calabash-ios console` to start the IRB?

**Comment by daviejaneway** [comment]
Hi @jmoody. Thanks for the reply. I have just installed briar and am seeing the same issue.

The error seems to be coming from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb This file defines the following method:

```
def ap(object, options = {})
    puts object.ai(options) # MY PATCH -> unless defined?(object.ai).nil?
    object unless AwesomePrint.console?
end
```

This looks like it handles irb output. The problem occurs when device_agent gets passed in here (e.g. by calling `device_agent` in the calabash console). device_agent isn't a normal object by the looks of it (is it a method?). I've patched this by basically preventing `ap` from running if `ai` is not defined on the input. This isn't really a solution though.

Weirdly, the console autocompletes `device_agent.wait_for...` but when I call, say, `device_agent.wait_for_view`, I get method missing.

It feels like I might be missing a dependency somewhere. I'm not sure it should be hitting awesome_print's `ap` method. Are `ai` & `ap` overridden elsewhere in the dependency chain?

**Comment by jmoody** [comment]
> briar

Do not use briar.  There is an `ai` console method in briar.  I regret mentioning briar.

> awesome print

There is a bug in awesome print 1.7.0.  

https://github.com/awesome-print/awesome_print/pull/212

This fix has not been released, but can be found in awesome-print/master

I will explore a patch.

**Comment by daviejaneway** [comment]
Aha! That looks like the one. Really appreciate your help there.

**Comment by jmoody** [comment]
As heads up, I am having trouble with the irb because I recently updated `homebrew` and the location of the readline library changed.  I compiled and installed my ruby with rbenv using the `--with-readline-dir` option.

I will post a wiki page about this at some point (the page is in progress).

**Comment by jmoody** [comment]
Sadly, there is no simple patch.  Will be fixed in the run-loop release.

> Weirdly, the console autocompletes device_agent.wait_for...

The Calabash::Cucumber::DeviceAgent API is limited - it does not include a `wait_*` API.

http://calabashapi.xamarin.com/ios/Calabash/Cucumber/DeviceAgent.html

Use the `Core#wait_*` API and call `device_agent` methods from the block.

There is a problem with the auto completion for the DeviceAgent class.

**Comment by daviejaneway** [comment]
Ok, cool. I think my understanding of device_agent was slightly off as well. The `Core#wait_*` API is working nicely for me.

**Comment by jmoody** [comment]
> tab completion

IRB: tab completion is incorrect for device_agent object #1213

**Comment by jmoody** [comment]
Fixed
