### ISSUE TITLE
Could not connect to the Calabash Server iOS10 xCode 8

### ISSUE THREAD

**Issue by noahmalmed** [calabash/calabash-ios#1212]
Hello,

I am getting a connection timeout when I try to run my tests, specifically when I run `Calabash::Cucumber::Launcher`'s method `relaunch`. Here is what the error log says.

>  Could not connect to the Calabash Server @ http://127.0.0.1:37265/.
> 
> ` See these two guides for help.
> - https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
> - https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators
> 1. Make sure your application is linked with Calabash.
> 2. Make sure there is not a firewall blocking traffic on http://10.0.4.31:37265/.
> 3. Make sure http://10.0.4.31:37265/ is correct.
>    
>    If your app is crashing at launch, find a crash report to determine the cause.
>    
>    (Calabash::Cucumber::ServerNotRespondingError)
>    ./features/support/launch.rb:44:in `Before'`

 I am able to build the -cal target and when I run it from xcode I see:

> 2016-10-21 11:03:14.567 DEBUG CalabashServer:252 | Creating the server: <LPHTTPServer: 0x608000151eb0>
> 
> 2016-10-21 11:03:14.568 DEBUG CalabashServer:253 | Calabash iOS server version: CALABASH VERSION: 0.20.3
> 
> 2016-10-21 11:03:14.568 DEBUG CalabashServer:256 | App Base SDK: iphonesimulator10.0
> 
> 2016-10-21 11:03:14.569 DEBUG CalabashServer:288 | IPHONE_SIMULATOR_ROOT: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
> 
> 2016-10-21 11:03:14.587 DEBUG CalabashServer:274 | Calabash iOS server is listening on: 10.0.4.31 port 37265

Even more, I am able to successfully run `start_test_server_in_background` in `calabash-ios console` and run  a `query` command. 

Here is the ruby code that is causing the error

```
Before do |scenario|
@calabash_launcher = Calabash::Cucumber::Launcher.new 
 if ENV['NO_STOP'] == "1"
    # Only notify because we don't want the app to restart
    @calabash_launcher.calabash_notify(self)
  else
    @calabash_launcher.relaunch
    @calabash_launcher.calabash_notify(self)
  end
end
```

Any idea on what is going on here?

**Comment by jmoody** [comment]
At first glance, it looks like the application has not been launched.

The `NO_STOP` check is passing, but the app has not been launched.

I think you need to update your hooks.  Here are some examples:

* [calabash-cucumber/test/cucumber/features/support/01_launch.rb](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/test/cucumber/features/support/01_launch.rb) 
* [CalSmokeApp](https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/support/01_launch.rb)

### Not related to your problem, things you should know about:

> NO_STOP

This variable is going to replaced with `QUIT_APP_AFTER_SCENARIO` or something similar.

> calabash_notify

There is no need to call `calabash_notify`.  This will be done at the correct time in the `Launcher#relaunch` method.
