### ISSUE TITLE
including Calabash::Cucumber::Operations causes Cucumber embed to raise a SystemStackError

### ISSUE THREAD

**Issue by werner77** [calabash/calabash-ios#1214]
With Cucumber 2.4.0:

I noticed that when calling embed (e.g. from screenshot_embed), a method which is dynamically added via operations.rb, this results in a SystemStackError (stack level to deep), because an infinite recursion occurs.

This happens because embed calls Cucumber::RbSupport::RbWorld:embed which delegates to formatters. If any of those formatters does not define embed, I guess the operations.rb dynamic method fix kicks in again which results in the inifinite recursion.

**Comment by jmoody** [comment]
Can you reproduce in cucumber < 2.4?

Thanks.

**Comment by werner77** [comment]
Yes also crashes in 2.3.3 with same error.

**Comment by werner77** [comment]
Update: 

The behaviour as specified above was cause by an import in our code:

include Calabash::Cucumber::Operations

It seems the this caused the embed method to suddenly be included everywhere which caused the SystemStackError. However, it feels like a hack. Maybe something to improve?

**Comment by jmoody** [comment]
> hack

It is 100% a hack.

> improve

Calabash 2.0 does a better job handling this problem.

**Comment by werner77** [comment]
Yes also cucumber 2.3.3

**Comment by jmoody** [comment]
> include Calabash::Cucumber::Operations

Just to be clear, you have resolved this problem right?

If you need to include `Operations` can you explain the use case?  A code same would be helpful.

**Comment by werner77** [comment]
Yes removing the import solved the problem, I'm not really sure why the import was there but it doesn't seem to break anything by removing it
