### ISSUE TITLE
Calabash can't dismiss Photo spring-board alert in German

### ISSUE THREAD

**Issue by JoeSSS** [calabash/calabash-ios#1219]
Looks like wording for this alert is different between iOS 10.0 and iOS 10.1. 

@jmoody :
```
            # Pre iOS 10?
             alert(@"Ja", YES, @"auf Ihre Fotos zugreifen"),
             # iOS >= 10?
             alert(@"OK", YES, @"möchte auf deine Fotos zugreifen"),
```

**Comment by jmoody** [comment]
Fixed by **Update SpringBoard alert definitions for iOS 10** [#175](https://github.com/calabash/DeviceAgent.iOS/pull/175)

Will be available in run-loop 2.2.3
