### ISSUE TITLE
calabash-iso 0.20.0(include 0.20.3) keyboard_enter_text not work in alert dialog input views

### ISSUE THREAD

**Issue by DoubleJ2011** [calabash/calabash-ios#1220]
=========================================================

xcode： 8.0
iOS device os: 10.0.1
calabash-ios: 0.20.0

Baisc Info:

$ xcode-select --print-path

/Applications/Xcode.app/Contents/Developer

$ xcodebuild -version

Xcode 8.0

Build version 8A218a

curl http://{ip}:37265/version

{"device_family":"iPod touch","outcome":"SUCCESS","server_port":37265,"simulator_device":"","simulator":"","app_name":"{my app}","app_version":"{my app version}","screen_dimensions":{"native_scale":2,"sample":1,"height":1136,"width":640,"scale":2},"git":{"revision":"3427493","remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master"},"device_name":"{my device}","4inch":false,"app_id":"{my app bundle id}","form_factor":"iPod7,1","system":"iPod7,1","version":"0.20.0","iOS_version":"10.0.1","short_version_string":"3.4","ios_version":"10.0.1","iphone_app_emulated_on_ipad":false,"model_identifier":"iPod7,1","app_base_sdk":"iphoneos10.0"}

=========================================================

Problems:

1. All calabash-ios features works well before upgrade device to iOS 10 and xcode to 8.0.

2. For my target app need to upgrade xcode 8.0 to build to support iOS 10. So upgrade calabash-iOS to 0.20.0, xcode to 8.0, run_loop: 2.2.1

3. Try to running features, keyboard enter text work well but can NOT enter text into alert dialogs.
4. Try to use "bundle exec calabash-ios console" and do some operations to pop up dialog which need to input some text.
5. Then try "keyboard_enter_text("text")", no any error pop up, but from device, not input text, but click "Cancel" button.
 
 
=========================================================
Upgrade to 0.20.3, still can NOT work. Include keyboard_enter_char("Return") also click Cancel button.

Now, I use set_text(query,text) can work. While if I want to test click action key, can NOT work.

**Comment by jurvis** [comment]
I'm having similar issues with entering text in UIAlertView dialogs. Calling `keyboard_enter_text` just dismisses the dialog right away.

**Comment by jmoody** [comment]
When reporting issues with UIAlertViews, please paste a screenshot of the alert view.

One of our test apps now has an Alert with text fields and we have a third-party app with such an alert view.  We have a fix that will be available in run-loop 2.2.3.
