### ISSUE TITLE
Calabash can't dismiss Apple Music/Media Library spring-board

### ISSUE THREAD

**Issue by traluzzatheking90** [calabash/calabash-ios#1221]
* Springboard alert title: `Would Like to Access Apple Music And Your Media Library`
* calabash ios version: 0.20.3
* ruby version: 2.3.1p112
* Xcode Version 8.0
* iOS Simulator Version 10.0

Further information: https://groups.google.com/forum/?fromgroups#!topic/calabash-ios/HLHw1vBc0ow

**Comment by jmoody** [comment]
@traluzzatheking90 We need the button titles as well - the error contains all the information you need.

**Comment by jmoody** [comment]
I _think_ we can get this into run-loop 2.2.3, but I am not sure.

**Comment by traluzzatheking90** [comment]
@jmoody 
Hy Jmoody,
this is the error :

{"title"=>"“MyApp” Would Like to Access Apple Music And Your Media Library", "buttons"=>["Don’t Allow", "OK"], "tries"=>20, "error"=>"A SpringBoard alert is blocking test execution and it cannot be dismissed."}

thanks for collaboration.
I was trying to fix  by myself in the run-loop project but I did not understand how to generate new DeviceAgent-Runner.app. 

Anyway thanks for your support.

**Comment by jmoody** [comment]
Thanks for the update.

> generate new DeviceAgent-Runner.app.

The DeviceAgent repo is closed source at the moment.   We have plans to open source at some point.

**Comment by jmoody** [comment]
@traluzzatheking90 Should the alert be dismissed with `Don't Allow` or `OK`?

**Comment by traluzzatheking90** [comment]
Thanks Jmoody. The alert should be dismissed with OK button. 
thanks for your support

**Comment by jmoody** [comment]
Fixed in run-loop 2.2.4.
