### ISSUE TITLE
start_test_server_in_background fails after upgrading to Xcode 8.1

### ISSUE THREAD

**Issue by rahulgautam** [calabash/calabash-ios#1222]
Having this problem since upgraded to Xcode 8.1 while running _start_test_server_in_background_ or running bundle exec cucumber feature

I am running simulator with iOS 9.3

**calabash-ios 0.20.3> start_test_server_in_background**

EXEC: xcrun simctl list devices --json
DEBUG: Sending 'TERM' to Simulator.app process '63794'
DEBUG: Waiting for Simulator.app with pid '63794' to terminate
DEBUG: Waited for 0.114037 seconds for Simulator.app with pid '63794' to terminate
DEBUG: Sending 'TERM' to apsd process '63968'
DEBUG: Waiting for apsd with pid '63968' to terminate
DEBUG: Waited for 0.101172 seconds for apsd with pid '63968' to terminate
DEBUG: Launching #<Simulator: iPhone 7 (10.1) 7136BD61-F03C-43FF-8189-FF838BA61869 x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 7136BD61-F03C-43FF-8189-FF838BA61869
DEBUG: Waiting for simulator to stabilize with timeout: 30 seconds
DEBUG: Waited for 10.014618 seconds for 'com.apple.audio.SystemSoundServer-iOS-Simulator' to start.
DEBUG: Timed out after 30 seconds waiting for simulator to stabilize
DEBUG: Took 32.204236 seconds to launch the simulator
EXEC: xcrun simctl install 7136BD61-F03C-43FF-8189-FF838BA61869 /Users/rahul/Library/Developer/Xcode/DerivedData/Cx-dtragphajbhvbpbxnemdrpglrhij/Build/Products/Debug-iphonesimulator/MyApp.app
DEBUG: Waiting for simulator to stabilize with timeout: 30 seconds
DEBUG: Waited for 10.120868 seconds for 'com.apple.audio.SystemSoundServer-iOS-Simulator' to start.
DEBUG: Waited a total of 30.511652 seconds for simulator to stabilize
DEBUG: HTTP: get http://127.0.0.1:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
EXEC: cd /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent
EXEC: ditto -xk Frameworks.zip .
EXEC: ditto -xk DeviceAgent-Runner.app.zip .
ArgumentError: App does not exist at path or is not an app bundle.

/Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/app/DeviceAgent-Runner.app

Bundle must:

1. be a directory that exists,
2. have a .app extension,
3. contain an Info.plist,
4. and the app binary (CFBundleExecutable) must exist

	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/app.rb:19:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/ios_device_manager.rb:86:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/ios_device_manager.rb:86:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:1233:in `launch_cbx_runner'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:264:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:140:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.2/lib/run_loop.rb:113:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
calabash-ios 0.20.3>

**Comment by jmoody** [comment]
Apple system ruby is no longer supported.

We recommend using rbenv.

* https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS
* https://github.com/calabash/calabash-ios/wiki/rbenv-guide
