### ISSUE TITLE
uia(%[uia.selectPickerValues('{<index> "<value>"}')])  alternate to Device_Agent

### ISSUE THREAD

**Issue by tapthaker** [calabash/calabash-ios#1223]
Earlier it was possible to execute UIAutomation queries using Calabash, which allowed us to select values for UIPickerViews, but now I cannot see an API that does this. 

I tried using the programmatic approach but the delegate methods will not be called that way (I know it's an expected behavior) 

```ruby
Calabash::Cucumber::Map.raw_map("UIPickerView", "selectRow:inComponent:animated:", 3, 0, true)
```

It is simple to tap on an element if there are only 2 or 3 elements, but if the UIPickerView has many elements eg: months in a year, this is not possible.

There are already closed issues around this but they seem to have found solutions when only 2 - 3 elements are present in the PickerView.

**Comment by tapthaker** [comment]
Referencing closed issues:
https://github.com/calabash/calabash-ios/issues/1183
https://github.com/calabash/calabash-ios/issues/1182

**Comment by jmoody** [comment]
> "selectRow:inComponent:animated:", 3, 0, true

That is not the correct API ^

```
# Try
[{selectRow:3, inComponent:0, animated:true}]
```

**Comment by tapthaker** [comment]
Didn't understand, are you talking about this to work with Calabash Server using rawMap or by using DeviceAgent.

It is straightforward to select an element from UIPickerView using XCUITest but it is unclear how DeviceAgent interfaces with XCUITest. Some documentation on this would be helpful.

**Comment by jmoody** [comment]
@tapthaker 

> raw Map or DeviceAgent

Neither.  Use query.  Don't call Map.raw_map.

```
query("UIPickerView", [{selectRow:3, inComponent:0, animated:true}]
```

https://github.com/calabash/calabash-ios/wiki/Calabash-iOS-Ruby-API#query

**Comment by tapthaker** [comment]
The following code worked for me 
```ruby 
query("UIPickerView", [{selectRow:10},{inComponent:0},{animated:true}])
```

From my understanding query function internally calls the raw_map function which then talks to Calabash Server & executes the Objective-C function. The problem is that if I take this approach the delegate methods of UIPickerView are not called thus not setting the respective values.

**Comment by jmoody** [comment]
You understand correctly.

And your point about delegate methods is correct.

Our UIDatePicker API _does_ ensure delegate methods are called.

We could update the LPServer to handle UIPickerViews.

In the short term, have you tried calling the delegate method directly?

```
query("UIPickerView", :delegate, [{pickerView:nil} < other args > ])
```

**Comment by tapthaker** [comment]
Interesting never thought of it this way. Calling the delegate directly is not something we want, still a good idea for sure. However, I went up implementing something like this:

```ruby
def select_menu_item_in_drop_down(select,choice)
   query("UIPickerView", [{selectRow:0},{inComponent:0},{animated:false}])

    wait_poll(:until_exists => "UIPickerColumnView index:0 label marked:'#{choice}'",
              :timeout => 60,
              timeout_message: "Unable to find element after scrolling down '#{choice}'") do
      tap_mark query("UIPickerColumnView index:0 label", :text).last
    end

   touch("UIPickerColumnView index:0 label marked:'#{choice}'")
end
```

**Comment by jmoody** [comment]
@tapthaker Cool.

I think the LPServer should have a native PickerView API like it has for UIDatePicker.
