### ISSUE TITLE
DeviceAgent can not dismiss Permissions Alerts in Portuguese

### ISSUE THREAD

**Issue by oscartanner** [calabash/calabash-ios#1226]
Calabash can not dismiss Permissions Alerts (spring-board) in Portuguese.
To solve these problems in older versions of iOS SDK, I created a Pull Request for run_loop, [#563](https://github.com/calabash/run_loop/pull/563), with these translations.
The messages are:

```
{"title"=>"Permitir que “Permissions” tenha acesso à sua localização enquanto você usa o aplicativo?", "buttons"=>["Não Permitir", "Permitir"]"}
{"title"=>"Permitir que “Permissions” tenha acesso à sua localização mesmo quando você não estiver usando o aplicativo?", "buttons"=>["Não Permitir", "Permitir"]}
{"title"=>"“Permissions” Deseja Ter Acesso aos Seus Contatos", "buttons"=>["Não Permitir", "OK"]}
{"title"=>"“Permissions” Deseja Ter Acesso ao Seu Calendário", "buttons"=>["Não Permitir", "OK"]}
{"title"=>"“Permissions” Deseja Ter Acesso aos Seus Lembretes", "buttons"=>["Não Permitir", "OK"]}
{"title"=>"“Permissions” Deseja Ter Acesso às Suas Fotos", "buttons"=>["Não Permitir", "OK"]}
{"title"=>"“Permissions” Deseja Ter Acesso à Câmera", "buttons"=>["Não Permitir", "OK"]}
{"title"=>"“Permissions” Deseja Enviar Notificações", "buttons"=>["Não Permitir", "Permitir"]}
```

All messages came from executions of the Permissions.app in an iPhone 7 simulator, running iOS 10.1. I could not run Permissions.app in a device. Ruby version 2.3.1p112 and calabash-ios 0.20.3.

**Comment by jmoody** [comment]
I added the localizations to DeviceAgent.  Thank you very much.

**Comment by oscartanner** [comment]
Thank you very much.

**Comment by oscartanner** [comment]
@jmoody Sorry, my bad! I forgot to add one localization.
For iOS <= 9.3, the push notification alert is different

```
{"title"=>"“Permissions” Deseja Enviar-lhe Notificações", "buttons"=>["Não Permitir", "OK"]}
```

I added this localization in the run_loop PR, but forgot to add it here.

Thank you very much.

**Comment by jmoody** [comment]
Captured.

**Comment by oscartanner** [comment]
Thank's
