### ISSUE TITLE
Unable to get URL for WKWebView

### ISSUE THREAD

**Issue by kateryna-streltsova** [calabash/calabash-ios#1231]
I'm trying to get a URL of WKWebView like query("WKWebView", :request) and get a result "*****" instead of URL. It used to work with usual WebView.
Details:
calabash-ios 0.20.3
simulator iphone 7, 10.1

calabash-ios 0.20.3> query("WKWebView")
[
    [0] {
                       "alpha" => 1,
                     "enabled" => true,
                          "id" => nil,
                     "visible" => 1,
                       "frame" => {
                 "y" => 0,
                 "x" => 0,
             "width" => 375,
            "height" => 603
        },
        "accessibilityElement" => false,
                       "class" => "WKWebView",
                       "label" => nil,
                 "description" => "<WKWebView: 0x7f83a988f400; frame = (0 0; 375 603); layer = <CALayer: 0x600000a22080>>",
                       "value" => nil,
                        "rect" => {
                   "y" => 64,
            "center_x" => 187.5,
            "center_y" => 365.5,
                   "x" => 0,
               "width" => 375,
              "height" => 603
        }
    }
]

**Comment by jmoody** [comment]
```
query("WKWebView", :request)
```

This means, "Find all views with class WKWebView and call the Objective-C selector: request on each one and return the result".

> "*****" 

This means that WKWebView does not respond the Objective-C selector `request`.

Looking at the WKWebView API, I can see that `request` is not part of the API.
