### ISSUE TITLE
Cannot start from console - iOS 10

### ISSUE THREAD

**Issue by cd24** [calabash/calabash-ios#1235]
I am trying to use the calabash console to learn the calabash environment. If I run the app from XCode, then I am able to connect to the instance (simulator or device) and run queries. 
However, if I then try to run 
```
start_test_server_in_background
```
without any explicit parameters then calabash successfully finds the correct app bundle:

```
INFO: Detected app at path:
INFO: /Users/jmcavey/Library/Developer/Xcode/DerivedData/MyApp-fvbcqlgqrfukavbjhwdtkejljuvs/Build/Products/Calabash-iphonesimulator/MyApp.app
```

However, when the device_runner attempts to connect it throws the following error:
```
ArgumentError: App does not exist at path or is not an app bundle.

/usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/app/DeviceAgent-Runner.app

Bundle must:

1. be a directory that exists,
2. have a .app extension,
3. contain an Info.plist,
4. and the app binary (CFBundleExecutable) must exist

        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/app.rb:19:in `initialize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/ios_device_manager.rb:86:in `new'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/ios_device_manager.rb:86:in `launch'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:1233:in `launch_cbx_runner'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:264:in `launch'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/client.rb:140:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop.rb:113:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:406:in `times'
        from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
        from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
        from (irb):1
        from /usr/local/bin/irb:11:in `<main>'
```

I have confirmed that all four conditions are met for the app bundle found by calabash.

My environment is configured as follows:

XCode 8.1
ruby 2.3.1p112 (OS X)
Calabash Version 0.20.3

I am using the Calabash scheme as described in https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-Calabash-config

**Comment by jmoody** [comment]
> /usr/local/lib/ruby/gems

This directory is probably write-protected.

**Comment by cd24** [comment]
chowning the directory resolved the issue, thanks!

**Comment by tylerhartwig** [comment]
I am having the exact same problem as outlined here, however I am explicitly declaring the path to my app using the APP environment variable. 

I have 'chown'ed the directory as well. 

Xcode 8.3
ruby 2.3.1p112 (also on latest 2.4.1)
calabash-ios 0.20.4

Any advice?

**Comment by jmoody** [comment]
Xcode 8.3 is not supported yet.

**Comment by onurburakozkan** [comment]
I have the same problem as well. One of my colleague could run calabash although he has Xcode 8.3 on his machine but I can not. I also have the exact setup with @tylerhartwig .

Xcode 8.3
ruby 2.3.1p112 (also on latest 2.4.1)
calabash-ios 0.20.4

**Comment by namburirajesh** [comment]
Please some one help to resolve my issue

My configuration  :
Xcode 8.2.1
ruby 2.3.1p112 
calabash-ios 0.21.4
I have same problem as well . I am pretty new to calabash.This is my first automation IOS App
I have using rbenv for ruby
Please find details of my process below 
1.Installed calabash-cucumber using command "sudo gem install calabash-cucumber"
2.Created Xcode Project of swift
3. Navigate to project folder in terminal and entered command "calabash-iso setup"
4.next i did "calabash-ios gen"
5. Respective GEM files has been created and even i can see .app file in mentioned location
6. I tried command "cucumber" and also DEVICE_TARGET="UUID" bundle exec cucumber
    Below is the error

ArgumentError: App does not exist at path or is not an app bundle.

/usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.2/lib/run_loop/device_agent/app/DeviceAgent-Runner.app

Bundle must:

1. be a directory that exists,
2. have a .app extension,
3. contain an Info.plist,
4. and the app binary (CFBundleExecutable) must exist

**Comment by jmoody** [comment]
> /usr/local/lib/ruby/gems/2.3.0

This directory needs to be writeable.

The solution for this problem is in a comment above.

Please do not post on closed issues.

**Comment by Niko489** [comment]
calabash-ios console
Running irb...

#########################  Useful Methods  ##########################
     ids => List all the visible accessibility ids.
  labels => List all the visible accessibility labels.
    text => List all the visible texts.
   marks => List all the visible marks.
    tree => The app's visible view hierarchy.
   flash => flash(<query>); Disco effect for views matching <query>
 verbose => Turn debug logging on.
   quiet => Turn debug logging off.
    copy => Copy console commands to clipboard.
   clear => Clear the console.

Calabash says, "Let's get this done!"
WARN: 

Connected to an app that was not launched by Calabash using instruments or DeviceAgent.

Queries will work, but gestures and other automator actions will not.


Attached to: #<Launcher: not attached to an automator>


how to solve it???
