### ISSUE TITLE
Calabash 'backdoor' doesn't work with Swift 3.0 iOS 10.1

### ISSUE THREAD

**Issue by PetarBel** [calabash/calabash-ios#1236]
Running calabash v0.20.3, iOS 10.0 under Swift 3.0. 

After following examples here: https://groups.google.com/forum/#!topic/calabash-ios/ZWXBOJ543cc, no success is achieved. 

App Delegate:
```
@objc
class AppDelegate: UIResponder, UIApplicationDelegate {

    @objc
    func calabashBackdoor(params:String) -> String {
        return "success"
    }
   ...
```
Bridging header: 

```
@interface AppDelegate : UIResponder <UIApplicationDelegate>

    - (NSString *)calabashBackdoor:(NSString*)params;

@end
```
After running  `backdoor("calabashBackdoor:", '')` , I get an error  "You must define 'calabashBackdoor:' in your UIApplicationDelegate."

**Comment by gredman** [comment]
Might be due to the new Swift method naming conventions and how they're translated to Obj-C. Does `backdoor("calabashBackdoorWithParams:", '')` work?

**Comment by PetarBel** [comment]
This indeed helps solve the problem. Thank you so much @gredman ! Can you point me to where I can read more about how they are translated to Obj-C ? Best !

**Comment by jmoody** [comment]
Updated backdoor wiki docs.

https://github.com/calabash/calabash-ios/wiki/Calabash-iOS-Ruby-API#backdoor

Thanks.
