### ISSUE TITLE
Evaluate a batch of queries in a single webservice call 

### ISSUE THREAD

**Issue by yamkay** [calabash/calabash-ios#1239]
Hi Team,

Since we do intensive validation for almost all view objects in a screen for each test scenario, it takes more time to complete each scenario due to the network latency in the webservice calls between calabash server and client.

Hence we came up with an idea to batch all the queries in a single request and send it to calabash server and validate the same batch and return the results. We have made the changes on our local copy and willing to contribute to the calabash repository.

I am getting this error while creating the branch feature/batch_query for raising the pull request.

remote: Permission to calabash/calabash-ios.git denied to yamkay.
fatal: unable to access 'https://github.com/calabash/calabash-ios.git/': The requested URL returned error: 403

Could you please guide the process for the same.

Thanks,
Mohan Kumar Selvaraj

**Comment by jmoody** [comment]
You need to create a fork, then a branch on your fork, then submit your pull request.

**Comment by jmoody** [comment]
I think we are not interested in this feature.

You can access child relationships using:

```
http({:method => :get, :path => "dump"})
```

If you want to expose that as a public method, I would consider it.

See: https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/console_helpers.rb#L248
