### ISSUE TITLE
Wrong touch coordinates on large device

### ISSUE THREAD

**Issue by Oopla** [calabash/calabash-ios#1242]
Hello,
I am having issues with the touch command on iDevices with large screens (see list below). It seems that the coordinates are wrong.
The app I'm testing is a webview app and it is not designed for iPad (small button on the bottom right corner to zoom/unzoom x1 or x2).

For example on the screenshot attached, you can see there's a Continue button below a Cancel button. When I request a touch on Continue button, it touches the Cancel button instead.
![app_screenshot](https://cloud.githubusercontent.com/assets/13355747/21045465/c3a5fa22-be00-11e6-8a37-a0f9e25f0868.png)

```
calabash-ios 0.20.3> start_test_server_in_background
DEBUG: HTTP: get http://192.168.2.9:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent-Runner is not running
DEBUG: HTTP: get http://192.168.2.9:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
EXEC: /Users/someuser/.rvm/gems/ruby-2.3.0/gems/run_loop-2.2.3/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id e712d77bfa42bb25cd53ea051ade1b7e22f5f0f7 --app-bundle /Users/someuser/.rvm/gems/ruby-2.3.0/gems/run_loop-2.2.3/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --codesign-identity iPhone Developer: XXXXX<removed>XXXXX
DEBUG: Took 9.015936 seconds to install DeviceAgent
EXEC: /Users/someuser/.rvm/gems/ruby-2.3.0/gems/run_loop-2.2.3/lib/run_loop/device_agent/bin/iOSDeviceManager start_test --device-id e712d77bfa42bb25cd53ea051ade1b7e22f5f0f7 >& /Users/someuser/.run-loop/xcuitest/ios-device-manager.log
DEBUG: HTTP: get http://192.168.2.9:27753/1.0/health {:retries=>1800, :timeout=>180.0}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: Took 16.900271 launch and respond to /health
DEBUG: HTTP: post http://192.168.2.9:27753/1.0/session {:retries=>1200, :timeout=>120}
DEBUG: Launched com.abc.xyz on #<Device: iPhone 6 plus (10.2) e712d77bfa42bb25cd53ea051ade1b7e22f5f0f7>
DEBUG: {"status":"launched!"}
DEBUG: Took 17.097278 seconds to launch com.abc.xyz on #<Device: iPhone 6 plus (10.2) e712d77bfa42bb25cd53ea051ade1b7e22f5f0f7>
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Trying to connect to Calabash Server: 2 of 10
DEBUG: Connected to Calabash Server on try: 2 of 10
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Connected to Calabash Server on try: 1 of 10
#<Launcher: DeviceAgent/ios_device_manager>
calabash-ios 0.20.3> touch("webView css:'*' textContent:'Continue'")
DEBUG: Sending request to perform 'touch' with:

{
  "gesture": "touch",
  "specifiers": {
    "coordinate": {
      "x": 187.5,
      "y": 630.4688
    }
  },
  "options": {
  }
}


DEBUG: HTTP: post http://192.168.2.9:27753/1.0/gesture {:retries=>1200, :timeout=>120}
[
    [0] {
             "center" => {
            "X" => 187.5,
            "Y" => 630.46875
        },
            "webView" => "<UIWebView: 0x135d0fb30; frame = (0 20; 320 548); opaque = NO; autoresize = W+H; layer = <CALayer: 0x174033460>>",
           "nodeName" => "BUTTON",
                 "id" => "",
        "textContent" => "Continue",
              "class" => "btn",
               "rect" => {
                   "x" => 0,
              "height" => 60,
                   "y" => 488,
               "width" => 320,
                "left" => 0,
                 "top" => 488,
            "center_y" => 630.4688,
            "center_x" => 187.5
        },
           "nodeType" => "ELEMENT_NODE"
    }
]
calabash-ios 0.20.3> 
```

Bug reproduced with
- calabash 0.20.3 with iPhone 6 Plus (10.2 beta 05)
- calabash 0.20.3 with iPad Air 2 (10.1.1)
- calabash 0.18.3 with iPad mini (8.3)

Bug not reproduced with calabash 0.20.3 and iPhone 7 (10.0)

Environment:
```
# xcode installation location
$ xcode-select --print-path
/Applications/Xcode-8.2-beta02.app/Contents/Developer

# xcode version
$ xcodebuild -version
Xcode 8.2
Build version 8C30a

# calabash version
$ calabash-ios version
0.20.3

# start your app manually in the simulator or from Xcode
$ curl http://localhost:37265/version
{"device_family":"iPhone","outcome":"SUCCESS","server_port":37265,"simulator_device":"",
"simulator":"","app_name":"my_app","app_version":"1.2.3","screen_dimensions":
{"native_scale":2.608695652173913,"sample":1.171875,"height":1136,"width":640,"scale":2},
"git":{"revision":"5ec0a54","remote_origin":"git@github.com:calabash\/calabash-ios-server.git",
"branch":"master"},"device_name":"iPhone 6 plus","4inch":false,"app_id":"com.abc.xyz",
"form_factor":"iphone 6+","system":"iPhone7,1","version":"0.20.3","iOS_version":"10.2",
"short_version_string":"1.2.3","ios_version":"10.2","iphone_app_emulated_on_ipad":false,
"model_identifier":"iPhone7,1","app_base_sdk":"iphoneos9.3"}
```

**Comment by jmoody** [comment]
This is a possible duplicate of **Cannot touch views on iPhone apps emulated on iPad - even in 1X mode** [#813](https://github.com/calabash/calabash-ios/issues/813).

> small button on the bottom right corner to zoom/unzoom x1 or x2

You can try to force x1 view mode which might correct the touch coordinates.

Call `ensure_ipad_emulation_1x` after `Calabash::Cucumber::Launcher#relaunch`.

> The app I'm testing is a webview app and it is not designed for iPad

Can you update the app so it is designed for iPad?

> calabash 0.20.3 with iPhone 6 Plus (10.2 beta 05)

This seems like a separate issue - touch coordinates for your application on iPhone 6 Plus form factors are incorrect.   I am not sure we can debug this problem without your app.  Can you share your app or produce a sample app that reproduces this issue?  In order to debug, we need an application that is _not_ linked with the calabash.framework.

**Comment by Oopla** [comment]
> You can try to force x1 view mode which might correct the touch coordinates.

Even when forcing x1 view mode, the touch coordinates are incorrect. It seems calabash touches the center of the screen while the aimed button is at the bottom.

> Can you update the app so it is designed for iPad?

Unfortunately the app will not be updated.

> Can you share your app or produce a sample app that reproduces this issue?

I'll ask our dev team to produce a sample application and come back to you.

**Comment by Oopla** [comment]
You can reproduce the iPad issue with the following Xcode (7.3.1) project
[WebViewSample.zip](https://github.com/calabash/calabash-ios/files/645701/WebViewSample.zip)

But I did not manage to reproduce the iPhone 6 Plus issue with a clean project yet.

**Comment by jmoody** [comment]
@Oopla Thank you for the sample project.  The iPad 1x/2x issue is not a high priority for us.  If you manage to reproduce on the iPhone 6 Plus, I will take a look.  Please include _steps to reproduce_.

**Comment by Oopla** [comment]
Hi again,
Our dev team managed to fix the issue with iPhone 6 Plus on our side. If I understood correctly, they did 2 changes:
* use auto layouts to contain the webview
* in html files, replacing `minimum-scale=0.5` and `maximum-scale=1.0` by `initial-scale=1.0`

As a result, the display looks more consistent on every iDevice and Calabash is using the correct coordinates to touch the buttons.

This did not fix the iPad issue, but as you mentioned there is already a case for this: #813
