### ISSUE TITLE
Touch doesn’t work after rotation on iPad

### ISSUE THREAD

**Issue by nayakj** [calabash/calabash-ios#1246]
Hello Team,
I am facing an issue since I have upgraded the calabash version to 0.20.0.
Right after rotating the iPad simulator the app page becomes unresponsive and I get connection refused error.
If I start the app manually on iPad and rotate the simulator manually by pressing cmd+left arrow then it works fine. It’s through calabash rotation when the page becomes unresponsive for any further action.

Steps to reproduce-
1.	Launch the app on iPad Air 2 (9.3)
2.	Rotate the device via rotate :left

Expected Result-
The device should rotate to landscape and should be functional

Actual Result-
After rotation the device becomes unresponsive and it gives connection refused error

Command I use to run test – 
bundle exec cucumber APP_BUNDLE_PATH=packages/our_app-Calabash.app -r features/scenarios/* -r features/support/ -r features/step_definitions/ -p auto -t @test -f pretty -f html --out calabashAndroidTestReport.html -f junit --out JUnitReport -f rerun -o rerun.txt

Error – 
Timeout exceeded (RunLoop::HTTP::Error)
  ./features/support/device_driver/calabash/commands/orientation.rb:11:in `rotate_device'
Connection refused - connect(2) for "127.0.0.1" port 37265 (127.0.0.1:37265) (Errno::ECONNREFUSED)
      ./features/support/hooks.rb:61:in `After'

#start your app manually in the simulator or from Xcode
$curl http://localhost:37265/version
{"device_family":"iPad","outcome":"SUCCESS","server_port":37265,"simulator_device":"iPad","simulator":"CoreSimulator 303.8 - Device: iPad Air 2 - Runtime: iOS 9.3 (13E233) - DeviceType: iPad Air 2","app_name":"OUR_APP","app_version":"1.0.0.0","screen_dimensions":{"native_scale":2,"sample":1,"height":2048,"width":1536,"scale":2},"git":{"revision":"3427493","remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master"},"device_name":"iPad Simulator","4inch":false,"app_id":"uk.co.our.app","form_factor":"ipad","system":"x86_64","version":"0.20.0","iOS_version":"9.3","short_version_string":"4.22.1","ios_version":"9.3","iphone_app_emulated_on_ipad":false,"model_identifier":"iPad5,4","app_base_sdk":"iphonesimulator10.1"}

#xcode installation location
$xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

#xcode version
$Xcode 8.0
Build version 8A218a

#Calabash version
$calabash-ios version
0.20.0

**Comment by jmoody** [comment]
I need to see your ./features/support/hooks.rb file.

It looks like you are rotating _after_ the application has exited.

**Comment by nayakj** [comment]
@jmoody Thanks for pointing it out. I have fixed it now.
We are good to close this ticket.
