### ISSUE TITLE
Calabash is trying to use port 27753 instead of 37265

### ISSUE THREAD

**Issue by wwlacy6** [calabash/calabash-ios#1256]
I am setting the following device endpoint: 
`export DEVICE_ENDPOINT=http://F2LPJAYDG5QF.local:37265`

However, when in calabash-ios console I attempt to run `start_test_server_in_background` with DEBUG=1 I get a runtime error:
```
Could not connect to the DeviceAgent service.

device: #<Device: F2LPJAYDG5QF (10.0.2) a6daccd6515ffc11d128c20cb6b185f3743ed2a2>
   url: http://F2LPJAYDG5QF.local:27753/
```

The thing that stands out to me is that it is using the url with the port 27753, which I did not specify. Where is it getting that from? And how can I make it use 37265?

Also, I noticed that issue #1233 also has this same error message and incorrect port.

**Comment by jmoody** [comment]
There are 2 servers:  DeviceAgent on port 27753 and the LPServer on 37265.

**Comment by matopeto** [comment]
I had the same problem and solution was run it on iOS 9 emulator, fails on 10.2 (maybe some incompatibiles with newests ios)

**Comment by wwlacy6** [comment]
The issue was actually due to the phone and my laptop being on different wifi networks. Once I set both to the same network I no longer have this issue. Hopefully this works for you too @matopeto
