### ISSUE TITLE
Error with DeviceAgent on first launch

### ISSUE THREAD

**Issue by singhujjwal** [calabash/calabash-ios#1257]
Hi,
With calabash 0.20.4 I am facing a strange issue. The first time i launch the calabsh console and try running the command start_test_server_in_background. Below output comes which says the DeviceAgent is already running which is running indeed. But fails to connect to the Calabash Server.

```
EXEC: xcrun simctl list devices --json
EXEC: xcrun instruments -s devices
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: DeviceAgent is already running
DEBUG: HTTP: post http://10.232.16.169:27753/1.0/session {:retries=>200, :timeout=>20}
DEBUG: Launched xxxx.xxxx.xxxxx.xxxxxx on #<Device: gb-colblr-ipad-rk (10.2) xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
DEBUG: {"status":"launched!"}
DEBUG: Took 0.066469 seconds to launch com.xxxxx.xxxxx.xxxxx on #<Device: gb-colblr-ipad-rk (10.2) xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Trying to connect to Calabash Server: 2 of 10
DEBUG: Trying to connect to Calabash Server: 3 of 10
DEBUG: Trying to connect to Calabash Server: 4 of 10
DEBUG: Trying to connect to Calabash Server: 5 of 10
DEBUG: Trying to connect to Calabash Server: 6 of 10
DEBUG: Trying to connect to Calabash Server: 7 of 10
DEBUG: Trying to connect to Calabash Server: 8 of 10
DEBUG: Trying to connect to Calabash Server: 9 of 10
DEBUG: Trying to connect to Calabash Server: 10 of 10
Calabash::Cucumber::ServerNotRespondingError: Could not connect to the Calabash Server @ http://10.232.16.169:37265.

See these two guides for help.

* https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
* https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators

1. Make sure your application is linked with Calabash.
2. Make sure there is not a firewall blocking traffic on http://10.232.16.169:37265.
3. Make sure http://10.232.16.169:37265 is correct.

If your app is crashing at launch, find a crash report to determine the cause.


	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http/http.rb:97:in `raise_on_no_connectivity'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http/http.rb:81:in `ensure_connectivity'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:388:in `relaunch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from /usr/local/bin/irb:11:in `<main>'
calabash-ios 0.20.4>
```

While on the subsequent calls to start_test_server_in_background succeeds, showing that the DeviceAgent is being shut down and started again.

e.g.

```
calabash-ios 0.20.4> start_test_server_in_background
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
EXEC: curl -X DELETE http://10.232.16.169:27753/1.0/session
DEBUG: HTTP: post http://10.232.16.169:27753/1.0/shutdown {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent-Runner says, "Goodbye."
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waited for 0.384362 seconds for DeviceAgent to shutdown
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
EXEC: /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 8679b6be3a472b3a15462d343978f97c9afefaba --app-bundle /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
DEBUG: Took 16.242683 seconds to install DeviceAgent
EXEC: /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/device_agent/bin/iOSDeviceManager start_test --device-id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx >& /Users/ujjsingh/.run-loop/xcuitest/ios-device-manager.log
DEBUG: HTTP: get http://10.232.16.169:27753/1.0/health {:retries=>1350, :timeout=>135.0}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: Took 25.825779 launch and respond to /health
DEBUG: HTTP: post http://10.232.16.169:27753/1.0/session {:retries=>200, :timeout=>20}
*DEBUG: Launched com.xxxxxx.xxxxxx.xxxxxx on #<Device: gb-colblr-ipad-rk (10.2)xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
*DEBUG: {"status":"launched!"}
DEBUG: Took 26.08277 seconds to launch com.xxx.xxxx.xxxxxxxx on #<Device: gb-colblr-ipad-rk (10.2) 8679b6be3a472b3a15462d343978f97c9afefaba>
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Trying to connect to Calabash Server: 2 of 10
DEBUG: Connected to Calabash Server on try: 2 of 10
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Connected to Calabash Server on try: 1 of 10
#<Launcher: DeviceAgent/ios_device_manager>
```

Also when i try to run this through a python script i get signing error.
Any help is much appreciated.

Thanks Much,
Ujjwal

**Comment by jmoody** [comment]
Is your application linked with the calabash.framework?

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode

**Comment by singhujjwal** [comment]
Yes the application is linked with the calabash.framework.

Thanks,
Ujjwal

**Comment by singhujjwal** [comment]
Also sometime calabash becomes very slow and even calabash_exit doesn't work.

It keeps giving  HTTPClient::ReceiveTimeoutError: execution expired

calabash-ios 0.20.4> calabash_exit
HTTPClient::ReceiveTimeoutError: execution expired
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `gets'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/http/retriable_client.rb:184:in `send_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/http/retriable_client.rb:163:in `block in request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/http/retriable_client.rb:150:in `times'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/http/retriable_client.rb:150:in `request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/http/retriable_client.rb:93:in `post'
	from /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.2.4/lib/run_loop/device_agent/client.rb:1463:in `_dismiss_springboard_alerts'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:118:in `_private_dismiss_springboard_alerts'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:22:in `http'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/connection_helpers.rb:14:in `http'
	from /usr/local/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/core.rb:1512:in `calabash_exit'
	from (irb):4
	from /usr/local/bin/irb:11:in `<main>'

**Comment by jmoody** [comment]
There are only a few things that could be wrong:

1. Your application is not linked with Calabash.
2. Another application is running on your device that _is_ linked with Calabash - thus the 37265 port is blocked.
3. The IP address of your device is incorrect.
4. Your device and the host machine are not on the same network.

You can test all of these by launching your application manually and running `curl`.

```
$ curl http://<ip address:37265/version
```
