### ISSUE TITLE
Calabash installation script on Mac OS Sierra

### ISSUE THREAD

**Issue by BartBM** [calabash/calabash-ios#1259]
I received my Macbook today with Mac OS Sierra. After installing XCode, I tried running my Calabash UI tests but I can't even install Calabash.

```
barry@~:$ curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash
Preparing Ruby 2.3.1...
######################################################################## 100.0%
Installing gems, this may take a little while...
######################################################################## 100.0%
Preparing sandbox...
######################################################################## 100.0%
Done! Installed:
calabash-ios:       <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
calabash-android:   <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
xamarin-test-cloud: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
Execute 'calabash-sandbox update' to check for gem updates.
Execute 'calabash-sandbox' to get started!
```

**Xcode:** 
/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

**Comment by jmoody** [comment]
Please use rbenv.  The sandbox is in a bad state.

**Comment by jmoody** [comment]
https://github.com/calabash/calabash-ios/wiki/rbenv-guide

**Comment by matopeto** [comment]
Same problem, is there any tutorial run  calabash tests without calabash-sandbox?

**Comment by ark-konopacki** [comment]
@matopeto  have you tried https://github.com/calabash/calabash-ios/wiki/Getting-Started?

**Comment by matopeto** [comment]
@ark-konopacki hi, i read the tutorial but i don't find in it, what gems i have to install to run the tests. In past i install only calabash-sandbox and all required was in it (calabash-cucumber, calabash-ios and....

**Comment by matopeto** [comment]
i found the error on the calabash-sandbox repository https://github.com/calabash/install/issues/65 i will follow the solution on it.

**Comment by lferro9000** [comment]
Just to note that i've rbenv installed with Ruby 2.3.3 and that the instalation of calabash by creating a target as stated on:

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A--Creating-a-cal-Target

Worked without any issues.

**Comment by jmoody** [comment]
Fixed by https://github.com/calabash/install/pull/68

I strongly recommend that you start using `rbenv`.
