### ISSUE TITLE
Cannot active run-loop because json 2.0.2 conflicts with json ~> 1.8

### ISSUE THREAD

**Issue by chanuuuu** [calabash/calabash-ios#1260]
Hi,
      I installed calabash 0.20.4. After running the cucumber command, I am getting following error:

Unable to activate run_loop-2.2.4, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)

These are gems installed on my mac:
*** LOCAL GEMS ***

addressable (2.5.0)
awesome_print (1.7.0)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.13.7)
calabash-cucumber (0.20.4)
CFPropertyList (2.3.4)
clipboard (1.1.1)
command_runner_ng (0.1.0)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
did_you_mean (1.1.0)
diff-lcs (1.2.5)
edn (1.1.1)
geocoder (1.4.1)
gherkin (4.0.0)
httpclient (2.8.3)
i18n (0.7.0)
io-console (default: 0.4.6)
json (default: 2.0.2, 1.8.6)
json-schema (2.7.0)
minitest (5.10.1)
multi_json (1.12.1)
multi_test (0.1.2)
net-telnet (0.1.1)
openssl (default: 2.0.2)
plist (3.2.0)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
rake (12.0.0)
rdoc (default: 5.0.0)
run_loop (2.2.4)
slowhandcuke (0.0.3)
test-unit (3.2.3)
thor (0.19.4)
xmlrpc (0.2.1)

How can I resolve this issue? json 2.0.2 is my default gem and I don't see any way to make json 1.8.6 as default gem for running calabash.

Thanks,
Chanikya

**Comment by jmoody** [comment]
Remove json 2.0.2 and use a Gemfile + bundler.

```
$ gem update --system
$ gem uninstall -Vax --force --no-abort-on-dependent json

# Make a Gemfile with the following contents.

source "https://rubygems.org"

gem "calabash-ios", "0.20.4"
gem "cucumber", "~> 2.4"

# Use bundler
$ bundle install
$ bundle exec cucumber
```

It is possible that some gem you are using _requires_ json 2.0.  If that is the case, you will need to pin that gem to a version that does not require json >= 2.0.

For example - the `fake-gem` version 3.0 might require json >= 2.0, but the `fake-gem` version 2.5 requires json >= 1.8.  

```
# Update your Gemfile
gem "fake-gem", "2.5"

# Run bundler again
$ bundle install
```

**Comment by jmoody** [comment]
Basically a duplicate of https://github.com/calabash/run_loop/issues/583

**Comment by chanuuuu** [comment]
Thanks @jmoody ... Use of bundle fixes my issue..
