### ISSUE TITLE
Link to setup Calabash IOS with Jenkins is Not Found

### ISSUE THREAD

**Issue by atteeela** [calabash/calabash-ios#1267]
On the wiki (https://github.com/calabash/calabash-ios/wiki/Continuous-Integration-and-Code-Coverage)  , the following link is no longer found.

Running Calabash-iOS on Jenkins
by Christopher Gretzki
http://blog.watchlaterapp.com//blog/2013/03-Calabash-iOS-Jenkins.html

**Comment by jmoody** [comment]
Removed dead link.  Thanks.
