### ISSUE TITLE
How can I uninstall and reinstall application before scenario with simulator

### ISSUE THREAD

**Issue by liubin-acn** [calabash/calabash-ios#1269]
Hi, Just one simple question. I don't know how can I uninstall and reinstall application before scenario with **iOS** simulator.

my 01_launch.rb as follow

```
require 'calabash-cucumber/launcher'

# APP_BUNDLE_PATH = "~/Library/Developer/Xcode/DerivedData/??/Build/Products/Calabash-iphonesimulator/??.app"
# You may uncomment the above to overwrite the APP_BUNDLE_PATH
# However the recommended approach is to let Calabash find the app itself
# or set the environment variable APP_BUNDLE_PATH

Before do |scenario|
  if xamarin_test_cloud?
    ENV['RESET_BETWEEN_SCENARIOS'] = '1'
  end
end

After do |scenario|
  keychain_clear
  unless @calabash_launcher.calabash_no_stop?
     calabash_exit
    if @calabash_launcher.active?
      @calabash_launcher.stop
    end
end
end

at_exit do
  launcher = Calabash::Cucumber::Launcher.new
  if launcher.simulator_target?
     Calabash::Cucumber::SimulatorHelper..stop unless launcher.calabash_no_stop?
  end
end
```

Above, Thank you! ~

**Comment by duboviy** [comment]
Hi, @liubin-acn !

I may suggest you to use env variable **RESET_BETWEEN_SCENARIOS**=1
But **it's not working** with latest run_loop **2.3.0** https://github.com/calabash/run_loop/issues/599
( e.g. i've created following pull request https://github.com/calabash/run_loop/pull/600 to fix it)

or if you don't want to wait for fix you may try to use following workaround:
regenerate your 01_launch.rb using:
$ calabash-ios gen

and try to use following code in your **Before** block:

```ruby
Before do |scenario|
  launcher = Calabash::Launcher.launcher
  options = {
    :relaunch_simulator=>true,
    :reset_app_sandbox=>true
      # Add launch options here.
  }
  end
  launcher.relaunch(options)
end
```

**Comment by liubin-acn** [comment]
@duboviy Thank you for your reply.

If I want to test some case about app reinstall, How can I do that?

**Comment by duboviy** [comment]
As far as I know RESET_BETWEEN_SCENARIOS only clears simulator app state.

**Comment by ark-konopacki** [comment]
@duboviy it was, but as i know recently was implemented "keep alive" functionality 
https://github.com/calabash/run_loop/blob/v2.3.0/CHANGELOG.md
You can check if it somehow related to option `:relaunch_simulator => true`

**Comment by jmoody** [comment]
@liubin-acn 



```
# Reset Simulator Content and Settings
device = RunLoop::Device.device_with_identifier("< UDID of Simulator >")
RunLoop::CoreSimulator.erase(device)

# Uninstall with CoreSimulator
device = RunLoop::Device.device_with_identifier("< UDID of Simulator >")
app = RunLoop::App.new("path/to/Your.app")
core_sim = RunLoop::CoreSimulator.new(device, app)
core_sim.uninstall_app_and_sandbox
```

**Comment by jmoody** [comment]
> As far as I know RESET_BETWEEN_SCENARIOS only clears simulator app state.

@ark-konopacki You are correct.

**Comment by liubin-acn** [comment]
@jmoody 

Thank you very much! ~~~

**Comment by dbharti2000** [comment]
@jmoody Many thanks, it works fine with simulator. Is there a way we can uninstall app on devices as we are doing it for simulator? cheers!
