### ISSUE TITLE
Application closed when finding elements on console

### ISSUE THREAD

**Issue by bansalvarsha** [calabash/calabash-ios#1273]
Hi Folks,

I am facing an issue is that when using a query 

> query("label {text 'CHECKLIST FOR INSPECTION}")

I try to find the elements on console, application opened on device closed and on console it shows me connection refused.

For other queries it works and facing no issue.

Please look at this side and see why is it happening?

Thanks,

**Comment by jmoody** [comment]
The query syntax is incorrect.

```
query("label {text < operator > 'CHECKLIST FOR INSPECTION'}")
```

The operators are `LIKE`, `CONTAINS`, `BEGINSWITH`, etc.

**Comment by bansalvarsha** [comment]
Thanks @jmoody 
it works
