### ISSUE TITLE
Could not install DeviceAgent-Runner.app. because of a parse profile error

### ISSUE THREAD

**Issue by otamas94** [calabash/calabash-ios#1274]
Hi, 

I would like to report an issue I'm facing in the latest time:
When I want to run a test on my local device it always fails with this error:

	Could not install /Users/user/.rvm/gems/ruby-2.3.1/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:
  
	2017-02-20 09:55:29.319 iOSDeviceManager[97429:3947629] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
	security cms failed to parse profile:
  	/Users/user/Library/MobileDevice/Provisioning Profiles/6003449e-ed1c-4913-be2b-0a56b0212685.mobileprovision
  	security cms failed to parse profile:
  	  /Users/user/Library/MobileDevice/Provisioning Profiles/cff04fc3-5b29-4dd4-b91a-465f68d7fa52.mobileprovision
  	security cms timed out after 10.00102164503187 seconds
  	security cms failed to parse profile:
  	  /Users/user/Library/MobileDevice/Provisioning Profiles/59dd97b7-bc3b-471f-85b9-15fbd6f0f0ed.mobileprovision
  	security cms timed out after 10.00104616896715 seconds
  	security cms timed out after 10.00170354702277 seconds
  	security cms failed to parse profile:
  	  /Users/user/Library/MobileDevice/Provisioning Profiles/c0fd3927-fe91-454e-86f7-a85bcff7ba7f.mobileprovision
  	security cms timed out after 10.00325956603047 seconds
  	There are no valid profiles on your machine.
  	Error creating product bundle for /var/folders/cg/fpx6_36d7xx3pj3j4s9swrgm0000gp/T/219D143D-49BE-407E-96A8-41A119358C9D-97429-000185E62A842190/DeviceAgent-Runner.app: 
	Error Domain=com.facebook.XCTestBootstrap Code=0 "Failed to codesign /var/folders/cg/fpx6_36d7xx3pj3j4s9swrgm0000gp/T/219D143D-49BE-407E-96A8-41A119358C9D-97429-000185E62A842190/DeviceAgent-Runner.app" 
	UserInfo={NSLocalizedDescription=Failed to codesign /var/folders/cg/fpx6_36d7xx3pj3j4s9swrgm0000gp/T/219D143D-49BE-407E-96A8-41A119358C9D-97429-000185E62A842190/DeviceAgent-Runner.app,
	NSUnderlyingError=0x7fe8ec002650 {Error Domain=sh.calaba.iOSDeviceManger Code=5 "Could not resign with the given arguments" 
	UserInfo={NSLocalizedDescription=Could** not resign with the given arguments, NSLocalizedFailureReason=The device UDID and code signing identity were 	invalid forsome reason.  
	Please check the logs.}}}
  
  	install
  		-d,--device-id	<device-identifier>	iOS Simulator GUIDs
  		-a,--app-bundle	<path/to/app-bundle.app>	Path .app bundle (for .ipas, unzip and look inside of 'Payload')
  		-c,--codesign-identity	<codesign-identity> [OPTIONAL] 	Identity used to codesign app bundle [device only]	DEFAULT=
  		-u,--update-app	<true-or-false> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1
  
   	(RuntimeError)
  	./features/support/01_launch.rb:102:in `Before'

It is appeared after the latest restart of the server, with run_loop 2.3.0, calabash-ios 0.20.3.

The provisioning profiles are not expired and linked with the code signing identity.

The execution code is: 
`APP_BUNDLE_PATH=Path to the apk/xxx.apk 
CODE_SIGN_IDENTITY="iPhone Developer: xxx (...)"
DEVICE_TARGET='UDID of the phone' 
DEVICE_ENDPOINT=http://x.x.2.6:37265 
cucumber features/test.feature`

**Comment by duboviy** [comment]
As far as i know to resign DeviceAgent app it requires valid profiles on your machine.

I don't know exactly what is wrong with your profiles, but there is a message in log: "There are no valid profiles on your machine."

Maybe your provisioning profiles are not expired and linked properly with the code signing identity, but are not associated with DEV team - that could be the root cause of problem, because DEV rights is also required to resign DeviceAgent app.

**Comment by jmoody** [comment]
Try not setting the `CODE_SIGN_IDENTITY`. 

The next version of the DeviceAgent stack will have an improved resigning algorithm.

**Comment by otamas94** [comment]
Thanks for the advices, but the problem was with the provisioning profiles were duplicated in the Keychain, after i removed them all and redownloaded from Apple Developer site, it started to work fine, and Xcode could build my app the way calabash could resign it.

**Comment by jmoody** [comment]
run-loop 2.4.0 has improved code signing.
