### ISSUE TITLE
Could not connect to the Calabash Server

### ISSUE THREAD

**Issue by ashisht99x** [calabash/calabash-ios#1276]
Here are the debug logs. It is interesting how connection is attempted after connection failure 

16:14:54.095 EXEC: xcrun simctl list devices --json
16:14:54.691 DEBUG: Simulator is already shutdown
16:14:54.703 DEBUG: Waited for 0.011362 seconds for device to have state: 'Shutdown'.
16:14:54.703 EXEC: xcrun simctl erase 4EA194A2-810C-433C-ABBA-BD02E8A12CB4
16:14:58.034 DEBUG: Launching #<Simulator: iPhone 6 (9.3) 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 x86_64> with:
16:14:58.034 EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 4EA194A2-810C-433C-ABBA-BD02E8A12CB4
16:15:28.198 DEBUG: Waiting for simulator to stabilize with timeout: 30 seconds
16:15:28.198 DEBUG: Timed out after 30 seconds waiting for simulator to stabilize
16:15:28.198 DEBUG: Took 30.16313 seconds to launch the simulator
16:15:28.350 EXEC: xcrun simctl install 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 /Applications/GoAgent1/pipelines/iOS_Shop_And_Book/ios/Source/MyApp/Build/MyApp.app
16:16:09.014 DEBUG: Waiting for simulator to stabilize with timeout: 30 seconds
16:16:09.014 DEBUG: Timed out after 30 seconds waiting for simulator to stabilize
16:16:09.169 DEBUG: HTTP: get http://127.0.0.1:27753/1.0/health {:retries=>1, :timeout=>0.5}
16:16:09.170 DEBUG: Waiting for DeviceAgent to launch...
16:16:09.540 EXEC: xcrun simctl install 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/run_loop-2.2.2/lib/run_loop/device_agent/app/DeviceAgent-Runner.app
16:16:20.686 DEBUG: Waiting for simulator to stabilize with timeout: 30 seconds
16:16:27.527 DEBUG: Waited a total of 14.739168 seconds for simulator to stabilize
16:16:27.707 DEBUG: Took 18.533613 seconds to install DeviceAgent
16:16:27.707 EXEC: /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/run_loop-2.2.2/lib/run_loop/device_agent/bin/iOSDeviceManager start_test --device-id 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 >& /Users/MyApp/.run-loop/xcuitest/ios-device-manager.log
16:16:35.811 DEBUG: HTTP: get http://127.0.0.1:27753/1.0/health {:retries=>900, :timeout=>90.0}
16:16:35.811 DEBUG: DeviceAgent says, "Calabash is ready and waiting."
16:16:35.811 DEBUG: Took 26.635531 launch and respond to /health
16:16:45.900 **Could not connect to the Calabash Server @ http://127.0.0.1:37265/.**
16:16:45.900 
16:16:45.900 See these two guides for help.
16:16:45.900 
16:16:45.900 * https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
16:16:45.900 * https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators
16:16:45.900 
16:16:45.900 1. Make sure your application is linked with Calabash.
16:16:45.900 2. Make sure there is not a firewall blocking traffic on http://127.0.0.1:37265/.
16:16:45.900 3. Make sure http://127.0.0.1:37265/ is correct.
16:16:45.900 
16:16:45.901 If your app is crashing at launch, find a crash report to determine the cause.
16:16:45.901 
16:16:45.901  (Calabash::Cucumber::ServerNotRespondingError)
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/http/http.rb:97:in `raise_on_no_connectivity'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/http/http.rb:81:in `ensure_connectivity'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/calabash-cucumber-0.20.3/lib/calabash-cucumber/launcher.rb:388:in `relaunch'
16:16:45.901 /Applications/GoAgent1/pipelines/iOS_Shop_And_Book/automation/feature_steps/ios/support/env.rb:73:in `<top (required)>'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_language.rb:96:in `load'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:142:in `load_file'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:83:in `each'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:254:in `load_step_definitions'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:62:in `run!'
16:16:45.901 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
16:16:45.902 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
16:16:45.902 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/bin/cucumber:23:in `load'
16:16:45.902 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/bin/cucumber:23:in `<main>'
16:16:45.902 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/bin/ruby_executable_hooks:15:in `eval'
16:16:45.902 /Users/MyApp/.rvm/gems/ruby-2.3.1@tantrum/bin/ruby_executable_hooks:15:in `<main>'
16:16:45.934 DEBUG: Took 0.024176 seconds to check if app was installed
16:16:45.934 DEBUG: HTTP: post http://127.0.0.1:27753/1.0/session {:retries=>100, :timeout=>10}
16:16:45.934 DEBUG: Launched com.MyApp.dev on #<Simulator: iPhone 6 (9.3) 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 x86_64>
16:16:45.934 DEBUG: {"status":"launched!"}
16:16:45.934 DEBUG: Took 26.782457 seconds to launch com.MyApp.MyApp.dev on #<Simulator: iPhone 6 (9.3) 4EA194A2-810C-433C-ABBA-BD02E8A12CB4 x86_64>
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 1 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 2 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 3 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 4 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 5 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 6 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 7 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 8 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 9 of 10
16:16:45.935 DEBUG: Trying to connect to Calabash Server: 10 of 10

**Comment by arulami** [comment]
I am also having this error. any help on this ?

**Comment by jmoody** [comment]
You need to confirm that your application is linked with calabash.

Have you followed these instructions:

```
16:16:45.900 Could not connect to the Calabash Server @ http://127.0.0.1:37265/.
16:16:45.900
16:16:45.900 See these two guides for help.
16:16:45.900
16:16:45.900 * https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
16:16:45.900 * https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators
16:16:45.900
16:16:45.900 1. Make sure your application is linked with Calabash.
16:16:45.900 2. Make sure there is not a firewall blocking traffic on http://127.0.0.1:37265/.
16:16:45.900 3. Make sure http://127.0.0.1:37265/ is correct.
16:16:45.900
16:16:45.901 If your app is crashing at launch, find a crash report to determine the cause.
```

**Comment by ashisht99x** [comment]
The application is linked with Calabash. This happens intermittently, like one out of 15 times. 
Am curious why attempt of connection is being made after the connection has already failed. Is this some sort of race situation !

**Comment by jmoody** [comment]
```
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 1 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 2 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 3 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 4 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 5 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 6 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 7 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 8 of 10
16:16:45.934 DEBUG: Trying to connect to Calabash Server: 9 of 10
16:16:45.935 DEBUG: Trying to connect to Calabash Server: 10 of 10
```

Are you talking about that ^

It is just retrying, which is fairly standard in client/server architectures.  There is no race condition.

Watch the simulator logs to see if there is some output that can help diagnose the problem.

```
# Terminal A
$ run-loop simctl tail

# Terminal B
$ < run your test >
```

**Comment by arulami** [comment]
I have got this info from Terminal A:

[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.30.16
	    0   libsystem_network.dylib             0x0000000111ea2666 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x00000001127df006 nw_socket_add_input_handler + 3164
	    2   libnetwork.dylib                    0x00000001127bc555 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x00000001127bb572 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x00000001127ba298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x00000001127d5ae1 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x00000001127d5510 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x00000001127ed1f9 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x0000

**Comment by sivaramprasadc** [comment]
DEBUG: HTTP: get http://192.168.2.15:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://192.168.2.15:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Users/sivaram.chakala/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id e0a35a120d8ffa47d3b8e73cb68917f39efd0103 -a /Users/sivaram.chakala/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
DEBUG: Took 13.7151 seconds to install DeviceAgent
SHELL: /Users/sivaram.chakala/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/bin/iOSDeviceManager start_test --device-id e0a35a120d8ffa47d3b8e73cb68917f39efd0103 >& /Users/sivaram.chakala/.run-loop/xcuitest/ios-device-manager.log
DEBUG: HTTP: get http://192.168.2.15:27753/1.0/health {:retries=>4500, :timeout=>450.0}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: Took 21.623922 launch and respond to /health
DEBUG: HTTP: post http://192.168.2.15:27753/1.0/session {:retries=>200, :timeout=>20}
DEBUG: Launched com.entradahealth.entradamobile on #<Device: sathish.siripuram’s iPhone (10.2.1) e0a35a120d8ffa47d3b8e73cb68917f39efd0103>
DEBUG: {"status":"launched!"}
DEBUG: Took 22.246412 seconds to launch com.entradahealth.entradamobile on #<Device: sathish.siripuram’s iPhone (10.2.1) e0a35a120d8ffa47d3b8e73cb68917f39efd0103>
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Trying to connect to Calabash Server: 2 of 10
DEBUG: Trying to connect to Calabash Server: 3 of 10
DEBUG: Trying to connect to Calabash Server: 4 of 10
DEBUG: Trying to connect to Calabash Server: 5 of 10
DEBUG: Trying to connect to Calabash Server: 6 of 10
DEBUG: Trying to connect to Calabash Server: 7 of 10
DEBUG: Trying to connect to Calabash Server: 8 of 10
DEBUG: Trying to connect to Calabash Server: 9 of 10
DEBUG: Trying to connect to Calabash Server: 10 of 10


Getting error:
Could not connect to the Calabash Server @ http://192.168.2.15.
      
      See these two guides for help.
      
      * https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
      * https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators
      
      1. Make sure your application is linked with Calabash.
      2. Make sure there is not a firewall blocking traffic on http://192.168.2.15.
      3. Make sure http://192.168.2.15 is correct.
      
      If your app is crashing at launch, find a crash report to determine the cause.

**Comment by jmoody** [comment]
>  http://192.168.2.15.

You need to set the port number of the LPServer

```
DEVICE_TARGET=https://192.168.2.15:37265
```
