### ISSUE TITLE
No device agent app built on iPhone 7 Plus iOS 10.2

### ISSUE THREAD

**Issue by aizatomar** [calabash/calabash-ios#1282]
After building and running the app, there is no DeviceAgent app being built as well in the simulator. This causes the app that I will like to test to not be able to found.

Error given when running cucumber test:
"App does not exist at path or is not an app bundle"

Building on simulator iPhone 7 iOS 10.2 works. DeviceAgent app is there.

**Comment by jmoody** [comment]
Please show what command you are running.

DeviceAgent is shipped with the run_loop gem.  It is not built locally.

Are you using the Apple system ruby?

**Comment by aizatomar** [comment]
No I am not using the Apple system ruby.

I am just pressing the Run button in Xcode to build the project. The DeviceAgent comes together with the app I am building on simulator iPhone 7 iOS 10.2 . But not on iPhone 7 Plus iOS 10.2.

**Comment by jmoody** [comment]
> The DeviceAgent comes together with the app I am building on simulator iPhone 7 iOS 10.2 

This is not possible.  You must mean something else.  Maybe you mean your application is not linking the calabash.framework?

Are you a Microsoft employee or contractor with access to the private DeviceAgent source code?

**Comment by aizatomar** [comment]
I don't understand. If my application is not linked to the calabash.framework, then the DeviceAgent app should not be there when I build my app for iPhone7 simulator.

So my scenario is that the DeviceAgent which is not there before on iPhone7 simulator is built together when I build my app for iPhone7 simulator.

![iphone7](https://cloud.githubusercontent.com/assets/5583193/23883681/b56f8d36-08a3-11e7-84e7-ac4c6b4cd9ac.png)

When I build for iPhone7+ simulator, the DeviceAgent does not appear at all in the simulator.

![iphone7plus](https://cloud.githubusercontent.com/assets/5583193/23883693/c4bf9c4a-08a3-11e7-9b2d-9e9e7d66f514.png)

I tried to build for iPhone SE as well just to test. The DeviceAgent app is still not there in the simulator for iPhone SE.

![iphonese](https://cloud.githubusercontent.com/assets/5583193/23883700/cb4006ea-08a3-11e7-83ae-7137b044c0ca.png)

It looks like it only appears on iPhone7 simulator which was the 1st time I built the app on simulator. Just so happen I was building for iPhone7 simulator at the time.

Am I missing something?

**Comment by aizatomar** [comment]
No I do not work or is affiliated with Microsoft. I do not have access to the private source code.

**Comment by jmoody** [comment]
DeviceAgent is _installed_ on a simulator or device when you run `cucumber`.  DeviceAgent is never _built_ with your application.

**Comment by aizatomar** [comment]
I am not really sure about this. Been running some tests but it doesn't work the way you say it. The DeviceAgent is not installed at all for the different simulators except for the 1st simulator I ran `cucumber` which for my case is iPhone 7 iOS 10.2 simulator.

**Comment by aizatomar** [comment]
After much research I found out I need to specify the device when running cucumber. Needed to downgrade Ruby to 2.3.1 as well because the latest was having conflict with running the latest version of cucumber.
