### ISSUE TITLE
Unable to run tests over iPad following Xcode 8.3 update (RunLoop::Shell::Error) 

### ISSUE THREAD

**Issue by davidshand** [calabash/calabash-ios#1287]
Hello,

I recently updated from Xcode 7.3 to Xcode 8.3 and also updated calabash. I am now using the latest calabash-sandbox stuff which contains:

- calabash-cucumber (0.20.4)
- run_loop (2.3.1) 
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

Now every time I try to run a test over the iPad using the command:

BUNDLE_ID=<> DEVICE_TARGET=<> DEVICE_ENDPOINT=http:<>:37265 cucumber --tags @login 

I pretty much instantly get the following output:

**There was an error executing:
  
  /Users/macadmin/.calabash/sandbox/Gems/gems/run_loop-2.3.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id ... -a /Users/macadmin/.calabash/sandbox/Gems/gems/run_loop-2.3.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --codesign-identity iPhone Developer: ...
  
  The command generated this output:
  
  
   (RunLoop::Shell::Error)
  ./features/support/01_launch.rb:27:in `Before'**

I've entered ... instead of the --device-id and --codesign-identity as I didn't want to put this in the message.

It might be helpful to note I can still run a test over the simulator.

If this helps my launch.rb file contains:

```
require 'calabash-cucumber/launcher'


#APP_BUNDLE_PATH = "#{ENV['HOME']}/Library/Developer/Xcode/DerivedData/Kykloud-fslhjzitdjnqepevmfkxltxshtmm/Build/Products/Debug-iphonesimulator/kykloud.app"
# You may uncomment the above to overwrite the APP_BUNDLE_PATH
# However the recommended approach is to let Calabash find the app itself
# or set the environment variable APP_BUNDLE_PATH


Before do |scenario|
    @calabash_launcher = Calabash::Cucumber::Launcher.new
    #unless @calabash_launcher.calabash_no_launch?
       @calabash_launcher.relaunch
       @calabash_launcher.calabash_notify(self)
    #end
end

After do |scenario|
    unless @calabash_launcher.calabash_no_stop?
        calabash_exit
        if @calabash_launcher.active?
            @calabash_launcher.stop
        end
    end
end

at_exit do
    launcher = Calabash::Cucumber::Launcher.new
    if launcher.simulator_target?
        launcher.simulator_launcher.stop unless launcher.calabash_no_stop?
    end
end
```
Any help would be appreciated.

Thanks in advance,

David

**Comment by davidshand** [comment]
This is an issue with Xcode 8.3 and calabash. I've downgraded back to Xcode 8.2.1 and its working again.

**Comment by davidshand** [comment]
Had to also downgrade my iPad back to iOS 10.2.1.

**Comment by jmoody** [comment]
run_loop 2.4.0 with Xcode 8.3 support has been released.

**Comment by jmoody** [comment]
If you having a problem after updating to run_loop 2.4.0, open a new issue.

**Comment by davidshand** [comment]
Brilliant, everything now working. Thanks...

**Comment by Krisgk1** [comment]
Can any of you please let know the commands to run an ipa  file on real device 

calabash ipa file was installed using iTunes 
How should we set the iPad file name?
Only the BUNDLE_ID is enough?
I did give the DEVICE_ENDPOINT pointing to device ip address as well
I am using Xcode 8.3 and run loop 2.4.1

When I run: start_test_server_in_background
**RunLoop::NoSimulatorAppFoundError: Recursively searched these directories to depth 10**

And its looking for app file rather than ipa file

**Comment by atsiarenia** [comment]
Hello. 
I have **xcode 8.3.2** with
calabash-android (0.9.0)
calabash-cucumber (0.20.5)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
**run_loop (2.4.1)**

ArgumentError: App does not exist at path or is not an app bundle.

/Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/app/DeviceAgent-Runner.app

Bundle must:

1. be a directory that exists,
2. have a .app extension,
3. contain an Info.plist,
4. and the app binary (CFBundleExecutable) must exist

	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/app.rb:19:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ios_device_manager.rb:108:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ios_device_manager.rb:108:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1354:in `launch_cbx_runner'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:271:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:147:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop.rb:113:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'

is it's means that I must use run_loop (2.4.0) ???

**Comment by jmoody** [comment]
@atsiarenia  The problem is that you are trying to use the Apple System Ruby.  This has nothing to do with Xcode 8.3.

https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS
