### ISSUE TITLE
After downloading the latest Calabash framework it still shows 0.20.4

### ISSUE THREAD

**Issue by gkrinord** [calabash/calabash-ios#1299]
> After downloading the latest Calabash framework it still shows 0.20.4 
I think MIN_SERVER_VERSION = "0.20.4" is not updated so it's misleading when we download the framework .Under calabash.framework->versions it still shows 0.20.4. 
I have not been successful in running the test with Xcode 8.2.1 on iOS 10.3 after downloading the latest framework.I plan to update my Xcode to 8.3.2 and will re-try.
Has anyone been successful in running latest calabash framework on  10.3.1?

**Comment by jmoody** [comment]
There no mistake.  There is no new server for 0.20.5.
