### ISSUE TITLE
How can I select the accessibilityLabel in Predicates?

### ISSUE THREAD

**Issue by Emilios1995** [calabash/calabash-ios#1302]
I want to query elements whose `accessibilityLabel` begins with a certain string. 
like `"label {text BEGINSWITH 'Cell 1'}"` but using the `accessibilityLabel` instead of `text`
Is this possible?

**Comment by jmoody** [comment]
```
"label {accessibilityLabel BEGINSWITH 'Cell 1'}"
```

**Comment by Emilios1995** [comment]
Thanks @jmoody. Is it possible to do the same with the accessibilityId? It doesn't seem to work.

**Comment by jmoody** [comment]
```
"label {accessibilityIdentifier BEGINSWITH 'Cell 1'}"
```

**Comment by Emilios1995** [comment]
@jmoody Thanks, that's great. Maybe it would be helpful to put these in the wiki.
