### ISSUE TITLE
easy way to uninstall calabash from ios?

### ISSUE THREAD

**Issue by awitherow** [calabash/calabash-ios#1308]
I need to cleanup my Pods.xcodeproj and app.xcodeproj and I would like to remove calabash ideally without having to interact with Xcode. Is this possible or only doable via the Xcode interface?

**Comment by jmoody** [comment]
I don't know the answer to this question. 

You will have to look at your Xcode Build Settings: Other Linker flags to see if Calabash is being linked.

These tutorials might be helpful.  

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode

**Comment by awitherow** [comment]
Hmm, not really impressed with how quickly this issue was closed...

Would be nice to address this issue, as I am surely not the only one who would like to get rid of Calabash within their iOS project.

**Comment by jmoody** [comment]
Other than pointing to the tutorials, I am not sure how to help you.

Using CocoaPods to link Calabash is not something I or any other maintainer is familiar with.

**Comment by awitherow** [comment]
That perplexes me a little... But okay 👍 Thank you for the link earlier.
