### ISSUE TITLE
iOS 11.0 Beta - Not able to use all commands with Calabash

### ISSUE THREAD

**Issue by RtgrV** [calabash/calabash-ios#1309]
Hello team,

Today we tried to run our project with the new iOS 11.0 Beta. When we try to query the calabash target with the ios-console terminal application, the simulator freezes and Calabash returns with a timeout. Doing more commands on the console, it will only responds with Connection refused errors. 
Like these: Errno::ECONNREFUSED: Connection refused - Connection refused - connect(2) for "127.0.0.1" port 37265 (127.0.0.1:37265)

When I try to reconnect Xcode with the simulator, by building and running the app. It's giving me the following error: "Error returned in reply: Connection Invalid" "Software caused connection abort". The only solution to get the Simulator working again is to force quit. If I want to rebuild the app I need to restart my Macbook.

I tried the following commands with the console which crashed the application: 
- start_test_server_in_background
- tree
- query

Some details about my system:
- Macbook Pro Mid 2015 2,2GHZ, 16GB Ram
- macOS Sierra 10.12.5
- iOS 11.0 Simulator (Beta)
- XCode 9.0 (Beta)
- App-cal target, iOS Deployment target 8.0 or 9.0 (tried both)
- Tried with 1 running simulator
- Calabash version: 0.20.5

If you need any more details, please let me know.

**UPDATE:**
After some rebooting the app and Calabash, it did respond. I have no clue why. The only command that crashes the app is 'start_test_server_in_background' with the behavior I described above.

Kind regards,

Rutger V

**Comment by jmoody** [comment]
We have not started Xcode 9 support yet.

**Comment by jmoody** [comment]
Don't expect any support until Xcode 9 beta 2.  If history repeats itself, don't expect stable tests with Xcode 9 until the beta 5 or 6.

**Comment by RtgrV** [comment]
Thanks for the reply and the heads up.

Have a nice day,
Rutger V

**Comment by TheChell** [comment]
Thanks for the reply here, just inquiring about any updates there might be now that we're on beta 6. 

Also, will we have support for iOS 11 at the same time? I'm not sure if iOS 11 has given us any extra headaches to deal with, like the previous change with UIAutomation/Device Agent. Hopefully not, but asking in case I'm uninformed.
