### ISSUE TITLE
calabash-ios setup for new project

### ISSUE THREAD

**Issue by shabi** [calabash/calabash-ios#1311]
While doing calabash-ios setup for new xcode project getting following error.

input: 
Selecting default target (TestPOC)
---------- - ----------
Duplicating target: TestPOC to new target: TestPOC-cal
Adding CFNetwork.framework to target TestPOC-cal
Adding calabash.framework to target TestPOC-cal
Adding Other Linker options to target TestPOC-cal
**ERROR: xcrun xcodebuild -version exited non-zero**

----------Setup done----------
Please validate by running the -cal target
from Xcode.
When starting the iOS Simulator using the
new -cal target, you should see:

  "Started LPHTTP server on port 37265"

in the application log in Xcode.

**Comment by jmoody** [comment]
The setup command is no longer supported.

Use one of these methods.

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode
