### ISSUE TITLE
Calabash UI Automation Couldn't install Device Agent 

### ISSUE THREAD

**Issue by piyush8** [calabash/calabash-ios#1321]
Hi,
 
/Users/apple/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id acd9daeb11c04eebaeef3d2c4f14cf6e45f8cbc1 -a /Users/apple/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app

I am not able to install Device getting the following error as above 
Note: I have to test this in IOS 11 device. I am using Xcode 9 beta version to build and run the app on the device.
Can any 1 one help me, please?

**Comment by jmoody** [comment]
iOS 11 support is not available yet.  It is coming soon.

**Comment by piyush8** [comment]
How can I run our app on IOS 11 device using Xcode 9 beta version? I need to test on IOS 11 (For future interptions)
