### ISSUE TITLE
Calabash error not able to run test on IOS 10

### ISSUE THREAD

**Issue by piyush8** [calabash/calabash-ios#1322]
Hi,
when I am running the Calabash test getting the error 
APPLEs-iMac-2: UIAutomation apple$ bundle exec cucumber
no implicit conversion of nil into String (TypeError)

Can any one help me, please?

![screen shot 2017-08-10 at 3 23 17 pm](https://user-images.githubusercontent.com/18065428/29165321-ebacf828-7ddf-11e7-9d85-119c3fad138c.png)

**Comment by piyush8** [comment]
Please help me 
When I am running: **Bundle exec cucumber -v**
The app is automatically getting uninstall why?
WARN: [2017-08-10 23:16:27 +0530] Could not launch the app.  Trying again after a reinstall.
[Device] Uninstalling app via ideviceinstaller...
[Device] Uninstall succeeded!
^C
Exiting... Interrupt again to exit immediately.
  Background:                                  # features/tests/articles/article_download.feature:4
  
  There was an error executing:
  
  /Users/apple/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 7a7b3d3f54b949b174bef369b8d162aa5d5921e7 -a /Users/apple/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --codesign-identity "iPhone Developer: David Every (88Y24499KG)"
  
  The command generated this output:
  
  
   (RunLoop::Shell::Error)
  ./features/helpers/application.rb:220:in `launch_and_check'
  ./features/helpers/application.rb:84:in `rescue in launch'
  ./features/helpers/application.rb:74:in `launch'
  ./features/support/01_launch.rb:54:in `Before'
    Given the viewer has been reset            # features/step_definitions/application_steps.rb:26
    And downloaded articles have been deleted  # features/step_definitions/application_steps.rb:80
    Then I wait for the collection to be ready # features/step_definitions/browse_view_steps.rb:98

  @smoke @TC_1542588
  Scenario: TC_1542588 - Download an article we entered from browse view # features/tests/articles/article_download.feature:10
    Given I see the "Iron Man" card                                      # features/step_definitions/browse_view_steps.rb:22
    When I tap the "Iron Man" card                                       # features/step_definitions/browse_view_steps.rb:68
    Then I wait for the article to be downloaded                         # features/step_definitions/article_download_steps.rb:44
    And I wait for the title to be "Iron Man"                            # features/step_definitions/hud_steps.rb:46

Failing Scenarios:
cucumber features/tests/articles/article_download.feature:10 # Scenario: TC_1542588 - Download an article we entered from browse view

1 scenario (1 failed)
7 steps (7 skipped)
0m29.189s

**Comment by jmoody** [comment]
> The app is automatically getting uninstall why?

```
[Device] Uninstalling app via ideviceinstaller...
```

Calabash does not use ideviceinstaller.  The app is being uninstalled because of something _your_ tests are doing.
