### ISSUE TITLE
Prompt user for something while running the test

### ISSUE THREAD

**Issue by vinamelody** [calabash/calabash-ios#1324]
Hi, how can I prompt user for a text while running the test, such as one time password?

I'm looking into something like this but the text is based on user's input.
```
Then /^I enter "([^\"]*)" into the "([^\"]*)" (?:text|input) field$/ do |text_to_type, field_name|
  touch("textField marked: '#{field_name}'")
  wait_for_keyboard
  keyboard_enter_text text_to_type
  sleep(STEP_PAUSE)
end
```

Thanks for help

**Comment by jmoody** [comment]
Use cucumber's `ask` method.

**Comment by vinamelody** [comment]
@jmoody do you mind to add link for example of using it with `calabash-ios` ? been trying to search for example but can't find it :(

**Comment by vinamelody** [comment]
Goodness!! guess this needs to wait for another day for another fresh brain...!
This should be the solution (case sensitive)!

Thanks @jmoody for the clue!

```
Then(/^I enter the secret$/) do
  print "What is the secret?"
  key = STDIN.gets
  wait_for_keyboard
  keyboard_enter_text key
  sleep(STEP_PAUSE)
end
```
