### ISSUE TITLE
Unable to run tests - JSON Dependecy

### ISSUE THREAD

**Issue by christerulfsparre** [calabash/calabash-ios#1326]
I'm no longer able to run any of the tests on my bitrise server as it uses json 2.0.2 gem as default, which collide with calabash. A default gem is not possible to remove so there is no way for me to fix the issue that I am aware of. Is there any chance that calabash will start using a newer version of the json gem?

The error that I get when trying to run my tests:
`Unable to activate run_loop-2.3.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)`

**Comment by sandersaelmans** [comment]
do you use bundler?

**Comment by christerulfsparre** [comment]
Yes I do, but it does not help. I did not have any problems with the tests before until the json gem became a default gem.

**Comment by christerulfsparre** [comment]
Sorry resolved it. I used bundler but not to execute the command only for installing the gem dependencies. My bad! Sorry for wasting time.
