### ISSUE TITLE
Could not connect to the DeviceAgent service - Xcode 9 beta 6 - iOS 11

### ISSUE THREAD

**Issue by nagaraja490** [calabash/calabash-ios#1327]
I installed xcode-beta (xcode 9 beta6). Running my test suite in simulator. My app is installed in simulator with DeviceAgent. But ended with the above error.

 Could not connect to the DeviceAgent service.
 
 device: #<Simulator: iPhone 6 (11.0) 7E930147-F592-4300-A483-875680A9C6D2 x86_64>
    url: http://127.0.0.1:27753/
 
 To diagnose the problem tail the launcher log file:
 
 $ tail -1000 -F /Users/nnaick001c/.calabash/iOSDeviceManager/logs/current.log
 
  (RuntimeError)
 ./features/support/01_launch.rb:19:in `launch'
 ./features/support/01_launch.rb:138:in `Before'

**Comment by nagaraja490** [comment]
I installed xcode-beta (xcode 9 beta6). Running my test suite in simulator.  My app is installed in simulator with DeviceAgent. But ended with the above error.

**Comment by jmoody** [comment]
More details please.

https://github.com/calabash/calabash-ios/wiki#reporting-problems

Specifically, what is your run-loop version?

**Comment by nagaraja490** [comment]
Update run loop  to *run_loop 2.5.4*. My script is running. 
@jmoody Thanks
