### ISSUE TITLE
High Sierra Support

### ISSUE THREAD

**Issue by ab-smith** [calabash/calabash-ios#1341]
Hello,
Trying to install calabash on OS X High Sierra fails :

curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash

ERROR: calabash-sandbox only runs on macOS El Cap and Sierra

Thank you,

**Comment by jmoody** [comment]
That tool has been deprecated.

We recommend installing ruby with rbenv and managing your gem versions with a Gemfile and bundler.

https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS
