### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by Oopla** [calabash/calabash-ios#1347]
In the wiki, the 3 tutorials links "how to add calabash to xcode" are not clickable anymore:
> [[Debug Config | Tutorial:-Link-Calabash-in-Debug-config]]
> [[Calabash Config | Tutorial:-Calabash-config]]
> [[-cal Target | Tutorial:--Creating-a-cal-Target]]

Same with "DeviceAgent" in the right menu:
> [[NEW DeviceAgent|DeviceAgent]]

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode

**Comment by jmoody** [comment]
Thanks!  Fixed.
