### ISSUE TITLE
DeviceAgent-Runner.app: the requested application's data container path does not exist

### ISSUE THREAD

**Issue by ketan077** [calabash/calabash-ios#1350]

**Comment by jmoody** [comment]
More information please.

**Comment by ketan077** [comment]
/Applications/Xcode_8.3.3.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=f16583ed3a14aecb08183682c94aab67943ca08a -derivedDataPath /Users/radmin/.run-loop/DeviceAgent/DerivedData

for above command ios 10.2 version i'm getiing below error


2017-11-21 16:37:33.736 xcodebuild[58104:680648]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.DeviceAgent-Runner [Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application's data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application's data container path does not exist., com.apple.dtdevicekit.stacktrace=(

**Comment by jmoody** [comment]
Please try updating to the latest Xcode.

**Comment by ketan077** [comment]
I updated xcode 8.3.3 to 9.0.1 still same issue i'm phasing

**Comment by ketan077** [comment]
below is the log
---------------------


 IDEDerivedDataPathOverride = /Users/radmin/.run-loop/DeviceAgent/DerivedData
    IDETestRunSpecificationPath = /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun

2017-11-22 06:54:09.765 xcodebuild[3424:117055] CoreSimulator detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework) and version (494.22.3) does not match existing job path (/Applications/Xcode_8.3.3.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (375.21).  Attempting to remove the stale service in order to add the expected version.
2017-11-22 06:54:10.080 xcodebuild[3424:117042]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/zj/6z_t753j721f6s6n8vb66yk80000gn/T/com.apple.dt.XCTest/IDETestRunSession-A3608CBD-85B8-4076-8961-DFEFEE4A652B/Unnamed-Test-Run-2A145171-6DF6-40CC-87C2-A1719F562A9C/Session-Unnamed-Test-Run-2017-11-22_065410-JB1bDW.log
2017-11-22 06:54:10.081 xcodebuild[3424:117037] [MT] IDETestOperationsObserverDebug: (FFB47626-9C04-4C32-B1A1-1ED54EDDB494) Beginning test session Unnamed-Test-Run-FFB47626-9C04-4C32-B1A1-1ED54EDDB494 at 2017-11-22 06:54:10.080 with Xcode 9A1004 on target <DVTiOSDevice: 0x7fb66e036260> {
		deviceSerialNumber:         DNRPKGVCG5MD
		identifier:                 f16583ed3a14aecb08183682c94aab67943ca08a
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           f16583ed3a14aecb08183682c94aab67943ca08a
		productVersion:             10.2.1
		buildVersion:               14D27
		deviceSoftwareVersion:      10.2.1 (14D27)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12025450496
		deviceAvailableCapacity:    9067147264
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fb66ddb2bc0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (10.2.1 (14D27))
2017-11-22 06:54:11.711 xcodebuild[3424:117042]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.DeviceAgent-Runner [Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010d48fa0d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010d490251 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x000000010d4a2206 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x000000010d4a10a2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x000000010d492235 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x000000010d49163f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x000000010d49143a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffa1bb3536 _dispatch_barrier_sync_f_invoke + 83
	9   DVTFoundation                       0x0000000101df4c78 DVTDispatchBarrierSync + 213
	10  DVTFoundation                       0x0000000101dce296 -[DVTDispatchLock performLockedBlock:] + 75
	11  DTDeviceKitBase                     0x000000010d491335 DTDKExecuteWithConnection + 231
	12  DTDeviceKitBase                     0x000000010d4920a1 DTDKExecuteInSession + 381
	13  DTDeviceKitBase                     0x000000010d4a0fd9 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	14  DVTFoundation                       0x0000000101df3fd7 __DVTDispatchAsync_block_invoke + 806
	15  libdispatch.dylib                   0x00007fffa1bbb524 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fffa1bc89a0 _dispatch_queue_serial_drain + 896
	18  libdispatch.dylib                   0x00007fffa1bbb306 _dispatch_queue_invoke + 1046
	19  libdispatch.dylib                   0x00007fffa1bb46b5 _dispatch_root_queue_drain + 476
	20  libdispatch.dylib                   0x00007fffa1bb448c _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffa1e015a2 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffa1e0107d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}]
2017-11-22 06:54:11.711 xcodebuild[3424:117159]  iPhoneConnect: Error uploading test configuration to app container: Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010d48fa0d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010d490251 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x000000010d4a2206 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x000000010d4a10a2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x000000010d492235 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x000000010d49163f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x000000010d49143a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffa1bb3536 _dispatch_barrier_sync_f_invoke + 83
	9   DVTFoundation                       0x0000000101df4c78 DVTDispatchBarrierSync + 213
	10  DVTFoundation                       0x0000000101dce296 -[DVTDispatchLock performLockedBlock:] + 75
	11  DTDeviceKitBase                     0x000000010d491335 DTDKExecuteWithConnection + 231
	12  DTDeviceKitBase                     0x000000010d4920a1 DTDKExecuteInSession + 381
	13  DTDeviceKitBase                     0x000000010d4a0fd9 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	14  DVTFoundation                       0x0000000101df3fd7 __DVTDispatchAsync_block_invoke + 806
	15  libdispatch.dylib                   0x00007fffa1bbb524 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fffa1bc89a0 _dispatch_queue_serial_drain + 896
	18  libdispatch.dylib                   0x00007fffa1bbb306 _dispatch_queue_invoke + 1046
	19  libdispatch.dylib                   0x00007fffa1bb46b5 _dispatch_root_queue_drain + 476
	20  libdispatch.dylib                   0x00007fffa1bb448c _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffa1e015a2 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffa1e0107d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}
2017-11-22 06:54:11.718 xcodebuild[3424:117037] Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010d48fa0d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010d490251 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x000000010d4a2206 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x000000010d4a10a2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x000000010d492235 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x000000010d49163f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x000000010d49143a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffa1bb3536 _dispatch_barrier_sync_f_invoke + 83
	9   DVTFoundation                       0x0000000101df4c78 DVTDispatchBarrierSync + 213
	10  DVTFoundation                       0x0000000101dce296 -[DVTDispatchLock performLockedBlock:] + 75
	11  DTDeviceKitBase                     0x000000010d491335 DTDKExecuteWithConnection + 231
	12  DTDeviceKitBase                     0x000000010d4920a1 DTDKExecuteInSession + 381
	13  DTDeviceKitBase                     0x000000010d4a0fd9 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	14  DVTFoundation                       0x0000000101df3fd7 __DVTDispatchAsync_block_invoke + 806
	15  libdispatch.dylib                   0x00007fffa1bbb524 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fffa1bb28fc _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fffa1bc89a0 _dispatch_queue_serial_drain + 896
	18  libdispatch.dylib                   0x00007fffa1bbb306 _dispatch_queue_invoke + 1046
	19  libdispatch.dylib                   0x00007fffa1bb46b5 _dispatch_root_queue_drain + 476
	20  libdispatch.dylib                   0x00007fffa1bb448c _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffa1e015a2 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffa1e0107d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}
2017-11-22 06:54:11.718 xcodebuild[3424:117037] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

**Comment by JoeSSS** [comment]
Looks like you didn’t change the path to your new Xcode, log still references to 8.3.3 . You can change the path by going in preferences - location in your Xcode

**Comment by ketan077** [comment]
/Applications/Xcode_9_1.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=f16583ed3a14aecb08183682c94aab67943ca08a -derivedDataPath /Users/radmin/.run-loop/DeviceAgent/DerivedData



see above command  & also same output for that
-----------------------------------------------------------------



User defaults from command line:
    IDEDerivedDataPathOverride = /Users/radmin/.run-loop/DeviceAgent/DerivedData
    IDETestRunSpecificationPath = /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun

2017-11-22 07:33:27.511 xcodebuild[1819:57329]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/zj/6z_t753j721f6s6n8vb66yk80000gn/T/com.apple.dt.XCTest/IDETestRunSession-582DDC5F-9F2F-4AE0-9D99-5EC25EF3BDD4/Unnamed-Test-Run-52D657F1-23ED-4232-9BC6-F475B8C210C7/Session-Unnamed-Test-Run-2017-11-22_073327-4OVNpb.log
2017-11-22 07:33:27.511 xcodebuild[1819:57325] [MT] IDETestOperationsObserverDebug: (4928342D-5D68-4C96-8452-6DFAB522CCB1) Beginning test session Unnamed-Test-Run-4928342D-5D68-4C96-8452-6DFAB522CCB1 at 2017-11-22 07:33:27.511 with Xcode 9B55 on target <DVTiOSDevice: 0x7f8c1b5a6db0> {
		deviceSerialNumber:         DNRPKGVCG5MD
		identifier:                 f16583ed3a14aecb08183682c94aab67943ca08a
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           f16583ed3a14aecb08183682c94aab67943ca08a
		productVersion:             10.2.1
		buildVersion:               14D27
		deviceSoftwareVersion:      10.2.1 (14D27)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12025450496
		deviceAvailableCapacity:    9061969920
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f8c1b73f140 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (10.2.1 (14D27))
2017-11-22 07:33:28.901 xcodebuild[1819:57383]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.DeviceAgent-Runner [Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001128a6d3d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x00000001128a7581 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x00000001128b9536 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001128b83d2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x00000001128a9565 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x00000001128a896f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x00000001128a876a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff935cc536 _dispatch_barrier_sync_f_invoke + 83
	9   libdispatch.dylib                   0x00007fff935d660d _dispatch_barrier_sync_f_slow + 540
	10  DVTFoundation                       0x00000001072206a8 DVTDispatchBarrierSync + 213
	11  DVTFoundation                       0x00000001071f9cc6 -[DVTDispatchLock performLockedBlock:] + 75
	12  DTDeviceKitBase                     0x00000001128a8665 DTDKExecuteWithConnection + 231
	13  DTDeviceKitBase                     0x00000001128a93d1 DTDKExecuteInSession + 381
	14  DTDeviceKitBase                     0x00000001128b8309 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	15  DVTFoundation                       0x000000010721fa07 __DVTDispatchAsync_block_invoke + 806
	16  libdispatch.dylib                   0x00007fff935d4524 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff935e19a0 _dispatch_queue_serial_drain + 896
	19  libdispatch.dylib                   0x00007fff935d4306 _dispatch_queue_invoke + 1046
	20  libdispatch.dylib                   0x00007fff935cd6b5 _dispatch_root_queue_drain + 476
	21  libdispatch.dylib                   0x00007fff935cd48c _dispatch_worker_thread3 + 99
	22  libsystem_pthread.dylib             0x00007fff9381a5a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x00007fff9381a07d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}]
2017-11-22 07:33:28.901 xcodebuild[1819:57396]  iPhoneConnect: Error uploading test configuration to app container: Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001128a6d3d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x00000001128a7581 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x00000001128b9536 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001128b83d2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x00000001128a9565 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x00000001128a896f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x00000001128a876a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff935cc536 _dispatch_barrier_sync_f_invoke + 83
	9   libdispatch.dylib                   0x00007fff935d660d _dispatch_barrier_sync_f_slow + 540
	10  DVTFoundation                       0x00000001072206a8 DVTDispatchBarrierSync + 213
	11  DVTFoundation                       0x00000001071f9cc6 -[DVTDispatchLock performLockedBlock:] + 75
	12  DTDeviceKitBase                     0x00000001128a8665 DTDKExecuteWithConnection + 231
	13  DTDeviceKitBase                     0x00000001128a93d1 DTDKExecuteInSession + 381
	14  DTDeviceKitBase                     0x00000001128b8309 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	15  DVTFoundation                       0x000000010721fa07 __DVTDispatchAsync_block_invoke + 806
	16  libdispatch.dylib                   0x00007fff935d4524 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff935e19a0 _dispatch_queue_serial_drain + 896
	19  libdispatch.dylib                   0x00007fff935d4306 _dispatch_queue_invoke + 1046
	20  libdispatch.dylib                   0x00007fff935cd6b5 _dispatch_root_queue_drain + 476
	21  libdispatch.dylib                   0x00007fff935cd48c _dispatch_worker_thread3 + 99
	22  libsystem_pthread.dylib             0x00007fff9381a5a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x00007fff9381a07d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}
2017-11-22 07:33:28.907 xcodebuild[1819:57325] Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application’s data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application’s data container path does not exist., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001128a6d3d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x00000001128a7581 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x00000001128b9536 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001128b83d2 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x00000001128a9565 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x00000001128a896f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x00000001128a876a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff935cc536 _dispatch_barrier_sync_f_invoke + 83
	9   libdispatch.dylib                   0x00007fff935d660d _dispatch_barrier_sync_f_slow + 540
	10  DVTFoundation                       0x00000001072206a8 DVTDispatchBarrierSync + 213
	11  DVTFoundation                       0x00000001071f9cc6 -[DVTDispatchLock performLockedBlock:] + 75
	12  DTDeviceKitBase                     0x00000001128a8665 DTDKExecuteWithConnection + 231
	13  DTDeviceKitBase                     0x00000001128a93d1 DTDKExecuteInSession + 381
	14  DTDeviceKitBase                     0x00000001128b8309 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	15  DVTFoundation                       0x000000010721fa07 __DVTDispatchAsync_block_invoke + 806
	16  libdispatch.dylib                   0x00007fff935d4524 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff935cb8fc _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff935e19a0 _dispatch_queue_serial_drain + 896
	19  libdispatch.dylib                   0x00007fff935d4306 _dispatch_queue_invoke + 1046
	20  libdispatch.dylib                   0x00007fff935cd6b5 _dispatch_root_queue_drain + 476
	21  libdispatch.dylib                   0x00007fff935cd48c _dispatch_worker_thread3 + 99
	22  libsystem_pthread.dylib             0x00007fff9381a5a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x00007fff9381a07d start_wqthread + 13
), NSLocalizedRecoverySuggestion=The requested application’s data container path does not exist., NSLocalizedDescription=The requested application’s data container path does not exist.}
2017-11-22 07:33:28.907 xcodebuild[1819:57325] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

**Comment by jmoody** [comment]
> CoreSimulator detected Xcode.app relocation or CoreSimulatorService version change. Framework path 

You need to restart your machine after you install Xcode, rename the Xcode.app directory, or move the Xcode.app anywhere.

> /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun

Given the other issues you have created, I suspect that your `/usr/local/lib/ruby` still has the wrong permissions.

**Comment by ketan077** [comment]
Hi jmoody
Thanks for help

After device resetting it works fine .

in device there is one device agent  is already installed which is corrupted file so that's why i'm getting above error. After device resetting it works fine .
