### ISSUE TITLE
can you help me below issue in ios v11 device??

### ISSUE THREAD

**Issue by ketan077** [calabash/calabash-ios#1352]
RBOX-1:~ radmin$  /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/bin/iOSDeviceManager install /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id cc231e63e356086dc01e5ba5520a755abbae76f0
2017-11-21 08:45:35.321 iOSDeviceManager[77006:1877990] *** Terminating app due to uncaught exception 'CBXException', reason: 'Unable to write EntitlementsMeta to application.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffc84df2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffdd2ef48d objc_exception_throw + 48
	2   iOSDeviceManager                    0x000000010023e0c6 +[Command resourcesFromArgs:] + 0
	3   iOSDeviceManager                    0x0000000100222948 +[Codesigner resignAppDir:baseDir:provisioningProfile:codesignIdentity:resourcesToInject:] + 1618
	4   iOSDeviceManager                    0x0000000100220da2 +[Codesigner resignApplication:withProvisioningProfile:withCodesignIdentity:resourcesToInject:] + 283
	5   iOSDeviceManager                    0x000000010021c621 -[PhysicalDevice installApp:mobileProfile:codesignIdentity:resourcesToInject:shouldUpdate:] + 607
	6   iOSDeviceManager                    0x000000010021c9d6 -[PhysicalDevice installApp:resourcesToInject:shouldUpdate:] + 67
	7   iOSDeviceManager                    0x000000010021f228 +[InstallAppCommand execute:] + 876
	8   iOSDeviceManager                    0x0000000100240c99 +[CLI process:] + 1063
	9   iOSDeviceManager                    0x000000010020c431 main + 121
	10  libdyld.dylib                       0x00007fffddbd5235 start + 1
	11  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by jmoody** [comment]
> Unable to write EntitlementsMeta to application
>  /usr/local/lib/ruby

This directory is not writeable.  Change the permissions to read/write.
