### ISSUE TITLE
NoMethodError: undefined method `wait_for_view' for #<DeviceAgent API: 1.2.2>

### ISSUE THREAD

**Issue by seshusangeetha** [calabash/calabash-ios#1366]
Hi,
As suggested with the usage document for device agent tried using the device_agent.wait_for_view method for element_exists to assert the presence of an element but have been presented with the below error
NoMethodError: undefined method `wait_for_view' for #<DeviceAgent API: 1.2.2>
<img width="598" alt="screen shot 2018-02-02 at 4 48 49 pm" src="https://user-images.githubusercontent.com/35687680/35731204-ce19c0b2-083a-11e8-9f55-d4c061b8bb57.png">

can you kindly help us with the usage of the same

Thanks

**Comment by jmoody** [comment]
I am adding a wait API to the next release of Calabash.

However, this is probably the last time some one at MSFT will add behavior to Calabash.

If you want to expand Calabash features, you have to do so yourself.

You can find the DeviceAgent HTTP API (including a wait API) in run-loop:

https://github.com/calabash/run_loop/blob/develop/lib/run_loop/device_agent/client.rb
