### ISSUE TITLE
Tap swipeAction element 

### ISSUE THREAD

**Issue by UGhari** [calabash/calabash-ios#1368]
I am using Calabash on IOS.

I have .a TableView, I am swiping left on one of the cells which reveals a swipe action. In this instance a label is revealed which snoozes a notification:

<img width="274" alt="screen shot 2018-03-02 at 18 10 42" src="https://user-images.githubusercontent.com/15021364/36914392-15f22328-1e45-11e8-9877-6571a08418e9.png">

I am trying to tap this label but I cant seem to find the element with Calabash. SwipeAction also does not have a member accessibilityIdentifier. Also when I output the `tree` structure of the view the Swipe menu automatically closes and its not shown in the `tree output` either.

Also if I manually Swipe the SwipeAction so 'Snooze' is visible and then use the command:

`query("* marked:'Snooze'")` 

I get an empty array returned and the SwipeAction disappears again. Is it possible to tap this button with Calabash?

Thanks

**Comment by jmoody** [comment]
>  Is it possible to tap this button with Calabash?

Probably.

> query("* marked:'Snooze'")

Try:

```
query("* text:'Snooze'")
```

> the SwipeAction disappears again.
>  output the tree structure of the view the Swipe menu automatically closes

That seems like a bug, but I am not sure how calabash could cause that bug.

**Comment by UGhari** [comment]
`query("* text:'Snooze'")` Didnt seem to work either.
