### ISSUE TITLE
Not able to query elements on app ratings screen of ios native application

### ISSUE THREAD

**Issue by sravanibattula** [calabash/calabash-ios#1370]
Hello @jmoody 

I am not able to query elements on app ratings screen of iOS native application.**Is there any way to touch or query elements on the app ratings screen?**Looks like app ratings screen is a part of OS of iPhone or iPad though it appears on the app.

Thank you,
Sravani

**Comment by jmoody** [comment]
You need to use the DeviceAgent API.

https://github.com/calabash/calabash-ios/wiki/DeviceAgent#when-should-i-use-the-new-deviceagent-methods
