### ISSUE TITLE
Calabash breaks logging in Xcode

### ISSUE THREAD

**Issue by ryanmeisters** [calabash/calabash-ios#1386]
We are currently using calabash-its v0.20.4 installed via Cocoapods and all is well. When I update to the latest version (0.21.5) all logging is broken. There are two logs from calabash, but nothing else (see screenshot below). Even adding a `print` statement at the beginning of `application(didFinishLaunchingWithOptions:)` doesn't work. 

Any insights? 

We have temporarily fixed by removing calabash-ios from our debug config, so it is only linked for our alpha builds. 
`pod 'Calabash', '~> 0.21.5', :configurations => ['Alpha']`

![screen shot 2018-07-09 at 11 55 16 am](https://user-images.githubusercontent.com/1131791/42470402-2aec043a-836f-11e8-9ffc-47c715bb7efd.png)

**Comment by JoeSSS** [comment]
This has changed in Xcode9. You can redirect logs to file (e.g. https://stackoverflow.com/questions/34026018/swift-redirect-console-log-to-document-folder)

**Comment by ryanmeisters** [comment]
@JoeSSS I'm not sure I follow. Is calabash-ios doing some internal log routing?

**Comment by jmoody** [comment]
@ryanmeisters Apple changed the entire logging system so you no longer see as many logs in Xcode.  Calabash tries to reroute the logs so they appear as they used to appear.  You can find all logs in the Console app.

**Comment by ryanmeisters** [comment]
I see. That seems like an odd side effect for a dependency. Is there a way to disable? Happy to make a PR if someone can point me in the right direction

**Comment by jmoody** [comment]
Remove code in these two places:

* https://github.com/calabash/calabash-ios-server/blob/develop/calabash/Classes/CalabashServer.m#L55
* https://github.com/calabash/DeviceAgent.iOS/blob/develop/Server/CBXCUITestServer.m#L68

> odd side effect

Perhaps.   On the other hand, Apple's logging changes have broken some user's workflows.

With that said, removing this behavior is probably the right decision.  Apps can opt-in by adding the redirect code.

**Comment by ryanmeisters** [comment]
Ah thanks for that. I was thinking we could just add a preprocessor macro, something like `CALABASH_DISABLE_LOG_REDIRECT`. I'm a bit confused now though since those two links are in other repositories. How does `calabash-ios` interact with `calabash-ios-server` and the main `calabash`?

**Comment by AlexWellsHS** [comment]
@jmoody the code blocks you referenced seem to only run if the app is running on a simulator. however, were experiencing this issue when running on attached devices as well. is this expected?

**Comment by jmoody** [comment]
> only if the app is running on the simulator

Not expected.  Probably not caused by Calabash.  I believe you have to look in the Console.app now.
