### ISSUE TITLE
Calabash is not linked to built IPA?

### ISSUE THREAD

**Issue by lkuich** [calabash/calabash-ios#1391]
Hi, I followed [this](https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-Calabash-config) guide for linking Calabash to my non-Xamarin.iOS project, and when running it directly from Xcode, my Xamarin.UITest's run fine.

However, I want to build it as an IPA so I can submit it to VS App Center for testing. It seems that Calabash is not linked in the IPA, even though I targeted my new scheme.

After I locally install the IPA and run my UITest:
`System.Exception : Unable to contact test backend running in app. A common cause is that the app is not properly linked with Calabash. Please verify that it includes the Calabash component.`
Sure enough: `calabash-ios check Calabash.ipa` shows it is not linked.

A lot of posts recommend adding `Xamarin.Calabash.Start()`, though this is not a Xamarin.iOS project. It's actually a Unity project, I've embedded an HTTP server to act as the middleman, and it works quite well locally.

I cannot understand if Calabash cannot be linked in the IPA, how am I supposed to upload a non Xamarin.iOS project to VS App Center?

Any advise is appreciated. Regards,
Loren

**Comment by jmoody** [comment]
How are you building the .ipa?

**Comment by lkuich** [comment]
@jmoody I edited the scheme to target my Calabash scheme on Archive (like this, but targeting Archive: https://cloud.githubusercontent.com/assets/466104/10657847/420b7358-7891-11e5-9106-8a8a6353b1d5.png), but the issue persists.

In Xcode, I'm going to Product > Archive > Export > Ad Hoc > No thinning > Automatic Signing

**Comment by lkuich** [comment]
I figured it out, I took a guess and added `calabash.framework`, under "Linked frameworks and Libraries" as well...
Maybe it would be good to include this in the various guides? I haven't seen this written anywhere.
