### ISSUE TITLE
Unable to download version 0.21.8

### ISSUE THREAD

**Issue by rgkobashi** [calabash/calabash-ios#1403]
Hi, first of all thanks for this framework.
I am having a problem updating my calabash version, I am following the steps described on the [guide](https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version) but seems that the version of my gem is not the same as the downloaded:

```
$ calabash-ios version
0.21.8
$ calabash-ios download

----------Info----------
caution: excluded filename not matched:  __MACOSX/*
caution: excluded filename not matched:  calabash.framework/.DS_Store
---------------------------
$ calabash.framework/Resources/version
0.21.7
```

My version installed is `0.21.8` but the downloaded is `0.21.7`. I thought that it might be my mac so I tried in my CI and same problem.
I dont have much experience working with calabash so perhaps I am missing something.
I would appreciate if someone can help me with this.
Btw, I am not using bundler.

Thanks in advance.

**Comment by jmoody** [comment]
The latest version of the Calabash iOS Server is 0.21.7.  It is compatible with the 0.21.8 version of the gem.
