### ISSUE TITLE
  i have an issue  execution expired (HTTPClient::ReceiveTimeoutError)

### ISSUE THREAD

**Issue by umapathireddy** [calabash/calabash-ios#1404]
: Search packge with Iflow artifacts.zip   : 201
17 : SuccessFactors Employee Central with IBM Kenexa.zip   : 201
18 : SuccessFactors Employee Central with Third-Party Time Vendor - Kronos.zip   : 201
19 : SuccessFactors Integration Center - Benefit Salary Template.zip   : 201
20 : SuccessFactors Integration Center - Bonus Template.zip   : 201
21 : TryOutTestPackage.zip   : 201
  0.094000   0.078000   0.172000 (120.120540)
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
execution expired (HTTPClient::ReceiveTimeoutError)
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `gets'
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
D:/Ruby23/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

**Comment by jmoody** [comment]
We need more of a stack trace.  From what you have posted, I cannot tell if Calabash iOS is even being used.

* https://github.com/calabash/calabash-ios/wiki#reporting-problems
* https://github.com/calabash/calabash-ios/wiki#examples-of-good-bug-reports
