### ISSUE TITLE
Xcode 12 - Could not connect to the DeviceAgent service

### ISSUE THREAD

**Issue by bboyle18** [calabash/calabash-ios#1425]
Hi 👋 

I know there was another issue logged for Xcode 12 [related to `UIAutomation.framework`](https://github.com/calabash/calabash-ios/issues/1424).
Not sure if this issue I'm facing is related. If it is, please feel free to close this issue.

I'm getting the following stacktrace when running `bundle exec cucumber`

```
Could not connect to the DeviceAgent service.

 device: #<Simulator: iPhone 11 Pro (14.0) 2FA16AB1-5D39-474F-99FF-01D2C4FD93BC x86_64>
    url: http://127.0.0.1:27753/

 To diagnose the problem tail the launcher log file:

 $ tail -1000 -F /Users/brianboyle/.calabash/iOSDeviceManager/logs/current.log

  (RuntimeError)
 ./features/support/01_launch.rb:31:in `Before'
```

I'm using iPhone 11 Pro by running `export DEVICE_TARGET="iPhone 11 Pro (14.0)"`

**Environment**
**Xcode** `12.0-beta1`
**Calabash-ios** `0.21.10`
**run_loop** `4.2.3`
**Ruby Version** `2.6.3`

Any pointers to get this running would be appreciated.
Thanks 🙂

**Comment by bboyle18** [comment]
👋  @jmoody Just wondering if there any plan to support iOS 14?
Thanks!

**Comment by jmoody** [comment]
I am no longer working on the Calabash project.

**Comment by bboyle18** [comment]
Thanks for the heads up @jmoody and thanks for all your work on this project 🙌🏻

Is there anyone still actively working on it?

**Comment by tkohout** [comment]
+1

**Comment by raamojirao** [comment]
I am facing this issue as well. Is there a solution yet

**Comment by bboyle18** [comment]
Solution here
https://github.com/calabash/calabash-ios/issues/1424#issuecomment-698357153
