### ISSUE TITLE
Feature request: profiler integration

### ISSUE THREAD

**Issue by niklassaers** [calabash/calabash-ios#155]
Hi,
It's awesome that I can take images of the screen, but when I'm writing my tests right now I find that what I really want to take a picture of is my profiler to see that I'm not leaking views and that the processor load doesn't change between test runs.

Is profiler integration something you are looking into? :-)

Cheers

   Nik

**Comment by jmoody** [comment]
Instructions work.  Will not be part of run-loop because the size of the trace files are ENORMOUS.
