### ISSUE TITLE
Connect to Running Server (vs Creating New One)

### ISSUE THREAD

**Issue by 8BitAce** [calabash/calabash-ios#176]
I know this is a rather strange use case, but I'd like to have Calabash running in two separate apps so I can switch between them and test both in one run. However, it is obviously not working as when the second app tries to create a server, it finds one is already running on that port.

Would it be at all possible to have both apps use the same server and send events to the frontmost one? I can try to make the modifications myself, but I can't find where exactly the server is initialized.

**Comment by lovarajukatari** [comment]
Hi Joshua,

Is connect to running server implemented yet? I am having a similar issue. If you have any info could you please share. I wanted to explain my problem here but could not do so as I feel this is not the platform for discussing. Need help with connecting two apps to the same port so I can test on both the apps. My apps switch from one app to another and that is the only way we can access the other app features.

Thanks,
Lova.

**Comment by lovarajukatari** [comment]
Sorry I posted about using single port. As you said earlier it is not possible to communicate on a single port, could you please advice me how I can communicate with two apps by connecting to two different ports?

**Comment by jmoody** [comment]
You can now set the port on a per application basis. [#94](https://github.com/calabash/calabash-ios-server/pull/94)

In your app's info plist create an entry for "CalabashServerPort" and set the port number.

I am not sure this will actually help test two apps at once.

**Comment by lovarajukatari** [comment]
Thanks Joshua.

**Comment by ark-konopacki** [comment]
Hi @jmoody, maybe i miss something but if there is the way to connect running app? I mean we have simulator started from calabash but app was restarted so can we some how reconnect to new app instance?

**Comment by jmoody** [comment]
@ark-konopacki I am afraid I don't understand your question.

This issue is so old, I can barely remember understand the problem even after re-reading the topic.

Can you open a new issue?

**Comment by jmoody** [comment]
> console_attach?  Does that not work?
