### ISSUE TITLE
UIAlertView not accessible / query-able on iOS 7 simulator / Xcode 5

### ISSUE THREAD

**Issue by madhikarma** [calabash/calabash-ios#215]
Also found it reported within here:
https://groups.google.com/forum/#!topic/calabash-ios/SWLfvrTW4KI

It's not possible to query for a UIAlertView via accessibility label / identifier either va cucumber or the interactive calabash-ios console

For a project with a UIAlertView on display via show method and tagged with an accessibility label / identifier running the following 
<code>query("*")</code>
<code>classes("alertView")</code>
<code>query("view marked:'SomethingNetworkErrorAlert'")</code>

does not find the element in iOS 7 (though i believe it should and did in iOS 6?)

Any leads on this? Apple may have changed something to do with which UIWindow the UIAlertView's are now presented in iOS 7. I recall traversing the UIWindow for it out of curiosity in a previous project

**Comment by Harani-me** [comment]
UIAlertControllerView is not working in cucumber feature file run and works fine in irb console. Please suggest.

 "class" => "_UIAlertControllerView",
                       "label" => "title",
                 "description" => "<_UIAlertControllerView: 0x7fba49651bb0; frame = (25 223; 270 122); layer = <CALayer: 0x7fba4968ef50>>",
                       "value" => nil,


"accessibilityElement" => true,
                       "class" => "_UIAlertControllerActionView",
                       "label" => "Button",
                 "description" => "<_UIAlertControllerActionView: 0x7fba497a9120; frame = (0 0; 270 44); Action = <UIAlertAction: 0x7fba4969d8a0 Title = \"Button\" Descriptive = \"(null)\" Image = 0x0>>",
