### ISSUE TITLE
Support for iFrame in webView

### ISSUE THREAD

**Issue by JonnyGibson** [calabash/calabash-ios#23]
We really need to be able to query and touch elements which are inside an iFrame. 

Currently a css or xpath node query returns nil

**Comment by SeleniumWD** [comment]
krukow. Thanks a lot for uia_query. it was very helpfull

**Comment by krukow** [comment]
@sapieneptus FYI

**Comment by sapieneptus** [comment]
Wowsers. Blast from the past. 

We are tracking the issue [here](https://github.com/calabash/calabash-ios-server/pull/308) for anyone interested.
