### ISSUE TITLE
query and uia_query behaving differently

### ISSUE THREAD

**Issue by crmitchelmore** [calabash/calabash-ios#290]
calabash-ios version 0.9.164
server_version "0.9.164

Trying to query a tableview cell that contains a label.

View hierarchy:
UITableViewCell -> UIView -> UILabel

Successfully works with swipe but not query
```
query("tableViewCell {text LIKE 'Stella Artois  Bottle '}")
[]
swipe("left", {:query => "tableViewCell {text LIKE 'Stella Artois  Bottle '"})
[object]
```
Using:
```
query("tableViewCell descendant view {text LIKE 'Stella Artois  Bottle '}")
```
also works

Full gist
https://gist.github.com/thinkplay11/8434163

**Comment by jmoody** [comment]
Outdated; closing.  I think uia_query and query _do_ behave differently, but I am not sure if we can do anything about it.
