### ISSUE TITLE
not able to get time when querying for CMTime

### ISSUE THREAD

**Issue by andyhuynh86** [calabash/calabash-ios#335]
querying an AVPlayer to get the :currentTime. That returns a CMTime, which is a struct. Unable to convert struct information to usable output.

Output is something like: 
"<f43bd3d8 03000000 00ca9a3b 01000000 00000000 00000000>"

**Comment by jmoody** [comment]
Can't add to this the server because it would require the server link AV frameworks.

A backdoor is your only option.
