### ISSUE TITLE
app arguments are not being passed when launching with ios-sim (and maybe not when launching with instruments)

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#363]
This [pull 76](https://github.com/calabash/calabash-ios/pull/76) provides support, but it looks like the behavior has been lost.

```
# args are never passed to SimLauncher::Simulator.launch_ios_app
launch_ios_app(app_bundle_path, sdk, device_family)
```

It looks like RunLoop supports passing arguments, but I am not sure it actually works.

Can test by passing:

```
# approximate German (heh) localizations
-NSDoubleLocalizedStrings YES

# put non-localized strings in all caps
-NSShowNonLocalizedStrings YES

# set the language 
-AppleLanguages (es)
```

There are more options here: http://nshipster.com/launch-arguments-and-environment-variables/

**Comment by Ashton-W** [comment]
With this still not working, is there anyway to configure the app before launching tests?

**Comment by mokagio** [comment]
@jmoody any news on this?

**Comment by jmoody** [comment]
@Ashton-W and @mokagio 

As of Calabash 0.13.0 and run-loop 1.2.8, I believe this will work:

```
options = {
  :args => ['-NSDoubleLocalizedStrings', 'YES']
}

...launcher.relaunch(options)
```

I have not had any time to write tests for this.

**Comment by mokagio** [comment]
@jmoody I works, thanks :+1:  And for the record I'm running on 0.12.3.

I'm using the launch argument to toggle on and off the _long_ onboarding flow on my project. I don't like having things hardcoded, so I've set the before hook like this:

```ruby
Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  options = {}
  unless @calabash_launcher.calabash_no_launch?
    if ENV["COMMA_SEPARATED_ARGUMENTS"]
      arguments = ENV["COMMA_SEPARATED_ARGUMENTS"].split(",")
      options[:args] = arguments
    end

    @calabash_launcher.relaunch(options)
    @calabash_launcher.calabash_notify(self)
  end
end
```

Does it make sense? I could open a PR with this edit, although I don't have a lot of time at the moment.

**Comment by jmoody** [comment]
@mokagio Sweet!  It worked.

Can you have a look at your run-loop version?  That is where the behavior was implemented.

> I could open a PR with this edit, although I don't have a lot of time at the moment.

Thanks for the offer!  However, we are not ready to advertise this yet as feature.  We need to see how it break first. :)

**Comment by mokagio** [comment]
>  We need to see how it break first. :)

Very good point :+1:

**Comment by benshan** [comment]
I wanted to share that we are using this to catch CoreData threading violations with our tests:
['-com.apple.CoreData.ConcurrencyDebug', '1']

**Comment by Ashton-W** [comment]
@mokagio has this been working for you?

**Comment by jmoody** [comment]
Fixed.
