### ISSUE TITLE
Reducing UIScript logging

### ISSUE THREAD

**Issue by towercap** [calabash/calabash-ios#389]
Looking to limit the type of events logged in the console. Currently, the -cal scheme floods the log with messages of the following type:
```C
May 16 10:57:05 ***[39027] <Warning>: Map POST, /map Parsed UIScript as
(
   "view:'UINavigationButton'",
   "with marked:'Menu'"
)
May 16 10:57:06 --- last message repeated 2 times ---
May 16 10:57:06 ***[39027] <Warning>: Map POST, /map Parsed UIScript as
(
   "view:'UIView'",
   "with marked:'Purpose'"
)
May 16 10:57:07 --- last message repeated 1 time ---
```
This becomes a nuisance when debugging a failing test.

**Comment by tommeier** [comment]
@krukow Would that allow us to use more descriptive logging levels? (rather than 'on', 'debug' and 'debug and http')? Would something like 'cocoalumberjack' help?

**Comment by krukow** [comment]
@tommeier yes that's possible. Three levels

```
  if ([@"debug" isEqualToString:[logLevel lowercaseString]]) {
    _logLevel = LPLogLevelDebug;
  } else if ([@"info" isEqualToString:[logLevel lowercaseString]]) {
    _logLevel = LPLogLevelInfo;
  } else if ([@"error" isEqualToString:[logLevel lowercaseString]]) {
    _logLevel = LPLogLevelError;
  }
```

**Comment by jmoody** [comment]
Added CocoaLumberjack.

There a number of NSLog related issued pending on the server.

Closing.
