### ISSUE TITLE
Some UIScrollViewDelegate methods does not get called when executing scroll commands

### ISSUE THREAD

**Issue by JaniJegoroff** [calabash/calabash-ios#392]
Only *scrollViewDidScroll* delegate method is called when executing scroll commands such as *scroll* and *scroll_to_collection_view_item*. For example delegate methods *scrollViewWillBeginDecelerating* and *scrollViewDidEndDecelerating* does not get called even those are implemented.

See discussing about the issue: https://groups.google.com/d/msg/calabash-ios/tlsmGHeMPYg/njO3nekpycsJ

Sample project to reproduce the issue: https://github.com/JaniJegoroff/ICViewPager

**Comment by avanderberg** [comment]
Has anyone found a solution for this? I have the same problem.
I use:
```
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

$ xcodebuild -version
Xcode 6.2
Build version 6C131e

$ calabash-ios version
0.13.0
```
```
> server_version
{
                         "app_id" => "de.axelspringer.weltipad",
                        "outcome" => "SUCCESS",
                    "server_port" => 37265,
                        "version" => "0.13.0",
                       "app_name" => "Unknown",
                         "system" => "x86_64",
               "simulator_device" => "iPad",
                      "simulator" => "",
                    "app_version" => "1.0",
    "iphone_app_emulated_on_ipad" => false,
                            "git" => {
             "revision" => "0a69c5b",
        "remote_origin" => "git@github.com:calabash/calabash-ios-server.git",
               "branch" => "master"
    },
              "screen_dimensions" => {
        "sample" => 1,
        "height" => 2048,
         "width" => 1536,
         "scale" => 2
    },
                          "4inch" => false,
                    "iOS_version" => "8.2"
}
```
Scrolling manually with my hand works fine.

**Comment by jmoody** [comment]
No update.  Pull requests are welcome.

**Comment by jmoody** [comment]
Replacing with **Scroll operations should call target action pairs and delegate methods (when possible)** [#223](https://github.com/calabash/calabash-ios-server/issues/223)
