### ISSUE TITLE
WebView scalesPageToFit

### ISSUE THREAD

**Issue by krukow** [calabash/calabash-ios#41]
https://groups.google.com/d/topic/calabash-ios/is9Humnl5ys/discussion

...
I did notice that setting webView.scalesPageToFit = YES will cause the 
links not to be clicked, even if they are visible - but this is not 
the cause of the issue in my original project.

**Comment by jmoody** [comment]
Closing; outdated and fixed as far as I can tell...

@michaelkirk Hi Michael!
