### ISSUE TITLE
Override DEFAULT_OPTS

### ISSUE THREAD

**Issue by brendensoares** [calabash/calabash-ios#488]
I want to override `DEFAULT_OPTS[:timeout]` but can't because `DEFAULT_OPTS` is frozen.

1) why is `DEFAULT_OPTS` frozen?
2) how do I override the timeout?

I don't want to manually override the timeout since it's needed in multiple step definitions. Is there no other way?

**Comment by niekske** [comment]
@jmoody The freeze does still exist on Android: https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/wait_helpers.rb

Any idea if it will be removed there also or was it intended to leave it on Android?

**Comment by jmoody** [comment]
It is a mistake.

Can you open a PR on the android repo?
