### ISSUE TITLE
NSUserDefaults synchronize does not persist in-memory contents to disk in CoreSimulator simulators

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#536]
I discovered this problem while testing reset_app_sandbox for CoreSimulators

I made a 4 minute video (no audio) that demonstrates the bug. [1]

The gist is that NSUserDefaults synchronize does not persist the in-memory contents of NSUserDefaults to disk when called programmatically or when UIEvents are triggered by UIAutomation via the instruments tool.  

Defaults are persisted if: 

1. the Instruments.app is used (shown in the video) and 
2. the UIEvent is triggered by a 'manual' gesture (not shown in the video).

This bug appears in some, but not all of the simulators.

- [1] http://www.screencast.com/t/dxwNbDxn0Dp

#### Reproduce

```
$ cd calabash-ios
$ script/ci/travis/cucumber-ci.rb
```

#### Expected

Scenario: 21 The switch should be on because I did not reset the app before this Scenario should pass because the switch is on.

#### Found

Despite this block of code being called in the app:

```
- (void) switchValueChanged:(UISwitch *) sender {
  NSLog(@"switch value changed");
  BOOL state = sender.isOn;
  NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  [defaults setBool:state forKey:kUserDefaultsSwitchState];
  [defaults synchronize];
}
```

the contents of NSUserDefaults is not persisted to disk.

#### Analysis

It is possible that this is isolated to iOS 8 simulators.  I have not had time to investigate.

**NB** 7.0.3 Simulators are not tested because of this bug. [1]

- [1] [REGRESSION Cannot launch iOS 7.0.3 Simulators with instrument Xcode 6](http://openradar.appspot.com/radar?id=5221532267708416)

##### Failing Scenarios

```
  # Demonstrate that resetting the app works using NSUserDefaults as proxy.  The
  # on/off state of the switch on the first view is persisted in NSUserDefaults.
  #
  # NSUserDefaults are part of the app sandbox and so are deleted by
  # `reset_app_sandbox`.
  #
  # NOTE: Keychain items _persist_ over app resets (at least on the simulator),
  # which is surprising.
  @user_defaults @reset_app_btw_scenarios
  Scenario: 20 I turn the switch on the first view on
    And I drop some files in the sandbox
    Given I turn the switch on

  @user_defaults @reset_app_btw_scenarios
  Scenario: 21 The switch should be on because I did not reset the app before this Scenario
    Then I should see the files I put in the sandbox
    Then I should see the switch is on  <== FAILS
```

##### Typical Results

```
=== SUMMARY ===

PASSING SIMULATORS
iPad 2 (7.1 Simulator)
iPad Retina (7.1 Simulator)
iPhone 4s (7.1 Simulator)
iPhone 5 (7.1 Simulator)

FAILING SIMULATORS
iPad 2 (8.0 Simulator)
iPad Air (8.0 Simulator)
iPad Air (7.1 Simulator)
iPad Retina (8.0 Simulator)
iPhone 4s (8.0 Simulator)
iPhone 5s (8.0 Simulator)
iPhone 5s (7.1 Simulator)
iPhone 5 (8.0 Simulator)

passed on '4' out of '12'
```

**Comment by fer662** [comment]
I'm seeing this issue about 50% of the time. Is this fix included in later versions of run_loop? Is there anything else that can be done to address it?

**Comment by jmoody** [comment]
@fer662 

Beyond using a different .plist (as described above) for the Calabash target, the only other option is to use the :shared_element strategy.

The :shared_element strategy _might_ speed up your tests on devices.  It will probably _not_ speed up your tests on simulators.

The :shared_element strategy can do almost everything the other strategies can except:  https://github.com/calabash/calabash-ios/issues/642

```
options = { 
  :uia_strategy => :shared_element
}

# Calabash 0.x
launcher.relaunch(options)
```

**Comment by jmoody** [comment]
Closing this issue.  Xcode 7 appears to have fixed this issue.
