### ISSUE TITLE
App doesn't launch in the simulator (iPhone 5, iOS 8.0)

### ISSUE THREAD

**Issue by ldiqual** [calabash/calabash-ios#540]
- Server & gem versions: 0.10.2
 - iPhone 5, iOS 8.0 - Simulator

Commandline logs: https://gist.github.com/ldiqual/1341bd1123f9b83a6b86

The simulator launches correctly (iPhone 5, iOS 8.0 - the default one), but not the app. Sometimes, the permission prompt appears and vanishes right away. Sometimes I can enter my password but nothing happens next.

**Comment by jmoody** [comment]
Closing; outdated.
