### ISSUE TITLE
Cannot launch iOS 7.0.3 simulators with Xcode 6 CoreSimulator

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#548]
@simi823 

Sorry -- I'm quite a newbie to XCode and calabash. App developed outside company but have source code. Successful in building app for iPhone 4s IOS 7.0. Then when I run calabash-ios console, I am able to query, but as I mentioned above not touch. So then I try to exit iOS Simulator and run calabash-ios console again with start_test_server_in_background. It opens IOS Simulator with iPhone 5 iOS 8.0, but not the app. It does this a few times before it errors out:

Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop to Start. 
 Logfile /var/folders/3t/5mkzq4_x5knbp0b4g07lw6q8g8pkby/T/run_loop20141007-6829-qfix47/run_loop.out 

 Waiting for device to boot...
Instruments Trace Error : *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/launcher.rb:729:in `new_run_loop'
	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/launcher.rb:597:in `relaunch'
	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/core.rb:838:in `start_test_server_in_background'
	from (irb):1
	from /Users/sasaro/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'

Then I try this:
->DEVICE_TARGET="iPhone 4s (7.0.3 Simulator)" calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background

The iOS Simulator starts but I get an alert saying:
Unable to run app in simulator
An error occurred while preparing the app for installation (no bundle identifier was found at the expected path)

This opens IOS Simulator a few times then errors out with:
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop to Start. 
 Logfile /var/folders/3t/5mkzq4_x5knbp0b4g07lw6q8g8pkby/T/run_loop20141007-9180-1f7fbn8/run_loop.out 

 Waiting for device to boot...

	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/launcher.rb:729:in `new_run_loop'
	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/launcher.rb:597:in `relaunch'
	from /Users/sasaro/.rvm/gems/ruby-2.1.2@global/gems/calabash-cucumber-0.10.2/lib/calabash-cucumber/core.rb:838:in `start_test_server_in_background'
	from (irb):1

What did I miss? Please let me know how I can get this started. I tried reading as much as possible, but I may have missed something. Thank you in advance for your assistance.

**Comment by lummyare** [comment]
I am having this same issue with iSO8.2 Xcode 6.1

**Comment by jmoody** [comment]
@lummyare Are you running Yosemite or Mavericks?

**Comment by nemesis** [comment]
Having the same issue with iOS 8.2, Xcode 6.2. Running Yosemite.

**Comment by jmoody** [comment]
7.0.3 is not supported on Yosemite.  You may see the 7.0.3 simulators are available, but Apple has stated they will not run on Yosemite.
