### ISSUE TITLE
NSPredicate matching crashes app

### ISSUE THREAD

**Issue by brendensoares** [calabash/calabash-ios#569]
This is likely not an issue in Calabash. When it crashes it it's not in the Calabash server.

That said...

# Problem

Having a `UILabel` with its text set to
> line 1
> line 2

and trying to run
```ruby
query "label {text =='line 1\nline 2'}"
```
crashes the app.

# Solution

```ruby
query "label {text =='line 1\u2028line 2'}"
```
Through trial and error, I found that when I don't programmatically set the text to the label to a `\n` and instead use `\u2028`(a unicode line separator) it works. I noticed this because setting a multi-line label in interface builder shows the unicode new line instead of `\n`. Weird.

This seems to be an issue in `NSPredicate` syntax; I can't find any mention of new lines there.

# Question

What is going on here? Even though I have a workable solution, I'd like to understand why `\n` crashes the iOS app.

Thanks.

**Comment by jmoody** [comment]
The problem is the newlines in non-interpolated strings are not evaluated as newline characters.

You have use double quotes and not single quotes.
