### ISSUE TITLE
Feature Request: whole-screen swipe

### ISSUE THREAD

**Issue by TeresaP** [calabash/calabash-ios#593]
Users need a supported way to swipe across the entire screen. Apple seems to have changed their coordinate system and it sent us scrambling as our swipe gestures broke when we updated to Xcode 6.0.  It would be great if you could add a swipe gesture that swipes across the whole screen and works for both portrait and landscape.

**Comment by TeresaP** [comment]
Do you forsee this on the radar any time soon @jmoody?

**Comment by TeresaP** [comment]
FYI @andyhuynh86

**Comment by froucher** [comment]
+1, to the support of the swipe across the entire screen

**Comment by jmoody** [comment]
Have you tried pan?

**Comment by jmoody** [comment]
@TeresaP Calabash 2.0 has a whole screen pan.  But I don't think that will ever make it into Calabash 0.x.
