### ISSUE TITLE
In CoreSimulator environments RESET_BETWEEN_SCENARIOS=1 resets the simulator contents and settings; should only reset the app sandbox

### ISSUE THREAD

**Issue by socoboy** [calabash/calabash-ios#597]
The environment variable RESET_BETWEEN_SCENARIOS doesn't not reset the app sandbox only. It reset content and settings of simulator. This will be issues when I have some settings on the keyboard of simulators for not auto correct, or do some it's magic. And after each scenarios, these settings lost. 

Thanks

**Comment by jmoody** [comment]
Fixed! In run-loop >= 1.5.4

**Comment by fabb** [comment]
Awesome, thank you!
