### ISSUE TITLE
Tests hang after starting and eventually time out

### ISSUE THREAD

**Issue by shodanuk** [calabash/calabash-ios#623]
My first feature in my test suite starts and fires up the app correctly (both on device or on simulator) but the steps of the test do not run. The test hangs for a period of time before eventually timing out with the following output:

```
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
 Unable to make connection to Calabash Server at http://localhost:37265/
 Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
  (RuntimeError)
 /usr/local/opt/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:786:in `rescue in ensure_connectivity'
 /usr/local/opt/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:748:in `ensure_connectivity'
 /usr/local/opt/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:616:in `relaunch'
 /Users/terrymorgan/Documents/Titanium_Studio_Workspace/*******/build/iphone/features/ios/support/01_launch.rb:28:in `Before'
```

I've disabled my firewall but that seems to make no difference.

The before hook code in 01_launch.rb is:

```
Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  scenario_tags = scenario.source_tag_names
  if scenario_tags.include?('@reinstall')
    @calabash_launcher.reset_app_jail
  end
  unless @calabash_launcher.calabash_no_launch?
    @calabash_launcher.relaunch
    @calabash_launcher.calabash_notify(self)
  end
end
```

As per a similar open issue on here, #619 , various combinations of rebooting and resetting the simulator seem to bring the tests back to life.

I am creating a new issue as I believe the output I'm seeing is different to #619 and also, the reporter of that issue states that his tests hang in-between scenarios whereas mine don't start at all. When they do, ie. after reboot, they always seem to run through to the end without hanging.

**Comment by krukow** [comment]
Closed due to lack of response

**Comment by doronzRumble** [comment]
im getting the same error...
calabash ios client = 14.3 and calabash server is 14.1 (as its the latest released....) in nslog i see server version 14.1

**Comment by doronzRumble** [comment]
in the meantime i downgraded to client version 14.1
do you have any idea when you will update server to 14.3?
