### ISSUE TITLE
uia_double_tap only accepts single-word queries

### ISSUE THREAD

**Issue by adzellman** [calabash/calabash-ios#652]
Below is what I did in the console. The first command, with just the one parameter behaves correctly, but as soon as I try to filter the results, chaos ensues.
Configuration:
```
ddp-mac-01:~ zellman$ xcode-select --print-path
/Xcode/6.1.1/Xcode.app/Contents/Developer
ddp-mac-01:~ zellman$ xcodebuild -version
Xcode 6.1.1
Build version 6A2008a
ddp-mac-01:~ zellman$ calabash-ios version
0.11.4
ddp-mac-01:~ zellman$ curl http://10.48.143.129:37265/version
{"app_id":"com.myapp","outcome":"SUCCESS","version":"0.11.4","app_name":"Unknown","system":"iPad4,4","simulator_device":"","simulator":"","app_version":"1.0","iphone_app_emulated_on_ipad":false,"git":{"revision":"bcc992b","remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master"},"screen_dimensions":{"sample":1,"height":2048,"width":1536,"scale":2},"4inch":false,"iOS_version":"8.1.2"}
```
> irb(main):023:0> uia_double_tap("view")
> nil
> irb(main):024:0> uia_double_tap("view index:0")
> {
>     "status" => "error",
>     "value" => "TypeError: null is not a valid argument for 'instanceof' (evaluating 'o instanceof t')  instance_QMARK_@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:4391:23\nfile:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21157:44\nfile:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:11579:38\nlazy_seq_value@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8173:24\ncljs$core$ISeqable$_seq$arity$1@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8220:64\n_seq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:3431:45\nseq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:4200:33\nfile:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:11121:50\nlazy_seq_value@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8173:24\ncljs$core$ISeqable$_seq$arity$1@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8220:64\n_seq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:3431:45\nseq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:4200:33\nfile:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:11121:50\nlazy_seq_value@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8173:24\ncljs$core$ISeqable$_seq$arity$1@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:8220:64\n_seq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:3431:45\nseq@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:4200:33\nperform_on__delegate@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21518:48\ncljs$lang$applyTo@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21537:32\napply__3@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9192:35\napply@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9267:29\nperform_on_first__delegate@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21544:32\ncljs$lang$applyTo@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21559:38\napply__3@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9192:35\napply@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9267:29\ndouble_tap__delegate@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21587:32\ncljs$lang$applyTo@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:21601:32\napply__2@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9178:35\napply@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:9265:29\nG__2973__delegate@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:23125:78\nG__2973@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:23132:36\neval code\neval@[native code]\nglobal code@file:///Users/zellman/5D7A8CD3-0277-4621-8DEF-62C612CB9784/_run_loop.js:23588:35",
>      "index" => 9
> }

**Comment by jmoody** [comment]
@adzellman @TeresaP 

Any movement on this?   I want to stress that the `uia_*` methods are not part of the public API and can change/be removed without notice.

**Comment by adzellman** [comment]
@jmoody ```double_tap('UIScrollView')``` does work. 
So does ```double_tap("view className:'UIScrollView'")```
and ```double_tap("view className:'UIScrollView' index:0")```
I will close this issue.
