### ISSUE TITLE
Somebody pls help me. very urgent pleaseee

### ISSUE THREAD

**Issue by lummyare** [calabash/calabash-ios#657]
Hi guys, 

Please i need help urgently.

i am running ruby versions:

rvm rubies

 * ruby-2.0.0-p451 [ x86_64 ]
=> ruby-2.0.0-p598 [ x86_64 ]

Xcode 6.1
calabash-ios version 0.11.4
server_version 0.11.4
Calabash::Cucumber::MIN_SERVER_VERSION 0.11.4

I have my pages setup correctly by extending BasePage and BasePage extending ibase. I had set up WebviewPage and defined methods.
so when i call: "WebViewPage.new.verify_webview_page" from my step defination i keep getting error below:

    Given I am on the WebView Screen # features/step_definitions/my_first_steps.rb:2
  uninitialized constant WebViewPage (NameError)
  ./features/step_definitions/my_first_steps.rb:5:in `/^I am on the WebView Screen$/'
  features/root_view.feature:8:in `Given I am on the WebView Screen'

I have been battling with this since and i have followed a video tutorial from Tejas which worked well for him but i seems to be hitting walls. Please i need urgent help as i have to deliever this project by wednesday. 

Please anyone.

Johnson

**Comment by jmoody** [comment]
Please do not cross post.

I am closing this because it is more appropriate to ask this kind of question on the forum.

**Comment by lummyare** [comment]
Ok I am so sorry. Please i know you are a guru in calabash i need help to this matter. i will never cross post again. Please help.
