### ISSUE TITLE
server version warning 

### ISSUE THREAD

**Issue by shams-ahmed** [calabash/calabash-ios#662]
```
WARN: The server version is not compatible with gem version.
Please update your server.
https://github.com/calabash/calabash-ios/wiki/B1-Updating-your-Calabash-iOS-version
       gem version: '0.12.0.pre5'
min server version: '0.12.0.pre1'
    server version: '0.12.0'
```
```
^Csd-imac-03:EnergyUATTests qa$ cucumber --version
1.3.18
sd-imac-03:EnergyUATTests qa$ calabash-ios version
0.12.0
```

**Comment by isachs** [comment]
I've been getting this as well, though things seem to be working anyway and server_version['version'] reports the correct version.

    WARN: The server version is not compatible with gem version.
    Please update your server.
    https://github.com/calabash/calabash-ios/wiki/B1-Updating-your-Calabash-iOS-version
           gem version: '0.12.0'
    min server version: '0.12.0'
        server version: '0.11.4'

and

    irb(main):005:0> server_version['version']
    "0.12.0"

**Comment by jmoody** [comment]
@shams-ahmed & @isachs

Have you deleted the old calabash targets from the simulator and devices?

The fastest way to delete simulator targets is:

```
$ bundle exec calabash-ios sim reset
```

Targets on devices must be deleted manually or with third-party software like ideviceinstaller.

@isachs Your experience is odd; can you somehow share this project this me?  Maybe over a shared Terminal using [tmate](http://tmate.io/)?

**Comment by shams-ahmed** [comment]
@jmoody sorry my i work won't allow this... but this happened in a test app i created using calabash-ios setup. i'll try zipping that up for you.

**Comment by jmoody** [comment]
@shams-ahmed 

Your checks are not enough to test the server version that is embedded in the app.

See https://github.com/calabash/calabash-ios/wiki/B1-Updating-your-Calabash-iOS-version for instructions on how to test the server version using `curl` or the `calabash-ios console`.

**Comment by isachs** [comment]
@jmoody I think we could do a tmate session next week.

I was so confused by this that I did the steps in https://github.com/calabash/calabash-ios/wiki/B1-Updating-your-Calabash-iOS-version multiple times and also completely removed my checkout of the app code and pulled it from scratch.  In the past all that's been necessary to be sure of having the new server version was to get a new checkout of the app code after updating calabash and re-run calabash-ios setup.

**Comment by jmoody** [comment]
@isachs 

I will be working Central Europe Time next week.  Can you contact me at joshua.moody@xamarin.com?

Thanks!

**Comment by spedepekka** [comment]
@shams-ahmed I have the same issue. I think this is a problem in the run_loop version comparison. See https://gist.github.com/spedepekka/4bce774f34d8448d4cf2

Issue: https://github.com/calabash/run_loop/issues/110
Fix: https://github.com/calabash/run_loop/pull/111

**Comment by jmoody** [comment]
@spedepekka wrote:

> I have the same issue. I think this is a problem in the run_loop version comparison.

I think the problem you found is unrelated; it concerned a bug in pre-release vs. release versions.  

@isachs Has a binary that is reporting 0.11.4 even though he has updated his calabash-ios server.

**Comment by spedepekka** [comment]
@isachs problem is not related, but the original problem with @shams-ahmed is most likely related to calabash/run_loop#110

**Comment by jmoody** [comment]
Fixed in run-loop 1.2.3 and will be part of calabash-ios 0.12.1

**Comment by mpumesix** [comment]
Hi all,  Is there any way one can set MIN_SERVER_VERSION and SERVER_VERSION manually perhaps through export in env file or bash_profile.

I'm using Xplatform example() and I don't have the original project per say.
_WARN: The server version is not compatible with gem version.
Please update your server.
https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version
       gem version: '0.20.4'
min server version: '0.20.4'
    server version: '0.11.4.pre2'_
 
Any suggestions guys?

**Comment by jmoody** [comment]
@mpumesix 

You need to update your calabash.framework.  There is no other way - you must have access to the original Xcode project.
