### ISSUE TITLE
Touch gesture takes up to 7 seconds to come back

### ISSUE THREAD

**Issue by TeresaP** [calabash/calabash-ios#670]
We are running server and client versions 12.0 on iOS8.0 and iOS8.1 iPads.

We noticed automation was failing due to timing issues and narrowed it down to the tap gesture taking far too long to come back.  At times, it works fine.  Other times, it takes as long as 7 seconds.  That means, we perform the tap gesture and then 7 seconds later the next task is executed.  

We have several tests that are timing-based.  Immediately after tapping this particular object, it goes through a series of state changes.  A normal 0.5 second delay is acceptable, but 7 seconds means the test case fails because the state change animation has completed its cycle.

Here is the command, where query_string is some view we are trying to touch:

   @core.touch(query_string)

Here's a copy of the logs:

```
BEFORE Touch. Time: 2015-01-14 17:17:44 -0800
Sending UIA command
uia.tapOffset('{:x 384, :y 512}')
2015-01-14 17:17:44 -0800: 8:uia.tapOffset('{:x 384, :y 512}')
2015-01-14 17:17:44 -0800: Trying write of command 8:uia.tapOffset('{:x 384, :y 512}') at index 8
2015-01-14 17:17:45 -0800: validate index written for index 8 ok
Result
{"status"=>"success", "value"=>true, "index"=>8}
AFTER Touch. Time: 2015-01-14 17:17:51 -0800
```

**Comment by jmoody** [comment]
@krukow Any thoughts?

@TeresaP Is this only on iPads?  Can you describe what is happening in the app before this call is made? 

Thanks.

**Comment by krukow** [comment]
Would be great with a binary ipa and instructions to reproduce locally?

**Comment by TeresaP** [comment]
@jmoody we only use iPads currently so I don't know if it happens on other devices.  I'll get you some more information on what is happening in the UI in a couple hours when I'm back at my work machine.  But I have noticed this time is variable.  If I run the test 10 times, I will get anything between a negligible delay and 7 seconds.

@krukow I don't even know where to begin making an ipa for you guys.  We are in an enterprise environment.  What kind of instructions do you need to reproduce?

**Comment by TeresaP** [comment]
@jmoody We have columns of content, so in the case above we are on column 20, then swipe to column 19.  We check to see that a given view (slideshow) is visible, check for a few other things, then tap on the slideshow.  

Is there any way to tap but not wait for the tap gesture to come back before we go and do other things?

**Comment by jmoody** [comment]
@TeresaP Thanks for the details.

> Is there any way to tap but not wait for the tap gesture to come back before we go and do other things?

For better or worse, no.

> re: an .ipa

I will ping you in IRC.

##### :shared_element

If you can, it would be great if you could try the :shared_element strategy.

In your 01_launch.rb hooks, call relaunch with the :shared_element strategy.


```
calabash_launcher.relaunch({:uia_strategy => :shared_element})
```

:shared_element has some limitations (see #675).  It would be helpful to see if the delay goes away or is reduced.

**Comment by TeresaP** [comment]
@jmoody That is genius.  I've run the test case several times and each time with this new launch method it has passed.  Thank you for a workaround!
