### ISSUE TITLE
wait_tap raises an error on iOS 8 physical devices - there is no support for :host strategy

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#675]
The `wait_tap` method will raise an error when using the `:host` strategy.

Users will encounter this error when running tests against iOS 8 _physical devices_.

The fastest workaround is to not use `wait_tap`, but to instead use the wait-then-touch pattern.

```
query_str = "button marked:'Touch me"
wait_for_element_exist([query_str])
touch(query_str)
```

There are also these alternatives.

#### Replace wait_tap with your own implementation

This will work as long as you don't override the default :uia_strategy at launch.

```
def my_wait_tap
  query_str = "button marked:'Touch me"
  if !simulator? && ios8?
    wait_for_element_exist([query_str])
    touch(query_str)
  else
    wait_tap(query_str)
  end
end
```

#### Use :shared_element strategy (experimental)

There are several known issues that make this option unattractive.

* Cannot call `send_app_to_background`
* When :uia_strategy => :shared_element, using URL Schemes for in-app navigation crashes the test #642

There may be other problems with this approach.

In your hooks:

```
Before do |scenario|
  options = {
    :uia_strategy => :shared_element
  }
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  unless @calabash_launcher.calabash_no_launch?
    @calabash_launcher.relaunch(options)
    @calabash_launcher.calabash_notify(self)
  end
end
```

### wait_tap in the console

The easiest thing to do is not use wait_tap in the console when targeting iOS 8 _physical devices_.

If you want to use `wait_tap` on the console and you are targeting an iOS 8 _physical device_, use:

```
> start_test_server_in_background({:uia_strategy => :shared_element})
```

but be advised that `:shared_element` has known issues (see above).

**Comment by chaoscope** [comment]
I am experiencing this same error in iOS 9 on Simulators, will use work arounds provided, just commenting in case this was not known yet
