### ISSUE TITLE
touch(element) does not touch in the correct place if the device is upside-down

### ISSUE THREAD

**Issue by rjanjua** [calabash/calabash-ios#692]
touch(element)  does not touch in the correct element if the device is in a reversed portrait orientation.
When it sends the touches to the device it seems to be touching in the wrong place on the y-axis, I believe what it is doing is tapping (X,Y) on the screen, but when the device is rotated the origin of each axis remain the same. Eg. In a normal portrait orientation touch(element) touches the coordinates (5,5), and when it is upside down it also touches (5,5) when it should touch (5,95).

However, when using touch(query_string) or tap_mark label it touches the correct element.

eg. The following will work in a normal orientation, but not in an upside down one

elements = query(webView css:'#someElement') => returns array of 3 elements
touch elements[2] => returns true // the subsequent touch is in the wrong place if device is in an 'upside down' orientation

**Comment by jmoody** [comment]
Please provide more information:   see https://github.com/calabash/calabash-ios/wiki#reporting-problems

Is the touch failing immediately after a rotation?   You can test this by rotating the device/simulator manually, then trying the same `touch` in the calabash-ios console.

**Comment by jmoody** [comment]
@rjanjua I am closing this because I haven't heard back from you.  Please let us know if this problem persists.
