### ISSUE TITLE
Non interactive version of `calabash-ios setup`

### ISSUE THREAD

**Issue by iMerica** [calabash/calabash-ios#703]
Hey guys!

I need to run tests in the context of a CI pipeline in Jenkins (ran on a Mac Mini). One of the steps I need to run is `calabash-ios setup`. Is there a way I can run this just by passing CLI arguments? For example `calabash-io setup scheme=<scheme> otherKey=<value>` ?

Thanks!

**Comment by iMerica** [comment]
If this isn't possible at the moment, can someone point me to a doc or example of how one might use calabash-ios as part of a CI build/test process ?

**Comment by jmoody** [comment]
>  Is there a way I can run this just by passing CLI arguments? 

Sadly, the setup script does not take any arguments

We have been experimenting using the xcodeproj gem from the CocoaPods group.  

Unfortunately, this work gets pushed to the back of the queue.

I am go to close this, but add a reference to **calabash-ios setup fails on fresh Xcode 6 project** #533

Whatever solution we come up with, we'll try to make it CI compatible.

**Comment by krukow** [comment]
Actually there is an environment variable you can set to pre select the target. Checkout the groups...

**Comment by iMerica** [comment]
Awesome! For anyone facing the same issue, I found the answer on this Google Group post:

https://groups.google.com/forum/#!searchin/calabash-ios/%22calabash-ios$20setup%22/calabash-ios/pUagzRSyEa0/2BRMghvRqGoJ

Basically set the `TARGET` environment variable before hand.
