### ISSUE TITLE
WKWebView support for Calabash iOS?

### ISSUE THREAD

**Issue by toupper** [calabash/calabash-ios#707]
According to this article in the wiki https://github.com/calabash/calabash-ios/wiki/06-WebView-Support Calabash supports querying on web view content. For instance, when we had an UIWebView, we could query to get all the HTML associated with the webview with this command: 

query("webView css:'*'")

And it works. Now I have a WKWebView instance, and try to do the same with the same keyword in the query ("webView"), but it returns an empty list.  If I query for the WKWebView like this:  query("WKWebView") I get the WKWebVIew information, but this command query("WKWebView css:'*'")  also returns empty.

Is there way to query the content of the WKWebView?

Thanks a lot,

Cesar

**Comment by avanderberg** [comment]
I am interested in this feature, too. When approximately (weeks or months) will support for WKWebView be integrated in Calabash?

**Comment by krukow** [comment]
@avanderberg we will include this in the next minor release in less than two weeks.

**Comment by jmoody** [comment]
@avanderberg @toupper 

I have started this work, but it is more challenging than expected.

We've decided to delay releasing until after 0.13.0.  We are planning the 0.13.0 for Wed Feb 25 or Thu Feb 26.  WKWebView support will be the next thing I work on.

**Comment by avanderberg** [comment]
Thanks for the information. I appreciate your effort and service.

**Comment by jmoody** [comment]
@avanderberg @toupper 

This is even more technically challenging than we thought.

We are going to need to distribute WKWebView support as a Calabash Plug-in.

The great news is that the support is working:

https://testcloud.xamarin.com/test/calwebview-cal_f5961e20-9c52-41bd-a6d1-49d0787b9a58/

**Comment by jmoody** [comment]
@toupper @avanderberg 

Have either of you found a way to detect the scale of a WKWebView?

**Comment by jmoody** [comment]
**UPDATE**  Instead of using a Calabash Plug-in, I've implemented the solution  by creating category and implementing a protocol on WKWebView at runtime.

**Comment by avanderberg** [comment]
I checked out the current [calabash-ios-server](https://github.com/calabash/calabash-ios-server) develop branch, builded it, added it to our app, and was able to `query("WKWebView css:'*'")` and touch HTML elements. Great! Getting the scale of a WKWebView maybe is possible with JavaScript, but I was not able to figure out the necessary commands. Do you have a suggestion?

**Comment by jmoody** [comment]
@avanderberg
> was able to query("WKWebView css:'*'") and touch HTML elements

Hurray!

I have not found any way of finding the scale; including with JavaScript.

The only solution that I have had any success with is to constrain the scale the `meta` tag.  This could be done at runtime.

https://github.com/calabash/calabash-ios-server/pull/146
