### ISSUE TITLE
Cannot start calabash ios on a remote build agent over SSH

### ISSUE THREAD

**Issue by dnadan** [calabash/calabash-ios#708]
Hi, hoping I can get some help!  I've been trying for more than a week to get this to work, but no joy.  Most of this setup is not calabash related but please bear with me - I get there in the end :).

### Background
I have set up an automated CI pipeline for my team, and the last stage is running a full suite of calabash tests.  However the tests never actually launch on the build agents (mac minis, OSX 10.10.2) no matter what I've tried.  Calabash (0.12.3) runs perfectly when I execute it locally on my dev machine (OSX 10.10.2)

As an attempt to try to solve my issues I tried to set up calabash as described in Jian Fang's excellent tutorial here: http://fangmobile.com/2014/05/08/do-you-love-calabash-ios-but-hate-that-cal-second-target/.  So I now have three configurations for my project (Debug, calabash and Release), just one main target and a second scheme just for building my new calabash configuration.  When I run this calabash scheme in XCode I see the familiar logs:

    Creating the server: <LPHTTPServer: 0x7a172320>
    Calabash iOS server version: CALABASH VERSION: 0.12.3
    simroot: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Devel
    Started LPHTTP server on port 37265
    Bonjour Service Published: domain(local.) type(_http._tcp.) name(Calabash Server)

### Working local setup
I have also integrated rake into our project and I'm able to build and run my calabash scheme with two simple commands.  There is a little more going on than this, but essentially:

    rake calabash
    cucumber

When I run this on my local machine, this works!  Calabash starts the simulator and the tests I have in the project start executing.

### Issue
The wall I've hit is that I simply *cannot* get this to run when executing on a remote machine.  Our build server (Bamboo) sends jobs to our mac mini build agents - and this works for compilation, unit testing, etc.  When it gets to the calabash tests though - it launches the simulator and then:

    20-Feb-2015 21:50:47	#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
    20-Feb-2015 21:50:47	  Unable to make connection to Calabash Server at http://localhost:37265/
    20-Feb-2015 21:50:47	  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
    20-Feb-2015 21:50:47	   (RuntimeError)
    20-Feb-2015 21:50:47	  /Users/myuser/.rvm/gems/ruby-2.2.0@b2bios/gems/calabash-cucumber-0.12.3/lib/calabash-cucumber/launcher.rb:809:in `rescue in ensure_connectivity'
    20-Feb-2015 21:50:47	  /Users/myuser/.rvm/gems/ruby-2.2.0@b2bios/gems/calabash-cucumber-0.12.3/lib/calabash-cucumber/launcher.rb:771:in `ensure_connectivity'
    20-Feb-2015 21:50:47	  /Users/myuser/.rvm/gems/ruby-2.2.0@b2bios/gems/calabash-cucumber-0.12.3/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
    20-Feb-2015 21:50:47	  /Users/myuser/bamboo-agent-home/xml-data/build-dir/P0P-IFT55-CA/MobileB2BApp/features/ios/support/01_launch.rb:31:in `Before' 
    20-Feb-2015 21:50:47	Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265))
    20-Feb-2015 21:50:48	Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://    localhost:37265))
    20-Feb-2015 21:50:48	Failing... Errno::ECONNREFUSED
    20-Feb-2015 21:50:48	Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://    localhost:37265))
    20-Feb-2015 21:50:49	Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://    localhost:37265))
    20-Feb-2015 21:50:49	Failing... Errno::ECONNREFUSED
    20-Feb-2015 21:50:49	    Given I login with valid credentials # features/ios/step_definitions/login_out_steps.rb:57
    20-Feb-2015 21:50:49	      Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265) (Errno::ECONNREFUSED)

### Reproduction
The same thing seems to happen when I SSH to the remote build agent and run the same commands on the terminal.  **When I VNC into the mac mini build agents and run these commands from the terminal *inside the VNC session* (with GUI), it works**! But this is not viable as part of CI system.

I have been looking at #83, #540 and #623 but I haven't been able to get something working from the information there.

This used to work magically in the past, but I believe with some OSX updates something broke along the way.

### Workaround attempts
I've tried doing the 

    DevToolsSecurity -enable
    security authorizationdb write system.privilege.taskport is-developer

And I've also tried adding my current user and the build user into the _developer OSX group.  But no progress.

Does anyone have any insight for why calabash does not seem to work when run on a remote machine, but is fine when run locally?  Or more importantly, how I can fix it? :)

**Comment by jmoody** [comment]
Hi @dnadan 

+1 for an excellent write up.

As far as I know, Xcode 6 does not allow `instruments` to be run over SSH.  This might be the cause of your problem.

You might try this solution we use on Travis to target simulators.

* https://github.com/jmoody/animated-happiness/blob/master/script/ci/travis/instruments-auth.sh

You might also look at this issue:

**Time out waiting for UIAutomation run-loop to Start.** #308 which describes how to fix calabash + tmux.

We prefer not to answer questions related to CI here on the GitHub issues page.  This is not a feature request or a bug report.  Although it might seem like a bug from the outside, so I can see why this would the natural place to ask such a question.  Ultimately, this is a `dev-ops` problem and, as such, not one that we are equipped to resolved.

I think I am going to update the CONTRIBUTING.md doc to reflect this.

**Comment by dnadan** [comment]
Hi @jmoody ,

Thanks very much for taking the time to help me.  Sorry about posting something out of scope of this project.

If you're willing - I have some follow up questions; Is there somewhere else I should post them? Calabash-ios google forums?

**Comment by jmoody** [comment]
Let's finish this issue off here. :)

**Comment by dnadan** [comment]
Hi @jmoody ,

Sorry about the delay.  I've been trying many different things in the meantime:

1. I added the plist files from your link to my https://github.com/jmoody/animated-happiness/blob/master/script/ci/travis/instruments-auth.sh but it didn't seem to do help launch the simulator calabash process, even after a reboot of the agents.

2. I'm confused about your reference to tmux - do you mean my CI server is possibly using tmux to connect to the agents and therefore needs that type of reattach-to-process fix?

3. Since we are using Bamboo, I tried editing the build agent scripts themselves - there is an option inside that bamboo-agent.sh allows you to run them as a specific user.  I tried setting that to the admin of the mac mini, e.g.:

    `RUN_AS_USER="username"`

I am feeling somewhat bittersweet right now since one of these things, and possibly a combination of other things I tried in the meantime, has now succeeded in allowing the calabash tests to start as they used to do.  I am ecstatic that its working; I am very annoyed that I don't know how I fixed it.  I imagine anyone else reading this issue in hope of a solution is equally annoyed (sorry!).  

I am also wary since I don't know how permanent this working state is either.

In any case thank you for the help.

**Comment by jmoody** [comment]
> I'm confused about your reference to tmux

Remote tmux sessions with tools like tmate use SSH.

**Comment by jmoody** [comment]
@dnadan Good analysis.  Bittersweet is only good for chocolate.  Despite the unsatisfying resolution, can we close this issue?

**Comment by dnadan** [comment]
Sure, thanks for the help.  Crossing my fingers.

**Comment by Rakeshvallabhaneni** [comment]
Hi @dnadan  @jmoody  can you please help me out in the below issue.

Completed calabash -set up manually

using Xcode 6.3 and Real device iPhone iOS 8.3 calabash-iOS 0.14

Below is the console after build and run the application in iPhone 6 8.3 iOS physical device

Creating the server: 
Calabash iOS server version: CALABASH VERSION: 0.14.3
App Base SDK: iphoneos8.3
simroot: (null)
Started LPHTTP server on port 37265
Bonjour Service Published: domain(local.) type(_http._tcp.) name(Calabash Server)
WKWebView successfully implemented LPWebViewProtocol
registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.



Now I launched the Terminal

DEVICE_ENDPOINT=http://localhost:37265/ BUNDLE_ID=com.//.// calabash-ios console

(Now entered in to i.r.b)

start_test_server_in_background

Here application launches in the device successfully .

Errno::ECONNREFUSED: Connection refused - connect(2)
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in initialize' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:inopen'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in block in connect' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:intimeout'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in connect' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:indo_start'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in start' from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:815:inping_app'
from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:788:in block in ensure_connectivity' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:intimeout'
from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:785:in ensure_connectivity' from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:642:inrelaunch'
from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:883:in start_test_server_in_background' from (irb):3 from /usr/bin/irb:12:in

'
Please Help me out for the above issue

Note: able to run in simulators but initially even simulator works like it appears and disappears continuously its not looks good for demo to clients 

If i tried server_version

Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://localhost:37265))            # calabash-cucumber-0.9.161/features/step_definitions/calabash_steps.rb:35
  Failing... Errno::ECONNREFUSED
  Connection refused - connect(2) (http://localhost:37265) (Errno::ECONNREFUSED)


Thanks In Advance,
Rakesh

**Comment by jmoody** [comment]
The version of Calabash linked to your app is too old.

```
calabash-cucumber-0.9.161/features/step_definitions/calabash_steps.rb:35
```

* https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version

**Comment by jmoody** [comment]
@Rakeshvallabhaneni Next time, open a new issue.  This one has been closed and I don't think it has anything to do problem you are reporting.

**Comment by Rakeshvallabhaneni** [comment]
Thanks @jmoody  its fixed as i passed wrong ip address in command instead of passing my Device connected wifi address.
