### ISSUE TITLE
setting DEVICE_TARGET to a simulator UDID causes crash

### ISSUE THREAD

**Issue by tsh-trifork** [calabash/calabash-ios#714]
If the Info.plist file name or location differs from standard calabash cannot find it. The problem is in lipo.rb line 112-114

    def plist_path
      File.join(@bundle_path, 'Info.plist');
    end

This only happens when i specify a device target.

**Comment by tsh-trifork** [comment]
After some digging i found that when i was trying to use a specific simulator using its identifier. Then calabash assumes that its running against a physical device because target does not contain 'simulator'

The fuck up happens in core.rb line 376

        unless /simulator/i.match(device_target)
          bundle_dir_or_bundle_id = options[:bundle_id] if options[:bundle_id]
        end

**Comment by jmoody** [comment]
@tsh-trifork 

That does look like a bug.

Can you move this issue over to run-loop and provide some steps to reproduce?

https://github.com/calabash/run_loop/issues

Do you work for Denmark or Switzerland?  I try to get to the GoTo nights in Zürich as often as I can.

**Comment by jmoody** [comment]
```
irb(main):001:0> ENV['DEVICE_TARGET']="721B1C09-63C5-4373-A96C-95161A36043D"
"721B1C09-63C5-4373-A96C-95161A36043D"
irb(main):002:0> start_test_server_in_background

INFO: Using uia strategy: 'preferences'
Sending 'QUIT' to instruments process '95374'
Waiting for instruments '95374' to terminate
Waited for 0.715627 seconds for instruments with '95374' to terminate
2015-03-12 04:42:29 +0100 [RunLoop:debug]: Preparation took 0.793572 seconds
RuntimeError: Could not find simulator with identifier '721B1C09-63C5-4373-A96C-95161A36043D'
	from /Users/moody/git/run-loop/lib/run_loop/core.rb:112:in `expect_compatible_simulator_architecture'
	from /Users/moody/git/run-loop/lib/run_loop/core.rb:205:in `run_with_options'
```

**Comment by jmoody** [comment]
Fixed with Can use simulator UDID for DEVICE_TARGET #150

**Comment by jmoody** [comment]
Will close when run-loop is released.
