### ISSUE TITLE
UIButton text querying returns stars

### ISSUE THREAD

**Issue by OlegAnghelov** [calabash/calabash-ios#717]
Hi!

We run the project and the tests on the following machine:

**Environment:**
* OS: 10.10.2 (14C109)
* Path:/Applications/Xcode.app/Contents/Developer
* XCode version: Xcode 6.1.1
     Build version 6A2008a
* calabash-ios version: 0.12.3

**Actual problem:**
After we implemented calabash in an existing project, we noticed the following problem:
```
irb(main):042:0> query("UIButton marked:'Filter'",:text)
[
    [0] "*****"
]
```

All queries that try to get the text from buttons return 5 stars. Same for `getText`, `getContent`. We tried on different buttons on different screen from the app: same results.

If there is anything else you need, let us know, we will provide necessary information. 

Could you help us on this one?

Thanks in advance!

**Comment by jmoody** [comment]
In general, queries have this structure:

```
query("a string that can be used to match views", an action to perform on the matches)
```

Your query says, "Find all buttons marked 'Filter' and then call the Objective-C selector `text`" on each one."    UIButton does not respond to `text` or `getText` or `getContent`.

You might have success with:

```
query("button marked:'Filter' descendant label", :text) 
```

but it will depend on how the button was created.

**Comment by AnilKumarp575** [comment]
I have been trying to get the property value of an element  and the query always results me '*****', I could able to successfully identify the element using the below query

query("Axecelerator.HousekeepingCellView child UIView child UIView child UIImageView")
Results:
[
    [0] {
                       "alpha" => 1,
                     "enabled" => false,
                          "id" => "DirtyWhiteIcon",
                     "visible" => 1,
                       "frame" => {
                 "y" => 5,
                 "x" => 8,
             "width" => 34,
            "height" => 34
        },
        "accessibilityElement" => false,
                       "class" => "UIImageView",
                       "label" => nil,
                 "description" => "<UIImageView: 0x108d006c0; frame = (8 5; 34 34); clipsToBounds = YES; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x17423ffc0>> - (null)",
                       "value" => nil,
                        "rect" => {
                   "y" => 69,
            "center_x" => 25,
            "center_y" => 86,
                   "x" => 8,
               "width" => 34,
              "height" => 34
        }
    }
]

But, when I try to retrieve the value of property 'id' using the below query am getting '*****' as result

query("Axecelerator.HousekeepingCellView child UIView child UIView child UIImageView index:0",:id)
[
    [0] "*****"
]

Please help

Thanks

**Comment by jmoody** [comment]
UIImageView does not respond to the `id`.
