### ISSUE TITLE
cannot connect to running app in simulator from console

### ISSUE THREAD

**Issue by bgulanowski** [calabash/calabash-ios#722]
# version info

Xcode 6.2 (6C131e)
Calabash 0.13.0
iPad 2 (7.1 Simulator) [UPDATED]

```json
{"app_version":"3.0","outcome":"SUCCESS","app_id":"com.jadedpixel.POS-Calabash","simulator_device":"iPad","version":"0.13.0","server_port":37265,"app_name":"POS-Calabash","iphone_app_emulated_on_ipad":false,"4inch":false,"git":{"remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master","revision":"0a69c5b"},"screen_dimensions":{"scale":1,"width":768,"sample":1,"height":1024},"iOS_version":"7.1","system":"x86_64","simulator":"CoreSimulator 117.5.4 - Device: iPad 2 - Runtime: iOS 7.1 (11D167) - DeviceType: iPad 2"}
```

Steps (from the docs at https://github.com/calabash/calabash-ios/wiki/01-Getting-started-guide):
- run my app using Calabash scheme
- run `calabash-ios console`
- type `start_test_server_in_background`
- confirm the Calabash server logs its status in the Xcode console

Expected: I can begin using the API

Actual:

- simulator quits, and
- the following error shows in the Calabash console:
```
RuntimeError: Unable to find your built app.
This means that Calabash can't automatically launch iOS simulator.
Searched in Xcode 4.x default: /Users/brent/Library/Developer/Xcode/DerivedData/*/info.plist

To fix there are a couple of options:

Option 1) Make sure you are running this command from your project directory, 
i.e., the directory containing your .xcodeproj file.
In Xcode, build your calabash target for simulator.
Check that your app can be found in
 /Users/brent/Library/Developer/Xcode/DerivedData


Option 2). In features/support/01_launch.rb set APP_BUNDLE_PATH to
the path where Xcode has built your Calabash target.
Alternatively you can use the environment variable APP_BUNDLE_PATH.

	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launch/simulator_launcher.rb:142:in `derived_data_dir_for_project'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launch/simulator_launcher.rb:223:in `app_bundle_or_raise'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:568:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/core.rb:849:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
```

I tried setting the `APP_BUNDLE_PATH` and `DEVICE_TARGET`, but that causes the simulator to restart repeatedly, and the console command never returns. I have to quit the simulator and then I get another console error.

**Comment by jmoody** [comment]
> I tried setting the APP_BUNDLE_PATH and DEVICE_TARGET, but that causes the simulator to restart repeatedly, and the console command never returns

This is because of:  [**Does not contain a compatible architecture for target device (RunLoop::IncompatibleArchitecture)**](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#3-does-not-contain-a-compatible-architecture-for-target-device-runloopincompatiblearchitecture).

> Expected: I can begin using the API

We need a little more information.  Please update this issue by followign the instructions here: [**Reporting Problems**](https://github.com/calabash/calabash-ios/wiki#reporting-problems).

> Xcode 6.2

Also, if you just upgraded to Xcode 6.2, you need to restart your machine to put the CoreSimulator environment into a good shape.  This is a known Apple bug (can be found in various release notes).

**Comment by bgulanowski** [comment]
The documentation on using the console in "Getting Started" needs to be clarified. It suggests that it will connect to the already-running instance:

> Try starting your app using the -cal scheme from Xcode and then run calabash-ios console. This will give you a Calabash console (it is just a Ruby irb with calabash loaded).

But then when I do that, it tries to launch the app. I don't want it to launch it—I want it to connect. If it must launch it, then why does the document suggest I should start it up first?

**Comment by bgulanowski** [comment]
The device/sim architecture disagreement doesn't seem to jive with other facts.

1. The app is the right architecture. I can launch it from the home screen of the sim just fine; I built it just before running the console
2. I'm using calabash > 0.12, but no error is reported

**Comment by bgulanowski** [comment]
Just to be thorough, I tried a variation of the suggestion to use a universal binary. Instead of changing my build settings, I changed the Run action of my scheme to use the Profile configuration. I have other reasons for not wanting to change the Debug build to be universal. But it had the same effect.

> lipo -info /Users/Shared/Xcode/Products/Profile-iphonesimulator/POS-Calabash.app/POS-Calabash 
Architectures in the fat file: /Users/Shared/Xcode/Products/Profile-iphonesimulator/POS-Calabash.app/POS-Calabash are: i386 x86_64

Ran with this command:

> APP_BUNDLE_PATH=/Users/Shared/Xcode/Products/Profile-iphonesimulator/POS-Calabash.app DEVICE_TARGET='iPad 2 (7.1 Simulator)' calabash-ios console

The problem still occurs.

**Comment by jmoody** [comment]
> The documentation on using the console in "Getting Started" needs to be clarified. It suggests that it will connect to the already-running instance:

>> Try starting your app using the -cal scheme from Xcode and then run calabash-ios console. This will give you a Calabash console (it is just a Ruby irb with calabash loaded).

The Getting Started guide obviously needs updating.  I was written back for iOS 4.

> But then when I do that, it tries to launch the app. I don't want it to launch it—I want it to connect. If it must launch it, then why does the document suggest I should start it up first?

Launch the app with Xcode, then opening a console has value: 

* You can query.
* You can ask for the `server_version` which is reasonable check to see if and what version of the calabash server has been embedded in your app.

You cannot, however, perform any gestures.

To perform gestures, you must first:

```
> start_test_server_in_background
> touch(...)
```

**Comment by jmoody** [comment]
> DEVICE_TARGET='iPad 2 (7.1 Simulator)' 

Is that simulator installed?  And did you restart your machine _after_ you installed it?

**Comment by bgulanowski** [comment]
> Is that simulator installed? And did you restart your machine after you installed it?

Yes and yes.

> You can query.

That at least lets me do some experiments, which is helpful to start with.

**Comment by jmoody** [comment]
@bgulanowski I am going to close this.  The Getting Starting page needs an update.

Please reopen or open a new issue if you continue to have problems.
