### ISSUE TITLE
README should highlight that Apple will reject apps that have the calabash.framework linked

### ISSUE THREAD

**Issue by michael-watson** [calabash/calabash-ios#725]
The below section of the READ.ME file should be moved up to the top of the page. It is very hard to find this information and could cause apple store rejections for anyone utilizing calabash-ios.

https://github.com/calabash/calabash-ios#important-notice

**Comment by jmoody** [comment]
@michael-watson The title was alarming.  I did not want to scare people off.

**Comment by michael-watson** [comment]
@jmoody yeah you're right, that definitely looks scary as a title. Thanks!

**Comment by avanderberg** [comment]
Done with https://github.com/calabash/calabash-ios/commit/3cac884a348e8aceecae3d8dd59d3c668029469c#diff-04c6e90faac2675aa89e2176d2eec7d8R43

**Comment by jmoody** [comment]
@michael-watson Can you have a look at the README?   Enough?

**Comment by jmoody** [comment]
@michael-watson Closing.

@avanderberg Thanks for adding the sha.

**Comment by jmoody** [comment]
Reopening.  It looks like we need to do a better job explaining this.
