### ISSUE TITLE
Calabash-iOS failing to start the app on iOS 8.1.3 @ XCode 6.2

### ISSUE THREAD

**Issue by JCzarniecki** [calabash/calabash-ios#726]
Hello.
I am using calabash-ios 0.13.0 (server and client), XCode 6.2 to test the app on iPhone 4S with iOS 8.1.3 on board.
However the app fails to start (cucumber starts up and prints Feature: and Scenario: info), just hangs up for about 1 minute (failing to even start the app) and then prints off these errors and quits.

Device iPod 5 with iOS 7.1.1 works just fine with the same setting as above.

Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError. 
   Logfile /var/folders/40/yzqtrwtn7cng2m4r2b0ncm9w000087/T/run_loop20150311-50259-n7addn/run_loop.out 
  
   2015-03-11 18:15:56.173 instruments[50355:268815] WebKit Threading Violation - initial use of WebKit from a secondary thread.
  
   (Calabash::Cucumber::Launcher::StartError)
  /Users/Shared/Jenkins/.rvm/gems/ruby-2.1.4/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:772:in `new_run_loop'
  /Users/Shared/Jenkins/.rvm/gems/ruby-2.1.4/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:630:in `relaunch'
  /Users/Shared/Jenkins/project/features/support/01_launch.rb:27:in `Before'

**Comment by avanderberg** [comment]
I found out that Xcode updates the simulators so the 8.1 simulators are not installed anymore, but the 8.2 simulators.
I suggest executing the command `instruments -s devices` and check which simulators are installed.
I changed the Calabash configuration to `DEVICE_TARGET='iPad Air (8.2 Simulator)'` and Calabash works fine again.

**Comment by JCzarniecki** [comment]
I am using it on iPhone 4S @ 8.1.3 not on a simulator, so it's irrelevant to this case.

**Comment by wshine29** [comment]
i have meet the same problem,my solution is that:
compiled the project with the -cal target,get the ipa file,then puts the ipa file in the current console path,retry to start calabash,all done!

**Comment by jmoody** [comment]
@JCzarniecki 

Have you read this HotTopic?

https://github.com/calabash/calabash-ios/wiki/Hot-Topics#5-errnoeintr-interrupted-system-call

**Comment by JCzarniecki** [comment]
Actually, it seems the issue is no longer present.
I've came along the checklist mentioned in that HotTopic and looks like I can't reproduce the issue anymore.

Probably it's worth to include Calabash::Cucumber::Launcher::StartError to the HotTopic.

**Comment by tejasv02** [comment]
I solved this issue by enabling UI Automation on calabash-ios 0.17.1 and xcode 7.2 --

Goto Settings on device
Scroll to "Developer" option
Switch on the option for UI Automation

**Comment by domy18** [comment]
Hello friend can help me for robotium webview

thanks
