### ISSUE TITLE
terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by vtiulenev** [calabash/calabash-ios#729]
I build the app without -cal scheme ==> it works fine.
I build the app with -cal scheme ==> it launches, allows me to create pin, then go to creating credentials screen, allows me to input credentials, then crashes with this message:

libc++abi.dylib: terminating with uncaught exception of type NSException

Xcode 6.1.1
Logs attached

**Comment by jmoody** [comment]
Not enough information.  I am going to close this.  It seems like your Xcode configuration is not correct.  Check your linker flags.
