### ISSUE TITLE
If "Enable UI Automation" is disabled the console fails silently

### ISSUE THREAD

**Issue by jrudolf** [calabash/calabash-ios#731]
Apologies if this has already been logged, but would it be possible to show a descriptive error message if the user tries to start the console with this disabled? Currently it fails silently when trying to "start_test_server_in_background".

**Comment by jmoody** [comment]
@jrudolf 

This is a difficult one to handle.  The information we get back from instruments about why it failed varies across Xcode and iOS version.  There is never a "Enable UIAutomation on your device message" that we can search for.  

I am not sure what we can do without a library that would allow us to ask questions about physical devices _before_ launching.
