### ISSUE TITLE
wait_for_none_animating fails for UIAlertController

### ISSUE THREAD

**Issue by JoeSzymanski** [calabash/calabash-ios#734]
I've run into one of the cases that wait_for_none_animating appears to always fail. When displaying a UIAlertController for either an alert or an action sheet, iOS makes use of a UIMotionEffect for parallax animations. Unfortunately, this means that the UIAlertController's view has a semi-permanent animation attached to it, which doesn't allow the wait_for_none_animating to ever succeed.

There are a few options to work around this. One option is to ignore animations that have the setting "removeOnCompletion" disabled. This might be overkill, since I'm not sure how often this occurs.
Another solution would be to look at the string key for the animations and ignore any of those that have the parallax class name in the key. This is also a bit of a hack, and may not be forward compatible.

Any other solution or workaround would be very useful, as we are trying not to have to have special steps for interacting with alerts or action sheets (especially since the person writing the test may not know that the button that needs to be pressed requires the special steps).

**Comment by JoeSzymanski** [comment]
Some additional information for the data associated with the parallax animations:
````
(lldb) p (NSString *)[[[0x7faf49c26120 layer] animationKeys] objectAtIndex:0]
(NSString *) $3 = 0x00007faf500e6bd0 @"<_UIParallaxMotionEffect: 0x7faf500315e0>"

(lldb) po [[0x7faf49c26120 layer] animationForKey:0x00007faf500e6bd0]

<CAAnimationGroup:0x7faf500e6b70; beginTimeMode = absolute; beginTime = 9047.26; removedOnCompletion = 0; duration = 0.0001; fillMode = both; animations = (
    "<CABasicAnimation: 0x7faf500e66d0>",
    "<CABasicAnimation: 0x7faf500e6820>"
)>

(lldb) po 0x7faf500e66d0
<CABasicAnimation:0x7faf500e66d0; removedOnCompletion = 0; additive = 1; fillMode = both; duration = 0.0001; toValue = 0.0; fromValue = 0.0; keyPath = position.y>

(lldb) po 0x7faf500e6820
<CABasicAnimation:0x7faf500e6820; removedOnCompletion = 0; additive = 1; fillMode = both; duration = 0.0001; toValue = 0.0; fromValue = 0.0; keyPath = position.x>
````
Based on this, it might be worth considering any animation with a short duration ( less than 0.01?) to still be "done".

**Comment by jmoody** [comment]
@JoeSzymanski Linking the PR here https://github.com/calabash/calabash-ios-server/pull/142

**Comment by jmoody** [comment]
Fixed in server develop branch.

**Comment by jmoody** [comment]
Fixed.
