### ISSUE TITLE
Segment fault crash on running cucumber command

### ISSUE THREAD

**Issue by navyah** [calabash/calabash-ios#737]
On running cucumber command I am getting a crash. Any one faced this issue?

.rvm/gems/ruby-2.0.0-p247/gems/gherkin-2.12.2/lib/gherkin_lexer_en.bundle: [BUG] Segmentation fault
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin14.0.0]

**Comment by jmoody** [comment]
This is not a Calabash problem.

It is a problem with gherkin.  You can find info about it by search for that particular error.

I recommend updating to ruby 2.2.1.
