### ISSUE TITLE
Xcode 6.3 instruments cannot launch an app that is already installed on iOS 8.3 Simulators

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#744]
Starting in Xcode 6.3 instruments has been unable to launch apps that are already installed on the iOS 8.3 Simulator.

Our testing has shown this to only be a problem when targeting _iOS 8.3_ simulators.  If your experience is different, please let us know.

```
Waiting for device to boot...
Instruments Trace Error : Target failed to run: The operation couldn’t be completed. 
(FBSOpenApplicationErrorDomain error 8.) : Failed to launch process with bundle identifier
'com.lesspainful.example.LPSimpleExample-cal'
```

There are three workarounds.

1. Use Xcode 6.2.
2. Use the iOS 8.2 Simulators
3. Reset the simulator content and settings before each Scenario.
```
# Add this to your features/O1_launch.rb before creating a new launcher.
RunLoop::SimControl.new.reset_sim_content_and_settings

**Comment by jmoody** [comment]
* This is not 100% reproducible; I am guessing 80%.
* I have been able to reproduce by running instruments from the command line using the same command args as the RunLoop::Instruments.spaw(...). 


### Reproduce

```
$ be calabash-ios sim reset
# Run one Scenario successfully
$ DEBUG=1 be cucumber -t @wip 

# Try running again and observe that the app did not launch
$ DEBUG=1 be cucumber -t @wip 

# Exit the command with control-c
# Quit the simulator
# Copy and paste the xcrun command and wrap -w arg in ""
$ xcrun instruments -w "iPhone 5s (8.3 Simulator)" ...

# Observe the hang.
# Manually delete the app from the Simulator
# Quit the simulator and observe that you can launch the app with instruments.
$ xcrun instruments -w "iPhone 5s (8.3 Simulator)" ...
```

**Comment by jmoody** [comment]
| installed? | simulator | instruments behavior |
|:----------:|:---------:|:--------------------:|
|     yes    |    open   |      [x]      |
|     no     |    open   |    cannot install    |
|     yes    |   closed  |     cannot launch    |
|     no     |   closed  |      [x]      |

**Comment by mvemjsun** [comment]
@jmoody will calabash 0.14.0 be able to launch app on physical devices that are on iOS 8.3 using Xcode 6.3. As it stands I can't launch App using Calabash 0.13.0 using Xcode 6.1.1 since the device was upgraded to iOS 8.3.
`2015-04-15 15:33:51.850 instruments[16675:4f03] Failed to start Instruments daemon on 'Iphone 6 plus-1 (8.3)' (The service is invalid.)`

**Comment by jmoody** [comment]
iOS 8.3 is incompatible with Xcode 6.1.1.  

You need to update your Xcode version to 6.3

Calabash 0.14.0 works with Xcode 5.1.1 - Xcode 6.3.

**Comment by jmoody** [comment]
From my perspective, this issue has been resolved.  I will keep it open for a while longer to see if the community encounters related problems.

**Comment by sairoshan** [comment]
I am facing similar issue on my Iphone5 (8.3). I get the message like:

Waiting for device to boot...
I tried using Xcode 6.2 and 6.3 both without any success.

Can somebody help on this?

**Comment by jmoody** [comment]
@sairoshan This usually means you have a corrupt CoreSimulator environment or you have incorrectly installed your side-by-side Xcode versions.

A restart of your machine usually corrects this problem.

From Apple's release notes:

* After installing a new version of Xcode, you must restart your machine.
* After install a new simulator SDK, you must restart your machine.
* If change the Xcode install path, you must restart your machine.  For example, if you renamed the Xcode.app to Xcode-6.2.app.

**Comment by navyah** [comment]
I am getting following error on trying the launch the app from device:
Bundle id is changed below.

Calabash-ios version: 0.14.0
xcode 6.0
iOS version 8.3

$ DEVICE_ENDPOINT=http://172.16.22.84:37265 DEVICE_TARGET=6e30e3595157fc29bafabe57400e0bb831ff3a95 BUNDLE_ID=com.xxx.xxx calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError. 
 Logfile /var/folders/48/78cws0l166n81cqr2bjjjwj8j0x1ll/T/run_loop20150417-1146-t084wd/run_loop.out 

 

	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/launcher.rb:772:in `new_run_loop'
	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/launcher.rb:630:in `relaunch'
	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/core.rb:849:in `start_test_server_in_background'
	from (irb):1
	from /Users/navya.hegde/.rvm/rubies/ruby-2.0.0-p643/bin/irb:12:in `<main>'
irb(main):002:0> 

Thanks.

**Comment by tomburns** [comment]
I just lost a day to this issue; was finally able to get cukes running on an actual device but not on the 8.3 simulator in Xcode 6.3.1.

Happy to provide any assistance I can here.

**Comment by jmoody** [comment]
@navyah 

The title of this case is "Xcode 6.3 instruments cannot launch an app that is already installed on iOS 8.3 Simulators".  Your issue is about physical devices.

Please see these Hot Topics:

* **Enable Development After Upgrading Devices to 8.***
* **Errno::EINTR: Interrupted system call**

**Comment by jmoody** [comment]
@tomburns 

Did you update run-loop to 1.3.1?  It contains a fix for this issue.

FYI/BTW run-loop 1.3.2 was just released (it also contains the fix).

**Comment by jmoody** [comment]
@tomburns If you are stilling seeing this problem, please open a new issue or @ mention me here.
