### ISSUE TITLE
unable to launch the app in the device from instruments

### ISSUE THREAD

**Issue by navyah** [calabash/calabash-ios#746]
irb(main):001:0> start_test_server_in_background
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError. 
 Logfile /var/folders/48/78cws0l166n81cqr2bjjjwj8j0x1ll/T/run_loop20150415-4494-1flbzbx/run_loop.out 

 

	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/launcher.rb:772:in `new_run_loop'
	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/launcher.rb:630:in `relaunch'
	from /Users/navya.hegde/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.0/lib/calabash-cucumber/core.rb:849:in `start_test_server_in_background'
	from (irb):1
	from /Users/navya.hegde/.rvm/rubies/ruby-2.0.0-p643/bin/irb:12:in `<main>'
irb(main):002:0> 

I am using calabash-ios version 0.14.0
device os: 8.3

**Comment by jmoody** [comment]
Please see these Hot Topics:

* [**5. Enable Development After Upgrading Devices to 8.\***](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#5-enable-development-after-upgrading-devices-to-8)
* [**6. Errno::EINTR: Interrupted system call**](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#6-errnoeintr-interrupted-system-call)

**Comment by jmoody** [comment]
@navyah I am closing this issue because the answer can be found in the Hot Topics.
