### ISSUE TITLE
Cucumber versions conflicts how to resolve it

### ISSUE THREAD

**Issue by vishnunairdsg412** [calabash/calabash-ios#747]
Unable to activate calabash-android-0.5.8, because cucumber-2.0.0 conflicts with cucumber (~>1.3.17) (Gem::ConflictError)

**Comment by jmoody** [comment]
The message is clear:  calabash does not support cucumber 2.0.  You need to uninstall cucumber 2.0.

See https://github.com/calabash/calabash-ios/issues/736
