### ISSUE TITLE
retriable should support older versions

### ISSUE THREAD

**Issue by nishanil** [calabash/calabash-ios#748]
As per @krukow 's suggestion, creating an issue here. 

I was running retriable (1.4.1) and landed into this error:
> uninitialized constant Retriable::VERSION (NameError)
 /Users/Nish/.calabash/gems/run_loop-1.3.1/lib/run_loop/patches/retriable.rb:7:in `tries_and_interval’ 

More info here:
http://www.screencast.com/t/x89yssI7o

**Comment by tommeier** [comment]
I fixed this by adding: 

```
require 'calabash-cucumber/launcher'
require 'retriable/version'
```

to my `01_launch.rb` file.

**Comment by jmoody** [comment]
@nishanil I pushed a fix to run-loop.  For now, @tommeier's patch should world.

Thanks @tommeier
