### ISSUE TITLE
NSLog output can cause apps to become unresponsive during testing.

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-ios#749]
Issue related with calabash server, when app print big message to log server and app are hanged, with same usage scenario, when app and tests run manually app does not hangs, if printing logs disabled in app when calabash runs smoothly.
Can i somehow deal with that issue from calabash perspective? (I always can disable logs in app but it's not best option) 

If addition information needed please give me know. 

calabash-cucumber = 0.13.0
server_version = 0.13.0
run_loop = 1.2.9
Xcode 6.3 
xcode-select version 2339
iOS simulator and real iPhone 5s
 
```
{"status"=>"success", "value"=>true, "index"=>20}
    Then I change Country to "Germany"                                                              # features/step_definitions/residence_steps.rb:55
Sending UIA command
uia.tapOffset('{:x 275, :y 42}')
2015-04-21 10:03:34 +0200 [RunLoop:debug]: 21:uia.tapOffset('{:x 275, :y 42}')
2015-04-21 10:03:34 +0200 [RunLoop:debug]: Trying write of command 21:uia.tapOffset('{:x 275, :y 42}') at index 21
2015-04-21 10:03:34 +0200 [RunLoop:debug]: validate index written for index 21 ok
Result
{"status"=>"success", "value"=>true, "index"=>21}
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
```

**Comment by jmoody** [comment]
This is a known issue.  There is no workaround.  The problem is with Apple's UIAutomation API.

See the Hot Topics.

https://github.com/calabash/calabash-ios/wiki/Hot-Topics

Our only recommendation is that you file a bug report with Apple.

https://bugreport.apple.com

**Comment by jmoody** [comment]
@ark-konopacki 

Is this all the console output from your app?  This does not seem like a lot of NSLog activity.  We haven't had reports that the logging from calabash itself is enough to cause the app to become unresponsive.

**Comment by ark-konopacki** [comment]
@jmoody, thanks for quick response, my mistake i haven't check hot-topics, and yes it's related to big message output via NSLog. 
Issue can be closed.
