### ISSUE TITLE
Multiple device automation calabash-ios

### ISSUE THREAD

**Issue by bkarthick** [calabash/calabash-ios#750]
# xcode installation location
 /Applications/Xcode.app/Contents/Developer

# xcode version
Xcode 6.2
Build version 6C131e

# calabash version
0.12.2

Is it possible to run calabash-ios script on multiple devices simultaneously which is connected to same system. If its possible please let me know the procedure and functionalities regarding this.

**Comment by jmoody** [comment]
@bkarthick 

This is  a question and not a feature.

Have a look at our [CONTRIBUTING.md](https://github.com/calabash/calabash-ios/blob/develop/CONTRIBUTING.md) doc and the [wiki front page] for places to post questions.

To answer your question:  Calabash uses Apple's instruments command-line tool to interact with Apple's UIAutomation API.  Apple does not allow more than one instruments process to be active at one time.  You can spawn multiple instruments processes, but they clobber each other's IO.  So there is no way to run more than one Calabash iOS tests.
