### ISSUE TITLE
run-loop 1.3.* - xctools.rb:192:in `split': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by Aswini999** [calabash/calabash-ios#752]
I'm trying to build the calabash target using rakefile.
```echo Yes\1| calabash-ios setup```
Calabash target has been created but  got this error

```bash
Adding Other Linker Options to target <projectname>-cal
/Users/<user>/.rvm/gems/ruby-2.1.2/gems/run_loop-1.3.1/lib/run_loop/xctools.rb:192:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /Users/<user>/.rvm/gems/ruby-2.1.2/gems/run_loop-1.3.1/lib/run_loop/xctools.rb:192:in `block (2 levels) in instruments'
```
ruby version is 2.1.2
calabash-cucumber-0.14.0
xcode version-6.2.2

Please help me to fix this

**Comment by jmoody** [comment]
Hi @Aswini999 

We usually don't try to support CI related problems.

Does this happen locally?

**Comment by ark-konopacki** [comment]
Hi @Aswini999 can you try to add: 
export LC_ALL="en_US.UTF-8" 
before running calabash-ios setup in your CI? (it works for me in Jenkins)

**Comment by jmoody** [comment]
I am actually don't know what to do about this issue.

My only thought is to mark every file as UTF-8, but as far as I know, this should not be necessary as ruby >= 1.9 is UTF-8 compat.

**Comment by ark-konopacki** [comment]
I have similar issue only on CI environment, and i think it mainly depends on sys locale not calabash itself

**Comment by jmoody** [comment]
@ark-konopacki Thanks for confirming.
