### ISSUE TITLE
Calabash iOS/Android feature parity:  iOS is missing 'wait_for_element_does_not_exist'

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-ios#757]
Have found some funny thing in wait helpers: 
in calabash-ios: wait_for_element_does_not_exists
in calabash-android wait_for_element_does_not_exist
is that 's' difference have some reasons?

**Comment by jmoody** [comment]
It is a typo.

The API will be the same (but different) in  Calabash 2.0.

If you want a patch, add this to your support/env/patches/calabash.rb:

```
require 'calabash-cucumber/wait_helpers'

module Calabash
  module Cucumber
    module WaitHelpers
      alias_method :wait_for_element_does_not_exist, :wait_for_element_does_not_exists
    end
  end
end
```

Pull requests welcome.

**Comment by ark-konopacki** [comment]
Please check
https://github.com/calabash/calabash-ios/pull/758

**Comment by jmoody** [comment]
@ark-konopacki 

Thanks for the PR.


All you need to do is add:

```
alias_method :wait_for_element_does_not_exist, :wait_for_element_does_not_exists
```

to: [wait_helpers.rb](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/wait_helpers.rb) at or around line 219

It would be great if you could try to write a unit test, but the rspec suite is difficult to work with.  If you don't have rspec experience, don't bother.

**Comment by ark-konopacki** [comment]
@jmoody thanks for support

**Comment by jmoody** [comment]
Thanks @ark-konopacki
