### ISSUE TITLE
Typo in calabash_steps.rb for touching tableViewCell

### ISSUE THREAD

**Issue by stevenbaker** [calabash/calabash-ios#762]
During a recent coding style cleanup in `calabash_steps.rb`, a typo was introduced to a step definition at this line:

https://github.com/calabash/calabash-ios/blob/bfdd138919cb1fc37a803bdc1a5a33eb74d77bd1/calabash-cucumber/features/step_definitions/calabash_steps.rb#L65

It appears that this:
```
touch("tableViewCell text:'#{cell_name}'")
```

Became this:
```
touch("tableViewCell text:' #{cell_name}'")
```

Note the space **after** the single quote.  

I believe the author likely intended a space **before** the quote.  (/cc @must-not-code)

This extra space causes errors such as the one in the attached screenshot below, where this step:
```
And I touch the list item "Baseball"
```

Generates an erroneous query of:
```
"tableViewCell text:' Baseball'"
```

![screen shot 2015-05-08 at 12 21 40 am](https://cloud.githubusercontent.com/assets/380392/7546694/a8322962-f595-11e4-858a-7dfca4c6f6ea.png)

**Comment by must-not-code** [comment]
That is my typo, sorry.
