### ISSUE TITLE
Intermittent JSON Parse error (Invalid JSON returned from calabash server)

### ISSUE THREAD

**Issue by mvemjsun** [calabash/calabash-ios#765]
Test environment

* Calabash 0.14.0
* Xcode 6.3 (6D570)
* Testing on an real Iphone 6+, iOS 8.3
* JSON gem version 1.8.2 (also tried 1.8.1)

During running of the test case I get a JSON parse error, I have noticed that the son returned from the calabash server is incorrect, This happens when the element being queried is not present.
`
22\n
{"results":[],"outcome":"SUCCESS"}\n
0
`

server response

```
POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 1.9.3 (2013-06-27))
Accept: */*
Date: Sun, 10 May 2015 17:01:46 GMT
Content-Length: 98
Host: 192.168.0.17:37265

{"query":"view marked:'tomorrowSectionHeader'","operation":{"method_name":"query","arguments":[]}}

= Response

22
{"results":[],"outcome":"SUCCESS"}
0

! CONNECTION CLOSED
```

The failure is encountered in the `Calabash::Cucumber::Map` module in method `raw_map` on code `res = JSON.parse(res)`.

**Comment by jmoody** [comment]
@mvemjsun 

This looks very strange.  Can you provide an app that demonstrates this problem?

Last summer, I ran into an app that was returning mysterious unicode characters.  I wonder if that is what the problem is here?

If you want to keep an example private, please contact me via the email address in my GitHub profile.

Thanks.

**Comment by mvemjsun** [comment]
Will try to dig out the version of the app (will check if we are allowed to share it), meanwhile you could be right the 22 at the start and 0 at the end definitely don't look correct.

**Comment by mvemjsun** [comment]
Have not encountered again recently so will close.
