### ISSUE TITLE
Not able to run test on multiple physical device connected to same mac machine

### ISSUE THREAD

**Issue by vishwas20** [calabash/calabash-ios#768]
Hi,

I am having issue on running the test case when connetecd multiple device on same mac machine, run_loop is waiting for getting to wait for other test finish.

Here is the log of mine:-

Running Physical Device => Device_IP : xx.xx.xxx.xx and UDID : 83bebe5c4bfb977ba9edcd0f95cd32e4aaf57bbf with Sandbox Server : http://xx.xx.xxx.xxx:4567
[32m
INFO: Using uia strategy: 'host'[0m
2015-05-13 11:45:50 +0800 [RunLoop:debug]: Preparation took 0.16459 seconds
2015-05-13 11:45:51 +0800 [RunLoop:debug]: 
{
                        :app => "sg.com.prep.sgiphone",
                       :args => [],
    :bundle_dir_or_bundle_id => "sg.com.prep.sgiphone",
                  :bundle_id => "sg.com.prep.sgiphone",
                     :device => "sg.com.prep.sgiphone",
              :device_target => "83bebe5c4bfb977ba9edcd0f95cd32e4aaf57bbf",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/run_loop.out",
                  :max_retry => 3,
                  :no_launch => false,
                    :no_stop => false,
                      :reset => true,
                :results_dir => "/var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w",
          :results_dir_trace => "/var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/trace",
                     :script => "/var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/_run_loop.js",
                :sdk_version => nil,
                    :timeout => 300,
                       :udid => "83bebe5c4bfb977ba9edcd0f95cd32e4aaf97bbf",
               :uia_strategy => :host,
                      :xcode => "6.3.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer/"
}

[35m### Starting on 83bebe5c4bfb977ba9edcd0f95cd32e4aaf97bbf App: 
sg.com.prep.sgiphone ###[0m
2015-05-13 11:45:51 +0800 [RunLoop:debug]: xcrun instruments -w 83bebe5c4bfb977ba9edcd0f95cd32e4aaf57bbf -D /var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/trace -t Automation sg.com.prep.sgiphone -e UIARESULTSPATH /var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w -e UIASCRIPT /var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/_run_loop.js >& /var/folders/f3/xwc43bl175ndr2zh5pzl3hyc0000gq/T/run_loop20150513-67896-1v5lx0w/run_loop.out

Same if other test launch on seconf device both are getting deadlock to each other in run loop here.

Please suggest how to resolve this.

**Comment by ark-konopacki** [comment]
Hi, @vishwas20 i think this is cannot be done due to instruments limitation. If you want to test on multiple device in same time you should check cloud testing.

**Comment by HannaPiatrouskaya** [comment]
you are not able to test on one machine multiple devices simultaneously. One of the approach is to use VMs

**Comment by vishwas20** [comment]
@ark-konopacki @HannaPiatrouskaya . Thanks for the reply guys. But i am worried about as , If its the case, i cant connect multiple device to the one Mac OS.  

Is there any way to setup my Test lab for IOS as i already have one for Android in which i have one Linux connected to multiple Android devices to run simultaneous test cases?

**Comment by jmoody** [comment]
@vishwas20

> Is there any way to setup my Test lab for IOS as i already have one for Android in which i have one Linux connected to multiple Android devices to run simultaneous test cases?

Please take this question to the Google Forum.  This is not right place ask for that kind of help.

**Comment by vishwas20** [comment]
@jmoody Apologies, But my issue was not that, My run_loop getting stuck in deadlock when running the test case on physical device & Simulator simultaneously on the same MAC machine.

Seems this is totally reflected to the Calabash-ios. I tried to run my test cases on Simulator & Physical device-Iphone6 connected to the same single Mac machine.

run_loop getting stuck to wait for finish the test either on Simulator or on Physical device, vice-versa.

Please suggest, if i can resolve this deadlock

**Comment by jmoody** [comment]
@vishwas20 

As mentioned above, there can only be one instruments process running on your Mac.  The instruments process that is interacting with your physical device is clobbering the IO of the instruments process that is interacting with your simulator.
