### ISSUE TITLE
Not updating app in simulator when building for command line

### ISSUE THREAD

**Issue by toniomg** [calabash/calabash-ios#772]
Hello,

I'm using JIRA to trigger the build of the app and the automation testing.

Right now, I do:

xctool -project VA.xcodeproj -scheme VA-cal -sdk iphonesimulator -configuration Debug build

The project is correctly build, so I do:

DEBUG=1 cucumber

And I see in the output: 

INFO: Using uia strategy: 'preferences'
2015-05-14 10:48:16 +0100 [RunLoop:debug]: Simulator instruction set 'x86_64' is compatible with ["i386"]
Waited for 0.139446 seconds for 'iOS Simulator' to start.
Waited for 0.413189 seconds for 'SimulatorBridge' to start.
2015-05-14 10:48:20 +0100 [RunLoop:debug]: 
{
                        :app => "/Users/xxx/Library/Developer/Xcode/DerivedData/VA-fbbsnvmolpizkxfafatokkmfdksv/Build/Products/Debug-iphonesimulator/VA-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/xxx/Library/Developer/Xcode/DerivedData/VA-fbbsnvmolpizkxfafatokkmfdksv/Build/Products/Debug-iphonesimulator/VA-cal.app",
                  :bundle_id => "com.VA",
                     :device => "iphone",
              :device_target => "simulator",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/yy/c1bptvrd5kv4fvxsp39bjq91vsh5fv/T/run_loop20150514-56272-8kojlc/run_loop.out",

The weird part here is that, even though the app and the bundle_dir_or_bundle_id are pointing to the right app (I checked), the simulator runs the previous app.

It won't work until I manually restart the simulator, then the new app gets installed.

​

**Comment by jmoody** [comment]
This is a known issue.  Starting in Xcode 6, instruments does not re-install the app if the app is already installed.

You can use the run-loop gem simctl command-line tool to re-install the app.

```
$ be run-loop simctl help install
Usage:
  run-loop install --app [OPTIONS] -a, --app=APP

Options:
  -a, --app=APP                # Path to a .app bundle to launch on simulator.
  -d, [--device=DEVICE]        # The device UDID or simulator identifier.
  -f, [--force]                # Force a re-install the existing app.
  -v, [--debug], [--no-debug]  # Enable debug logging.
```

1. If the app is not installed, install it.
2. If the app is installed and the checksum is the same as the app you are trying to test, skip the installation.
3. If the app is installed and the checksum is different, uninstall and then reinstall.
4. You can force an install always by using the --force argument.

Uninstalling the app will delete any data associated with app.

You can also use:

```
$ be calabash-ios sim reset

or

RunLoop::SimControl.new.reset_sim_content_and_settings
```

**Comment by toniomg** [comment]
Thanks!

**Comment by toniomg** [comment]
run-loop install --app [OPTIONS] -a, --app=APP 
should be:
run-loop simctl install --app [OPTIONS] -a, --app=APP
