### ISSUE TITLE
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)

### ISSUE THREAD

**Issue by hangnm84** [calabash/calabash-ios#779]
Hi
I am having issue with HTTPClient
1.Test envirorment:
    - Calabash-cucumber: 0.14.3
    - Httpclient: 2.6.0.1
    - run_loop: 1.3.3
    - simulator: iPad Air (8.2 Simulator)
-------------------
2.When I touch button Next in screen to go other screen (by command or by manual), calabash-server hasn't any response, wait forever. And when I use command+C , my terminal have log in below

irb(main):005:0> touch("* tag:145")
= Request

POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.0.0 (2014-05-08))
Accept: */*
Date: Mon, 25 May 2015 04:48:41 GMT
Content-Length: 72
Host: localhost:37265

{"query":"* tag:145","operation":{"method_name":"query","arguments":[]}}

= Response

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 473
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Date: Mon, 25 May 2015 04:48:41 GMT
Accept-Ranges: bytes
Access-Control-Max-Age: 3000

{"status_bar_orientation":"left","results":[{"id":null,"selected":false,"visible":1,"label":"次へ","frame":{"y":29,"width":60,"x":950,"height":25},"enabled":true,"description":"<UIButton: 0x7e8d4120; frame = (950 29; 60 25); opaque = NO; autoresize = RM+BM; tag = 145; layer = <CALayer: 0x7e85c7e0>>","alpha":1,"value":null,"rect":{"y":29,"width":60,"center_x":980,"x":950,"center_y":41.5,"height":25},"accessibilityElement":true,"class":"UIButton"}],"outcome":"SUCCESS"}Sending UIA command
uia.tapOffset('{:x 980, :y 41.5}')
= Request

POST /uia HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.0.0 (2014-05-08))
Accept: */*
Date: Mon, 25 May 2015 04:48:41 GMT
Content-Length: 48
Host: localhost:37265

{"command":"uia.tapOffset('{:x 980, :y 41.5}')"}

= Response

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Date: Mon, 25 May 2015 04:48:41 GMT

^CIRB::Abort: abort then interrupt!
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `call'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `gets'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `gets'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:972:in `read_body_chunked'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:696:in `get_body'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:1196:in `do_get_block'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:57:in `block in make_http_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:50:in `times'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:29:in `http'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:28:in `uia'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:454:in `uia_handle_command'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:201:in `uia_tap_offset'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/actions/instruments_actions.rb:93:in `query_action'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/actions/instruments_actions.rb:15:in `touch'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:1166:in `query_action_with_options'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:177:in `touch'
	from (irb):5
	from /Users/setacinq/.rvm/rubies/ruby-2.0.0-p481/bin/irb:12:in `<main>'i

--------------------------
3.If in a state of wait (when touch button Next in step 2 ), In terminal, I use command query("*") => have issues in below

irb(main):003:0> query("*")
= Request

! CONNECT TO localhost:37265
! CONNECTION ESTABLISHED
POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.0.0 (2014-05-08))
Accept: /
Date: Mon, 25 May 2015 03:31:22 GMT
Content-Length: 64
Host: localhost:37265

{"query":"*","operation":{"method_name":"query","arguments":[]}}

= Response

! CONNECTION CLOSED
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
= Request

! CONNECT TO localhost:37265
! CONNECTION ESTABLISHED
POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.0.0 (2014-05-08))
Accept: /
Date: Mon, 25 May 2015 03:33:25 GMT
Content-Length: 64
Host: localhost:37265

{"query":"*","operation":{"method_name":"query","arguments":[]}}

= Response

^CIRB::Abort: abort then interrupt!
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `call'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `gets'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:485:in `gets'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `block in parse_header'
	from /Users/setacinq/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Users/setacinq/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:855:in `read_header'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:662:in `get_header'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:1247:in `do_get_header'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:1194:in `do_get_block'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:57:in `block in make_http_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:50:in `times'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/http_helpers.rb:29:in `http'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/map.rb:71:in `raw_map'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/map.rb:23:in `map'
	from /Users/setacinq/.rvm/gems/ruby-2.0.0-p481/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:112:in `query'
	from (irb):3

**Comment by Anitha-me** [comment]
Am also facing the same issue since from a month. Kindly help me after looking into the below logs,.

Mac:rt-mobile anupama$ DEVICE_TARGET='iPhone 5s (8.1 Simulator)' cucumber features/02.OfferList.feature --tags @offerlist
Feature: OfferList

  @offerlist
  Scenario: OfferList screen                                       # features/02.OfferList.feature:3
    Given I am on the OfferList screen                             # features/step_definitions/OfferList.rb:4
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
Failing... HTTPClient::ReceiveTimeoutError
    Then I should have check for all the offerlist screen elements # features/step_definitions/OfferList.rb:11
      execution expired (HTTPClient::ReceiveTimeoutError)
      ./features/Pages/OfferList_Page.rb:11:in `offerlist_screenelements'
      ./features/step_definitions/OfferList.rb:13:in `/^I should have check for all the offerlist screen elements$/'
      features/02.OfferList.feature:6:in `Then I should have check for all the offerlist screen elements'
    And I should compare the offer list title count with UI Count  # features/step_definitions/OfferList.rb:16
    And I should check for the each offer labels present           # features/step_definitions/OfferList.rb:21
    Then I should tap on the respective offer                      # features/step_definitions/OfferList.rb:25
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
Failing... HTTPClient::ReceiveTimeoutError
      execution expired (HTTPClient::ReceiveTimeoutError)
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `gets'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `block in parse_header'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:855:in `read_header'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:662:in `get_header'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:1247:in `do_get_header'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:1194:in `do_get_block'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643@global/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/http_helpers.rb:58:in `block in make_http_request'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/http_helpers.rb:50:in `times'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/http_helpers.rb:29:in `http'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
      /Users/anupama/.rvm/gems/ruby-2.0.0-p643/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/core.rb:805:in `calabash_exit'
      /Users/anupama/Desktop/CalabashMob/rt-mobile/features/support/01_launch.rb:41:in `After'

Failing Scenarios:
cucumber features/02.OfferList.feature:3 # Scenario: OfferList screen

1 scenario (1 failed)
5 steps (1 failed, 3 skipped, 1 passed)
13m7.318s
Mac:rt-mobile anupama$ gem list

*** LOCAL GEMS ***

awesome_print (1.6.1)
bigdecimal (1.2.0)
builder (3.2.2)
bundler (1.9.9, 1.9.6)
bundler-unload (1.0.2)
calabash-common (0.0.1)
calabash-cucumber (0.14.1)
CFPropertyList (2.3.1)
cucumber (1.3.19)
diff-lcs (1.2.5)
edn (1.0.6)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
geocoder (1.2.8)
gherkin (2.12.2)
httpclient (2.6.0.1)
io-console (0.4.2)
json (1.8.2, 1.7.7)
minitest (4.3.2)
multi_json (1.11.0)
multi_test (0.1.2)
mysql (2.9.1)
psych (2.0.0)
rack (1.6.1)
rack-protection (1.5.3)
rake (0.9.6)
rdoc (4.0.0)
retriable (2.0.2)
rspec (3.2.0)
rspec-core (3.2.3)
rspec-expectations (3.2.1)
rspec-mocks (3.2.1)
rspec-support (3.2.2)
rubygems-bundler (1.4.4)
run_loop (1.3.3, 1.3.2)
rvm (1.11.3.9)
sim_launcher (0.4.13)
sinatra (1.4.6)
slowhandcuke (0.0.3)
test-unit (2.0.0.0)
thor (0.19.1)
tilt (2.0.1)
tiny_tds (0.6.2)
version (1.0.0)

**Comment by Anitha-me** [comment]
I dont see any support Krukow or Joshua. Kindly help me on this since I have used to Calabash automation completely. I dont find any issue when am running the app in Simulator from XCODE but am facing the issue whenever am running the feature file/ in irb mode, i could see the HTTPClient problem.

Problem is completely with Calabash but neither from the network issue nor from the XCode issue. Please suggest me.

**Comment by jmoody** [comment]
@hangnm84

I don't completely understand the problem you are having.

Is Calabash hanging after the "tap" gesture?

If so, you should have a look at the Hot Topic **[NSLog output can cause apps to become unresponsive during testing**](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#2-nslog-output-can-cause-apps-to-become-unresponsive-during-testing) and try to determine if it is NSLog output that is causing the hang.

In the future, please use  ``` GitHub code-block formatting to make your report easier to read.

@Harani-me 

We need more information.  Please open a separate issue with the details of your environment.  See https://github.com/calabash/calabash-ios/wiki#reporting-problems

**Comment by narendra-sphinx** [comment]
Hi

I am also experiencing same issue on android with device and also in virtual device too.

@jmoody - yes I have observed calabash handing after the "tap" gesture. But this is not for each & every tap. More precisely I can say, Its reproducible when tap on any button. 

Great if we could fix this quickly :)

**Comment by jmoody** [comment]
@narendra-sphinx 

Please open a new issue with details.

I can't make sense of the logs that are posted here.

My best guess is that it is the NSLog problem I mentioned.

> I am also experiencing same issue on android with device and also in virtual device too.

Please report this issue on the android repo.

**Comment by jmoody** [comment]
@hangnm84 If you are still having this problem, please create a new issue and use markdown formatting.
