### ISSUE TITLE
Does `calabash-ios` install App to device?

### ISSUE THREAD

**Issue by cybertk** [calabash/calabash-ios#781]
Does `calabash-ios` install App to device when I run with the following command as mentioned in [07-Testing-on-physical-iDevices](https://github.com/calabash/calabash-ios/wiki/07-Testing-on-physical-iDevices)

```
BUNDLE_ID=com.example.app DEVICE_TARGET=7ezz..a DEVICE_ENDPOINT=http://10.0.1.56:37265 cucumber
```

My output is

```
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
   Logfile /var/folders/ft/d3401yq51xn4_8yyh18kqfsr0000gq/T/run_loop20150605-15851-1jvlcmc/run_loop.out
```

**Comment by jmoody** [comment]
No.  The ipa must be installed on the device.

**Comment by cybertk** [comment]
See https://github.com/calabash/calabash/blob/develop/lib/calabash/ios/device/physical_device_mixin.rb

**Comment by jmoody** [comment]
That is a link to Calabash 2.0.  Those hooks are not available in Calabash iOS 0.x.

I am not sure why added that link to this issue.

If you are looking for an example of how to use a third-party tool to manage apps on a real device, see https://github.com/calabash/ios-smoke-test-app/tree/master/CalSmokeApp/features/support

We like use the GitHub issues for feature requests and bugs.  General questions should be asked elsewhere.

https://github.com/calabash/calabash-ios/wiki#getting-help
