### ISSUE TITLE
Support for Native UI Testing in iOS 9

### ISSUE THREAD

**Issue by fabb** [calabash/calabash-ios#788]
iOS 9 will support native UI testing via XCTest. Could Calabash use this for executing its tests?

From the Xcode 7 beta release notes:
> UI Testing. Xcode 7 introduces UI testing as a major new feature of the existing XCTest framework. UI testing is implemented as an extension to the existing APIs and concepts in XCTest, making it easy to adopt for developers who have familiarity with Xcode’s testing features. (10975541)

**Comment by jmoody** [comment]
@fabb It is really too early to answer this question.  We have only just started to look at this new feature.

**Comment by jmoody** [comment]
Closing as there is nothing actionable here.
