### ISSUE TITLE
screenshot does not capture all views; e.g. custom keyboards and OpenGL views

### ISSUE THREAD

**Issue by MortenGregersen** [calabash/calabash-ios#789]
I'm using calabash to take a lot of screenshots for the App Store and our manual UI test report.

Some of the UI elements look weird when we take screenshots. I can't figure out how to create an issue on calabash-ios-server on Github, so I will post the issue here with screenshots.

I'm using the latest version of Calabash (0.14.3) and inject the dylib into my Swift app.

I see the issue with `UIDatePicker`, `UISegmentedControl` and ASCII keyboard.

I've looked at the code generating the screenshot (https://github.com/calabash/calabash-ios-server/blob/develop/calabash/Classes/FranklyServer/Routes/LPScreenshotRoute.m). It looks a bit old and outdated.

Maybe it should be updated to the newest way to take screenshots/snapshots with `drawViewHierarchyInRect:afterScreenUpdates:` (https://developer.apple.com/library/ios/qa/qa1817/_index.html)

`UIDatePicker`: Here are two date pickers
![image](https://cloud.githubusercontent.com/assets/759680/8225360/ff3c1970-1593-11e5-8f7e-8a8b2e71937b.png)
`UISegmentedControl`: In the selected segment I see the text 'Indbetaling' when run on device or simulator
![image](https://cloud.githubusercontent.com/assets/759680/8225362/03de1000-1594-11e5-8888-42efeb5bdcc2.png)
ASCII keyboard: Backspace key, numbers key and the globe key is light blue but are grey on device and simulator. The shift key is dark grey but grey on device and simulator.
![image](https://cloud.githubusercontent.com/assets/759680/8225364/077bba5a-1594-11e5-8341-78127a980468.png)

**Comment by jmoody** [comment]
We need to give the user the option to use the newer screenshots.

**Comment by jmoody** [comment]
@MortenGregersen In issue #347 we do a side-by-side comparison of screenshots.  No strategy works for everything.  

Can you try:

```
$ be calabash-ios console
> start_test_server_in_background
> uia("UIATarget.localTarget().captureScreenWithName('my-screenshot')")
```

The location where this screenshot is saved is strange, so we'll use Unix to find it.

```
$ find ~/.run-loop "*.png" -print
```

Thanks.

**Comment by MortenGregersen** [comment]
I've tried your suggestion. I didn't use `be` as I don't know what it is and the command isn't found. The last command needs a `-name` before `"*.png"`.

It gave me another (but not better) result. We have a couple of apps with the same functionality but with individual design, so don't compare the images by the design, only by the UI components mentioned.

The first `UIDatePicker` looks better, but the second one is only partial.
![my-screenshot 10](https://cloud.githubusercontent.com/assets/759680/13348131/f7d816fc-dc71-11e5-9f28-d046d403cc2e.png)

The selected part of `UISegmentedControl` looks better, but the unselected part has disappeared (shown in simulator).
![my-screenshot 12](https://cloud.githubusercontent.com/assets/759680/13348157/1ac286ca-dc72-11e5-8b4b-30b6ba119517.png)

The ASCII keyboard (and the OK button) has disappeared (shown in simulator)
![my-screenshot 6](https://cloud.githubusercontent.com/assets/759680/13348206/6338cb58-dc72-11e5-8f09-a2baacc24790.png)

**Comment by jmoody** [comment]
@MortenGregersen 

If you get a chance, can you try with this [calabash.framework.tar.gz](https://files.zenhub.io/56d02adc9d84c5730698e87d) framework?  

It is 0.18.1.pre1.

 It uses `drawViewHierarchyInRect:afterScreenUpdates:` for screenshots.  We are probably going to change the implementation despite the problems with UIAlertView and UISheetView.


Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by MortenGregersen** [comment]
@jmoody we use dylib injection. Do you have 0.18.1.pre1 as dylib, or is it possible to update to a pre gem?

**Comment by jmoody** [comment]
[calabash-dylibs.tar.gz](https://files.zenhub.io/56d03a9c9d84c5730698e9da)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

No pre release.

**Comment by MortenGregersen** [comment]
I was not able to inject the dylib. I replaced the dylibs from the installed gem with the dylibs from the link.

I am running Ruby 2.2.1 with calabash-cucumber 0.18.1 (with the new pre-dylibs) and run_loop 2.0.7.

It gave me this result:
```
mobilimac:automated_tests bdumgr$ APP_BUNDLE_PATH=project/apps/MyApp.app DEBUG=1 calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background({:inject_dylib => true, :uia_strategy => :preferences, :args => %w(-AppleLanguages, (da))})

INFO: Using uia strategy: 'preferences'
DEBUG: Searching for run-loop results with glob: /Users/bdumgr/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.024701 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 6 instruments caches
DEBUG: Will delete 1 instruments caches
DEBUG: Deleted 1 instruments caches in 0.028382 seconds
DEBUG: Simulator instruction set 'x86_64' is compatible with '["i386"]'
DEBUG: Launching #<Simulator: iPhone 6s (9.2) FF4200D7-01E8-48E9-A0A4-336ED8B631DE x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID FF4200D7-01E8-48E9-A0A4-336ED8B631DE
DEBUG: Waiting for simulator to stabilize with timeout: 30
DEBUG: Simulator stable after 1.1357439999999999 seconds
DEBUG: Waited a total of 3.135744 seconds for simulator to stabilize
DEBUG: Took 3.263257 seconds to launch the simulator
EXEC: xcrun simctl install FF4200D7-01E8-48E9-A0A4-336ED8B631DE /Users/bdumgr/Desktop/BDMobilAutoTest/automated_tests/project/apps/MyApp.app
DEBUG: Waiting for simulator to stabilize with timeout: 30
DEBUG: Simulator stable after 15.105045 seconds
DEBUG: Waited a total of 17.105045 seconds for simulator to stabilize
2016-02-29 10:02:51 +0100 [RunLoop:debug]:
{
                        :app => "/Users/bdumgr/Desktop/BDMobilAutoTest/automated_tests/project/apps/MyApp.app",
                       :args => [
        [0] "-AppleLanguages,",
        [1] "(da)"
    ],
    :bundle_dir_or_bundle_id => "/Users/bdumgr/Desktop/BDMobilAutoTest/automated_tests/project/apps/MyApp.app",
                  :bundle_id => "dk.myapp.mobileapps.myapp.Cal",
                     :device => "iphone",
              :device_target => "simulator",
               :inject_dylib => "/Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/dylibs/libCalabashDynSim.dylib",
                :instruments => #<Instruments 7.2.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/Users/bdumgr/.run-loop/results/2016-02-29_10-02-21",
          :results_dir_trace => "/Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/trace",
                     :script => "/Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6s (9.2)",
               :uia_strategy => :preferences,
                      :xcode => "7.2.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on simulator App: /Users/bdumgr/Desktop/BDMobilAutoTest/automated_tests/project/apps/MyApp.app ###
EXEC: xcrun instruments -s devices
2016-02-29 10:02:58 +0100 [RunLoop:debug]: xcrun instruments -w FF4200D7-01E8-48E9-A0A4-336ED8B631DE -D /Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/trace -t Automation /Users/bdumgr/Desktop/BDMobilAutoTest/automated_tests/project/apps/MyApp.app -e UIARESULTSPATH /Users/bdumgr/.run-loop/results/2016-02-29_10-02-21 -e UIASCRIPT /Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/_run_loop.js -AppleLanguages, (da) >& /Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/run_loop.out
2016-02-29 10:02:58 +0100 [RunLoop:debug]: Preparation took 37.684927 seconds
2016-02-29 10:03:11 +0100 [RunLoop:debug]: Launching took 12.620304 seconds
DEBUG: Starting lldb injection with a timeout of 10 seconds
EXEC: xcrun lldb --no-lldbinit --source /Users/bdumgr/.run-loop/inject-dylib.lldb
DEBUG: lldb tried for 10.060951 seconds to inject calabash dylib before giving up.
DEBUG: Starting lldb injection with a timeout of 10 seconds
EXEC: xcrun lldb --no-lldbinit --source /Users/bdumgr/.run-loop/inject-dylib.lldb
DEBUG: lldb tried for 10.093675 seconds to inject calabash dylib before giving up.
DEBUG: Starting lldb injection with a timeout of 10 seconds
EXEC: xcrun lldb --no-lldbinit --source /Users/bdumgr/.run-loop/inject-dylib.lldb
DEBUG: lldb tried for 10.099709 seconds to inject calabash dylib before giving up.
RuntimeError: Could not inject dylib
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/run_loop-2.0.7/lib/run_loop/dylib_injector.rb:112:in `retriable_inject_dylib'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/run_loop-2.0.7/lib/run_loop/core.rb:381:in `run_with_options'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/run_loop-2.0.7/lib/run_loop.rb:122:in `run'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/lib/calabash-cucumber/launcher.rb:718:in `block in new_run_loop'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/lib/calabash-cucumber/launcher.rb:716:in `times'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/lib/calabash-cucumber/launcher.rb:716:in `new_run_loop'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/lib/calabash-cucumber/launcher.rb:584:in `relaunch'
  from /Users/bdumgr/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.18.1/lib/calabash-cucumber/core.rb:943:in `start_test_server_in_background'
  from (irb):1
  from /Users/bdumgr/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

The run_loop.out file contains this:
```
2016-02-29 10:03:34.502 instruments[3046:101201] Attempting to change event horizon while disengage
UT
2016-02-29 09:03:11 +0000 Default: <LOTS OF STARS>
2016-02-29 09:03:34 +0000 Fail: The target application appears to have died
Instruments Trace Complete (Duration : 32.976547s; Output : /Users/bdumgr/.run-loop/results/2016-02-29_10-02-21/trace.trace)
```

Any idea why it can't inject the pre-dylib?

**Comment by MortenGregersen** [comment]
I don't know if it matters, but the app is written in Swift.

**Comment by MortenGregersen** [comment]
I got it to work on another Mac.

I ran the command `screenshot` in the console and got the screenshots. They look exactly the same as the screenshot from my first post. Should I be running af different command?

**Comment by jmoody** [comment]
@MortenGregersen I hope that did not send you the wrong dylib.

> Should I be running a different command?

No.  `screenshot` is correct.

Would you mind checking:

```
$ xcrun strings libCalabashDynSim.dylib | grep -E 'CALABASH VERSION'

# After the app has launched and the dylib has been injected:
> server_version["version"]
```

Alternatively, could we set up a tmate session where we can try to resolve this issue together?  Or could you send the .app?

We can live chat on [Gitter](https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by MortenGregersen** [comment]
My bad. I had some troubles with my RubyGems and Ruby version so I switched between 2 versions and ended up running my test on the version where I hadn't replaced the dylibs.

It works fine now and the screenshots of `UIDatePicker` and  `UISegmentedControl` looks fine. The screenshots of the login screen with the ASCII keyboard is missing the keyboard. The built-in keyboard (ASCII) and my custom input view keyboard (for password entry) is missing from the screenshots with this dylib.

**Comment by MortenGregersen** [comment]
It looks like the keyboard is in a different window, and you can iterate through the windows and draw it to the context:
http://stackoverflow.com/questions/28169843/iphone-snapshot-including-keyboard

**Comment by jmoody** [comment]
> Swift?

Doesn't matter.

**Comment by MortenGregersen** [comment]
@jmoody It looks exactly as it should. **Approved!** :)

**Comment by jmoody** [comment]
Will be part of 0.18.2.
