### ISSUE TITLE
Feature request/Query: Support for Apple Watch

### ISSUE THREAD

**Issue by bhumikasrinivas** [calabash/calabash-ios#791]
Hi,

We recently built an Apple Watch app. We were looking for a way to write some sort of functional tests to check the features available on the watch app - like the Glance or the WatchKit app and possibly the integration between the WatchKit app and the mobile app. Is there any plan soon to help with some sort of support for Apple Watch apps or is there a way we can use the current version to automate this?

Thanks,
Bhumika

**Comment by jmoody** [comment]
Hi Bhumika,

We have not tried any automation on the Watch or Watch Simulator.

I am not sure that there is a way of interacting with watches with UIAutomation.

**Comment by Rakeshvallabhaneni** [comment]
@jmoody @bhumikasrinivas Any Update on this please 


Thanks In Advance ,
Rakeshkumar

**Comment by jmoody** [comment]
There is no UIAutomation API for WatchKit; at least we haven't found any.
