### ISSUE TITLE
Build server with debugging info

### ISSUE THREAD

**Issue by sapieneptus** [calabash/calabash-ios#792]
So that the binary .ipa can later be debugged, including the attached `calabash-ios-server`

**Comment by jmoody** [comment]
Are we talking about distributing dSYMs internally?  Making them public available?  Including more debugging symbols?

The libraries are built with the Debug configuration.

We don't strip debugging symbols.

==

![image](https://cloud.githubusercontent.com/assets/466104/8355251/68578498-1b4e-11e5-9f9a-498c728246bf.png)

==

One problem with distributing a .dSYM bundle is that we build two binaries:  one for arm and one for i386/x86_64 and combine them using `lipo`.  I don't know if this invalidate the .dSYMs.

**Comment by sapieneptus** [comment]
The use case is that, given an .ipa linked to calabash, we'd want to run the ipa on a device and be able to attach the debugger to the process to debug calabash-ios-server. I would think you'd need the .dSYM but I'm not 100% sure.

**Comment by jmoody** [comment]
OK.  So you've attached lldb the process and you want to step through the _server code_. I am not sure how we can do that, but I am willing to try to figure it out. :)

**Comment by jmoody** [comment]
If you know enough about the server code, you can set symbolic break points in lldb.

**Comment by sapieneptus** [comment]
If you build a debug app locally with calabash linked, install on your phone, launch from your phone (not xcode) you will be able to attach the xcode debugger to the process and step through the source. I am just unclear whether or not we can do that with the .ipa files that we get from XTC.

**Comment by jmoody** [comment]
> Attaching the Xcode debugger

Correct.  That is a neat trick.

> Attaching to debugserver on devices w/ just the .ipa

I have tried to do this with:

```
* idevicedebugserverproxy
* idevicedebug
```

with limit success.  The use case was different: I was trying to inject a dylib.  I did not try to step through a program.

**Comment by jmoody** [comment]
Moving this to issue calabash-ios-server.
