### ISSUE TITLE
Xcode 6.3/6.4 System AlertView auto accepted iOS8

### ISSUE THREAD

**Issue by RichardStoff** [calabash/calabash-ios#796]
**environment:**
* OSX: Yosemite 10.10.3 (14D136)
* Xcode path: /Applications/Xcode.app/Contents/Developer
* Xcode: 6.3.2 (6D2105)
* Calabash: 0.14.3
* Bundler: 1.10.5
* Ruby: 2.1.2p95
* iOS simulator : 8.1, 8.2, 8.3
* terminal using oh my zsh

Gemfile
```
source 'https://rubygems.org'

gem 'faker', '~> 1.4'
gem 'xcpretty', '~> 0.1'
gem 'pry', '~> 0.10'
gem 'briar', '~> 1.1'
gem 'calabash-cucumber', '~> 0.14'

# patch for cucumber and ruby 2.2.0
gem 'minitest'
```

server
```
{"app_version":"7.0.6",
"outcome":"SUCCESS",
"git":{"remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master","revision":"c2d009b"},
"app_id":"com.appName.www",
"simulator_device":"iPhone",
"app_base_sdk":"iphonesimulator8.3",
"version":"0.14 . 3",
"server_port":37265,
"app_name":"appName",
"iphone_app_emulated_on_ipad":false,
"form_factor":"iphone 4in",
"4inch":true,
"short_version_string":"7.0",
"screen_dimensions":{"scale":2,"width":640,"sample":1,"height":1136},
"iOS_version":"8.3",
" system":"x86_64",
"simulator":""}%

```

Page I used
```
require 'calabash-cucumber/ibase'

class GeolocPage < Calabash::IBase

  def accept_geoloc(allow)
    if uia_query(:alert).count > 0
      uia_tap_mark 'OK'
    end
  end
end
```

I use an application with System AlertViews such as Geloc, Notification, Contact, Photo. My bug is pretty simple, every times one of those Alert shows up, it will be automatically selected to YES (even in console mode). I can't check the uia_query when the pop-up show up because it accept it anyway. when I use .feature I even remove the accept_geoloc and it still accept it...

I tried using ruby 2.0.1 even new Xcode 6.4 every iOS8 simulator I can it still go on. Any suggestions ?

**Comment by jmoody** [comment]
Dismissing these privacy alerts is actually a feature of Calabash.

We are tracking this issue here: https://github.com/calabash/run_loop/issues/66

There is no way to disable this behavior.

**Comment by jmoody** [comment]
@RichardStoff Tracking in run-loop.
