### ISSUE TITLE
Unable to get SVProgressHUD

### ISSUE THREAD

**Issue by ec4Guogo** [calabash/calabash-ios#800]
There is a SVProgressHUD in my view.I got nothing when I run 'query("SVProgressHUD")'.What happened?

**Comment by jmoody** [comment]
Try:

query("view:'SVProgressHUD'")

I have no idea what a SVProgressHUD view is.

It is possible that is appearing in a window other than the main
application window or that it is not passing the visibility heuristics.

Try:

query("all ...")

**Comment by ec4Guogo** [comment]
I tried and still got nothing.
Yeah! I have two windows in my application.And the `SVProgressHUD` view is in a window in front of the main application window.

**Comment by jmoody** [comment]
Try `uia_query_windows`

http://calabashapi.xamarin.com/ios/Calabash/Cucumber/UIA.html#uia_query_windows-instance_method

**Comment by if1else0** [comment]
I tried this way：uia_query_windows :view, {marked:'textabc'}
But, it still can not work. Is there any available way to query a text which is in front of the main application window.

**Comment by jmoody** [comment]
Can you share a screenshot?

**Comment by if1else0** [comment]
![img_0056](https://cloud.githubusercontent.com/assets/10397913/8718329/46155fe8-2bd6-11e5-9a93-129b1c165461.PNG)

**Comment by jmoody** [comment]
See if you can find this using the UIA JavaScript API.

```
> uia("UIATarget.localTarget().frontMostApp().windows()")
```
 
https://developer.apple.com/library/ios/documentation/DeveloperTools/Reference/UIAutomationRef/

**Comment by if1else0** [comment]
What does this result mean?
![b](https://cloud.githubusercontent.com/assets/10397913/8720668/ba9b2522-2be6-11e5-871c-a3faf24b4f87.png)

**Comment by if1else0** [comment]
Does it mean, there are 4 windows? And what is the meaning of "'index' => 2"? Thanks.

**Comment by jmoody** [comment]
> Does it mean there are 4 windows?

Yes.

```
# This will show you the elements of the first window.
> uia("UIATarget.localTarget().frontMostApp().windows()[0].elements()")
```

> And what is the meaning of "'index' => 2"?

It is a book keeping value for calabash.  It should be ignored. It has nothing to do with the results of the query.

**Comment by jmoody** [comment]
Closing for lack of response.
