### ISSUE TITLE
Can I specify the scheme?

### ISSUE THREAD

**Issue by onmyway133** [calabash/calabash-ios#803]
I note that the scheme must end with `-cal`, can it be optional ? What if I have multiple schemes?

**Comment by jmoody** [comment]
Do you mean Xcode Scheme?  You can call the Xcode Scheme whatever you like.

You can also call the Calabash _Target_ anything you like.

**Comment by onmyway133** [comment]
@jmoody thanks, what option should I feed into `cucumber` command for it to choose `MyApp-calabash` scheme  instead of `MyApp-cal` scheme ?

**Comment by jmoody** [comment]
@onmyway133 

Ah, for the auto-detection of your .app bundle?

I believe you don't need to do anything differently - Calabash will probably be able to find your .app.

I don't use this feature.  I use scripts to build my .app and _always_ use the `APP` variable.

```
$ make app-cal
$ APP=./My-cal.app be cucumber 
```

You can see examples of how to use build scripts in this repo:

https://github.com/calabash/ios-smoke-test-app
