### ISSUE TITLE
Cannot check label with apostrophe in text

### ISSUE THREAD

**Issue by petergerdes** [calabash/calabash-ios#805]
In Cucumber the following test will always fail:
`Then I should see "Passwords don't match".`

It cannot escape the character correctly? Also if I escape myself does not work: 
`Then I should see "Passwords don\\'t match".`

If I check with calabash-console and list all the labels, the label with text "Then I should see "Passwords don't match" is there.

Specifications:
* OS X 10.10.4
* Ruby 2.0.0p481
* XCode 6.4
* calabash-cucumber-0.14.3

**Comment by jmoody** [comment]
Can I see your step definition?

If you are using the predefined step:

```
Then /^I should see "([^\"]*)"$/ do |expected_mark|
  until element_exists("view marked:'#{expected_mark}'") ||
        element_exists("view text:'#{expected_mark}'")
    screenshot_and_raise "No element found with mark or text: #{expected_mark}"
  end
end
```

you will fail because the `'` is not properly escaped in the query.

Write your own Step and use the `escape_string` method around the text you are trying to match.

http://calabashapi.xamarin.com/ios/Calabash/Cucumber/QueryHelpers.html#escape_string-instance_method

**Comment by petergerdes** [comment]
Ah, yeah, then it works! Now made my own step:

`Then /^I should see escaped "([^\"]*)"$/ do |expected_mark|
	expected_mark = escape_string(expected_mark)
  until element_exists("view marked:'#{expected_mark}'") ||
        element_exists("view text:'#{expected_mark}'")
    screenshot_and_raise "No element found with mark or text: #{expected_mark}"
  end
end`

Thanks! But can this not be default?

**Comment by jmoody** [comment]
> Thanks! But can this not be default?

The predefined steps get no love.  They exist to serve as examples.  We recommend that you not use them and write your own steps.

If you mean: "All strings should be escaped", then the answer is probably not.  There are some confusing edge cases that we just cannot handle.
