### ISSUE TITLE
iOS 9 beta simulator: touching any element hangs

### ISSUE THREAD

**Issue by dslysenko** [calabash/calabash-ios#810]
(As iOS 9 is still beta software, feel free to close this issue if it is determined to be an issue from Apple's side or not worth the effort to fix right now.)

When I run my test suite or a console on the iOS 9 beta simulator, execution hangs on `instruments` whenever I try to touch any element.

If I force kill the test suite execution, the stack trace is something like the following:

```Exiting... Interrupt again to exit immediately.
    When I press "Sign Up"                                              # calabash-cucumber-0.14.0/features/step_definitions/calabash_steps.rb:14```
```Could not parse response ''; the app has probably crashed (RuntimeError)```

The command `touch "view marked:'Sign Up'"` in the console freezes execution, even when `query "view marked:'Sign Up'"` returns 2 elements.

**Comment by dslysenko** [comment]
Server and gem versions are both 0.14.3.

**Comment by dslysenko** [comment]
App logs fill in with hundreds of lines of this:

```
2015-07-29 11:35:33.656 Riff[13974:9048180] Current request: {
    command = "uia.tapOffset('{:x 160, :y 424}')";
    index = 0;
}
2015-07-29 11:35:33.760 Riff[13974:9048180] Current request: {
    command = "uia.tapOffset('{:x 160, :y 424}')";
    index = 0;
}
2015-07-29 11:35:33.865 Riff[13974:9048180] Current request: {
    command = "uia.tapOffset('{:x 160, :y 424}')";
    index = 0;
}
2015-07-29 11:35:33.966 Riff[13974:9048180] Current request: {
    command = "uia.tapOffset('{:x 160, :y 424}')";
    index = 0;
}
2015-07-29 11:35:34.067 Riff[13974:9048180] Current request: {
    command = "uia.tapOffset('{:x 160, :y 424}')";
    index = 0;
}```

**Comment by jmoody** [comment]
@dslysenko It was not until October last year that instruments stabilized against iOS Simulators.  We've had some success on iOS 9 beta 4 devices.

If you don't mind, I'd rather close this issue.  We can't make any real progress until Apple delivers a stable product.

**Comment by dslysenko** [comment]
Fair enough, Joshua!
