### ISSUE TITLE
touch could not find view: 'textField marked:.

### ISSUE THREAD

**Issue by alpersilistre** [calabash/calabash-ios#812]
Feature: Login validation
      Login must be successful

    Scenario: Login is successful
      Given I am on the Login Screen
      Then I enter "person@abc.com" into the "emailField" input field
      Then I enter "password" into the "passwordField" input field
      Then I touch the "loginButton" button

This is my test script for my xamarin ios project. I follow [this link](http://developer.xamarin.com/recipes/testcloud/set-accessibilityidentifier-ios/) and add Accessibility Identifier with Xcode Interface Builder. But I still cant reach fields or button. It gives me this error.

    Given I am on the Login Screen                                  # features/step_definitions/my_first_steps.rb:1
    Then I enter "person@abc.com" into input field number 1 # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:125
    Then I enter "password" into the "passwordField" input field    # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:100
      touch could not find view: 'textField marked: 'passwordField'', args: {:query=>"textField marked: 'passwordField'"} (RuntimeError)
      features/my_first.feature:7:in `Then I enter "password" into the "passwordField" input field'
    Then I touch the "loginButton" button                           # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:30

    Failing Scenarios:
    cucumber features/my_first.feature:4 # Scenario: Login is successful

    1 scenario (1 failed)
    4 steps (1 failed, 1 skipped, 2 passed)
--
    xcode-select --print-path
    /Applications/Xcode.app/Contents/Developer
    xcodebuild -version
    Xcode 6.4
    Build version 6E35b
    calabash-ios version
    0.14.3

I tried to rebuild, reinstall project on ios simulator but I still can't solve. Thank you.

**Comment by jmoody** [comment]
@alpersilistre 

What is the exact cucumber command you are running?  In particular, how are specifying the APP?  I am thinking that you may have set the identifier correctly, but you are not running against the app you think you are running against.

Can you open a console and try to query for the text field?  Try this and paste the result into this case.


```
$ APP=/path/to/your/app bundle exec calabash-ios console
> start_test_server_in_background
> query("textField index:1")  # Not sure what index the password field is.
```

You are looking for the 'id' key/value pair.

It might also be that you have built the app (from Xamarin Studio, I am assuming), but the app installed on the simulator is stale (from a previous build).  Starting in Xcode 6, instruments stopped installing newer versions of apps.

You can do the following to ensure the app on the simulator is the one you are expecting:

```
1. Build from Xamarin Studio
2. $ bundle exec run-loop simctl install --app /path/to/your/new.app --debug
3. $ APP=/path/to/your/new.app bundle exec calabash-ios console
4. > start_test_server_in_background
5. > query("textField index:1")
```

**Comment by alpersilistre** [comment]
Hi @jmoody

This is very interesting this is the output when I run bundle exec... 

    bundle exec calabash-ios console
    Could not locate Gemfile or .bundle/ directory

without bundle exec, this is the output;

    rb(main):002:0> query("textField index:1")
    [
        [0] {
                          "id" => nil,
                    "selected" => false,
                     "visible" => 1,
                       "label" => nil,
                       "frame" => {
                 "y" => 64,
             "width" => 205,
                 "x" => 200,
            "height" => 35
            },
                     "enabled" => true,
                 "description" => "<UITextField: 0x7be0cbc0; frame = (200 64; 205 35); text = '';      clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray:  0x80b90030>; layer = <CALayer: 0x7be0d020>>",
                        "text" => "",
                       "alpha" => 1,
                       "value" => "",
        "accessibilityElement" => false,
                        "rect" => {
            "center_x" => 346.5,
                   "y" => 145,
               "width" => 205,
                   "x" => 244,
            "center_y" => 162.5,
              "height" => 35
        },
                       "class" => "UITextField"
    }
    ]

id looks like nil. I am %100 sure I add identifier. Yes this project in Xamarin Studio. And it gives same error after the 5 steps you define;

    Could not locate Gemfile or .bundle/ directory    

Looks like I am missing something. Thank you for your help.

**Comment by jmoody** [comment]
You should be using a Gemfile and bundler.  You can find sample Gemfiles in the calabash GitHub organization projects.

If you prefer not use a Gemfile and bundler, just remove the 'bundle exec' from the commands.

**Comment by alpersilistre** [comment]
Thanks for comment. I am adding accessibility identifiers directly on code and it work fine. But I cant use if I add it on Xcode like Xamarin Documentation said. Anyway thank you for your help.

**Comment by jmoody** [comment]
@alpersilistre Can you file a bug or post something to the Xamarin forum?

Since you are a Xamarin customer, I am escalating this internally.

**Comment by alpersilistre** [comment]
I will post it on Xamarin Forum when I have time. Thank you for your concern.

**Comment by jmoody** [comment]
@alpersilistre I hope you got some help.  Closing because this appears to be Xamarin app issue.
