### ISSUE TITLE
iOS 8 - Touch is not working in console - Calabash-ios version 0.12.2

### ISSUE THREAD

**Issue by bkarthick** [calabash/calabash-ios#816]
**Environment**

1. Calabash version  - 0.12.2 

2. Xcode 6.4
-Build version 6E35b

3. Device - IPod OS 8.4.1

**Steps to reproduce:**

1. Build app to iPod (8.4 Physical device)
2. Launch calabash-ios console
3. Execute: touch(query('UIImageView')[7])

**Console trace:**

RuntimeError: uia action failed because: Timed out running command uia.tapOffset('{:x 23, :y 42}')

	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/uia.rb:37:in `uia'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/uia.rb:454:in `uia_handle_command'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/uia.rb:201:in `uia_tap_offset'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/actions/instruments_actions.rb:101:in `query_action'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/actions/instruments_actions.rb:15:in `touch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/core.rb:1132:in `query_action_with_options'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.2/lib/calabash-cucumber/core.rb:177:in `touch'
	from (irb):15
	from /usr/bin/irb:12:in `<main>'

**Comment by jmoody** [comment]
Gestures are only available if you launch the app with instruments.

```
> start_app_in_background
> touch("UIImageView index:7")
```

This syntax:

```
touch(query("UIImageView")[7])
```

is not officially supported.

**Comment by bkarthick** [comment]
I have tried touch("UIImageView index:7") but still touch is not working in console

**Comment by jmoody** [comment]
Please update to most recent version.

* https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version

Can you confirm that you are first calling `start_test_server_in_background` before you try to touch.

**Comment by jmoody** [comment]
Reopen if you still have the problem with the most recent version of Calabash iOS.
