### ISSUE TITLE
iOS 9 Simulator/Real Device - Touch is not working in console

### ISSUE THREAD

**Issue by agileseph** [calabash/calabash-ios#817]
What I try?
0) install xcode 7 beta (choose the appropriated version of Xcode: "sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer" )
1) compile app for iOS9/iOS8/iOS7 for Simulator/Real device
2) install app to iOS Simulator/real device with iOS 9
3) patch the hardcoded path to Simulator.app inside bridge.rb and other files (run_loop gem) from <"#{dev_dir}/Applications/iOS Simulator.app"> to <"#{dev_dir}/Applications/Simulator.app"> 
4) run calabash console for simulator/real device, as usual
5) run command: "start_test_server_in_background" - It's OK
6) run command: "query("*")" - It's OK
7) run command: "touch("ANY USUAL LOCATOR")" - it is stucking on performance of the command and then throws Exception after 2 min timeout: 
```
"RuntimeError: uia action failed because: Timed out running command uia.tapOffset('{:x 160.25, :y 527.5}')

	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:37:in `uia'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:454:in `uia_handle_command'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/uia.rb:201:in `uia_tap_offset'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/actions/instruments_actions.rb:94:in `query_action'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/actions/instruments_actions.rb:15:in `touch'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:1166:in `query_action_with_options'
	from /Users/User/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:177:in `touch'"
```

**Comment by jmoody** [comment]
Thanks for the report.

We are not supporting iOS 9 on simulators yet.

**Comment by vpalivela** [comment]
Thanks for the response Joshua. Any idea on whether this will be in 2.0 release or the 0.x release?

**Comment by agileseph** [comment]
I have patched the calabash-cucumber 0.14.3 (added ability to set up DEVICE_TARGET with simulator hash) and run_loop 1.4.1 gem (fixed some regexps and device select function for iOS 9) in forked repo:
1) https://github.com/agileseph/calabash-ios/tree/ios9_support
2) https://github.com/agileseph/run_loop/tree/ios9_support

I have to patched the DEVICE_TARGET with simulator names for iOS9 too. Now it works like a charm with DEVICE_TARGET='HASH Simulator' and IOS_SDK=iphonesimulator9.0 options. IOS_SDK=iphonesimulator9.0 is required because we should have ability recognize that we running tests on simulator in case we defined DEVICE_TARGET via simulator hash.

My cucumber config run: 
```
cucumber -p ios_your_default_profile -f pretty --color -t @your_tests DEVICE_TARGET=639C11F0-2796-4C96-A4F8-4B53D8B0DB4C BUNDLE_ID=build/sources/ios_src/build/Applications/YOUR_APP.app/ IOS_SDK=iphonesimulator9.0
```

**Comment by jmoody** [comment]
@agileseph 

I have begun updating run-loop for Xcode 7.

@vpalivela 

Both 0.x and 2.0 will be supported.

**Comment by jmoody** [comment]
@agileseph :+1:

**Comment by SherJJK** [comment]
I am facing the same touch issue for iOS 9 device.

**Comment by jmoody** [comment]
@SherJJK We need more details.

* https://github.com/calabash/calabash-ios/wiki#reporting-problems
* https://github.com/calabash/calabash-ios/wiki#examples-of-good-bug-reports
