### ISSUE TITLE
Errno::ECONNREFUSED: Connection refused - connect(2) while running the start_test_server_in_background in Terminal Using real device.

### ISSUE THREAD

**Issue by Rakeshvallabhaneni** [calabash/calabash-ios#818]
Hi,

Completed calabash -set up manually 

using Xcode 6.3 and Real device iPhone iOS 8.3 

Below is the console after build and run the application in iPhone 6 8.3iOS physical device 

Creating the server: <LPHTTPServer: 0x1469c020>
Calabash iOS server version: CALABASH VERSION: 0.14.3
App Base SDK: iphoneos8.3
simroot: (null)
 Started LPHTTP server on port 37265
Bonjour Service Published: domain(local.) type(_http._tcp.) name(Calabash Server)
WKWebView successfully implemented LPWebViewProtocol
 registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

Now I launched the Terminal 

DEVICE_ENDPOINT=http://localhost:37265/ BUNDLE_ID=com.//.//  calabash-ios console
start_test_server_in_background 

Here application launches in the device successfully .

Errno::ECONNREFUSED: Connection refused - connect(2)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:815:in `ping_app'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:788:in `block in ensure_connectivity'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:785:in `ensure_connectivity'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:642:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:883:in `start_test_server_in_background'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'

Please Help me out for the issue 

Note: able to run in simulators but initially even simulator works like it appears and disappears continuously

Thanks,
Rakesh

**Comment by jmoody** [comment]
@Rakeshvallabhaneni 

Please use markdown formatting.

* https://github.com/calabash/calabash-ios/wiki#reporting-problems

The problem is that you are not setting the `DEVICE_ENDPOINT` correctly.  For physical devices, the endpoint _must be your device's IP address_.

* http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-DEVICE_ENDPOINT
