### ISSUE TITLE
Problems with cucumber 1.3.20

### ISSUE THREAD

**Issue by kmiloaguilar** [calabash/calabash-ios#822]
This morning I was installing calabash-cucumber and I had this problem

     ERROR:  Error installing calabash-cucumber:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Library/Ruby/Gems/2.0.0/cache/cucumber-1.3.20.gem

So what I did is install cucumber 1.3.17 first and then install this calabash-cucumber

**Comment by jmoody** [comment]
This is a problem with your gem environment and not with Calabash.

We recommend that you use a managed ruby environment (like rbenv or rvm) and a Gemfile with bundler.

https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS

I am going to close this because it is not a problem with Calabash.
