### ISSUE TITLE
Calabash Server start

### ISSUE THREAD

**Issue by bjsully6** [calabash/calabash-ios#83]
I am trying to setup calabash to run tests from Team City.  Calabash is working fine from the command line inside of my xcode workspace using the -cal target.  I runs the tests and works just fine.  That code base is checked into an svn repository.  I setup a command line xcodebuild and cucumber commands to run a build and test from Team City.  The build looks good but the Calabash Server does not start so it pings http://localhost:37265 until it times out.  

I cannot seem to figure out why the server won't start. The other link flag has the force load to pull in the framework.  Is there a command line way to start it since the simulator does not seem to be starting it?  Can you think of something else I might have missed?

xcodebuild -target MobileShopper-cal -sdk iphonesimulator -arch i386 -configuration Release clean build

APP_BUNDLE_PATH='./build/Release-iphonesimulator/MobileShopper-cal.app' OS=ios6 cucumber

Thanks,
Brian

**Comment by RunningYoung** [comment]
$: DEVICE=iphone OS=ios8 NO_LAUNCH=1 DEVICE_TARGET="5B3B6A8B-370C-48E9-A1BC-F138629853FA" cucumber
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Failing... Errno::ECONNREFUSED
    Then I swipe left                                # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:222
      Connection refused - connect(2) (localhost:37265) (Errno::ECONNREFUSED)
      features/my_first.feature:8:in `Then I swipe left'
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:217

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (1 failed, 2 skipped, 1 passed)
0m1.035s

**Comment by jmoody** [comment]
@RunningYoung 

This issue is closed.  Please open a new issue and use GitHub markdown when reporting.

With that said, the command you are using to launch is outdated.

> DEVICE=iphone

This variable is deprecated.

> OS=ios8 

This variable is deprecated.

> NO_LAUNCH=1

This variable is deprecated

Try:

```
DEVICE_TARGET="5B3B6A8B-370C-48E9-A1BC-F138629853FA" cucumber
```

You can find the documentation for environment variables here:

http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html

**Comment by RunningYoung** [comment]
@jmoody 
I'm sorry ,but I still have some questions to ask，
I will open a new issue
