### ISSUE TITLE
App Not getting installed in the Physical Device because of Run Loop error

### ISSUE THREAD

**Issue by vigneshbumpy** [calabash/calabash-ios#833]
Environment Details

1. Xcode Version - 7 beta 6
2. Iphone Version - 8.4
3. Run loop version - 1.5.1

When i try to run the start_test_server_in_background, the following run loop error is displayed

[RunLoop:debug]: Preparation took 0.966898 seconds
2015-09-11 11:38:29 +0530 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-09-11 11:38:29 +0530 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError

i have already Enabled the "Enable UI Automation" in the device, any other solution?

**Comment by jmoody** [comment]
@vigneshbumpy 

There is an entire Hot Topic for this issue.

https://github.com/calabash/calabash-ios/wiki/Hot-Topics#7-errnoeintr-interrupted-system-call

With that said, we haven't released Xcode 7 support yet.

Xcode 7 GM has been released.  You should update your Xcode version.

**Comment by vigneshbumpy** [comment]
@jmoody I already had a look at the Hot-Topics but i dont have solution for my issue there, can you let me know what exactly to do for the above error?

**Comment by jmoody** [comment]
Beyond the Hot Topic for this issue, I have no other suggestions other than to:

* Update Xcode 7 GM
* Wait for iOS 9  to be released.
