### ISSUE TITLE
Can not find release 0.15.0 via cocoapods.

### ISSUE THREAD

**Issue by tarbrain** [calabash/calabash-ios#834]
Hi folks,

I have tried to install calabash-ios 0.15.0 via cocoa pods but it is not available.

Can you give me an update when version 0.15.0 will be available as a pod?

Thanks
tarbrain

**Comment by jmoody** [comment]
Hi @tarbrain We don't control the CocoaPods spec.

Please ask on the [forum](https://groups.google.com/forum/?fromgroups#!forum/calabash-ios).
