### ISSUE TITLE
Calabash CocoaPods 

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-ios#842]
Hi, not sure if it right place for that question. Do we update calabash pod manually? On page http://cocoapods.org/pods/Calabash only 0.14.3 version available but on Github we have 0.15.0 already.

**Comment by jmoody** [comment]
**Can not find release 0.15.0 via cocoapods.** #834

We don't control the CocoaPods spec.

Please ask on the [forum](https://groups.google.com/forum/?fromgroups#!forum/calabash-ios).
