### ISSUE TITLE
Cannot run tests with Calabash 0.14.3 and run_loop 1.5.2 

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-ios#843]
Hi, due to project specifics we should use calabash 0.14.3 and it work good with run_loop 1.5.1 but after run_loop update to 1.5.2 version i cannot run tests:

```
WARN: deprecated '1.5.0' - 
RunLoop::XCTools has been replaced with RunLoop::Xcode.
Please update your sources to pass an instance of RunLoop::Xcode
/Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.2/lib/run_loop/core.rb:483:in `default_simulator'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:277:in `reset_app_sandbox'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:593:in `relaunch'
/Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:87:in `launch_app'
/Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:33:in `block in <top (required)>'
 undefined method `version_gte_71?' for #<RunLoop::XCTools:0x007ff695012640> (NoMethodError)
 /Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.1/lib/rspec/matchers.rb:926:in `method_missing'
 /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.2/lib/run_loop/core.rb:489:in `default_simulator'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:277:in `reset_app_sandbox'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:593:in `relaunch'
 /Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:87:in `launch_app'
 /Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:33:in `Before'
```

maybe we should add comments that 1.5.2 not supported by 0.14.3?

**Comment by jmoody** [comment]
Ugh.  Yeah, I see the problem.

I deprecated RunLoop::XCTools and then did not implement a `version_gte_71?` in XCTools.

The work around until I can get a patch out is add this to your `01_launch.rb`

```
require 'run_loop'
module RunLoop
   class XCTools
      def version_gte_71?
         xcode.version_gte_71?
      end
   end
end
```

```

**Comment by jmoody** [comment]
@ark-konopacki Thanks for reporting so quickly!

Calabash 0.16.1 will be out shortly.

**Comment by ark-konopacki** [comment]
Calabash 0.14.3 with run_loop 1.5.3 runs without any issues 
only warn about depreciated methods:
WARN: deprecated '1.5.0' - Replaced by RunLoop::Xcode
/Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.3/lib/run_loop/sim_control.rb:21:in `xctools'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:277:in `reset_app_sandbox'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:593:in `relaunch'
/Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:87:in `launch_app'
/Users/akn/repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:33:in `block in <top (required)>'

Thanks for quick fix. That issue can be closed
