### ISSUE TITLE
Calabash Ios Runloop debug :Instruments failed to launch app: 'FBSOpenApplicationErrorDOmain error 8 

### ISSUE THREAD

**Issue by pfisher3** [calabash/calabash-ios#844]
Hello, Ive been getting Failed to launch error on usng calabash ios. 
When running:
> bundle exec calabash-ios sim reset
DEBUG=1
cucumber --tags '~@wip' --tags '~@manual'

The error is displayed against my 1st test scenario
 Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8: Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8  

Here is a more detailed error output:
I receive the following error
 *** Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8 ***
�[0m
2015-09-08 19:36:27 -0400 [RunLoop:debug]: Preparation took 1.434106 seconds
2015-09-08 19:36:42 -0400 [RunLoop:debug]: Failed to launch. Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8: Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8
2015-09-08 19:36:44 -0400 [RunLoop:debug]: Simulator instruction set 'x86_64' is compatible with ["i386", "x86_64"]
Updating device state attempt 1 failed in '0.089666'; will retry in '0.1'
Updating device state attempt 2 failed in '0.263689'; will retry in '0.1'
Updating device state attempt 3 failed in '0.440139'; will retry in '0.1'
Updating device state attempt 4 failed in '0.615082'; will retry in '0.1'
Updating device state attempt 5 failed in '0.785775'; will retry in '0.1'
Updating device state attempt 6 failed in '0.9552'; will retry in '0.1'
Waited for 0.139497 seconds for 'iOS Simulator' to start.
Waited for 0.401445 seconds for 'SimulatorBridge' to start.
2015-09-08 19:36:47 -0400 [RunLoop:debug]: 
{
:app => "/Users/jenkinsmacmini/Library/Developer/Xcode/DerivedData/ToysRUs-exsivqtmrahowueohymunroqghvx/Build/Products/calabash-iphonesimulator/project.app",
:args => [],
:bundle_dir_or_bundle_id => "/Users/jenkinsmacmini/Library/Developer/Xcode/DerivedData/ToysRUs-exsivqtmrahowueohymunroqghvx/Build/Products/calabash-iphonesimulator/project.app",
:bundle_id => "com.project.project",
:device => "iphone",
:device_target => "iPhone 6 (8.3 Simulator)",
:launch_method => :instruments,
:launch_retries => 5,
:log_file => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/run_loop.out",
:no_launch => false,
:no_stop => true,
:relaunch_simulator => true,
:reset => false,
:results_dir => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0",
:results_dir_trace => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/trace",
:script => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/_run_loop.js",
:sdk_version => nil,
:timeout => 500,
:udid => "iPhone 6 (8.3 Simulator)",
:uia_strategy => :preferences,
:xcode => "6.3",
:xcode_path => "/Applications/Xcode.app/Contents/Developer"

Current Build settings being sent:
-workspace project.xcworkspace -scheme project-calabash -sdk iphonesimulator8.3 'ARCHS=i386 x86_64' 'VALID_ARCHS=i386 x86_64' ONLY_ACTIVE_ARCH=NO clean build

Current Debugging Ive attempted,
> - reset_content_and_settings in launch.rb after each scenario
> - changing the Simulator from 8.4 to 8.3 and 8.2, currently at 8.3
> - adding reset launch tags to the failing scenario, which is usually the 1st
> - setting timeout to 500, as launch can take a while

Thanks in advance.

**Comment by jmoody** [comment]
Please update to Calabash 0.16.1.  If that is not possible, update to 
run-loop 1.5.3.

jjm

**Comment by pfisher3** [comment]
@jmoody 
That seems to have fixed the issue for me, will continue to monitor.

Thanks
