### ISSUE TITLE
Launch the app with specific variable

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash-ios#846]
Hello,
I'm trying to launch test on ios app with calabash but I want to launch the app with a specific variable instead of build it everytime I want to change it (because it's "hardcoded" in the app).
As example, I have in my app code : initVariable:@"12345"

Can I make a command like : cucumber initVariable:@"56789" to launch the app with this value ?
Thanks a lot !

**Comment by jmoody** [comment]
https://github.com/calabash/run_loop/issues/178

**Comment by ericzered** [comment]
Thanks ! I was looking for this !
