### ISSUE TITLE
Install on device w/ Xcode 7 fails due to lack of bitcode

### ISSUE THREAD

**Issue by michaelkirk** [calabash/calabash-ios#863]
I recently updated to Xcode 7. I can compile my app to simulator targets, but the build fails when I try to build and install on my personal device with:

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

More output:
```
ld: '<snip>/calabash.framework/calabash(GCDAsyncSocket.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Running `calabash-ios download` download and installs the same version (0.14.3)

I'm using Xcode Version 7.0 (7A220)

**Comment by michaelkirk** [comment]
I believe the workaround is to disable bitcode for my target until my installed calabash includes the corresponding bitcode.

To disable bitcode for your project, go to your projects build settings and change "Enable Bitcode" to "NO". More details here: http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

Allegedly apple will make this a requirement at some point, but it might be years.

**Comment by jmoody** [comment]
@michaelkirk 

Hey Michael!

Xcode 7 / iOS 9 requires an update to Calabash iOS 0.16.3.

https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version#updating-calabash-ios

**Comment by agnesmary90** [comment]
When a bitcode app is submitted to the App Store, Apple with take on this final step and create ... This means the app installed on iOS devices will be smaller. ......http://www.trainingintambaram.in/salesforce-training-in-chennai.html

**Comment by jmoody** [comment]
@agnesmary90 Your comment looks like spam and is not relevant to this discussion.  I am going to delete it.
