### ISSUE TITLE
uia("target.shake()") is not working on iOS9 devices

### ISSUE THREAD

**Issue by mansis15** [calabash/calabash-ios#873]
uia("target.shake()") is working fine on iOS devices with version < 9 but same doesn't work on iOS9 devices.
Please help.
Thanks

**Comment by jmoody** [comment]
If UIAutomation shake is broken, it is because Apple broke it.  Have you filed a radar?

https://bugreport.apple.com

**Comment by mansis15** [comment]
Thanks Joshua.. can you please suggest if there is any other way to achieve shake gesture on iOS9 devices.

**Comment by jmoody** [comment]
@mansis15 No.  You could have a look at this server route and see if you can make a  shake route that works on iOS 9.

https://github.com/calabash/calabash-ios-server/pull/261

**Comment by tommeier** [comment]
Apple have broken/removed this, unsure which, but you can see via the Automation instruments that the 'shake' gesture can no longer be recorded, same applies to rotation. Not sure how this is meant to be replicated now.

**Comment by tommeier** [comment]
(I filed radar://22796974)

**Comment by tommeier** [comment]
FYI, I work around this issue for now, as there are several stripped items from UIAutomation on iOS9+ devices, via the calabash backdoor commands and trigger the 'shake' or unmapped gestures manually that way (https://github.com/calabash/calabash-ios/wiki/Calabash-iOS-Ruby-API#backdoor).

Hope that helps

**Comment by jmoody** [comment]
@tommeier Thanks for filing the radar!  Woot!  You made my day.

Would you be interested in sharing your shake backdoor and/or the unmapped gestures?

Or maybe submitting a pull request on the server for a new shake route?

You can see how I implemented deactivate here:

**Add 'suspend' route to suspend and resume app** [#261](https://github.com/calabash/calabash-ios-server/pull/261)

**Comment by tommeier** [comment]
@jmoody no problem at all :) did it a while ago. The backdoor to get around the missing shake is pretty simple: https://gist.github.com/tommeier/ff0fc26642c17e26604a , for my own use it was to trigger the private Facebook Tweaks menu 'shake to open' so in this backdoor i've triggered all of that. I've removed that from the gist for clarity.

Not sure how we'd actually trigger the shake, I'll need to play around with suggestions like (http://stackoverflow.com/questions/24433763/programmatically-trigger-shake-event-ios) to see if its possible before making a PR on the server shake route. Thanks for all the hard work!

**Comment by mansis15** [comment]
@tommeier Thanks for reply. I need help as i am new to this tool. The changes you mentioned related to backdoor seems to be done at application code level or calabash code? I dont have permissions to do any change in the application code. Please suggest..

**Comment by tommeier** [comment]
@mansis15 yes, app code only run on the calabash target, to get the utility of that one ruby line I'm afraid . If you have no access to the application code, then it will need to be added to the server as @jmoody is suggesting as a new route to workaround this missing feature on UIAutomation.

**Comment by mansis15** [comment]
@jmoody : I tried your solution to suspend and resume app and it was working fine. Thanks for the solution. Can you also provide the same solution for shake gesture.
@jmoody and @tommeier : Thanks for all your support provided..

**Comment by jmoody** [comment]
@mansis15 

>  Can you also provide the same solution for shake gesture.

I am actually asking if someone else can make the fix.  I am extremely busy putting out other fires.

**Comment by tommeier** [comment]
:fire: :fire_engine: :)

@jmoody I've been trying to work out the obj-c way to trigger it, as my workaround is to trigger the resulting action of the shake, not the shake itself. First step is a manual trigger but UIKit has changed quite a bit under the hood since past people have attempts with UIMotionEvent's. Will keep trying to work it out.

**Comment by tommeier** [comment]
@mansis15 with no access to the code, another workaround is to test on iOS8.4 devices for now, that has no issues with the original shake gesture.

**Comment by tommeier** [comment]
@jmoody success, I was trying to overthink it, simulator (haven't tested on device yet) can trigger a shake via 

```
  UIEvent *m = [[UIEvent alloc] init];
  [[UIApplication sharedApplication] sendEvent:m];
  [[[UIApplication sharedApplication] keyWindow] motionBegan:UIEventSubtypeMotionShake withEvent:m];
  [[[UIApplication sharedApplication] keyWindow] motionEnded:UIEventSubtypeMotionShake withEvent:m];
```

I'll look at creating the necessary changes to calabash server after I plough through my work, have a few of my own iOS 9.1 related :fire: 's to sort.

**Comment by mansis15** [comment]
Thanks @tommeier, i would really appreciate if you can take out some time to resolve this one as well :)
Thanks!!
