### ISSUE TITLE
Swift 2.0 Xcode UI Testing framework and Calabash?

### ISSUE THREAD

**Issue by dnadan** [calabash/calabash-ios#876]
Hello @jmoody!

Have you guys thought of leveraging the new Xcode UI Testing (instead of UIA) with the introductions and improvements to the native automated UI testing in Swift 2.0?  Plugging in XCUIApplication, XCUIElement and XCUIElementQuery into the Calabash core?  I've tried out the XC7 recording tool and the testing playback is super fast.  It also seems to be able to hook into the app's idle state.

Thanks for all the work you've done, I'm a big Calabash user and fan.

**Comment by kosta-tachtevrenidis** [comment]
+1

**Comment by jmoody** [comment]
We are investigating.  UIAutomation is on the ropes, that much is clear. 

I am going to close this issue because it is a question and not a feature request or bug report.
