### ISSUE TITLE
NoMethodError: undefined method `touch' for nil:NilClass

### ISSUE THREAD

**Issue by jfrndz** [calabash/calabash-ios#877]
I get this error each time I `touch` a view from the console. Calling `touch` from cucumber works as expected. Other methods (`query`, `scroll`, `flash`) work as expected in both places. This happens from the simulator and an iPhone 5c running 8.3; here's some console output:
```
irb(main):019:0> query("view:'UITextField'")
[
    [0] {
                          "id" => nil,
                    "selected" => false,
                     "visible" => 1,
                       "label" => "",
                       "frame" => {
                 "y" => 71,
             "width" => 280,
                 "x" => 20,
            "height" => 40
        },
                     "enabled" => true,
                 "description" => "<UITextField: 0x18141960; frame = (20 71; 280 40); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x180cf040>; layer = <CALayer: 0x18142270>>",
                        "text" => "",
                       "alpha" => 1,
                       "value" => "",
        "accessibilityElement" => false,
                        "rect" => {
                   "y" => 135,
               "width" => 280,
            "center_x" => 160,
                   "x" => 20,
            "center_y" => 155,
              "height" => 40
        },
                       "class" => "UITextField"
    }
]
irb(main):020:0> touch("view:'UITextField'")
NoMethodError: undefined method `touch' for nil:NilClass
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:1204:in `query_action_with_options'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:177:in `touch'
	from (irb):20
	from /usr/bin/irb:12:in `<main>'
irb(main):021:0> 
```

Other methods that invoke touch also encounter this error. Here's the version information:
```
saith-cysgadur:iphone jesus$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

saith-cysgadur:iphone jesus$ xcodebuild -version
Xcode 7.0.1
Build version 7A1001

saith-cysgadur:iphone jesus$ calabash-ios version
0.16.4

saith-cysgadur:iphone jesus$ curl http://10.0.18.245:37265/version
{  
  "outcome":"SUCCESS",
  "ios_version":"8.3",
  "app_id":"com.hipmunk.hipmunk.debug",
  "app_name":"Devmunk",
  "app_base_sdk":"iphoneos9.0",
  "git":{  
    "remote_origin":"git@github.com:calabash\/calabash-ios-server.git",
    "branch":"master",
    "revision":"3bf68ff"
  },
  "iOS_version":"8.3",
  "simulator_device":"",
  "version":"0.16.4",
  "server_port":37265,
  "model_identifier":"iPhone5,3",
  "form_factor":"iphone 4in",
  "app_version":"20151012.9233317",
  "simulator":"",
  "4inch":true,
  "iphone_app_emulated_on_ipad":false,
  "device_family":"iPhone",
  "screen_dimensions":{  
    "scale":2,
    "width":640,
    "sample":1,
    "height":1136
  },
  "short_version_string":"4.0",
  "system":"iPhone5,3",
  "device_name":"HipPhone5C_8.3"
}
```

Thanks for taking a look!

**Comment by janemckay** [comment]
Also seeing this issue using XCode 7.0.1 when using touch and IOS 9.

Config details are here:

    user$ xcode-select --print-path
    /Applications/Xcode.app/Contents/Developer

    user$ xcodebuild -version
    Xcode 7.0
    Build version 7A220

    user$ calabash-ios version
    0.16.4

    user$ curl http://localhost:37265/version
    {"device_family":"iPhone",
    "outcome":"SUCCESS",
    "server_port":37265,
    "simulator_device":"iPhone",
    "simulator":"CoreSimulator 179 - Device: iPhone 5s - Runtime: iOS 9.0 (13A340) - DeviceType: iPhone 5s",
    "app_name":"",
    "app_version":"1",
    "screen_dimensions":{
          "sample":1,
         "height":1136,
         "width":640,
         "scale":2
     },
    "device_name":"iPhone Simulator","4inch":true,
    "form_factor":"iphone 4in", 
    "system":"x86_64",
    "version":"0.16.4",
    "iOS_version":"9.0",
    "short_version_string":"1.0",
    "ios_version":"9.0",
    "iphone_app_emulated_on_ipad":false,"model_identifier":"iPhone6,1",
    "app_base_sdk":"iphonesimulator9.0"
    }


Error details are:

   
    irb(main):004:0> flash("button marked:'Log in with Facebook'")
    [
        [0] {
                          "id" => nil,
                 "description" => "<FBSDKLoginButton: 0x7ff20b5d9660; baseClass = UIButton; frame = (73 349; 174 30); opaque = NO; tintColor = UIDeviceWhiteColorSpace 1 1; layer = <CALayer: 0x7ff20b5d9930>>",
                       "label" => "Log in with Facebook",
                       "frame" => {
                 "y" => 349,
                 "x" => 73,
             "width" => 174,
            "height" => 30
        },
        "accessibilityElement" => true,
                       "value" => nil,
                       "alpha" => 1,
                     "enabled" => true,
                     "visible" => 1,
                    "selected" => false,
                       "class" => "FBSDKLoginButton",
                        "rect" => {
                   "y" => 349,
            "center_x" => 160,
            "center_y" => 364,
                   "x" => 73,
               "width" => 174,
              "height" => 30
        }
    }
    ]
    irb(main):005:0> touch("button marked:'Log in with Facebook'")
    NoMethodError: undefined method `touch' for nil:NilClass
    from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-    cucumber/core.rb:1204:in `query_action_with_options'
	    from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:177:in `touch'
	    from (irb):5
	    from /usr/bin/irb:12:in `<main>'

**Comment by TeresaP** [comment]
Can you try running this from your features folder?

**Comment by TeresaP** [comment]
Also, have you used start_test_server_in_background?

**Comment by jfrndz** [comment]
@TeresaP I'm not sure what you mean by "running this"? Did you mean running cucumber tests that call `touch` or launching the console from inside the features folder?

**Comment by TeresaP** [comment]
The console

**Comment by janemckay** [comment]
Just realised that start_test_server_in_background (using simulator) was failing as in the existing run_loop issue #874  - so not even sure that my 'touch' issue is valid. 
Everything works ok on a physical device.

**Comment by jmoody** [comment]
@jfrndz @janemckay 

In case you missed it, you must run start_test_server_in_background before executing _gestures_.  query and flash will work as normal, but the app must be launched with instruments to perform gestures.

@jfrndz Please run with DEBUG=1 to see if you are encountering a problem launching the app with instruments.

I am not sure yet what is causing the Fifo problem in run-loop.

**Comment by jfrndz** [comment]
@TeresaP I ran `start_test_server_in_background` and everything works as expected. I can query views and execute gestures in the simulator and on device.

@jmoody Thanks for the explanation on the difference between queries and gestures, that helped a lot!
