### ISSUE TITLE
Add documentation on switching locales

### ISSUE THREAD

**Issue by yakovsh** [calabash/calabash-ios#880]
Since **calabash-ios sim locale** has been broken as per issue #564, it is still possible to switch languages using the **support/hooks.rb** file as per issue #363. Can these instructions be added to the wiki, maybe the Hot Topics section?

We ended doing the following in **hooks.rb**:
```
require 'calabash-cucumber/launcher'

Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  options = {}
  unless @calabash_launcher.calabash_no_launch?
    options = {
	:args => ['-AppleLanguages', '(es)']
    }
    @calabash_launcher.relaunch(options)
    @calabash_launcher.calabash_notify(self)
  end
end
```

**Comment by jmoody** [comment]
Created this page https://github.com/calabash/calabash-ios/wiki/Changing-Locale-and-Language

It is start...
