### ISSUE TITLE
Incorrect URL in calabash-ios console warning message

### ISSUE THREAD

**Issue by CMTaylor** [calabash/calabash-ios#887]
If you start a calabash-ios console and try to do a "touch" operation on an iPad app that was not launched by THE SAME calabash-ios console you get this warning:

WARNING 

Warning Trying to connect to simulator that was not launched by Calabash/instruments.
To fix this you must let Calabash or instruments launch the app.
Query will work, but gestures will not.

 WARNING 

Please read: https://github.com/calabash/calabash-ios/wiki/A0-UIAutomation---instruments-problems

The final URL link is to a non-existant wiki page.

**Comment by jmoody** [comment]
Thanks for reporting!

**Comment by jmoody** [comment]
@CMTaylor 

You should be using `console_attach`.

* http://calabashapi.xamarin.com/ios/Calabash/Cucumber/Core.html#console_attach-instance_method
* http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-NO_STOP

**Comment by jmoody** [comment]
@CMTaylor Reviewing the relevant code, I have a suspicion that you are using `NO_LAUNCH`.  This is a deprecated variable; it is never appropriate to set this variable.

http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-Deprecated+Variables
