### ISSUE TITLE
Can not connect to calabash server

### ISSUE THREAD

**Issue by kaorijp** [calabash/calabash-ios#889]
Hi all
I'd like to report my problem . And I need the supporting from you guy.

Run calabash with Simulator

```
$ DEBUG=1 DEVICE_TARGET="FC2B39B8-8A0A-4538-B222-A914A39FE9FE" cucumber -v

2015-10-27 21:02:53 +0900 [RunLoop:debug]:
{
                        :app => "/Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app",
                  :bundle_id => "jp.ne.boobby.vihe-cal",
                     :device => "iphone",
              :device_target => "FC2B39B8-8A0A-4538-B222-A914A39FE9FE",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/Users/boobby/.run-loop/results/2015-10-27_21-02-28/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/Users/boobby/.run-loop/results/2015-10-27_21-02-28",
          :results_dir_trace => "/Users/boobby/.run-loop/results/2015-10-27_21-02-28/trace",
                     :script => "/Users/boobby/.run-loop/results/2015-10-27_21-02-28/_run_loop.js",
                :sdk_version => nil,
                       :udid => "FC2B39B8-8A0A-4538-B222-A914A39FE9FE",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

###Starting on FC2B39B8-8A0A-4538-B222-A914A39FE9FE App: /Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-27 21:03:00 +0900 [RunLoop:debug]: xcrun instruments -w FC2B39B8-8A0A-4538-B222-A914A39FE9FE -D /Users/boobby/.run-loop/results/2015-10-27_21-02-28/trace -t Automation /Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app -e UIARESULTSPATH /Users/boobby/.run-loop/results/2015-10-27_21-02-28 -e UIASCRIPT /Users/boobby/.run-loop/results/2015-10-27_21-02-28/_run_loop.js >& /Users/boobby/.run-loop/results/2015-10-27_21-02-28/run_loop.out
2015-10-27 21:03:00 +0900 [RunLoop:debug]: Preparation took 31.145576 seconds
2015-10-27 21:03:09 +0900 [RunLoop:debug]: Launching took 9.960614 seconds
DEBUG: It took 41.106516 seconds to launch the app
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:823:in `rescue in ensure_connectivity'
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:783:in `ensure_connectivity'
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:646:in `relaunch'
  /Users/boobby/.jenkins/jobs/myapp-cal/workspace/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:217
      unsupported proxy mda-sg600.zdc.local:3128 (ArgumentError)
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:478:in `proxy='
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1028:in `load_environment'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:420:in `initialize'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:92:in `new'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:92:in `init_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:53:in `block in make_http_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:50:in `times'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:29:in `http'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:877:in `calabash_exit'
      /Users/boobby/.jenkins/jobs/myapp-cal/workspace/features/support/01_launch.rb:34:in `After'
```

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
5m42.548s

##################

## My environment

**xcode-select --print-path**
/Applications/Xcode.app/Contents/Developer

**xcodebuild -version**
Xcode 7.0.1
Build version 7A1001

**calabash version**
0.16.4

**Comment by hoangvm** [comment]
What is the recommendation for calabash iOS when running with below Environment : 
1. MacBook Pro : Yosemite 10.10.5
2. Xcode versrion : 7.0.1

**Comment by jmoody** [comment]
Is this only happening in Jenkins or does it happen locally?  I don't like to try to provide support for CI environments because they are incredibly difficult to set up.

For example, Jenkins cannot be launched as a daemon or it will be not be able to launch simulators.  Starting in Yosemite, I haven't been able to get simulators to launch _unless I manually start Jenkins from the UI_.

In a nutshell, if you installed Jenkins with the official installer or with homebrew, you will not be able to launch simulators.

My best guess is that your:

```
/Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app
```

is not linked with Calabash.  This is mentioned in the error:

```
Timed out connecting to Calabash server after 10 retries. 
Make sure it is linked and App isn't crashing
Unable to make connection to Calabash Server at http://localhost:37265/
Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
```

You can test this:

```
$ xcrun strings /Users/boobby/.jenkins/jobs/myapp-cal/workspace/vehi-cal.app/<name> | grep -E 'CALABASH VERSION'
```

where <name> is the name of the executable - in this case it is probably "vehi"

**Comment by jmoody** [comment]
> What is the recommendation for calabash iOS when running with below Environment : 

We always recommend the most recent version Calabash, regardless of the Xcode or MacOS version.

**Comment by hoangvm** [comment]
I re-setup on local PC and report you soon

**Comment by hoangvm** [comment]
@jmoody 
I have already setting and try run on Local PC.
Here is the result

$$$$$$$$$$$$$$$
DEBUG=1 DEVICE_TARGET="FC2B39B8-8A0A-4538-B222-A914A39FE9FE" cucumber -v

Code:
  * features/support/env.rb
  * features/support/01_launch.rb
  * features/support/02_pre_stop_hooks.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/my_first_steps.rb

Features:
  * features/my_first.feature
Parsing feature files took 0m0.003s

Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6

INFO: Using uia strategy: 'host'
DEBUG: Searching for run-loop results with glob: /Users/boobby/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.001493 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 5 instruments caches
DEBUG: Will delete 0 instruments caches
DEBUG: Deleted 0 instruments caches in 0.000137 seconds
DEBUG: Sending 'QUIT' to instruments process '90287'
DEBUG: Waiting for instruments with pid '90287' to terminate
DEBUG: Waited for 1.541093 seconds for instruments with pid '90287' to terminate
DEBUG: Simulator instruction set 'x86_64' is compatible with '["i386", "x86_64"]'
DEBUG: Deleting /Users/boobby/Library/Developer/CoreSimulator/Devices/FC2B39B8-8A0A-4538-B222-A914A39FE9FE/data/tmp/instruments_i8e8Ik/stdio.pipe
DEBUG: Installed app is the same as #<APP: /Users/boobby/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app>
DEBUG: Launching #<Simulator: iPhone 5s (8.3) FC2B39B8-8A0A-4538-B222-A914A39FE9FE x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID FC2B39B8-8A0A-4538-B222-A914A39FE9FE
DEBUG: Simulator stable after 2.34862 seconds
DEBUG: Waited a total of 3.34862 seconds for simulator to stabilize
DEBUG: Took 3.363842 seconds to launch the simulator
2015-10-28 11:14:06 +0900 [RunLoop:debug]:
{
                        :app => "/Users/boobby/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/boobby/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app",
                  :bundle_id => "jp.ne.boobby.vehi-cal",
                     :device => "iphone",
              :device_target => "FC2B39B8-8A0A-4538-B222-A914A39FE9FE",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/Users/boobby/.run-loop/results/2015-10-28_11-14-00/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/Users/boobby/.run-loop/results/2015-10-28_11-14-00",
          :results_dir_trace => "/Users/boobby/.run-loop/results/2015-10-28_11-14-00/trace",
                     :script => "/Users/boobby/.run-loop/results/2015-10-28_11-14-00/_run_loop.js",
                :sdk_version => nil,
                       :udid => "FC2B39B8-8A0A-4538-B222-A914A39FE9FE",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on FC2B39B8-8A0A-4538-B222-A914A39FE9FE App: /Users/boobby/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-28 11:14:08 +0900 [RunLoop:debug]: xcrun instruments -w FC2B39B8-8A0A-4538-B222-A914A39FE9FE -D /Users/boobby/.run-loop/results/2015-10-28_11-14-00/trace -t Automation /Users/boobby/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app -e UIARESULTSPATH /Users/boobby/.run-loop/results/2015-10-28_11-14-00 -e UIASCRIPT /Users/boobby/.run-loop/results/2015-10-28_11-14-00/_run_loop.js >& /Users/boobby/.run-loop/results/2015-10-28_11-14-00/run_loop.out
2015-10-28 11:14:08 +0900 [RunLoop:debug]: Preparation took 9.799604 seconds
2015-10-28 11:14:15 +0900 [RunLoop:debug]: Launching took 6.865708 seconds
DEBUG: It took 16.665507 seconds to launch the app
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:823:in `rescue in ensure_connectivity'
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:783:in `ensure_connectivity'
  /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:646:in `relaunch'
  /Users/boobby/.jenkins/jobs/INP3.0-Calabash/workspace/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:217
      unsupported proxy mda-sg600.boobby.local:3128 (ArgumentError)
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:478:in `proxy='
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1028:in `load_environment'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:420:in `initialize'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:92:in `new'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:92:in `init_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:53:in `block in make_http_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:50:in `times'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/http_helpers.rb:29:in `http'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
      /Users/boobby/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:877:in `calabash_exit'
      /Users/boobby/.jenkins/jobs/INP3.0-Calabash/workspace/features/support/01_launch.rb:34:in `After'

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
5m17.614s

$$$$$$$$$$$$$$$$$$$$$$$$


**xcrun strings /Users/zdc/Library/Developer/Xcode/DerivedData/vehi-btjujhlgtmjtksgasjepcykhjmna/Build/Products/Debug-iphonesimulator/vehi-cal.app/vehi-cal | grep -E 'CALABASH VERSION'**
CALABASH VERSION: 0.16.4

**Comment by hoangvm** [comment]
I do NOT think the reason come from my Jenkins.

**curl http://localhost:37265/version**
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>

Of course my company has a proxy. 
I also setting http_proxy, https_proxy, no_proxy in .bash_profile file

**Comment by TeresaP** [comment]
When you boot up Xcode and build/launch the app on the simulator, do you see anything in the logs about Calabash?

**Comment by hoangvm** [comment]
@TeresaP 
The firstly , I build vehi-cal.app in Simulator by Xcode
- Target selected : vehi-cal
- Device_target of Simulator is the same with Above command ( #1)

**Comment by hoangvm** [comment]
One more thing : 
- In my environment, I have many many kind of Simulator in Xcode ( You can see as above list device )
So, when I run `cucumber` I MUST pointing at exactly DEVICE_TYPE, is that correct ? 

(Because if I call only `cucumber` command,Simulator will by opened that is the other one with Xcode selected before ...)

**Comment by jmoody** [comment]
If you don't set `DEVICE_TARGET`, the _default simulator_ will be launched.

The default simulator will depend on the active Xcode version.

**Comment by TeresaP** [comment]
@kaorijp What does the Xcode console log say?

**Comment by TeresaP** [comment]
If the xcode console logs don't say anything about Calabash, I believe you have not successfully loaded the Calabash framework

**Comment by kaorijp** [comment]
@jmoody @TeresaP 
> If the xcode console logs don't say anything about Calabash, I believe you have not successfully loaded the Calabash framework

But when I build vehi-cal Target by Xcode in to Simulator. It's working normally. 
I also checked again on Other flags link,... There is no wrong..
How can I know/confirm that the Calabash framework already loaded or not ?

**Comment by kaorijp** [comment]
@TeresaP 
I got the logs content related to Calabash from Xcode:

2015-10-29 14:39:49.837 DEBUG CalabashServer:217 | Creating the server: <LPHTTPServer: 0x79819290>
2015-10-29 14:39:49.837 DEBUG CalabashServer:218 | Calabash iOS server version: CALABASH VERSION: 0.15.0
2015-10-29 14:39:49.837 DEBUG CalabashServer:221 | App Base SDK: iphonesimulator9.1
2015-10-29 14:39:49.838 DEBUG CalabashServer:249 | IPHONE_SIMULATOR_ROOT: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot
2015-10-29 14:39:59.824 vehi[72015:1353864] WKWebView successfully implemented LPWebViewProtocol
POIIF::POIInitialize start
mkdirFlg -1

**Comment by kaorijp** [comment]
Dear friends!
I already resolved my problem. 
*Reason* : default TIME_OUT is not enough for my app starting. Because my app need more time to get information from Server(using Internet) then execute something... Thats the reason I have to expends more time out. 

*Solution* : Edit 01_launch.rb file as below
**Before change**
`@calabash_launcher.relaunch`
**After change**
`@calabash_launcher.relaunch({:timout => 300})`

@jmoody  : Please help me to close this problem. 
Thank you so much @TeresaP @jmoody
