### ISSUE TITLE
Calabash is stuck after Launching took

### ISSUE THREAD

**Issue by kaorijp** [calabash/calabash-ios#895]
Hi @jmoody 
Please help me to investigate this problem.

RESET_BETWEEN_SCENARIOS=1 DEBUG=1 DEVICE_TARGET="003997FE-3D8C-4CDC-BED8-25038AE652E2" cucumber -v
Code:
  * features/support/env.rb
  * features/support/01_launch.rb
  * features/support/02_pre_stop_hooks.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/my_first_steps.rb

Features:
  * features/my_first.feature
Parsing feature files took 0m0.030s

Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6

INFO: Using uia strategy: 'preferences'
2015-11-04 11:45:38 +0900 [RunLoop:debug]: Simulator instruction set 'i386' is compatible with ["i386", "x86_64"]
Sending 'TERM' to com.apple.CoreSimulator.CoreSimulatorService process '24591'
Waiting for com.apple.CoreSimulator.CoreSimulatorService '24591' to terminate
Waited for 2.065751 seconds for com.apple.CoreSimulator.CoreSimulatorService with '24591' to terminate
Sending 'KILL' to com.apple.CoreSimulator.CoreSimulatorService process '24591'
Waiting for com.apple.CoreSimulator.CoreSimulatorService '24591' to terminate
Waited for 0.102084 seconds for com.apple.CoreSimulator.CoreSimulatorService with '24591' to terminate
Waited for 6.419506 seconds for 'SimulatorBridge' to start.
2015-11-04 11:47:04 +0900 [RunLoop:debug]:
{
                        :app => "/Users/zdc/Library/Developer/Xcode/DerivedData/Testing-dvjuumfhappvpsflyxkofqygzcys/Build/Products/Debug-iphonesimulator/Testing-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/zdc/Library/Developer/Xcode/DerivedData/Testing-dvjuumfhappvpsflyxkofqygzcys/Build/Products/Debug-iphonesimulator/Testing-cal.app",
                  :bundle_id => "jp.ne.sample.Testing-cal",
                     :device => "iphone",
              :device_target => "003997FE-3D8C-4CDC-BED8-25038AE652E2",
                :instruments => #<Instruments 7.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => true,
                :results_dir => "/var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb",
          :results_dir_trace => "/var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/trace",
                     :script => "/var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/_run_loop.js",
                :sdk_version => nil,
                    :timeout => 300,
                       :udid => "003997FE-3D8C-4CDC-BED8-25038AE652E2",
               :uia_strategy => :preferences,
                      :xcode => "7.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer/"
}

###Starting on 003997FE-3D8C-4CDC-BED8-25038AE652E2 App: /Users/zdc/Library/Developer/Xcode/DerivedData/Testing-dvjuumfhappvpsflyxkofqygzcys/Build/Products/Debug-iphonesimulator/Testing-cal.app ###
2015-11-04 11:47:20 +0900 [RunLoop:debug]: xcrun instruments -w 003997FE-3D8C-4CDC-BED8-25038AE652E2 -D /var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/trace -t Automation /Users/zdc/Library/Developer/Xcode/DerivedData/Testing-dvjuumfhappvpsflyxkofqygzcys/Build/Products/Debug-iphonesimulator/Testing-cal.app -e UIARESULTSPATH /var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb -e UIASCRIPT /var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/_run_loop.js >& /var/folders/b7/f1yzx1ls7wjgn_953my63m200000gp/T/run_loop20151104-24788-6on0qb/run_loop.out
2015-11-04 11:47:20 +0900 [RunLoop:debug]: Preparation took 105.690721 seconds
2015-11-04 11:48:14 +0900 [RunLoop:debug]: Launching took 54.277496 seconds
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/zdc/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/launcher.rb:820:in `rescue in ensure_connectivity'
  /Users/zdc/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/launcher.rb:780:in `ensure_connectivity'
  /Users/zdc/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.15.0/lib/calabash-cucumber/launcher.rb:647:in `relaunch'
  /Users/zdc/CalabashINP/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:158
    And take picture                                # calabash-cucumber-0.15.0/features/step_definitions/calabash_steps.rb:217
Sending 'QUIT' to instruments process '26168'
Waiting for instruments '26168' to terminate
Waited for 2.041741 seconds for instruments with '26168' to terminate
Sending 'KILL' to instruments process '26168'
Waiting for instruments '26168' to terminate
Waited for 0.101519 seconds for instruments with '26168' to terminate

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
7m59.347s

## My environment

**xcode-select --print-path**
/Applications/Xcode.app/Contents/Developer

**xcodebuild -version**
Xcode 7.0.1
Build version 7A1001

**calabash version**
0.16.4

**Comment by kaorijp** [comment]
It seems my app can not linked with Calabash server .
I do not see anything message log about CalabashServer ...
How to fix it or whats the problem in my App setting build ?
Please help me !

**Comment by kaorijp** [comment]
I have already checked setting at "Other linker Flags" that is OK.
Of course It should be OK when run calabash-ios setup from beginning.
I don't know why my App can not LINKED with Calabash server !

**Comment by jmoody** [comment]
> INFO: Using uia strategy: 'preferences'

:preferences is not supported when testing against iOS 9 simulators.

I can't tell what simulator you are trying to launch.  Is it an iOS 9 
simulator?

Your report contains conflicting information:

The logs say you are using Calabash 0.15.0, but you say you are using 
0.16.4.

The logs say you are using Xcode 7.1, but you say you are using Xcode 
7.0.1.

Your timeout is 300 seconds which is 10 time longer than the default and 
it appears like run-loop is spending an very long time in the 
preparation phase.  Is your app large?  Your machine slow?

```
2015-11-04 11:47:20 +0900 [RunLoop:debug]: Preparation took 105.690721 
seconds
2015-11-04 11:48:14 +0900 [RunLoop:debug]: Launching took 54.277496 
seconds
```

Finally, are you sure your .app is linked with Calabash?

**Comment by jmoody** [comment]
@kaorijp Would you be willing to do a tmate + text chat session to try to resolve your problem?

http://tmate.io/

**Comment by jmoody** [comment]
Closing; no respone.

**Comment by kaorijp** [comment]
Sorry for late reply. 
No matching Calabash version is the problem. 
I'm working on  auto testing by calabash in Jenkins/Server Mac that I can not control the calabash version at that time
I'm sorry!!!
