### ISSUE TITLE
Manually start Calabash Server

### ISSUE THREAD

**Issue by paulpatarinski** [calabash/calabash-ios#897]
Is there a way to manually start the Calabash Server from code as oppose to linking the library? I am thinking something in the lines of : add the framework to my project and call CalabashServer start from my AppDelegate didFinishLaunchingWithOptions. My end goal is to be able to do this in a Cordova app via a Cordova Plugin.

**Comment by jmoody** [comment]
Yes there is a way.

In your linker flags the `--force_load` option starts the server.

If you treat the _calabash.framework_ like an actual Objective-C framework by 

* removing the `--force_load /path/to/framework/lib` from the linker flags
* Add the calabash.framework to your target's Header Search Path
* Add the following snippet to your App delegate


```objc
#import "CalabashServer.h"

- (BOOL)application:(UIApplication *)application 
     didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

  [CalabashServer start];

  return YES;
}

```
