### ISSUE TITLE
touch webView not accessing the correct element

### ISSUE THREAD

**Issue by YazeedFares** [calabash/calabash-ios#898]
Hello,

if I have a login screen that and I try to use touch function to enter some text in the user name field, calabash is not touching the correct field, for example:
 
touch("webView css:'input#userName'")

for some strange reason calabash is accessing the login button instead, this issue happened on Android and iPhone, the more strange thing is, it works fine on iPad Air in portrait mode only !!!

I am using ruby 2.2.1 and the latest calabash on OS X El Capitan

**Comment by jmoody** [comment]
@YazeedFares  Can you create an example app that reproduces the problem?

My best guess is that you will need to use a more sophisticated css or xpath query.

https://github.com/calabash/calabash-ios/wiki/06-WebView-Support
