### ISSUE TITLE
Calabash IOS cucumber running on other simulator

### ISSUE THREAD

**Issue by carlocepres** [calabash/calabash-ios#899]
HI There,

is there a way or command that I can run the calabash target on the other simulator because every time I run this command cucumber DEVICE_TARGET='iPhone 6 (9.0 Simulator)' I having this error:

Could not find simulator with name or UDID that matches: 'iPhone 6 (9.0 Simulator)' (RuntimeError)
 /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.5/lib/run_loop/core.rb:185:in `prepare_simulator'
 /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.5/lib/run_loop/core.rb:310:in `run_with_options'
 /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.5/lib/run_loop.rb:107:in `run'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:765:in `times'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop'
 /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
 /Users/FDMCarlo/TMSample/TMSample/features/support/01_launch.rb:29:in `Before'

please help me or give some suggestion:

Thank you so much

Regards:
Carlo

**Comment by jmoody** [comment]
> Could not find simulator with name or UDID that matches: 'iPhone 6 (9.0 Simulator)'

In Xcode 7, the format of the simulator names have changed.

Try:

```
DEVICE_TARGET="iPhone 6 (9.0)"
```

Use:

```
$ xcrun instruments -s devices
```

to find the available simulators and devices.

**Comment by kyleect** [comment]
I'm experiencing this error as well. I ran `$ xcrun instruments -s devices` and this listing from the output: `iPhone 6 (9.2)` and that did get it past the error.  This caused a new issue though. The simulator will start, it doesn't launch the test app but just sits there until it closes. It then reopens, sits there and closes. It seems to be stuck in a loop as it cycled 6 times before I killed it.

I don't know if its related but the original issue I was trying to fix was https://github.com/calabash/run_loop/issues/361. I followed the advice in this comment: https://github.com/calabash/run_loop/issues/361#issuecomment-167604972 which is what caused me to see the "Could not find simulator with name" error.

**Comment by jmoody** [comment]
@kyleect 

Try using the UDID of the simulator.  

This has nothing to do with the "cannot find run_loop_*.js" bug.

**Comment by kyleect** [comment]
I tried that but still seeing the same issue. The simulator launching, not opening app, closing simulator and repeat. I had successfully integrated calabash-ios in to a fresh project yesterday but unable to recreate those results today. I was hoping someone else had experienced this looping issue.

**Comment by jmoody** [comment]
What version of Xcode?  And would you like to discuss live on Gitter?

https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by lindanordstrom** [comment]
I'm having a problem with this as well. Using the UDID works fine, but I also want to use the RESET_BETWEEN_SCENARIOS=1 which only works if simulator_target? returns true. That makes sence. BUT if I am setting my DEVICE_TARGET to the UDID, it will not contain the word "simulator", and therefor simulator_target? will return false.. :(

**Comment by jmoody** [comment]
> simulator_target? returns false

What version of Calabash iOS are you using @lindanordstrom ?

For some time now, the `simulator_target?` method has been detecting simulators by UDID.

Do you have a stack trace?

**Comment by lindanordstrom** [comment]
Hi! Oh, of course, we were apparently running 0.15.0..  
I updated to v. 0.17.1 (with run_loop >= 2.0.3) and it is working fine now! Sorry about that, and thanks for the simple solution :smile:

**Comment by neuberfran** [comment]
https://forum.ionicframework.com/t/enoent-no-such-file-or-directory-stat-var-root-library-logs-coresimulator-792d38b1-e2ef-4547-ad8e-f2c3fa46f542-system-log/72775

**Comment by neuberfran** [comment]
https://forum.ionicframework.com/t/enoent-no-such-file-or-directory-stat-var-root-library-logs-coresimulator-792d38b1-e2ef-4547-ad8e-f2c3fa46f542-system-log/72775
