### ISSUE TITLE
error of activating selenium_cucmber

### ISSUE THREAD

**Issue by rajitha23** [calabash/calabash-ios#900]
when excute the feature file below error got occor..please help me to solve it.

*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansic
on/) to get coloured output on Windows
Unable to activate selenium-cucumber-2.1.3, because cucumber-2.1.0 conflicts wit
h cucumber (>= 1.3.18, ~> 2.0.0) (Gem::LoadError)
C:/Ruby200/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts'

C:/Ruby200/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
C:/Ruby200/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
C:/Ruby200/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in
require'
C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
C:/Users/rajeeda/Gmail_login/features/support/env.rb:2:in `<top (required)>'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/rb_support/rb_la
nguage.rb:99:in `load'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/rb_support/rb_la
nguage.rb:99:in `load_code_file'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_
code.rb:232:in `load_file'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_
code.rb:99:in `block in load_files!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_
code.rb:98:in `each'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime/support_
code.rb:98:in `load_files!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime.rb:262:i
n `load_step_definitions'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime.rb:65:in
 `run!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:32:i
n `execute!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.1.0/bin/cucumber:8:in `<top (requ
ired)>'
C:/Ruby200/bin/cucumber:23:in `load'
C:/Ruby200/bin/cucumber:23:in `<main>'

**Comment by jmoody** [comment]
@rajitha23 

Calabash iOS is not supported on Windows.

> Unable to activate selenium-cucumber-2.1.3, because cucumber-2.1.0 conflicts
> with cucumber (>= 1.3.18, ~> 2.0.0) (Gem::LoadError)

The error message tells you everything you need to know.  You are trying to use selenium-cucumber version 2.1.3 which _requires_ cucumber > 2.0.  Calabash iOS does not support cucumber 2.0. 

To make progress, I recommend you use bundler and a Gemfile.
