### ISSUE TITLE
cannot run the calabash ios on the real devices 

### ISSUE THREAD

**Issue by carlocepres** [calabash/calabash-ios#903]
HI There Sir

I set up the ios application on my device iphone 5s and then I enter the ip address on my device on the command line I'm using this command: DEVICE=iphone OS=ios9 NO_LAUNCH=1 cucumber features/my_first.feature DEVICE_ENDPOINT=http://192.168.0.40 to run the calabash-ios on the real device but I got this error: Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:80))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:80))
Failing... Errno::ECONNREFUSED
is there other way or other commands that I can run on the real device for the calabash-ios or I did something wrong on my setup for running the calabash-ios on the real device 

Thank you

Regards.
Carlo

Carlos-Mac-mini:TMSample FDMCarlo$ DEVICE=iphone OS=ios9 NO_LAUNCH=1 cucumber features/my_first.feature DEVICE_ENDPOINT=http://192.168.0.40
Feature: Running a test
  As an QA Tester
  I want to have a sample feature file
  So I can begin testing quickly

  @Login
  Scenario: Login                                        # features/my_first.feature:7
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:80))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:80))
Failing... Errno::ECONNREFUSED

**Comment by jmoody** [comment]
Your `DEVICE_ENDPOINT` needs to include the port.

```
DEVICE_ENDPOINT=http://192.168.0.40:37265
```

For more details see the [Testing on Physical Devices](https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices) wiki page.

**Comment by carlocepres** [comment]
still getting the error Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:8080))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://192.168.0.40:8080))
Failing... Errno::ECONNREFUSED I already include the port on my DEVICE_ENDPOINT :8080

DEVICE=iphone OS=ios9 NO_LAUNCH=1 cucumber features/my_first.feature DEVICE_ENDPOINT=http://192.168.0.40:8080 (this is my command) but still not work.

Thanks

**Comment by jmoody** [comment]
@carlocepres 

```
NO_LAUNCH=1
```

You cannot set this variable.  Did you read the wiki page that I mentioned?
