### ISSUE TITLE
Unable to make connection to Calabash Server at http://localhost:37265/???

### ISSUE THREAD

**Issue by RunningYoung** [calabash/calabash-ios#907]
I set up the environment in accordance with the following procedure

	1.gem install calabash-cucumber
	2.calabash-ios setup
	3.calabash-ios gen
	4. add calabash.framework
	5. add -force_load "$(SRCROOT)/calabash.framework/calabash" -lstdc++

 but my program does not show：

	HTTPServer: Started HTTP server on port 37265

There are mistakes：

	1.2015-11-11 17:37:05.665 DEBUG CalabashServer:222 | 	Creating the server: <LPHTTPServer: 0x7ff90af10330>
	2015-11-11 17:37:05.665 DEBUG CalabashServer:223 | 	Calabash iOS server version: CALABASH VERSION: 0.16.4
	2015-11-11 17:37:05.666 DEBUG CalabashServer:226 | 	App Base SDK: iphonesimulator9.1
	2015-11-11 17:37:05.667 DEBUG CalabashServer:254 | 	IPHONE_SIMULATOR_ROOT: /Applications/Xcode.app/	Contents/Developer/Platforms/	iPhoneSimulator.platform/Developer/SDKs/	iPhoneSimulator.sdk
		2015-11-11 17:37:05.767 zuche[16015:533625] 	WKWebView successfully implemented LPWebViewProtocol

	
	 2. bddBranch ✔   	DEVICE_TARGET="5B3B6A8B-370C-48E9-A1BC-F138629853FA" cucumber
	Feature: Take a quiz
 	 As a user
 	 I want to take a quiz
 	 So I can improve my general knowledge
	
 	 @wip
 	 Scenario: View quiz question      # features/	take_a_quiz.feature:6
	#<RuntimeError: Timed out connecting to Calabash 	server after 10 retries. Make sure it is linked and 	App isn't crashing>
	 Unable to make connection to Calabash Server at 	http://localhost:37265/
	 Make sure you don't have a firewall blocking 	traffic to http://localhost:37265/.
  	(RuntimeError)
 	/Library/Ruby/Gems/2.0.0/gems/calabash-	cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:	823:in `rescue in ensure_connectivity'
 	/Library/Ruby/Gems/2.0.0/gems/calabash-	cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:	783:in `ensure_connectivity'
	 /Library/Ruby/Gems/2.0.0/gems/calabash-	cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:	646:in `relaunch'
 	/Users/xuchuanliang/Desktop/shenzhou_IOS/zuche_ios/	features/support/01_launch.rb:27:in `Before'
		    Given I am on the Quiz Screen   # features/	take_a_quiz.feature:7
 	 	  When I view a question          # features/	take_a_quiz.feature:8
  	  Then a question is displayed    # features/	take_a_quiz.feature:9
    	And the answer is not displayed # features/	take_a_quiz.feature:10

	Failing Scenarios:
	cucumber features/take_a_quiz.feature:6 # Scenario: 	View quiz question

	1 scenario (1 failed)
	4 steps (4 undefined)
	6m5.975s
	

thanks

**Comment by RunningYoung** [comment]
I solved the problem!!!
##Because the simulator open is not the same, but that is not the same all iPhone6

**Comment by carlocepres** [comment]
Hi SIr Young

can you share how you resolved this problem running the calabash on the
real device because I have the problem running the calabash target on the
real device

thanks

Regards,
Carlo

**Comment by jmoody** [comment]
> Because the simulator open is not the same, but that is not the same all iPhone6

Can you try again to explain what you mean?

**Comment by RunningYoung** [comment]
@carlocepres 
2. DEVICE_TARGET="90E602DD-376F-4EF9-9B82-208D9016B61D" cucumber      
Determine whether the device id is consistent with your running

**Comment by jmoody** [comment]
@RunningYoung 

> add -force_load "$(SRCROOT)/calabash.framework/calabash" -lstdc++

This is incorrect.  You are missing `-ObjC` and the `-lstdc++` is not necessary.

```
# If your application already links CFNetwork
-ObjC -force_load "$(SOURCE_ROOT)/calabash.framework/calabash"
# If your application does not link CFNetwork

-ObjC -force_load "$(SOURCE_ROOT)/calabash.framework/calabash" -framework CFNetwork

```

**Comment by RunningYoung** [comment]
I know, I have resolved   ，Thanks
