### ISSUE TITLE
Documentation for swipe is missing "swipe-delta" but it still works

### ISSUE THREAD

**Issue by TeresaP** [calabash/calabash-ios#911]
swipe-delta still works (as of 16.4), but I don't see any documentation for it on https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/core.rb#L316

We still use swipe-delta for doing cross-screen swipes rather than flick in some areas.

Example syntax:

      swipe(:up, {:offset => {:x => center_x, :y => height}, :'swipe-delta' => {:vertical => {:dx => 0, :dy => height}}})
      swipe(:down, {:'swipe-delta' => {:vertical => {:dx => 0, :dy => (center_x-1)}}})

Current documented options for "options" parameter
      # @param {Hash} options option for modifying the details of the touch.
      # @option options {Hash} :offset (nil) optional offset to touch point. Offset supports an `:x` and `:y` key
      #   and causes the touch to be offset with `(x,y)` relative to the center (`center + (offset[:x], offset[:y])`).
      # @option options {String} :query (nil) if specified, the swipe will be made relative to this query.
      # @option options [Symbol] :force (nil) Indicates the force of the swipe.
      #  Valid values are :strong, :normal, :light.

**Comment by jmoody** [comment]
Pull requests are welcome!

**Comment by jmoody** [comment]
@TeresaP To be completely honest, I don't understand the "swipe-delta" options enough to document them.

Deferring until 0.17.1

**Comment by jmoody** [comment]
DeviceAgent is the future.
