### ISSUE TITLE
Update Calabash pod?

### ISSUE THREAD

**Issue by kosta-tachtevrenidis** [calabash/calabash-ios#914]
Not sure if this is the right place for this. The current Calabash-ios pod points to Calabash 0.16.3 (has since Sept). 

```
"name": "Calabash",
  "version": "0.16.3",
  "license": {
    "type": "Eclipse Public License 1.0",
    "text": "Calabash-ios Copyright (2015) Karl Krukow. All rights reserved.\nThe use and distribution terms for this software are covered by the\nEclipse Public License 1.0\n(http://opensource.org/licenses/eclipse-1.0.php) which can be found in\nthe file epl-v10.html at the root of this distribution.  By using this\nsoftware in any fashion, you are agreeing to be bound by the terms of\nthis license.  You must not remove this notice, or any other, from\nthis software."
  },
  "platforms": {
    "ios": null
  }
```

Is there a process by which this is updated? Since 0.16.4 has been out and there is already a gem for it (```https://rubygems.org/downloads/calabash-cucumber-0.16.4.gem```), it seems like it would be easy to update?

**Comment by jmoody** [comment]
We do not maintain the Podspec.

I recommend that you ask on the forum or submit an update yourself.
