### ISSUE TITLE
scenarios stopped working after xcode update

### ISSUE THREAD

**Issue by StrJack** [calabash/calabash-ios#915]
Hi team,

I've not used calabash for few weeks and had xcode update to 7.1, since that almost all scenarios stop working in my project with weird errors like no title found or it just can't open keyboard itself, I have no idea what's going wrong, is it known issue with new xcode update or something else?

some information:
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer/
$ xcodebuild -version
Xcode 7.1
Build version 7B91b
$ calabash-ios version
0.16.4

**Comment by jmoody** [comment]
There are no know issues upgrading to Xcode 7.1.

Did you restart your machine after the upgrade and/or after installing iOS Simulators?

Are the failures on devices or iOS Simulators?

Did you happen to upgrade to El Capitan as well?

**Comment by StrJack** [comment]
@jmoody , it's iOS Simulator.
I've restarted my mac (Yosemite 10.10.5) but it doesn't help.
However, I've noticed that this trouble reproduces for iPhone 6S (ios 9.1) simulator once I start my tests without DEVICE_TARGET, if I specify this flag with iPhone 5s (ios 9.1) everything goes well.
Moreover I think this issue is about wrong tap coordinates (I'm not sure), when I wanted to tap the 'button B' which is located under 'button A' Calabash is trying to tap 'button A', the same is about other controls, but as I mentioned before everything good for iPhone 5s (ios 9.1) simulator.

Thanks

**Comment by ark-konopacki** [comment]
@StrJack I have Xcode Version 7.1.1 (7B1005) and calabash 0.16.4 running without any issues 
there is known issue related to El Capitan but it is about gems not calabash itself.
Can you try to uninstall and install all required gems?

**Comment by StrJack** [comment]
@ark-konopacki I made what you asked and still have the same issue, but as I mentioned before it reproduces on default simulator Calabash starts (iPhone 6s ios 9.1), did you run your tests on such simulator?

**Comment by ark-konopacki** [comment]
@StrJack Yes i use both 5s and 6s with 9.1 iOS sim. Can you try to tap or flash element which are you using in calabash-ios console in both sim? It can be some layout issue not calabash itself. I mean if you tap and it works there is no issue ;)

**Comment by StrJack** [comment]
@ark-konopacki thanks for reply. There is fine thing, I checked both simulators from calabash-ios console and I've got the same issue, so 5s is working fine at all but 6s and 6 works like they try to tap on 50-100 px (not sure how much exactly) above for example for function 'touch', I checked few screens in application and this reproduces for all of them.

**Comment by jmoody** [comment]
@StrJack Is your app optimized for the iPhone 6* screen sizes?  Specifically, does it have the required launch images and app icons?

Can you check this for me on an iPhone 6s, iPhone 6s plus, iPhone 6, and iPhone 6 plus?

```
> start_test_server_in_background
> screen_dimensions
```

Thanks.

**Comment by StrJack** [comment]
@jmoody , I'm apologizing for not responding quickly. 
Yes, our app supports all iPhone dimensions including iPone 6 size screen

it's output of command you requested from me above
**irb(main):003:0> screen_dimensions**
{
    :sample => 1,
    :height => 1136,
     :width => 640,
     :scale => 2
}

**Comment by jmoody** [comment]
@StrJack Can we get a copy of this .app or .ipa with steps to reproduce?

Alternatively, we could do a tmate session on your machine?  http://tmate.io

If you want to live chat, join us at https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

You can also contact me by email using my GitHub address.

**Comment by jmoody** [comment]
Closing for lack of response.

Possibly related to: Screen coordinates are incorrect when running in Zoomed mode #998

Check to see if your device is in Zoom or Standard display mode.

**Comment by TeresaP** [comment]
@StrJack for the keyboard error, see if this applies: https://github.com/calabash/calabash-ios/issues/976
