### ISSUE TITLE
Setting Up Xcode Project Documentation Wrong or Incomplete

### ISSUE THREAD

**Issue by CMTaylor** [calabash/calabash-ios#917]
In this documentation: https://github.com/CMTaylor/calabash-ios#setting-up-xcode-project
the steps that say:
* From the menu select Edit Scheme and select manage schemes.
* Rename the new scheme from ".. copy" to "..-cal"
* Optionally, set the Product name to ..-cal in Build settings for the new target.
Do not work. 
1. You cannot rename a scheme once it has been created (if you know a way, please add to document)
2. You cannot change the build target inside the scheme (if you know a way, please add to document)

The ONLY way I can figure out of getting a ..-cal scheme is to create a new one from scratch. This is tedious, but it does seem to work whereas the copying suggested in the documentation does not work.

I'm using Xcode 6.4 on iOS 10.10.3.

**Comment by jmoody** [comment]
Those instructions have been replaced.

* https://github.com/calabash/calabash-ios/blob/develop/README.md

From correspondence  outside of GitHub, I know that you are make changes to the server and the gem.  I want to make sure you understand that these repos follow the _git flow_ methodology.  Briefly, this means that you should be working off the _develop_ branch.
