### ISSUE TITLE
Add ruby API for resetting the simulator content and settings

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#924]
For iOS Simulators, run-loop has:

```
RunLoop::CoreSimulator.erase(RunLoop::Device)
```

Calabash should have:

```
Launcher::reset_simulator(string-or-device)
```

**Comment by ark-konopacki** [comment]
Hi @jmoody is it just to pack run_loop method  to launcher method or it should be something different?
I think i can help with pull request.

**Comment by jmoody** [comment]
@ark-konopacki If I understand your question correctly, this new Launcher method should call RunLoop::CoreSimulator.erase.  It should be able to take a String that identifies the simulator (UDID or human readable name) or a RunLoop::Device.  It should raise an error if no matching simulator can be found or if RunLoop::Device#physical_device? is true.

```
Scenario: An instance of launcher can reset a simulator's content and settings
  Given the Simulator is closed
  Then I can reset a simulator using a simulator UDID
  And I can reset a simulator using the human readable name
  And I can reset a simulator using a RunLoop::Device instance
  When no matching simulator can be found
  Then reset_simulator raises an ArgumentError
  When passed a RunLoop::Device instance that is a physical device
  Then reset_simulator raises an ArgumentError
```
