### ISSUE TITLE
Incorrect run_loop dependency < 2.0 

### ISSUE THREAD

**Issue by ark-konopacki** [calabash/calabash-ios#927]
In Calabash we have:
calabash-cucumber-0.16.4 depends on run_loop (< 2.0, >= 1.5.5)
so we cannot use newest run_loop 2.0.0 with newest calabash 0.16.4

**Comment by jmoody** [comment]
Correct.  Run-loop will be available for use with Calabash 0.17.0.

**Comment by jmoody** [comment]
@ark-konopacki Can you contact me directly with your email address?  I want to invite you to preview a new Calabash tool we have developed.  You can contact me at: joshuajmoody@gmail.com.

Thanks!
