### ISSUE TITLE
calabash-ios check gives false negative

### ISSUE THREAD

**Issue by sapieneptus** [calabash/calabash-ios#945]
After using `calabash-tool` to link calabash, 
`calabash-ios check <app.ipa>` says it's not linked, but inspecting the payload and using `otool -L` says otherwise. 

CC; @jmoody 

(I can do this fix if you want)

**Comment by jmoody** [comment]
There are several other problems with the check tool.

Marking this as bug.  I don't want to fix this right now; there are too many other problems with the command line tools.

**Comment by jmoody** [comment]
```
$ be calabash-ios check injected.ipa 
Ipa: injected.ipa *contains* calabash.framework
0.17.0
```
