### ISSUE TITLE
Tracker:  some CI fields are empty

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#949]
This is because they don't return true/false, but rely on ruby truthy-ness.

**Comment by sapieneptus** [comment]
Seems like it'd be easy to just convert to strings then

**Comment by sapieneptus** [comment]
Also, UUID field is empty. I think that may warrant a hotfix...

**Comment by sapieneptus** [comment]
JK - the relay server just needs to be updated to register `user_id` as the 'Distinct ID'

**Comment by jmoody** [comment]
> UUID field is empty

I _think_ that has been solved.

**Comment by jmoody** [comment]
Empty fields will be correct in run-loop 2.0.2

See also **Track GitLab CI** #958
