### ISSUE TITLE
App locks up if UIAlertView appears after set_location is called

### ISSUE THREAD

**Issue by vocaro** [calabash/calabash-ios#95]
Calling the Calabash API method set_location, and then displaying a UIAlertView in the app under test, causes the app to freeze. (Tapping the button to dismiss the alert view does nothing.)

To reproduce in Calabash 0.9.126 with calabash-ios-example:
1. Add a button handler to LPFirstViewController:
   
   ```
   - (IBAction)login:(id)sender {
       UIAlertView *alert = [[UIAlertView alloc] initWithTitle:nil
                                                       message:@"this is an alert"
                                                      delegate:nil
                                             cancelButtonTitle:@"OK"
                                             otherButtonTitles:nil];
       [alert show];
   }
   ```
2. Link the Login button's Touch Up Inside to the handler.
3. Launch the app.
4. Launch the Calabash console and do: set_location(latitude: -17.884659, longitude: -5.099488). Any parameters should work here.
5. Wait a few moments.
6. Tap Login.

At this point, you should see the alert view, but clicking on it does nothing.

**Comment by Harani-me** [comment]
UIAlertViewController is not working in iOS8 & above
