### ISSUE TITLE
Timeout: UIAutomation run-loop for command uia.typeString('', '')

### ISSUE THREAD

**Issue by AartiJ** [calabash/calabash-ios#962]
I had Xcode 6.3.2, calabash-cucumber 0.16.4 , run_loop 1.5.6 which was working perfectly fine. but after upgrading to Xcode 7.2 I started seeing issue. App launches fine, but it's just retrying filling out string and then gives below error
Time out waiting for UIAutomation run-loop for command uia.typeString('', ''). Waiting for index:15

Please help

**Comment by jmoody** [comment]
Please update to 0.17.0 and at least run-loop 2.0.

If you are still seeing the error, please update this issue.

**Comment by AartiJ** [comment]
That did not help still see the same issue

**Comment by jmoody** [comment]
Try:

```
uia("uia.keyboard().typeString('some string')")
```

**Comment by AartiJ** [comment]
tried the suggested above but got below error
uia action failed because: Input: uia.keyboard().typeString('u1@gmail.com')
     [exec]       . Error: VerboseError: target.frontMostApp().keyboard() failed to tap '@'  typeString@[native code]
     [exec]       eval code
     [exec]       eval@[native code]
     [exec]       global code@file:///Users/...../BCA587C0-3AF1-4BA7-A2E1-A8C58EA87138/_run_loop.js:28494:35 (RuntimeError)

**Comment by jmoody** [comment]
Does the keyboard you are using have a "@" character?  I believe there are some keyboards that do not have this character.

**Comment by AartiJ** [comment]
Yes, the keyboard has '@ character

**Comment by AartiJ** [comment]
uia_set_responder_value(text).. this worked .

**Comment by tommeier** [comment]
FYI: was also hitting this issue recently with XCode 7.1, though appears to have been reduced/fixed in XCode 7.1.2.

**Comment by tommeier** [comment]
actually i take that back, getting it a _lot_ now on deep nested UIWebView on slow mac minis (fast boxes are fine). `uia_set_responder_value` works, but is pretty unstable with missing characters and elements, i don't think the JS is triggering on all occasions. Is there a way to increase timeout to the base `uia` command `uia("uia.keyboard().typeString('some string')")`?

**Comment by tommeier** [comment]
(my work around that works consistently, has been to remove multiple capitalised letters and reduce string length and remove the `.` i was closing with.)
