### ISSUE TITLE
usage tracking: capture the Xcode version

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#963]
We need to make decisions about when to drop Xcode versions.

**Comment by jmoody** [comment]
@ark-konopacki This needs doing.

**Comment by ark-konopacki** [comment]
@jmoody I have some ideas but i think it should be done in run_loop and calabash because i cannot find reliable way to get Xcode version from run_loop, or maybe you have an idea how to handle that?

**Comment by jmoody** [comment]
Fixed.
