### ISSUE TITLE
Can not scroll twice into UIPageViewController 

### ISSUE THREAD

**Issue by Douvi** [calabash/calabash-ios#964]
In my app I have 3 UITabBarController into a UIPageViewController. Each UITabBarController contains between 2 to 3 UIViewControllers.

when I open my app I'm at the position "0" of my UIPageViewController. I need to swipe 2 times to be on at the last screen position "2".

So in Calabash I use this method:
           
             scroll("scrollView", :right) //swipe 1 position "1"
             console : [
                               [0] "<_UIQueuingScrollView: 0x7d39f000; frame = (0 0; 320 416); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7af6ad60>; layer = <CALayer: 0x7af6a5f0>; contentOffset: {320, 0}; contentSize: {960, 416}>"
                             ]
             scroll("scrollView", :right) //swipe 2 position "2"
             console : [
                               [0] "<_UIQueuingScrollView: 0x7d39f000; frame = (0 0; 320 416); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7af6ad60>; layer = <CALayer: 0x7af6a5f0>; contentOffset: {320, 0}; contentSize: {960, 416}>"
                             ]

But the second swipe do not do any action. It's like calabash lose the focus. However If i swipe with the mouse Calabash can swipe again but not twice.

**Comment by jmoody** [comment]
It might be helpful to see a screen shot.  I don't understand the layout of your app.  You have a UITabBarController _inside_ a UIPageViewController?

Try running with debug logging:  `DEBUG=1`.

It might also be helpful to see the simulator log:

```
$ bundle exec calabash-ios console
> start_test_server_in_background

# In another Terminal window
$ bundle exec run-loop simctl tail
```

Please only include a _small_ part of the simulator log.

This issue is missing a lot of required information.  Please update your question with the required information: [Reporting Problems](https://github.com/calabash/calabash-ios/wiki#reporting-problems).

**Comment by Douvi** [comment]
I do have 3 UITabBarController side by side into a UIPageViewController. And each UITabBarController have 3 UIViewController. See below the scheme:

           --------------------------------------------------------------
           |  					UIPageViewController					 |
           | ==========================================================  |
           | |		( 0 )		 |		( 1 )		|	   ( 2 )  	   | |
           | |UITabBarController |UITabBarController|UITabBarController| |
           | |					 |					|				   | |
           | |-------------------|------------------|------------------| |
           | | TAB1|TAB2|TAB3	 | TAB1|TAB2|TAB3	| TAB1|TAB2|TAB3   | |
           | |=========================================================| |
           --------------------------------------------------------------

When I start the app i'm on the position "0", I want to swipe twice to be position "2"

Terminal: first swipe

        irb(main):004:0> scroll "*", :right
        [
             [ 0] nil,
             [ 1] nil,
             [ 2] nil,
             [ 3] nil,
             [ 4] nil,
             [ 5] "<_UIQueuingScrollView: 0x7abb9a00; frame = (0 0; 320 416); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x78649140>; layer = <CALayer: 0x78648880>; contentOffset: {320, 0}; contentSize: {960, 416}>",
             [ 6] nil
        ]

Log:

        Dec 21 09:28:17 User-MBP project[54511]: Map POST, /map Parsed UIScript as
	          (
	              "view:'UIView'"
	           )
Terminal: second swipe

        irb(main):005:0> scroll "*", :right
        [
             [ 0] nil,
             [ 1] nil,
             [ 2] nil,
             [ 3] nil,
             [ 4] nil,
             [ 5] "<_UIQueuingScrollView: 0x7abb9a00; frame = (0 0; 320 416); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x78649140>; layer = <CALayer: 0x78648880>; contentOffset: {320, 0}; contentSize: {960, 416}>",
             [ 6] nil,
             [ 7] nil,
             [ 8] nil,
             [ 9] nil,
             [10] nil
         ]

Log:

        Dec 21 09:28:23 User-MBP project[54511]: Map POST, /map Parsed UIScript as
	          (
	             "view:'UIView'"
	          )
        Dec 21 09:28:29 User-MBP assertiond[54445]: assertion failed: 14F1509 12F70: assertiond + 14647 [D82D8D7B-5253-3300-B083-B6F739F68355]: 0x1

I do not have more log

**Comment by jmoody** [comment]
+100 for ASCII art!  ATTN @TobiasRoikjer 

I think you should try to specify exactly the view you are trying to scroll on.

```
> scroll(< some query that identifies the view controller of the _page_ view, :right)
```

But default, `scroll` tries to scroll from the middle of the view.  I think you might also need to apply an offset. 

Does swipe not work?  This is more like a swipe than a scroll gesture.

**Comment by Douvi** [comment]
ASAP i will try your comment 'swipe'.

**Comment by jmoody** [comment]
@Douvi You should sleep between each swipe.  That is the problem.

**Comment by jmoody** [comment]
Closing.
