### ISSUE TITLE
0.17.0: version tool is spamming profiling information: "Objects-normal/x86_64/main.gcda: cannot open: No such file or directory"

### ISSUE THREAD

**Issue by kaorijp** [calabash/calabash-ios#966]
Hi @jmoody 

I have just upgraded calabash version from 0.15.0 to latest version 0.17.0.
After finished, I check version of calabash.framework that seems have some problem. 
Could you please have a look at on it ? 

##### 1. Check version of calabash.framework  (`I think we have problem in here`)

```
>calabash.framework/Resources/version
0.17.0
profiling: /Users/moody/git/calabash/calabash-ios-server/build/framework/version-tool/Build/Intermediates/calabash.build/Release/version.build/Objects-normal/x86_64/main.gcda: cannot open: No such file or directory
profiling: /Users/moody/git/calabash/calabash-ios-server/build/framework/version-tool/Build/Intermediates/calabash.build/Release/version.build/Objects-normal/x86_64/main.gcda: cannot open: No such file or directory
profiling: /Users/moody/git/calabash/calabash-ios-server/build/framework/version-tool/Build/Intermediates/calabash.build/Release/version.build/Objects-normal/x86_64/main.gcda: cannot open: No such file or directory
profiling: /Users/moody/git/calabash/calabash-ios-server/build/framework/version-tool/Build/Intermediates/calabash.build/Release/version.build/Objects-normal/x86_64/main.gcda: cannot open: No such file or directory  
```

##### 2. Check calabash-ios version  

```
>calabash-ios version
0.17.0  
```

#### 4. Other info  

```
>xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

>xcodebuild -version
Xcode 7.0.1
Build version 7A1001  

>MacBook Pro : Yosemite 10.10.5
```

**Comment by jmoody** [comment]
Thanks for reporting!

>  check version of calabash.framework that seems have some problem. 

The tool is reporting the correct version.  The `profiling` information should not be there.  This is not a blocking error.

I thought I fixed this with:

** version tool is generating "cannot find gcda" output** [#289](https://github.com/calabash/calabash-ios-server/issues/289)

**Comment by kaorijp** [comment]
Hi @jmoody 

I got it. 
By the way, can you tell me the schedule that you will release new version that include above problem?

Thank you so much !

**Comment by jmoody** [comment]
* 0.17.0 _contains the problem_.
* I hope I will fix this for 0.17.1 - the release will be after Jan 3.

This bug is _just in the version tool_; it should not affect Calabash performance.

**Comment by kaorijp** [comment]
Yep. Thank you so much dear friend !

**Comment by kaorijp** [comment]
@jmoody 

>2015-12-21 18:01:11 +0900 [RunLoop:debug]: Preparation took 2.493673 seconds
2015-12-21 18:01:17 +0900 [RunLoop:debug]: Launching took 6.783969 seconds
DEBUG: It took 9.277966 seconds to launch the app

It seems does not work when I upgrade calabash-cucumber from 0.15.0 -> 0.17.0
It has been stopped after launch app
Is there any reason for that ?

**Comment by kaorijp** [comment]
http://stackoverflow.com/questions/28977220/calabash-ios-simulator-stuck-at-launching-took-xxx-seconds

My problem is same above. 
I'm running on real device. It was worked on 0.15.0 as normal.

**Comment by kaorijp** [comment]
More infor : 

 >RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
 Unable to make connection to Calabash Server at http://10.42.12.127:37265
 Make sure you don't have a firewall blocking traffic to http://10.42.12.127:37265.
  (RuntimeError)

**Comment by jmoody** [comment]
> RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and 

I believe your app does not have the Calabash server linked.

Would you be willing to try a tmate session?

https://tmate.io/

**Comment by kaorijp** [comment]
@jmoody
I can not report exactly reason. But I have resolved it. 
Firtsly, I run calabash-ios download for get latest version then open Xcode to check linked. -> it does not work . 

I can not judgement any reasonable. So I clear all then just download only (it same meaning overwrite calabash.framework) -> buil again -> It works

**Comment by jmoody** [comment]
@kaorijp If you have more trouble, please open a new issue.
