### ISSUE TITLE
Xcode 7.2 calabash-ios 0.17.0 issue

### ISSUE THREAD

**Issue by zeljkoilic** [calabash/calabash-ios#970]
Hi,
I'm using Xcode 7.2 and calabash-ios 0.17.0.
When I use the following sequence of commands:

**calabash-ios console
start_test_server_in_background**

I get the following error message:

**TypeError: no implicit conversion of nil into String
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launch/simulator_launcher.rb:255:in `join'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launch/simulator_launcher.rb:255:in `app_bundle_or_raise'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launcher.rb:541:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/core.rb:943:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'**

Before Xcode 7.2 I was able to run those commands. Do you have an idea what could have caused this issue? Thanks in advance!

Best,
Zeljko

**Comment by ark-konopacki** [comment]
Hi @zeljkoilic can you try to specify path to app like:

**Comment by jmoody** [comment]
@zeljkoilic We are tracking this issue here:

0.17.0 Cannot automatically detect app #959

@ark-konopacki suggestion is correct.
