### ISSUE TITLE
Can not run calabash with .app file building from xcode command line

### ISSUE THREAD

**Issue by kaorijp** [calabash/calabash-ios#971]
I have problem with calabash on physical device when using app file that building from command line.
Look like:  

```
xcodebuild 
  -scheme Myapp-cal \
  -workspace Myapp.xcworkspace \
  CODE_SIGN_IDENTITY="iPhone Distribution: XXXX" \
  PROVISIONING_PROFILE="YYYYY" \
  -configuration Debug \
  -sdk iphoneos \
  build
```

I don't know what is the difference between 2 ways of build xcode project from command line and Xcode App.

Here is the error log when I run calabash  
 
```
2016-01-05 14:41:50 +0900 [RunLoop:debug]: Preparation took 1.469397 seconds
2016-01-05 14:42:20 +0900 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-01-05 14:42:20 +0900 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError`  
```

More info:  

#### 1. Command line build simulator mode:

```
xcodebuild 
  -scheme Myapp-cal \
  -workspace Myapp.xcworkspace \
  CODE_SIGN_IDENTITY="iPhone Distribution: XXXX" \
  PROVISIONING_PROFILE="YYYYY" \
  -configuration Debug \
  -sdk iphonesimulator \ 
  build
```

#### 2. Command line build device mode: 

```
xcodebuild 
  -scheme Myapp-cal \
  -workspace Myapp.xcworkspace \
  CODE_SIGN_IDENTITY="iPhone Distribution: XXXX" \
  PROVISIONING_PROFILE="YYYYY" \
  -configuration Debug \
  -sdk iphoneos \
  build  
```

#### 3. Calabash testing result 

Building from command line

| Type of device  |    Calabash Run  |
|----------|:-------------:|
| Simulator  |  OK |
| Real device |    NG  |
  
Building from Xcode

| Type of device  |    Calabash Run  |
|----------|:-------------:|
| Simulator  |  OK |
| Real device |    OK  |

**Comment by jmoody** [comment]
+100 for the tables!

> CODE_SIGN_IDENTITY="iPhone Distribution: XXXX" 

You cannot use a _Distribution_ profile.  You must use a _Developer_ profile.

This will explain the FIFO error.

**Comment by jmoody** [comment]
I also need to add that you must create a .ipa from the .app you are building for physical devices.

We recommend that use Apple's `ditto` command:

```
xcrun ditto -ck --rsrc --sequesterRsrc --keepParent \
  "${PAYLOAD_DIR}" \
  "${INSTALLED_IPA}"
```

Have a look at this script: https://github.com/calabash/calabash-ios-server/blob/develop/bin/make/ipa-cal.sh and feel free to copy it to your project.  All you will need to do is update some of variables.

**Comment by jmoody** [comment]
If you need more help, please join use in Gitter:

https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by kaorijp** [comment]
>You cannot use a Distribution profile. You must use a Developer profile.
>This will explain the FIFO error.
I don't think so. 
Because I also using Distribution profile when building by Xcode -> Get .app file -> Its working fine !

**Comment by jmoody** [comment]
Using _Distribution_ profiles and UIAutomation is not allowed by Apple.

**Comment by kaorijp** [comment]
>Using Distribution profiles and UIAutomation is not allowed by Apple.  

@jmoody 
So, why I can run Calabash when build by XCODE with Distribution profiles ?
I just confusing about build by Xcode and Command line

**Comment by jmoody** [comment]
If you could inspect the .ipa built by Xcode you would see that when it is installed, it is signed with a Developer profile.  You would have to hack your phone to gain access to the .app bundle on your device.

**Comment by kaorijp** [comment]
I have not build .ipa in Xcode. 
I just build .app file then install into my iPhone by command :  
ideviceinstall -i myapp.app

In Xcode setting, I can make sure I using Distribution profiles
