### ISSUE TITLE
Cordova Calabash iOS plugin

### ISSUE THREAD

**Issue by paulpatarinski** [calabash/calabash-ios#982]
I have created a Cordova plugin for Calabash iOS to help test Cordova based Hybrid apps. It links the Calabash framework and provides a simple api for starting the Calabash Http Server.

Available here : 

https://cordova.apache.org/plugins/?q=calabash
https://www.npmjs.com/package/calabash-ios

Repo : 
https://github.com/paulpatarinski/Cordova-Calabash-iOS-Plugin

Would you be interested in including this as part of the docs?

**Comment by jmoody** [comment]
@paulpatarinski 

This looks interesting.  We have system for loading third-party frameworks into Calabash at runtime.  Would you be interested in discussing the merits of your approach over the one we have already?

We can discuss live here: https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link


* https://github.com/calabash/memoryPluginCalabash

It is not well documented, but the approach is simple.

**Comment by jmoody** [comment]
@paulpatarinski The wiki is publicly editable.  If you want to add docs to the wiki, go for it.  Just tell me the page and I will decide where it goes.

Thanks.
