### ISSUE TITLE
Add support for including screenshot properties to calabash-ios logs

### ISSUE THREAD

**Issue by aknackiron** [calabash/calabash-ios#991]
Calabash for Android has support for logging screenshot capturing steps with eg. screenshot file name to Calabash logs but this is not supported on iOS. Having the possibility to add information about screenshot properties (eg. name and timestamp) on Calabash-iOS would be great. 

Eg.

*Android*
```
Then I wait                                                       # calabash-android-0.5.14/lib/calabash-android/steps/progress_steps.rb:5
    Then I press view with id "radio2"                                # calabash-android-0.5.14/lib/calabash-android/steps/press_button_steps.rb:13
2016-02-10 12:24:04 - java -jar /usr/local/rvm/gems/ruby-2.1.2/gems/calabash-android-0.5.14/lib/calabash-android/lib/screenshotTaker.jar "HT43YSF03900" "screenshots/screenshot_0.png"
    Then I take a screenshot                                          # calabash-android-0.5.14/lib/calabash-android/steps/screenshot_steps.rb:9
    Then I wait                                                       # calabash-android-0.5.14/lib/calabash-android/steps/progress_steps.rb:5
2016-02-10 12:24:11 - Action: keyboard_enter_text - Params: Hello Calabash
```
but with *iOS* the only thing that gets logged for screenshot taking is the test step:

```
Then I press "Use Testdroid Cloud"                                                    # calabash-cucumber-0.17.1/features/step_definitions/calabash_steps.rb:14
    Then I wait                                                                           # calabash-cucumber-0.17.1/features/step_definitions/calabash_steps.rb:196
    Then I take picture                                                                   # calabash-cucumber-0.17.1/features/step_definitions/calabash_steps.rb:217
Sending UIA command
uia.tapOffset('{:x 384, :y 865}')
2016-02-10 00:34:57 -0800 [RunLoop:debug]: 2:uia.tapOffset('{:x 384, :y 865}')
```

**Comment by jmoody** [comment]
I don't think we will add this.  I think the Android behavior might be a bug.

@TobiasRoikjer Can you comment on this?

**Comment by jmoody** [comment]
You can patch Calabash iOS to behave like Calabash Android.

It is not something we will add to Calabash iOS.

**Comment by aknackiron** [comment]
Do I understand correctly that providing a patch to the reporting could be merged to Calabash iOS?

**Comment by jmoody** [comment]
@aknackiron Such a patch would _not_ be merged.  You could add a patch to your local cucumber project(s).  The easiest way to do this would be to put the patch file in your `features/support` directory.

Here is a patch for cucumber `pending` that we use in [feature skeleton](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/features-skeleton/support/patches/cucumber.rb).

Your screenshot patch might look like this:

```
# features/support/patches/calabash_ios_screenshot.rb
module Calabash
  module Cucumber
   module FailureHelpers
       def screenshot(options={:prefix => nil, :name => nil})
       # Your implementation.  It could be as simple as copy-and-pasting the original
       # implementation and adding a `puts` statement

       # must return a path to screenshot
          path
       end
    end
end

**Comment by jmoody** [comment]
@aknackiron 

You might also be interested in this Scenario:

https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/screenshots.feature

which shows how to change the name of a screenshot.
