### ISSUE TITLE
Adding calabash framework makes app to crash.

### ISSUE THREAD

**Issue by rKrums** [calabash/calabash-ios#992]
I've been struggling with this issue for few days now. 

I've tried various calabash versions, and still the same result.

I add the calabash framework using `calabash-ios setup` from project root. It adds everyting successfully and creates -cal target. 
I build the -cal target using Xcode 7.2
When I launch the app on device
It instantly crashes with message: 
`<Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't parse JSON configuration file: Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 324." UserInfo={NSDebugDescription=Badly formed object around character 324.}'`

I've tried two physical devices with two different iOS versions
Tried to reset the device settings
Even updated it to 9.2.1

When I build the regular app target, everything works fine, and the app runs. 
I can start instruments automation, but when I hit record or play, the app still crashes
I'm out of ideas. Has someone experienced something similar?

**Comment by jmoody** [comment]
```
<Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't parse JSON configuration file:
```


That looks like a problem on your side.  We are not loading a JSON config file.

I recommend that you do not try to use the `setup` tool and instead use one of the tutorials.

https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode

**Comment by jmoody** [comment]
@rKrums Closing for lack of response.   I am interested to know if this issue has been resolved.  Thanks.

**Comment by rKrums** [comment]
@jmoody I didn't remember how I resolved it, but it was either a bad combination of gem versions, or it was difference in line ending formatting somewhere.
