### ISSUE TITLE
Simulate press home button on iOS device

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash-ios#993]
Hello,
I'm looking for a way to simulate pressing Home during an app test, is it possible with calabash-ios ?
I'm using ruby.
Thanks !

**Comment by jmoody** [comment]
```
send_app_to_background(< seconds >)
```

**Comment by ericzered** [comment]
Hello, 
Thanks for the answser but I have a problem with this function. It looks like calabash is not able to re-open the app after the timer.
I have this error : 
RuntimeError: uia action failed because: Input: var x = target.deactivateAppForDuration(1); var MAX_RETRY=5, retry_count = 0; while (!x && retry_count < MAX_RETRY) { x = target.deactivateAppForDuration(1); retry_count += 1}; x
. Error: VerboseError: -[UIAElementNil _prepareForAction:]: unrecognized selector sent to instance 0x7fef22902790  deactivateAppForDuration@[native code]
eval code
eval@[native code]
global code@file:///Users/elerouge/Documents/GitWorkspace/EbuzzingTesting/teads_iOS_SDK/C3C741DC-7E5E-4B04-89EE-C65AF09BBD98/_run_loop.js:28494:35
from /Users/elerouge/.rvm/gems/ruby-2.2.1@cucumber1317/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/uia.rb:53:in `uia'
and the simulator, Iphone 6 iOS 9.1, give me that :
![capture d ecran 2016-02-15 a 15 51 25](https://cloud.githubusercontent.com/assets/8480016/13051969/73f214be-d3fc-11e5-91e5-2eb8fb353109.png)

**Comment by ericzered** [comment]
Hello, 
Thanks for the answser but I have a problem with this function. It looks like calabash is not able to re-open the app after the timer.
I have this error : 
_RuntimeError: uia action failed because: Input: var x = target.deactivateAppForDuration(1); var MAX_RETRY=5, retry_count = 0; while (!x && retry_count < MAX_RETRY) { x = target.deactivateAppForDuration(1); retry_count += 1}; x
. Error: VerboseError: -[UIAElementNil _prepareForAction:]: unrecognized selector sent to instance 0x7fef22902790 deactivateAppForDuration@[native code]
eval code
eval@[native code]
global code@file:///Users/elerouge/Documents/GitWorkspace/EbuzzingTesting/teads_iOS_SDK/C3C741DC-7E5E-4B04-89EE-C65AF09BBD98/_run_loop.js:28494:35
from /Users/elerouge/.rvm/gems/ruby-2.2.1@cucumber1317/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/uia.rb:53:in `uia'_

and the simulator, Iphone 6 iOS 9.1, give me that :
![capture d ecran 2016-02-15 a 15 51 25](https://cloud.githubusercontent.com/assets/8480016/13052076/05da7f1a-d3fd-11e5-8f24-41599d034b5c.png)

**Comment by jmoody** [comment]
Update to the latest version of Calabash iOS

**Comment by TeresaP** [comment]
Oh nice, I thought this was still broken due to an iOS limitation
